Repository wix/wix-style-react, pull requests merged in 2018-10, with the labels that each got.

#2282 Dnd testkit portals
  src/SortableList/SortableList.spec.js
  src/SortableList/driverHelpers.js
Labels: WIP

#2235 <PopoverMenuItem/> & <TableActionCell/> - disable menu items
  src/PopoverMenu/PopoverMenu.spec.js
  src/PopoverMenuItem/PopoverMenuItem.js
  src/PopoverMenuItem/PopoverMenuItem.scss
  src/TableActionCell/TableActionCell.js
  src/TableActionCell/TableActionCell.spec.js
  stories/TableActionCell/TableActionCell.story.js
  stories/TableActionCell/examples/DisabledSecondaryExample.js
  stories/Tooltip/Composite/ExamplePopoverMenu.js
  stories/Tooltip/Composite/PopoverMenuBuilder.js
  stories/Tooltip/Composite/PopoverMenuTemplate.js
Labels: WIP

#2293 <SideMenu/> - fix infinite loop when using React 16
  src/SideMenu/DrillView/DrillView.js
Labels: React 16

#2294 <InputWithTags/> replace hasHover state with native css
  src/MultiSelect/InputWithTags.js
  src/MultiSelect/InputWithTags.scss
  src/MultiSelect/MultiSelect.e2e.js
  src/MultiSelect/MultiSelect.spec.js
  stories/MultiSelect/ExampleReorderable.js
Labels: WIP

#2361 `<TextField/>` - deprecated component, and add snippet story using `<FormField/>`
  .storybook/common/stories.js
  src/TextField/README.md
  src/TextField/TextField.js
  stories/Dropdown/DropdownStory.js
  stories/Input/index.js
  stories/Input/storySettings.js
  stories/TextField/ExampleAdornments.js
  stories/TextField/ExampleBasic.js
  stories/TextField/ExampleSizes.js
  stories/TextField/ExampleStandard.js
  stories/TextField/ExampleStandard.scss
  stories/TextField/TextFieldTemplate.js
  stories/TextField/index.js
  stories/Typography/TypographyClassesMigration.md
  stories/Typography/TypographyClassesStory.js
  stories/Typography/TypographyClassesTable.md
  stories/UXStoryTemplate.js
  stories/storiesHierarchy.js
Labels: Docs
