Repository wix/wix-style-react, pull requests merged in 2018-11, with the labels that each got.

#2251 <Collapse/> - add new component and revise <Card/> implementation
  .storybook/common/stories.js
  src/Card/CollapsedHeader/CollapsedHeader.driver.js
  src/Card/CollapsedHeader/CollapsedHeader.js
  src/Card/CollapsedHeader/CollapsedHeader.spec.js
  src/Card/README.md
  src/Collapse/Collapse.js
  src/Collapse/Collapse.spec.js
  src/Collapse/index.js
  src/Grid/README.md
  stories/Card/ExampleCollapsableHeaders.js
  stories/Card/ExampleCollapse.js
  stories/Card/index.js
  stories/Collapse.story.js
  testkit/testkit-smoke.test.js
Labels: WIP

#2514 `<Avatar/>` - Improve story: props and examples
  .storybook/config-offline/manager-head.html
  .storybook/config-offline/preview-head.html
  src/Avatar/Avatar.js
  src/Avatar/README.md
  stories/AutoExampleWrapper.js
  stories/Avatar/Avatar.story.js
  stories/Avatar/AvatarStory.scss
  stories/Avatar/AvatarTestStory.js
  stories/Avatar/storySettings.js
  stories/Tag.story.js
  stories/utils/Components/LiveCodeExample/index.js
Labels: Docs

#2515 `<Table/>` - testkit - Add ability to use Table driver when using Table in Page
  src/DataTable/DataTable.js
  src/Table/README.TESTKIT.md
  src/Table/Table.spec.js
  src/Table/components/TableContent.js
  src/Table/components/TableTitleBar.js
Labels: testkit bug
