Repository wix/wix-style-react, pull requests merged in 2019-12, with the labels that each got.

#4598 Cheatsheet - add <PreviewWidget/>
  stories/Introduction/Cheatsheet/componentsFamilies/ContentWidgetsFamily.js
  stories/symbolsComponentsMapping/components.js
  stories/symbolsComponentsMapping/families/buttonsFamily.js
  stories/symbolsComponentsMapping/families/contentWidgetsFamily.js
  stories/symbolsComponentsMapping/families/foundationFamily.js
  stories/symbolsComponentsMapping/families/inputsFamily.js
  stories/symbolsComponentsMapping/families/layoutFamily.js
  stories/symbolsComponentsMapping/families/modalsFamily.js
  stories/symbolsComponentsMapping/families/navigationFamily.js
  stories/symbolsComponentsMapping/families/notificationsFamily.js
  stories/symbolsComponentsMapping/families/otherFamily.js
  stories/symbolsComponentsMapping/families/pickerFamily.js
  stories/symbolsComponentsMapping/families/selectionFamily.js
  stories/symbolsComponentsMapping/families/tooltipPopoverFamily.js
  stories/symbolsComponentsMapping/symbols.js
Labels: <PreviewWidget/>, PR: unreviewed

#4553 <DropdownLayout/> - Fix hover behaviour loss on click
  src/DropdownLayout/DropdownLayout.js
Labels: <DropdownLayout/>, PR: reviewed-approved, PR: unreviewed

#4617 Added types to <ListItemSelect/> and <ListItemSection/>
  src/ListItemSection/ListItemSection.uni.driver.d.ts
  src/ListItemSection/index.d.ts
  src/ListItemSelect/ListItemSelect.uni.driver.d.ts
  src/ListItemSelect/index.d.ts
  test/types/ListItemSection.tsx
  test/types/ListItemSelect.tsx
  testkit/enzyme.d.ts
Labels: PR: reviewed-approved

#4628 Revert pull-4553 requires a small investigation
  src/DropdownLayout/DropdownLayout.js
  src/DropdownLayout/test/DropdownLayout.spec.js
Labels: PR: unreviewed

#4578 `<ToggleSwitch/>`- migration from wix-ui-backoffice
  .wuf/components.json
  src/ToggleSwitch/ToggleSwitch.driver.js
  src/ToggleSwitch/ToggleSwitch.js
  src/ToggleSwitch/ToggleSwitch.meta.js
  src/ToggleSwitch/ToggleSwitch.protractor.driver.js
  src/ToggleSwitch/ToggleSwitch.st.css
  src/ToggleSwitch/constants.js
  src/ToggleSwitch/docs/ControlledToggleSwitch.js
  src/ToggleSwitch/docs/ExampleFormField.js
  src/ToggleSwitch/docs/examples.js
  src/ToggleSwitch/docs/index.story.js
  src/ToggleSwitch/test/ToggleSwitch.spec.js
  src/ToggleSwitch/test/ToggleSwitch.visual.js
  src/ToggleSwitch/test/storySettings.js
Labels: DO NOT MERGE, PR: reviewed-changes-requested, PR: unreviewed

#4590 `<ModalSelectorLayout/>` - add sideActions node
  src/ModalSelectorLayout/ModalSelectorLayout.js
Labels: PR: reviewed-approved

#4591 <InputWithOptions /> - add onOptionsShow/onOptionsHide callbacks
  src/InputWithOptions/InputWithOptions.js
  src/InputWithOptions/InputWithOptions.spec.js
  src/InputWithOptions/README.md
Labels: PR: reviewed-approved

#4634 release/7.20.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#4633 <Popover/> <InputWithOptions/> - add disableClickOutsideWhenClosed prop
  package.json
  src/InputWithOptions/InputWithOptions.js
  src/MultiSelectCheckbox/docs/index.story.js
  src/Popover/Popover.js
Labels: <InputWithOptions/>, <Popover/>, PR: unreviewed

#4640 Update to version 7.20.1
  package.json
Labels: PR: unreviewed

#4636 `<Search>` - fixed issue where `clearButton` prop didn't work
  src/Search/Search.js
  src/Search/test/Search.spec.js
Labels: PR: reviewed-approved

#4641 <ListItemSection/> - Add onClick prop
  src/ListItemSection/ListItemSection.js
  src/ListItemSection/test/ListItemSection.spec.js
Labels: <ListItemSection/>, PR: unreviewed

#4638 ability to add custom data-hooks to ModalSelectLayout
  src/ModalSelectorLayout/ModalSelectorLayout.js
Labels: PR: unreviewed

#4632 <AutoCompleteWithLabel /> - fix reset options after select
  src/AutoCompleteWithLabel/AutoCompleteWithLabel.js
  src/AutoCompleteWithLabel/docs/examples.js
  src/AutoCompleteWithLabel/docs/index.story.js
  src/AutoCompleteWithLabel/test/AutoCompleteWithLabel.spec.js
Labels: PR: reviewed-changes-requested

#4643 `<FillPreview/>` - add support for rendering as something else and fix broken stylable extending feature
  src/FillPreview/FillPreview.js
  src/FillPreview/FillPreview.st.css
Labels: PR: unreviewed

#4625 Change Card.Subheader and Table neutral skin background-colors to D10…
  src/Card/Subheader/Subheader.st.css
  src/DataTable/DataTable.scss
  src/Foundation/stylable/colors.st.css
  src/colors.scss
Labels: PR: reviewed-approved

#4645 add clearOnBlur prop to Multiselect
  src/MultiSelect/MultiSelect.js
  src/MultiSelect/test/MultiSelect.spec.js
Labels: PR: reviewed-approved

#4642 <Input /> should accept a pattern attribute
  src/Input/Input.driver.js
  src/Input/Input.js
  src/Input/Input.uni.driver.js
  src/Input/tests/Input.spec.js
Labels: PR: reviewed-approved

#4646 release(7.21.0)
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#4651 <Table/> - add getRowsCount to Puppeteer testkit
  src/Table/Table.puppeteer.driver.js
Labels: <Table/>, PR: unreviewed

#4652 <PopoverMenu> fix wrong typing
  src/beta/PopoverMenu/PopoverMenu.uni.driver.d.ts
Labels: PR: reviewed-approved

#4657 Move ListItemSelect/ListItemSection testkit typings to generator template
  .wuf/components.json
  .wuf/testkits/enzyme-typescript.template.ejs
  .wuf/testkits/vanilla-typescript.template.ejs
  src/index.d.ts
  test/types/ListItemSection.tsx
  test/types/ListItemSelect.tsx
  testkit/enzyme.d.ts
  testkit/index.d.ts
Labels: PR: reviewed-approved

#4624 <ColorInput /> bug fix: color swatch will display the previous color after input is cleared
  src/ColorInput/ColorInput.js
  src/ColorInput/ColorInput.spec.js
  src/ColorInput/hex-helpers.js
Labels: PR: reviewed-approved

#4670 Icons: Update docs and add deprecation warning
  CHANGELOG-V3-V6.md
  docs/contribution/ADDING_ICONS.md
  docs/migration/ICONS.md
  docs/migration/NEW_ICONS_MIGRATION.md
  docs/migration/v4-v5.md
  scripts/proxy-wix-ui-icons/index.js
  scripts/proxy-wix-ui-icons/proxy-wix-ui-icons.js
  scripts/proxy-wix-ui-icons/utils/diskUtils.js
  scripts/proxy-wix-ui-icons/utils/fileContentUtils.js
  src/new-icons/README.md
Labels: PR: reviewed-approved

#4672 <ListItemSection/> - change prefix to be vertically aligned down
  src/ListItemSection/ListItemSection.st.css
Labels: <ListItemSection/>, PR: unreviewed

#4603 <Palette> - new component
  .wuf/components.json
  src/Palette/Palette.js
  src/Palette/Palette.meta.js
  src/Palette/Palette.st.css
  src/Palette/Palette.uni.driver.js
  src/Palette/docs/examples.js
  src/Palette/docs/index.story.js
  src/Palette/index.d.ts
  src/Palette/index.js
  src/Palette/test/Palette.private.uni.driver.js
  src/Palette/test/Palette.spec.js
  src/Palette/test/Palette.visual.js
  src/Palette/test/storySettings.js
  src/index.js
  stories/index.js
  testkit/enzyme.d.ts
  testkit/enzyme.js
  testkit/index.d.ts
  testkit/index.js
  testkit/protractor.d.ts
  testkit/protractor.js
  testkit/puppeteer.d.ts
  testkit/puppeteer.js
Labels: PR: unreviewed

#4668 `<ToggleSwitch/>`- adding uni driver and refactoring unit tests
  src/ToggleSwitch/ToggleSwitch.js
  src/ToggleSwitch/ToggleSwitch.uni.driver.js
  src/ToggleSwitch/test/ToggleSwitch.spec.js
Labels: PR: unreviewed

#4673 Release 7.22.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#4674 <TimeInput/> - Remove font usage
  src/TimeInput/TimeInput.driver.js
  src/TimeInput/TimeInput.js
  src/TimeInput/TimeInput.scss
  src/TimeInput/test/TimeInput.spec.js
Labels: <TimeInput/>, PR: reviewed-approved, PR: unreviewed, Refactor

#4679 `<SidebardSectionItem/>` - make sure to use css that is supported in microsoft edge
  src/ListItemAction/ListItemAction.st.css
  src/SidebarBackButton/SidebarBackButton.st.css
  src/SidebarSectionItem/SidebarSectionItem.st.css
Labels: PR: unreviewed

#4680 Deprecate bundles-analyse script and make sure to run bundles under NODE_ENV=production
  package.json
Labels: PR: unreviewed

#4662 updated running local eyes
  docs/contribution/VISUAL_TESTING.md
Labels: PR: reviewed-approved

#4631 `<LinearProgressBar/>`- adding success skin and update existing colors
  src/LinearProgressBar/LinearProgressBar.driver.js
  src/LinearProgressBar/LinearProgressBar.js
  src/LinearProgressBar/LinearProgressBar.st.css
  src/LinearProgressBar/LinearProgressBar.uni.driver.js
  src/LinearProgressBar/constants.js
  src/LinearProgressBar/docs/examples.js
  src/LinearProgressBar/docs/index.story.js
  src/LinearProgressBar/test/LinearProgressBar.spec.js
  src/LinearProgressBar/test/LinearProgressBar.visual.js
  stories/Introduction/Cheatsheet/componentsFamilies/OtherFamily.js
Labels: PR: unreviewed

#4681 <FilePicker/> - Remove font usage
  perfer.config.js
  src/FilePicker/FilePicker.js
  src/FilePicker/FilePicker.scss
  src/FilePicker/test/FilePicker.visual.js
Labels: <FilePicker/>, PR: unreviewed, Refactor

#4658 Update auto complete with label disable state ui
  src/AutoCompleteWithLabel/AutoCompleteWithLabel.uni.driver.js
  src/AutoCompleteWithLabel/test/AutoCompleteWithLabel.spec.js
Labels: PR: reviewed-approved

#4682 <TimeTable/> - fix wrong position of dragged element
  src/TimeTable/TimeTable.js
Labels: PR: reviewed-approved

#4690 <ColorPicker/> - Add dataHook to prop types
  src/ColorPicker/ColorPicker.js
  src/ColorPicker/tests/ColorPicker.spec.js
Labels: <ColorPicker/>, PR: reviewed-changes-requested, PR: unreviewed, Refactor

#4691 <DatePicker/> - Remove font usage
  src/Calendar/DatePickerHead/index.js
  src/Calendar/DatePickerHead/styles.scss
Labels: <DatePicker/>, PR: reviewed-changes-requested, PR: unreviewed, Refactor

#4686 `<Table/>`- fixing table with action cell example
  src/Table/Table.js
  src/Table/docs/examples/TableActionCellExample.js
Labels: PR: unreviewed

#4693 <MessageBoxFunctionalLayout/> - Remove font usage
  src/MessageBox/FunctionalLayout/MessageBoxFunctionalLayout.js
  src/MessageBox/FunctionalLayout/MessageBoxFunctionalLayout.scss
Labels: <MessageBoxFunctionalLayout/>, PR: reviewed-approved, PR: unreviewed, Refactor

#4683 `<FloatingNotification/>`- adding dark skin
  src/FloatingNotification/FloatingNotification.js
  src/FloatingNotification/FloatingNotification.scss
  src/FloatingNotification/constants.js
  src/FloatingNotification/docs/examples.js
  src/FloatingNotification/docs/examples/ExampleAllOptions.js
  src/FloatingNotification/docs/examples/ExampleAllTypes.js
  src/FloatingNotification/docs/examples/ExampleFullWidth.js
  src/FloatingNotification/docs/examples/ExampleHref.js
  src/FloatingNotification/docs/examples/index.js
  src/FloatingNotification/docs/index.story.js
  src/FloatingNotification/test/FloatingNotification.visual.js
  stories/Introduction/Cheatsheet/componentsFamilies/NotificationFamily.js
Labels: PR: reviewed-approved

#4694 `<FloatingNotification/>`- refactoring uni driver and constants file
  src/FloatingNotification/FloatingNotification.js
  src/FloatingNotification/FloatingNotification.uni.driver.js
  src/FloatingNotification/constants.js
  src/FloatingNotification/datahooks.js
  src/FloatingNotification/docs/index.story.js
  src/FloatingNotification/index.js
Labels: PR: reviewed-approved

#4661 `<TableActionCell/>` - changed the disabled visible items behaviour
  src/TableActionCell/TableActionCell.js
  src/TableActionCell/test/TableActionCell.spec.js
Labels: PR: reviewed-approved

#4697 Perfer - skip Carousel build as it fails on production mode
  scripts/bundlify-components/webpack.config.js
Labels: PR: unreviewed

#4696 <Divider/> - fix height when rendering inside a flex container
  src/Divider/Divider.st.css
Labels: <Divider/>, PR: unreviewed

#4700 <Text/> - Made visuals better
  src/Text/test/Text.visual.js
Labels: <Text/>, PR: unreviewed, Refactor

#4695 <MessageBoxMarketerialLayout/> - Remove font usage
  src/MessageBox/MarketerialLayout/MessageBoxMarketerialLayout.js
  src/MessageBox/MarketerialLayout/MessageBoxMarketerialLayout.scss
Labels: <MessageBox/>, PR: unreviewed, Refactor

#4706 release: v7.23.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#4699 <GooglePreview/> | #PROM-3311 | Adding ellipsis to url
  src/GooglePreview/GooglePreview.js
  src/GooglePreview/test/GooglePreview.visual.js
Labels: PR: unreviewed

#4711 Release 7.23.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#4709 Perfer - migrate bundle generator to use yoshi build instead
  .perfer/package.json
  .perfer/yoshi.config.js
  package.json
  perfer.config.js
Labels: PR: unreviewed

#4705 `<Avatar/>`- updating SVGs
  src/Avatar/Avatar.const.js
  src/Avatar/Avatar.js
  src/Avatar/Avatar.uni.driver.js
  src/Avatar/DataHooks.js
  src/Avatar/assets.js
  src/Avatar/docs/examples.js
  src/Avatar/test/Avatar.spec.js
  src/Avatar/test/Avatar.visual.js
  src/Avatar/test/string-to-color.spec.js
Labels: PR: unreviewed

#4712 release 7.24.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#4720 Unfreeze yoshi
  package.json
Labels: PR: unreviewed

#4725 Add rtl/ltr to Storybook
  .storybook/addons.js
  .storybook/config.js
  .storybook/visual/addons.js
  .storybook/visual/config.js
  package.json
Labels: Docs, PR: unreviewed

#4724 Generator- adding "d.ts" file to component unidriver
  .wuf/generator/templates/Component/Component.uni.driver.d.ts
Labels: PR: unreviewed

#4728 Remove text component, use its root class instead
  src/MessageBox/FunctionalLayout/MessageBoxFunctionalLayout.js
Labels: <MessageBoxFunctionalLayout/>, PR: unreviewed

#4717 3.1 Text Input – Removed Affix and disable example
  stories/TextInput/examples.js
  stories/TextInput/index.story.js
Labels: PR: unreviewed

#4729 Storybook - always show toolbar
  .storybook/config.js
  .storybook/visual/config.js
Labels: PR: unreviewed

#4730 Release version 7.25.0
  package.json
Labels: PR: unreviewed

#4685 <DataTable /> - fixed header cell cursor css when not sortable
  src/DataTable/DataTable.js
Labels: PR: reviewed-approved

#4734 Fix issue with EllipsisHOC creating new components on each render
  src/common/EllipsisHOC/EllipsisHOC.js
Labels: PR: reviewed-approved

#4732 <Stepper/> - Use transparent background for error step circle style
  src/Stepper/Step/StepCircle/StepCircle.st.css
Labels: PR: reviewed-approved

#4737 Add storybook-snapper to fix visual flakiness
  package.json
  src/NoBorderInput/test/NoBorderInput.visual.js
  src/SidebarHeader/test/SidebarHeader.visual.js
Labels: Internal, PR: reviewed-approved, PR: unreviewed

#4747 Set @types/node to 12.x.x
  package.json
Labels: PR: unreviewed

#4745 Storybook - fix all links in all stories
  package.json
  src/EmptyState/docs/index.story.js
  src/ModalMobileLayout/docs/index.story.js
  src/ModalPreviewLayout/docs/index.story.js
  src/StatsWidget/docs/index.story.js
  src/Typography/docs/cssClasses.story.js
  src/Typography/docs/index.story.js
  stories/CardLayout/index.story.js
  stories/Introduction/Cheatsheet/componentsFamilies/FoundationFamily.js
  stories/Introduction/Cheatsheet/componentsFamilies/InputFamily.js
  stories/Introduction/Cheatsheet/componentsFamilies/LayoutFamily/examples/CardExamples.js
  stories/Introduction/Cheatsheet/componentsFamilies/LayoutFamily/examples/PageExamples.js
  stories/Introduction/Cheatsheet/componentsFamilies/ModalFamily.js
  stories/Introduction/Cheatsheet/componentsFamilies/NavigationFamily.js
  stories/Introduction/Cheatsheet/componentsFamilies/SelectionFamily.js
  stories/Introduction/Cheatsheet/componentsFamilies/TooltipFamily.js
  stories/ModalMobileLayout/index.story.js
  stories/MultiSelect/index.story.js
  stories/NumberInput/index.story.js
  stories/PageLayout/index.story.js
  stories/PopoverMenu/index.story.js
  stories/SegmentedToggle/index.story.js
  stories/Sidebar/index.story.js
  stories/Slider/index.story.js
  stories/TextArea/index.story.js
  stories/TextInput/index.story.js
  stories/Tooltip/index.story.js
  stories/index.js
  stories/symbolsComponentsMapping/storybookMapping.js
Labels: Docs, PR: unreviewed

#4744 Release 7.26.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#4600 Remove unused _fixedContainerStyle
  src/Page/Page.js
Labels: PR: unreviewed

#4748 Docs - update react version required
  README.md
  docs/migration/v6-v7.md
Labels: Docs, PR: unreviewed

#4650 <DataTable/> - add propType for onSortClick
  src/DataTable/DataTable.js
Labels: PR: unreviewed

#4746 `<NumberInput/>`- fixing defaultValue logic
  src/NumberInput/NumberInput.js
  src/NumberInput/test/NumberInput.spec.js
Labels: PR: unreviewed

#4750 Commiting auto generated files after new component
  .wuf/components.json
  src/Box/docs/index.story.js
  testkit/enzyme.d.ts
  testkit/enzyme.js
  testkit/index.d.ts
  testkit/index.js
  testkit/protractor.d.ts
  testkit/protractor.js
  testkit/puppeteer.d.ts
  testkit/puppeteer.js
Labels: PR: unreviewed

#4742 Typography - Define Text API
  src/Avatar/Avatar.st.css
  src/Foundation/stylable/fonts/helvetica.st.css
  src/Foundation/stylable/typography.st.css
  src/SidebarHeader/SidebarHeader.st.css
  src/SidebarSectionTitle/SidebarSectionTitle.st.css
  src/Text/Text.st.css
  src/Text/test/Text.visual.js
Labels: PR: unreviewed, Refactor, Typography

#4751 Release version 7.27.0
  package.json
Labels: PR: unreviewed

#4752 ❤️ 🎅Updated Readme.md ❤️🎅
  README.md
Labels: PR: unreviewed

#4754 <PopoverMenu /> add dataHook in documentation
  src/PopoverMenu/PopoverMenu.js
  src/beta/PopoverMenu/PopoverMenu.js
Labels: PR: unreviewed

#4756 <PopoverMenu/> - Fix SSR rendering
  src/PopoverMenu/PopoverMenu.js
Labels: PR: unreviewed

#4757 Release 7.28.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#4616 <Table> Enlarge table select checkbox click area
  src/Table/Table.js
  src/Table/Table.st.css
Labels: PR: unreviewed

#4753 Typography - Remove explicit font-family definition
  src/Badge/Badge.st.css
  src/CircularProgressBar/CircularProgressBar.st.css
  src/FormField/FormField.scss
  src/Foundation/stylable/typography.st.css
  src/Heading/Heading.st.css
  src/LinearProgressBar/LinearProgressBar.st.css
Labels: Internal, PR: unreviewed, Typography

#4760 Fix PopoverMenu columns documentation
  src/beta/PopoverMenu/PopoverMenu.js
Labels: PR: unreviewed

#4761 yoshi lint --fix
  src/AutoCompleteWithLabel/test/AutoCompleteWithLabel.visual.js
  src/Avatar/docs/index.story.js
  src/Breadcrumbs/test/Breadcrumbs.spec.js
  src/CalendarPanel/tests/CalendarPanel.spec.js
  src/ColorPicker/ColorPicker.uni.driver.js
  src/ColorPicker/ColorPickerConverterHsb.js
  src/ColorPicker/ColorPickerConverterRGB.js
  src/CounterBadge/index.js
  src/DataTable/test/DataTable.spec.js
  src/DragAndDrop/Draggable/components/DraggableTarget.js
  src/DragAndDrop/docs/SortableList/index.js
  src/Dropdown/Dropdown.protractor.driver.js
  src/Dropdown/tests/Dropdown.spec.js
  src/DropdownLayout/test/DropdownLayout.spec.js
  src/FormField/FormField.puppeteer.driver.js
  src/Loader/docs/index.story.js
  src/ModalSelectorLayout/test/ModalSelectorLayout.spec.js
  src/NestableList/NestableList.spec.js
  src/PageHeader/docs/index.story.js
  src/Range/docs/ExampleStandard.js
  src/RichTextInputArea/Toolbar/RichTextToolbar.private.uni.driver.js
  src/SectionHelper/docs/index.story.js
  src/Skeleton/docs/index.story.js
  src/SortableList/SortableList.spec.js
  src/Swatches/Swatches.uni.driver.js
  src/Tabs/docs/index.story.js
  src/Thumbnail/docs/index.story.js
  stories/FieldWithSelectionComposite/FieldWithSelectionTemplate.js
  stories/Introduction/Cheatsheet/sharedComponents/index.js
  testkit/component-definitions.js
  testkit/polyfills/index.js
Labels: Internal, PR: unreviewed

#4763 <NoBorderInput/> - Remove explicit use of font
  src/NoBorderInput/NoBorderInput.driver.js
  src/NoBorderInput/NoBorderInput.js
  src/NoBorderInput/NoBorderInput.scss
  src/NoBorderInput/dataHooks.js
Labels: PR: unreviewed, Refactor, Typography

#4768 Infra: remove prepublishOnly from publish flow
  package.json
Labels: PR: reviewed-approved

#4772 Make tests more robust
  src/Box/Box.private.uni.driver.js
  src/Box/test/Box.spec.js
  src/DropdownLayout/test/DropdownLayout.spec.js
  src/EditableSelector/EditableSelector.driver.js
  src/EditableSelector/EditableSelector.spec.js
  src/EditableSelector/EditableSelector.uni.driver.js
  src/GoogleAddressInput/GoogleAddressInput.spec.js
  src/Input/tests/Input.spec.js
  src/ListItemAction/ListItemAction.uni.driver.js
  src/ListItemAction/test/ListItemAction.spec.js
  src/MessageBox/FunctionalLayout/MessageBoxFunctionalLayout.spec.js
  src/MessageBox/MarketerialLayout/MessageBoxMarketerialLayout.private.driver.js
  src/MessageBox/MarketerialLayout/MessageBoxMarketerialLayout.private.uni.driver.js
  src/MessageBox/MarketerialLayout/MessageBoxMarketerialLayout.spec.js
  src/MultiSelect/MultiSelect.driver.js
  src/MultiSelect/MultiSelect.uni.driver.js
  src/MultiSelect/test/MultiSelect.spec.js
  src/NestableList/NestableList.spec.js
  src/Notification/Notification.spec.js
  src/Tabs/test/Tabs.spec.js
  src/common/Focusable/FocusableHOC.spec.js
Labels: PR: reviewed-approved, Refactor, Testkit
