Repository wix/wix-style-react, pull requests merged in 2019-04, with the labels that each got.

#3214 <RichTextInputArea/> - add `placeholder` prop
  src/RichTextInputArea/RichTextInputArea.js
  src/RichTextInputArea/RichTextInputArea.scss
  src/RichTextInputArea/RichTextInputArea.spec.js
  src/RichTextInputArea/docs/index.story.js
Labels: RichTextArea

#3222 <DataTable/> - style attribute gets to render array
  src/DataTable/DataTable.js
Labels: type:bug

#3084 <Button/> - add header section on storypage
  src/Button/Button.e2e.js
  src/Button/Button.js
  src/Button/Button.uni.driver.js
  src/Button/README.TESTKIT.md
  src/Button/docs/README.TESTKIT.md
  src/Button/docs/Skins.md
  src/Button/docs/examples.js
  src/Button/docs/examples.scss
  src/Button/docs/index.story.js
Labels: WIP

#3242 <RichTextInputArea/> - hide placeholder after changing the block type
  src/RichTextInputArea/EditorUtilities.js
  src/RichTextInputArea/RichTextInputArea.js
  src/RichTextInputArea/RichTextInputArea.private.uni.driver.js
  src/RichTextInputArea/RichTextInputArea.scss
  src/RichTextInputArea/RichTextInputArea.spec.js
  src/RichTextInputArea/RichTextInputArea.uni.driver.js
  src/RichTextInputArea/RichTextInputAreaTypes.js
Labels: RichTextArea

#3247 <RichTextInputArea/> - add visual tests
  .storybook-test/stories.js
  src/RichTextInputArea/test/RichTextInputArea.visual.js
Labels: RichTextArea

#3110 <Tooltip/> - major refactor
  scripts/generate-testkit-exports/templates/enzyme.js
  scripts/generate-testkit-exports/templates/vanilla.js
  src/ImageViewer/ImageViewer.js
  src/Tooltip/README.SPEC.md
  src/Tooltip/TooltipNext/MIGRATION-API.md
  src/Tooltip/TooltipNext/Tooltip.js
  src/Tooltip/TooltipNext/Tooltip.meta.js
  src/Tooltip/TooltipNext/Tooltip.st.css
  src/Tooltip/TooltipNext/Tooltip.uni.driver.js
  src/Tooltip/TooltipNext/docs/Usage.md
  src/Tooltip/TooltipNext/docs/examples.js
  src/Tooltip/TooltipNext/docs/index.story.js
  src/Tooltip/TooltipNext/index.js
  src/Tooltip/TooltipNext/test/Tooltip.private.uni.driver.js
  src/Tooltip/TooltipNext/test/Tooltip.spec.js
  src/Tooltip/TooltipNext/test/storySettings.js
  src/Tooltip/index.js
  stories/index.js
  testkit/enzyme.js
  testkit/protractor.js
  testkit/puppeteer.js
  testkit/testkit-definitions.js
Labels: DO NOT MERGE, Tooltip, WIP

#3253 relocate component stories to be under "Components" category
  .storybook/webpack.config.js
  package.json
  src/AddItem/AddItem.e2e.js
  src/AddItem/docs/storySettings.js
  src/CircularProgressBar/docs/index.story.js
  src/Dropdown/Dropdown.e2e.js
  src/Dropdown/docs/ExampleControlled.js
  src/Dropdown/docs/ExampleStandard.js
  src/Dropdown/docs/ExampleWithCustomValue.js
  src/Dropdown/docs/index.story.js
  src/Dropdown/docs/storySettings.js
  src/EmptyState/docs/storySettings.js
  src/FullTextView/docs/index.story.js
  src/ImageViewer/ImageViewer.e2e.js
  src/ImageViewer/docs/index.story.js
  src/LinearProgressBar/docs/index.story.js
  src/Loader/Loader.e2e.js
  src/Loader/docs/index.story.js
  src/SideMenu/DrillView/DrillView.e2e.js
  src/SideMenu/docs/index.js
  src/StatsWidget/docs/index.story.js
  src/StatsWidget/docs/storySettings.js
  stories/Dropdown/DropdownStory.js
  stories/Dropdown/Example.js
  stories/MultiSelect/index.story.js
  stories/index.js
Labels: Docs

#3255 <RichTextInputArea/> - add disabled mode
  src/RichTextInputArea/RichTextInputArea.js
  src/RichTextInputArea/RichTextInputArea.scss
  src/RichTextInputArea/RichTextInputArea.spec.js
  src/RichTextInputArea/RichTextInputArea.uni.driver.js
  src/RichTextInputArea/Toolbar/RichTextToolbar.js
  src/RichTextInputArea/Toolbar/RichTextToolbarButton.js
  src/RichTextInputArea/Toolbar/RichTextToolbarButton.scss
  src/RichTextInputArea/Toolbar/RichTextToolbarLinkButton.js
  src/RichTextInputArea/test/RichTextInputArea.visual.js
Labels: RichTextArea

#3263 <RichTextInputArea/> - add maxHeight prop
  src/RichTextInputArea/RichTextInputArea.js
  src/RichTextInputArea/RichTextInputArea.scss
  src/RichTextInputArea/test/RichTextInputArea.visual.js
Labels: RichTextArea

#3281 <RichTextInputArea/> - support error design
  src/ErrorIndicator/ErrorIndicator.js
  src/ErrorIndicator/ErrorIndicator.scss
  src/ErrorIndicator/ErrorIndicator.spec.js
  src/ErrorIndicator/ErrorIndicator.uni.driver.js
  src/ErrorIndicator/index.js
  src/InputArea/InputArea.driver.js
  src/InputArea/InputArea.js
  src/InputArea/InputArea.scss
  src/RichTextInputArea/RichTextInputArea.js
  src/RichTextInputArea/RichTextInputArea.private.uni.driver.js
  src/RichTextInputArea/RichTextInputArea.scss
  src/RichTextInputArea/RichTextInputArea.spec.js
  src/RichTextInputArea/RichTextInputArea.uni.driver.js
  src/RichTextInputArea/Toolbar/RichTextToolbar.private.uni.driver.js
  src/RichTextInputArea/test/RichTextInputArea.visual.js
  testkit/enzyme.js
  testkit/index.js
  testkit/protractor.js
  testkit/puppeteer.js
  testkit/testkit-definitions.js
Labels: RichTextArea

#3155 add onOptionFocused to DropdownLayout
  src/DropdownLayout/DropdownLayout.js
  src/DropdownLayout/DropdownLayout.spec.js
Labels: DropdownLayout, type:feature
