Repository wix/wix-style-react, pull requests merged in 2019-01, with the labels that each got.

#2734 <MessageBoxFixedHeaderFooter/> - remove component
  src/MessageBox/MessageBoxFixedHeaderFooter.js
  src/MessageBox/MessageBoxFixedHeaderFooter.scss
Labels: Next Major Version

#2735 <Card/> - remove deprecated header components
  scripts/generate-testkit-exports/testkit-definitions.js
  src/Card/ButtonHeader/ButtonHeader.driver.js
  src/Card/ButtonHeader/ButtonHeader.js
  src/Card/ButtonHeader/ButtonHeader.spec.js
  src/Card/ButtonHeader/index.js
  src/Card/Card.js
  src/Card/CollapsedHeader/AnimationPolyfill.js
  src/Card/CollapsedHeader/CollapsedHeader.driver.js
  src/Card/CollapsedHeader/CollapsedHeader.js
  src/Card/CollapsedHeader/CollapsedHeader.spec.js
  src/Card/CollapsedHeader/README.TESTKIT.md
  src/Card/CollapsedHeader/index.js
  src/Card/LinkHeader/LinkHeader.driver.js
  src/Card/LinkHeader/LinkHeader.js
  src/Card/LinkHeader/LinkHeader.spec.js
  src/Card/LinkHeader/index.js
  testkit/component-definitions.js
Labels: Next Major Version

#2747 Typography - cleanups, remove old mixins
  src/Typography/Typography.scss
  src/Typography/Typography.spec.js
  src/Typography/Typography_INTERNAL.scss
  src/Typography/Typography_old.scss
  src/Typography/index.js
Labels: Next Major Version

#2757 V6 - Remove MultiSelect upgrade prop
  src/MultiSelect/MultiSelect.deprecated.spec.js
  src/MultiSelect/MultiSelect.js
  src/MultiSelect/MultiSelect.spec.js
Labels: Next Major Version

#2737 <Tags/> - remove useOldMargins prop flag, set the behaviour to false
  src/MultiSelect/InputWithTags.js
  src/Tag/Tag.js
  src/Tag/Tag.scss
  src/Tag/Tag.spec.js
  stories/Tag/Tag.story.js
  testkit/component-definitions.js
Labels: Next Major Version

#2743 <MessageBoxMarketerialLayout/> - remove `fixImagePosition` prop
  src/MessageBox/MessageBoxMarketerialLayout.js
  src/MessageBox/MessageBoxMarketerialLayout.scss
  src/MessageBox/MessageBoxMarketerialLayout.spec.js
  stories/MessageBox/AnnouncementExamples/DisabledAction.js
  stories/MessageBox/AnnouncementExamples/Footnote.js
  stories/MessageBox/AnnouncementExamples/PremiumAction.js
  stories/MessageBox/AnnouncementExamples/Standard.js
Labels: Next Major Version

#2738 <Text/> - remove the `bold` prop
  src/Text/MIGRATION.md
  src/Text/Text.driver.js
  src/Text/Text.js
  src/Text/Text.st.css
  stories/ModalSelectorLayout.story.js
Labels: Next Major Version

#2736 Remove old polyfills
  src/Backoffice/Tooltip/CancelAnimationPolyfill.js
  src/DatePicker/Polyfills.js
  src/utils/RangePolyfill.js
Labels: Next Major Version

#2739 Remove deprecated `Table/Toolbar` folder
  src/Table/Toolbar/TableToolbar.js
  src/Table/Toolbar/index.js
Labels: Next Major Version

#2741 <InputWithOptions/> - remove key presses methods from the driver
  src/InputWithOptions/InputWithOptions.driver.js
Labels: Next Major Version

#2742 <DataTable/> - remove the deprecated `infoTooltip` prop
  src/DataTable/DataTable.js
  stories/Table/TableExample.js
Labels: Next Major Version

#2728 Feat/thumbnail
  scripts/generate-testkit-exports/testkit-definitions.js
  src/Thumbnail/README.md
  src/Thumbnail/Thumbnail.driver.js
  src/Thumbnail/Thumbnail.driver.private.js
  src/Thumbnail/Thumbnail.e2e.js
  src/Thumbnail/Thumbnail.js
  src/Thumbnail/Thumbnail.spec.js
  src/Thumbnail/Thumbnail.st.css
  src/Thumbnail/index.js
  src/index.js
  stories/Thumbnail/exampleControlled.js
  stories/Thumbnail/examples.js
  stories/Thumbnail/index.story.js
  stories/Thumbnail/storySettings.js
  stories/Thumbnail/testStory.js
  stories/index.js
  testkit/enzyme.js
  testkit/index.js
  testkit/protractor.js
  testkit/puppeteer.js
Labels: new components

#2746 <ButtonWithOptions/>, <IconWithOptions/> - remove components
  scripts/generate-testkit-exports/testkit-definitions.js
  src/ButtonWithOptions/ButtonWithOptions.driver.js
  src/ButtonWithOptions/ButtonWithOptions.js
  src/ButtonWithOptions/ButtonWithOptions.protractor.driver.js
  src/ButtonWithOptions/ButtonWithOptions.scss
  src/ButtonWithOptions/ButtonWithOptions.spec.js
  src/ButtonWithOptions/README.TESTKIT.md
  src/ButtonWithOptions/README.md
  src/ButtonWithOptions/index.js
  src/IconWithOptions/IconWithOptions.driver.js
  src/IconWithOptions/IconWithOptions.e2e.js
  src/IconWithOptions/IconWithOptions.js
  src/IconWithOptions/IconWithOptions.protractor.driver.js
  src/IconWithOptions/IconWithOptions.scss
  src/IconWithOptions/IconWithOptions.spec.js
  src/IconWithOptions/README.TESTKIT.md
  src/IconWithOptions/README.md
  src/IconWithOptions/index.js
  src/StatsWidget/StatsWidget.driver.js
  src/StatsWidget/StatsWidget.js
  src/StatsWidget/StatsWidget.spec.js
  src/index.js
  stories/Deprecated/ButtonWithOptions/ButtonWithOptionsStandard.js
  stories/Deprecated/ButtonWithOptions/ExampleButton.scss
  stories/Deprecated/ButtonWithOptions/Template.js
  stories/Deprecated/ButtonWithOptions/index.js
  stories/Deprecated/IconWithOptions/Example.js
  stories/Deprecated/IconWithOptions/index.js
  stories/index.js
  testkit/enzyme.js
  testkit/index.js
  testkit/protractor.js
Labels: Next Major Version

#2809 <Button/> - add premium light skin
  src/Button/Button.js
  stories/Button/examples/ExamplesFilled.js
Labels: Button

#2842 `<Calendar/>` - Add `autoFocus` prop (#2838)
  src/Calendar/Calendar.driver.js
  src/Calendar/Calendar.js
  src/Calendar/Calendar.spec.js
  stories/Popover/index.story.js
Labels: version_5.x

#2797 <SegmentedToggle/> - new component
  scripts/generate-testkit-exports/testkit-definitions.js
  src/SegmentedToggle/SegmentedToggle.driver.js
  src/SegmentedToggle/SegmentedToggle.e2e.js
  src/SegmentedToggle/SegmentedToggle.js
  src/SegmentedToggle/SegmentedToggle.spec.js
  src/SegmentedToggle/SegmentedToggle.st.css
  src/SegmentedToggle/ToggleButton/ToggleButton.driver.private.js
  src/SegmentedToggle/ToggleButton/ToggleButton.js
  src/SegmentedToggle/ToggleButton/ToggleButton.spec.js
  src/SegmentedToggle/ToggleButton/ToggleButton.st.css
  src/SegmentedToggle/ToggleIcon/ToggleIcon.driver.private.js
  src/SegmentedToggle/ToggleIcon/ToggleIcon.js
  src/SegmentedToggle/ToggleIcon/ToggleIcon.spec.js
  src/SegmentedToggle/ToggleIcon/ToggleIcon.st.css
  src/SegmentedToggle/index.js
  src/index.js
  stories/SegmentedToggle/API.md
  stories/SegmentedToggle/examples.js
  stories/SegmentedToggle/index.story.js
  stories/SegmentedToggle/storySettings.js
  stories/SegmentedToggle/testStory.js
  stories/index.js
  testkit/enzyme.js
  testkit/index.js
  testkit/protractor.js
  testkit/puppeteer.js
Labels: DO NOT MERGE, WIP, new components
