Repository wix/wix-style-react, pull requests merged in 2019-08, with the labels that each got.

#3867 fix(testkits/protractor.d.ts): exclude ts definitions of components w/o protractor testkit
  .wuf/testkits/protractor-typescript.template.ejs
  testkit/protractor.d.ts
Labels: infrastructure, testkit:bug

#3881 <Text/> - extract HOC from the render function
  src/Text/ProxyText.js
Labels: Text

#3882 Cheatsheet- notification family
  stories/Introduction/Cheatsheet/ComponentsFamilies/InputFamily.js
  stories/Introduction/Cheatsheet/ComponentsFamilies/NotificationFamily.js
Labels: Docs

#3893 <StatisticsWidget/> - Add new component
  .wuf/components.json
  .wuf/testkits/definitions.js
  src/StatisticsWidget/StatisticsWidget.js
  src/StatisticsWidget/StatisticsWidget.meta.js
  src/StatisticsWidget/StatisticsWidget.st.css
  src/StatisticsWidget/StatisticsWidget.uni.driver.js
  src/StatisticsWidget/dataAttrs.js
  src/StatisticsWidget/dataHooks.js
  src/StatisticsWidget/docs/index.story.js
  src/StatisticsWidget/index.js
  src/StatisticsWidget/test/StatisticsWidget.private.uni.driver.js
  src/StatisticsWidget/test/StatisticsWidget.spec.js
  src/StatisticsWidget/test/StatisticsWidget.visual.js
  src/StatisticsWidget/test/StatisticsWidgetStories.js
  src/StatisticsWidget/test/storySettings.js
  src/index.js
  stories/index.js
  testkit/enzyme.d.ts
  testkit/enzyme.js
  testkit/index.d.ts
  testkit/index.js
  testkit/protractor.d.ts
  testkit/protractor.js
  testkit/puppeteer.d.ts
  testkit/puppeteer.js
Labels: WIP

#3900 <InputWithOptions/> - add `native` prop
  src/Dropdown/docs/ExampleNative.js
  src/Dropdown/docs/ExampleWithCustomValue.js
  src/Dropdown/docs/index.story.js
  src/InputWithOptions/InputWithOptions.js
  src/InputWithOptions/InputWithOptions.scss
  src/InputWithOptions/InputWithOptions.spec.js
  src/InputWithOptions/InputWithOptions.uni.driver.js
  test/utils/unidriver/ReactBase.js
Labels: InputWithOptions

#3884 Cheatsheet- Picker family
  stories/Introduction/Cheatsheet/ComponentsFamilies/ContentWidgetsFamily.js
  stories/Introduction/Cheatsheet/ComponentsFamilies/LayoutFamily/examples/CardExamples.js
  stories/Introduction/Cheatsheet/ComponentsFamilies/LayoutFamily/examples/TableExamples.js
  stories/Introduction/Cheatsheet/ComponentsFamilies/PickerFamily.js
  stories/Introduction/Cheatsheet/sharedComponents/Preview.js
  stories/Introduction/Cheatsheet/sharedComponents/SingleComponentStacked.js
  stories/Introduction/Cheatsheet/sharedComponents/SingleComponentStacked/Preview.js
  stories/Introduction/Cheatsheet/sharedComponents/SingleComponentStacked/index.js
  stories/Introduction/Cheatsheet/sharedComponents/index.js
Labels: Docs

#3929 cheatsheet- adding links to TextInput and TextArea
  stories/Introduction/Cheatsheet/ComponentsFamilies/InputFamily.js
  stories/Introduction/Cheatsheet/sharedComponents/ComponentStorybookName.js
  stories/Introduction/Cheatsheet/sharedComponents/ComponentsNames.js
  stories/Introduction/Cheatsheet/urlsMapping/inputsUrlsMapping.js
  stories/Introduction/Cheatsheet/urlsMapping/shared.js
Labels: Docs

#3966 <ModalPreviewLayout/> - add playground
  src/ModalPreviewLayout/docs/examples/ModalWrapper.js
  src/ModalPreviewLayout/docs/examples/ScrollableContent.js
  src/ModalPreviewLayout/docs/index.story.js
Labels: Docs, ModalPreviewLayout

#3933 cheatsheet- adding links to InputFamily
  docs/FAQ/README.md
  stories/Introduction/Cheatsheet/ComponentsFamilies/InputFamily.js
  stories/Introduction/Cheatsheet/sharedComponents/ComponentStorybookName.js
  stories/Introduction/Cheatsheet/sharedComponents/ComponentsNames.js
  stories/Introduction/Cheatsheet/sharedComponents/utils.js
  stories/symbolsComponentsMapping/InputsFamily.js
  stories/symbolsComponentsMapping/components.js
  stories/symbolsComponentsMapping/storybookMapping.js
  stories/symbolsComponentsMapping/symbols.js
Labels: Docs

#3964 <ModalPreviewLayout/> - refactor to use <Text/>
  src/ModalPreviewLayout/ModalPreviewLayout.js
  src/ModalPreviewLayout/docs/examples/ScrollableContent.js
  src/ModalPreviewLayout/docs/index.story.js
  src/ModalPreviewLayout/test/ModalPreviewLayout.spec.js
Labels: ModalPreviewLayout

#3967 <ModalPreviewLayout/> - adjust visual test
  src/ModalPreviewLayout/test/ModalPreviewLayout.visual.js
Labels: ModalPreviewLayout

#3968 cheatsheet- adding links to layout family
  stories/Introduction/Cheatsheet/ComponentsCheatsheet.js
  stories/Introduction/Cheatsheet/ComponentsFamilies/LayoutFamily/LayoutFamily.js
  stories/Introduction/Cheatsheet/ComponentsFamilies/LayoutFamily/examples/CardExamples.js
  stories/Introduction/Cheatsheet/ComponentsFamilies/LayoutFamily/examples/PageExamples.js
  stories/Introduction/Cheatsheet/ComponentsFamilies/LayoutFamily/examples/TableExamples.js
  stories/Introduction/Cheatsheet/sharedComponents/SingleComponentStacked.js
  stories/symbolsComponentsMapping/LayoutFamily.js
  stories/symbolsComponentsMapping/components.js
  stories/symbolsComponentsMapping/storybookMapping.js
  stories/symbolsComponentsMapping/symbols.js
Labels: Docs

#3973 Cheatsheet - adding links selection family
  stories/Introduction/Cheatsheet/ComponentsFamilies/SelectionFamily.js
  stories/symbolsComponentsMapping/SelectionFamily.js
  stories/symbolsComponentsMapping/components.js
  stories/symbolsComponentsMapping/symbols.js
Labels: Docs

#3982 Cheatsheet - adding links to Buttons & Navigation Family
  stories/Introduction/Cheatsheet/ComponentsFamilies/ButtonFamily.js
  stories/Introduction/Cheatsheet/ComponentsFamilies/NavigationFamily.js
  stories/Introduction/Cheatsheet/sharedComponents/ComponentNaming.js
  stories/Introduction/Cheatsheet/sharedComponents/ComponentsNames.js
  stories/symbolsComponentsMapping/ButtonsFamily.js
  stories/symbolsComponentsMapping/InputsFamily.js
  stories/symbolsComponentsMapping/NavigationFamily.js
  stories/symbolsComponentsMapping/components.js
  stories/symbolsComponentsMapping/storybookMapping.js
  stories/symbolsComponentsMapping/symbols.js
Labels: Docs

#3876 `<Inputwithoptions/>` - migrate menu opening mechanism to popover
  src/GoogleAddressInput/GoogleAddressInput.spec.js
  src/InputWithOptions/InputWithOptions.driver.js
  src/InputWithOptions/InputWithOptions.js
  src/InputWithOptions/InputWithOptions.protractor.driver.js
  src/InputWithOptions/InputWithOptions.spec.js
  src/InputWithOptions/InputWithOptions.st.css
  src/InputWithOptions/InputWithOptions.uni.driver.js
  src/InputWithOptions/docs/index.story.js
  src/MultiSelect/MultiSelect.driver.js
  stories/index.js
Labels: InputWithOptions

#3992 cheatsheet- adding links to modal & picker family
  stories/Introduction/Cheatsheet/ComponentsFamilies/ModalFamily.js
  stories/Introduction/Cheatsheet/ComponentsFamilies/PickerFamily.js
  stories/symbolsComponentsMapping/components.js
  stories/symbolsComponentsMapping/families/ModalsFamily.js
  stories/symbolsComponentsMapping/families/PickerFamily.js
  stories/symbolsComponentsMapping/storybookMapping.js
  stories/symbolsComponentsMapping/symbols.js
Labels: Docs

#4007 Cheatsheet- adding links to Other & Content Widgets families
  stories/Introduction/Cheatsheet/ComponentsFamilies/ContentWidgetsFamily.js
  stories/Introduction/Cheatsheet/ComponentsFamilies/OtherFamily.js
  stories/symbolsComponentsMapping/components.js
  stories/symbolsComponentsMapping/families/ContentWidgetsFamily.js
  stories/symbolsComponentsMapping/families/InputsFamily.js
  stories/symbolsComponentsMapping/families/OtherFamily.js
  stories/symbolsComponentsMapping/storybookMapping.js
  stories/symbolsComponentsMapping/symbols.js
Labels: Docs

#4016 Cheatsheet- adding and improving existing examples (Modals, Navigation & Inputs)
  stories/Introduction/Cheatsheet/ComponentsFamilies/InputFamily.js
  stories/Introduction/Cheatsheet/ComponentsFamilies/LayoutFamily/examples/CardExamples.js
  stories/Introduction/Cheatsheet/ComponentsFamilies/LayoutFamily/examples/PageExamples.js
  stories/Introduction/Cheatsheet/ComponentsFamilies/LayoutFamily/examples/TableExamples.js
  stories/Introduction/Cheatsheet/ComponentsFamilies/ModalFamily.js
  stories/Introduction/Cheatsheet/ComponentsFamilies/NavigationFamily.js
  stories/Introduction/Cheatsheet/ComponentsFamilies/SelectionFamily.js
  stories/symbolsComponentsMapping/components.js
  stories/symbolsComponentsMapping/families/ContentWidgetsFamily.js
  stories/symbolsComponentsMapping/families/InputsFamily.js
  stories/symbolsComponentsMapping/families/LayoutFamily.js
  stories/symbolsComponentsMapping/families/ModalsFamily.js
  stories/symbolsComponentsMapping/families/OtherFamily.js
  stories/symbolsComponentsMapping/families/SelectionFamily.js
  stories/symbolsComponentsMapping/storybookMapping.js
Labels: Docs
