Repository wix/wix-style-react, pull requests merged in 2019-11, with the labels that each got.

#4407 <PreviewWidget/>- Blank type
  .wuf/components.json
  src/PreviewWidget/PreviewWidget.js
  src/PreviewWidget/PreviewWidget.meta.js
  src/PreviewWidget/PreviewWidget.st.css
  src/PreviewWidget/PreviewWidget.uni.driver.js
  src/PreviewWidget/constants.js
  src/PreviewWidget/docs/index.story.js
  src/PreviewWidget/index.js
  src/PreviewWidget/test/PreviewWidget.spec.js
  src/PreviewWidget/test/PreviewWidget.visual.js
  src/PreviewWidget/test/storySettings.js
  src/index.js
  stories/index.js
  testkit/component-definitions.js
  testkit/enzyme.d.ts
  testkit/enzyme.js
  testkit/index.d.ts
  testkit/index.js
  testkit/protractor.d.ts
  testkit/protractor.js
  testkit/puppeteer.d.ts
  testkit/puppeteer.js
Labels: WIP, type:new components

#4444 <SidebarSectionItem/> - fix warnings
  src/SidebarSectionItem/SidebarSectionItem.st.css
  src/SidebarSectionTitle/SidebarSectionTitle.st.css
Labels: Sidebar

#4422 <DataTable> - use row reference for rowDetails instead of row number
  src/DataTable/DataTable.js
  src/DataTable/test/DataTable.spec.js
Labels: DataTable

#4445 <SidebarSectionItem/> - improve design
  src/SidebarSectionItem/SidebarSectionItem.st.css
Labels: Sidebar

#4446 <GoogleMapsLoader/> - Fix deprecation warning
  src/GoogleAddressInput/README.md
  stories/utils/GoogleAPILoader.js
Labels: GoogleAddressInput

#4429 Sidebar back button
  .wuf/components.json
  src/SidebarBackButton/SidebarBackButton.js
  src/SidebarBackButton/SidebarBackButton.meta.js
  src/SidebarBackButton/SidebarBackButton.st.css
  src/SidebarBackButton/SidebarBackButton.uni.driver.js
  src/SidebarBackButton/docs/examples.js
  src/SidebarBackButton/docs/index.story.js
  src/SidebarBackButton/index.js
  src/SidebarBackButton/test/SidebarBackButton.private.uni.driver.js
  src/SidebarBackButton/test/SidebarBackButton.spec.js
  src/SidebarBackButton/test/SidebarBackButton.visual.js
  src/SidebarBackButton/test/storySettings.js
  src/index.js
  stories/index.js
  testkit/enzyme.d.ts
  testkit/enzyme.js
  testkit/index.d.ts
  testkit/index.js
  testkit/protractor.d.ts
  testkit/protractor.js
  testkit/puppeteer.d.ts
  testkit/puppeteer.js
Labels: Sidebar

#4452 <SidebarBackButton/> - use within the Sidebar example
  stories/Sidebar/examples.js
  stories/Sidebar/index.story.js
Labels: Sidebar

#4449 <BarChart/> - fix padding according to spec
  src/BarChart/BarChart.st.css
Labels: BarChart

#4476 <SidebarSectionItem/> - change padding when drillable
  src/SidebarSectionItem/SidebarSectionItem.st.css
Labels: Sidebar

#4477 <Sidebar/> - change width to 228px
  src/Sidebar/main.scss
  src/SidebarDivider/test/SidebarDivider.visual.js
  src/SidebarHeader/SidebarHeader.st.css
  src/SidebarSectionItem/SidebarSectionItem.st.css
  src/SidebarSectionTitle/SidebarSectionTitle.st.css
Labels: Sidebar

#4447 Button Family - Fix documentation
  src/Button/docs/examples.js
  src/Button/docs/index.story.js
  src/CloseButton/docs/examples.js
  src/CloseButton/docs/index.story.js
  src/IconButton/docs/examples.js
  src/IconButton/docs/index.story.js
  src/ListItemAction/docs/examples.js
  src/ListItemAction/docs/index.story.js
  src/TextButton/TextButton.js
  src/TextButton/docs/examples.js
  src/TextButton/docs/index.story.js
  src/ToggleButton/docs/examples.js
  src/ToggleButton/docs/index.story.js
Labels: Button, IconButton, TextButton

#4414 <Tabs/> - Remove dependency in WixComponent
  src/Tabs/Tabs.js
  src/Tabs/Tabs.uni.driver.js
  src/Tabs/docs/examples.js
Labels: Tabs

#4489 <Checkbox/> - Added fullWidth prop
  src/Checkbox/Checkbox.js
  src/Checkbox/Checkbox.scss
  src/Checkbox/docs/examples.js
  src/Checkbox/docs/index.story.js
  src/Checkbox/test/Checkbox.visual.js
Labels: Checkbox

#4485 <InputWithOptions/> - Fix onClickOutside callback not triggering
  src/InputWithOptions/InputWithOptions.js
  src/InputWithOptions/InputWithOptions.spec.js
Labels: InputWithOptions

#4454 Fix PopoverMenu.MenuItem documentation
  src/beta/PopoverMenu/PopoverMenu.js
  src/beta/PopoverMenu/docs/compound.md
  src/beta/PopoverMenu/docs/testkit.md
  src/beta/PopoverMenu/index.d.ts
Labels: PR: reviewed-approved

#4494 updating setup instructions
  CONTRIBUTING.md
Labels: Docs, PR: unreviewed

#4492 Update <Modal> prop types
  src/Modal/Modal.js
Labels: PR: reviewed-approved

#4474 <PreviewWidget/> - changing component API
  src/PreviewWidget/PreviewWidget.js
  src/PreviewWidget/PreviewWidget.private.uni.driver.js
  src/PreviewWidget/PreviewWidget.st.css
  src/PreviewWidget/constants.js
  src/PreviewWidget/docs/index.story.js
  src/PreviewWidget/index.d.ts
  src/PreviewWidget/test/PreviewWidget.spec.js
  src/PreviewWidget/test/PreviewWidget.visual.js
  testkit/index.d.ts
Labels: PR: unreviewed, WIP, type:new components

#4500 Vertical tabs
  .wuf/components.json
  src/VerticalTabs/VerticalTabs.js
  src/VerticalTabs/VerticalTabs.meta.js
  src/VerticalTabs/VerticalTabs.st.css
  src/VerticalTabs/VerticalTabs.uni.driver.js
  src/VerticalTabs/docs/fullWidgetExample.js
  src/VerticalTabs/docs/index.story.js
  src/VerticalTabs/docs/storySettings.js
  src/VerticalTabs/docs/verticalTabsWithPrefixExample.js
  src/VerticalTabs/index.js
  src/VerticalTabs/test/VerticalTabs.private.uni.driver.js
  src/VerticalTabs/test/VerticalTabs.spec.js
  src/VerticalTabs/test/VerticalTabs.visual.js
  src/VerticalTabs/test/storySettings.js
  src/VerticalTabsItem/VerticalTabsItem.js
  src/VerticalTabsItem/VerticalTabsItem.meta.js
  src/VerticalTabsItem/VerticalTabsItem.st.css
  src/VerticalTabsItem/VerticalTabsItem.uni.driver.js
  src/VerticalTabsItem/docs/index.story.js
  src/VerticalTabsItem/docs/storySettings.js
  src/VerticalTabsItem/index.js
  src/VerticalTabsItem/test/VerticalTabsItem.private.uni.driver.js
  src/VerticalTabsItem/test/VerticalTabsItem.spec.js
  src/VerticalTabsItem/test/VerticalTabsItem.visual.js
  src/VerticalTabsItem/test/storySettings.js
  src/index.js
  stories/index.js
  testkit/enzyme.d.ts
  testkit/enzyme.js
  testkit/index.d.ts
  testkit/index.js
  testkit/protractor.d.ts
  testkit/protractor.js
  testkit/puppeteer.d.ts
  testkit/puppeteer.js
Labels: PR: reviewed-approved, VerticalTabs

#4501 EllipsisHOC - add `showTooltip` prop
  src/Text/docs/examples.js
  src/Text/docs/index.story.js
  src/common/EllipsisHOC/EllipsisHOC.js
  src/common/EllipsisHOC/index.js
Labels: PR: reviewed-approved

#4503 expose inputDriver from InputWithLabel driver
  src/InputWithLabel/InputWithLabel.uni.driver.js
Labels: PR: reviewed-approved

#4507 Update <ErrorIndicator> prop types
  src/ErrorIndicator/ErrorIndicator.js
Labels: PR: unreviewed

#4458 `<Swatches/> - add isEmptySwatchSelected to testkit
  src/Swatches/Swatches.uni.driver.js
  src/Swatches/test/Swatches.spec.js
Labels: PR: unreviewed

#4499 Button family - migrate stylesheets from core
  src/Button/Button.js
  src/Button/Button.st.css
  src/Button/Button.uni.driver.js
  src/CloseButton/CloseButton.js
  src/CloseButton/CloseButton.st.css
  src/FloatingNotification/FloatingNotification.js
  src/IconButton/IconButton.js
  src/IconButton/IconButton.st.css
  src/MessageBox/MarketerialLayout/MessageBoxMarketerialLayout.private.driver.js
  src/MessageBox/MarketerialLayout/MessageBoxMarketerialLayout.private.uni.driver.js
  src/MessageBox/MarketerialLayout/MessageBoxMarketerialLayout.spec.js
  src/TextButton/TextButton.js
  src/TextButton/TextButton.st.css
  src/utils/generateDataAttr.js
  src/utils/generateDataAttr.spec.js
Labels: PR: unreviewed

#4504 <FormField/> - fix puppeteer testkit getLabelValue() method
  src/FormField/FormField.puppeteer.driver.js
Labels: PR: reviewed-approved

#4509 <ImageViewer/> - remove @testing-library from the private driver
  src/ImageViewer/ImageViewer.private.driver.js
  src/ImageViewer/ImageViewer.spec.js
Labels: ImageViewer, PR: unreviewed

#4511 <InputArea/> - remove redundant usage
  src/InputArea/InputArea.js
Labels: InputArea, PR: unreviewed

#4512 <Sidebar/> - align backgroundColor with spec
  src/Sidebar/main.scss
Labels: PR: unreviewed, Sidebar

#4505 <BarChart /> - align text in a tooltip to the start of the line
  src/BarChart/BarChart.js
Labels: PR: unreviewed

#4506 <StatisticsWidget /> - align text in a tooltip to the start of the line
  src/StatisticsWidget/StatisticsItem/StatisticsItem.js
Labels: PR: unreviewed

#4514 Update to version 7.15.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#4521 Revert "Button family - migrate stylesheets from core"
  src/Button/Button.js
  src/Button/Button.st.css
  src/Button/Button.uni.driver.js
  src/CloseButton/CloseButton.js
  src/CloseButton/CloseButton.st.css
  src/FloatingNotification/FloatingNotification.js
  src/IconButton/IconButton.js
  src/IconButton/IconButton.st.css
  src/MessageBox/MarketerialLayout/MessageBoxMarketerialLayout.private.driver.js
  src/MessageBox/MarketerialLayout/MessageBoxMarketerialLayout.private.uni.driver.js
  src/MessageBox/MarketerialLayout/MessageBoxMarketerialLayout.spec.js
  src/TextButton/TextButton.js
  src/TextButton/TextButton.st.css
  src/utils/generateDataAttr.js
  src/utils/generateDataAttr.spec.js
Labels: PR: unreviewed

#4522 Release 7.15.1
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#4526 Freeze yoshi version until we resolve missing webpack.config.js file
  package.json
Labels: PR: unreviewed

#4525 <Checkbox/> - added size small
  src/Checkbox/Checkbox.js
  src/Checkbox/test/Checkbox.visual.js
Labels: Checkbox, PR: reviewed-approved, PR: unreviewed

#4517 <Table/> - Fixed missing separator border for Table.Content when column titles are hidden
  src/Table/Table.st.css
  src/Table/components/TableContent.js
  src/Table/test/Table.visual.js
Labels: PR: reviewed-approved

#4516 <BadgeOption /> added missing color styles to match those in <Badge />
  src/BadgeSelectItemBuilder/BadgeSelectItem.st.css
Labels: PR: reviewed-approved

#4519 <Breadcrumbs /> - fix onClick typing
  src/Breadcrumbs/index.d.ts
Labels: PR: reviewed-approved, types

#4528 <AutoCompleteWithLabel /> - added native support
  src/AutoCompleteWithLabel/AutoCompleteWithLabel.js
  src/InputWithOptions/InputWithOptions.scss
Labels: PR: reviewed-approved

#4508 vertical tabs component and design
  src/VerticalTabs/VerticalTabs.js
  src/VerticalTabs/VerticalTabs.uni.driver.js
  src/VerticalTabs/VerticalTabsContext.js
  src/VerticalTabs/docs/fullWidgetExample.js
  src/VerticalTabs/docs/index.story.js
  src/VerticalTabs/docs/verticalTabsExample.js
  src/VerticalTabs/docs/verticalTabsWithPrefixExample.js
  src/VerticalTabs/test/VerticalTabs.spec.js
  src/VerticalTabsItem/VerticalTabsItem.js
  src/VerticalTabsItem/VerticalTabsItem.st.css
  src/VerticalTabsItem/docs/index.story.js
Labels: PR: reviewed-changes-requested, VerticalTabs

#4495 Migrate eyes storybook version to next generation
  applitools.config.js
  package.json
  src/ImageViewer/ImageViewer.visual.js
Labels: PR: unreviewed

#4536 `<SocialPreview/> - resolve visual flakiness
  src/ImageViewer/ImageViewer.visual.js
  src/SocialPreview/tests/SocialPreview.visual.js
Labels: PR: unreviewed

#4537 `<ImageViewer/>` - make sure that onImageLoad is called after the state has been changed
  src/ImageViewer/ImageViewer.js
Labels: PR: unreviewed

#4532 <VerticalTabs/> - hover, selection and spaces design feedback
  src/VerticalTabs/VerticalTabs.js
  src/VerticalTabs/docs/index.story.js
  src/VerticalTabs/docs/verticalTabsExample.js
  src/VerticalTabsItem/VerticalTabsItem.js
  src/VerticalTabsItem/VerticalTabsItem.st.css
  src/VerticalTabsItem/docs/index.story.js
Labels: PR: unreviewed, VerticalTabs

#4542 `<SocialButton/>` - align icon to center
  src/SocialButton/SocialButton.st.css
Labels: PR: reviewed-approved

#4496 `<MobilePreviewWidget/>`- new component
  .wuf/components.json
  src/MobilePreviewWidget/MobilePreviewWidget.js
  src/MobilePreviewWidget/MobilePreviewWidget.meta.js
  src/MobilePreviewWidget/MobilePreviewWidget.st.css
  src/MobilePreviewWidget/MobilePreviewWidget.uni.driver.js
  src/MobilePreviewWidget/constants.js
  src/MobilePreviewWidget/docs/index.story.js
  src/MobilePreviewWidget/index.d.ts
  src/MobilePreviewWidget/index.js
  src/MobilePreviewWidget/test/MobilePreviewWidget.private.uni.driver.js
  src/MobilePreviewWidget/test/MobilePreviewWidget.spec.js
  src/MobilePreviewWidget/test/MobilePreviewWidget.visual.js
  src/MobilePreviewWidget/test/storySettings.js
  src/index.js
  stories/index.js
  testkit/component-definitions.js
  testkit/enzyme.d.ts
  testkit/enzyme.js
  testkit/index.d.ts
  testkit/index.js
  testkit/protractor.d.ts
  testkit/protractor.js
  testkit/puppeteer.d.ts
  testkit/puppeteer.js
Labels: PR: unreviewed, WIP, type:new components

#4423 TableActionCell: Enable setting dataHook for each action
  src/DropdownBase/DropdownBase.uni.driver.js
  src/DropdownLayout/DropdownLayout.uni.driver.js
  src/TableActionCell/TableActionCell.driver.js
  src/TableActionCell/TableActionCell.js
  src/TableActionCell/TableActionCell.st.css
  src/TableActionCell/docs/index.story.js
  src/TableActionCell/test/TableActionCell.spec.js
  src/beta/PopoverMenu/PopoverMenu.uni.driver.d.ts
  src/beta/PopoverMenu/PopoverMenu.uni.driver.js
  src/beta/PopoverMenu/docs/testkit.md
  src/beta/PopoverMenu/test/PopoverMenu.spec.js
Labels: PR: reviewed-approved

#4523 Buttons Family - migrate stylesheets to wsr & update disabled color according to specs
  src/Button/Button.js
  src/Button/Button.st.css
  src/Button/Button.uni.driver.js
  src/Button/test/Button.visual.js
  src/CloseButton/CloseButton.js
  src/CloseButton/CloseButton.st.css
  src/CloseButton/test/CloseButton.visual.js
  src/FloatingNotification/FloatingNotification.js
  src/IconButton/IconButton.js
  src/IconButton/IconButton.st.css
  src/IconButton/test/IconButton.visual.js
  src/MessageBox/MarketerialLayout/MessageBoxMarketerialLayout.private.driver.js
  src/MessageBox/MarketerialLayout/MessageBoxMarketerialLayout.private.uni.driver.js
  src/MessageBox/MarketerialLayout/MessageBoxMarketerialLayout.spec.js
  src/TextButton/TextButton.js
  src/TextButton/TextButton.st.css
  src/TextButton/contstants.js
  src/TextButton/test/TextButton.visual.js
  src/utils/ButtonHelpers/index.js
  src/utils/generateDataAttr.js
  src/utils/generateDataAttr.spec.js
Labels: PR: unreviewed

#4545 <VerticalTabs/> - add visual tests
  src/VerticalTabs/test/VerticalTabs.visual.js
  src/VerticalTabsItem/test/VerticalTabsItem.visual.js
Labels: PR: unreviewed, VerticalTabs

#4549 fix(Perfer): broken performence test
  perfer.config.js
Labels: PR: unreviewed

#4555 `<ColorInput/>`, `<DropdownBase/>` - use clickOutside of popover uni driver
  src/ColorInput/ColorInput.private.uni.driver.js
  src/ColorInput/ColorInput.spec.js
  src/DropdownBase/DropdownBase.uni.driver.js
Labels: PR: unreviewed

#4556 release(7.16.0)
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#4515 `<BrowserPreviewWidget/>`- new component
  .wuf/components.json
  src/BrowserPreviewWidget/BrowserPreviewWidget.js
  src/BrowserPreviewWidget/BrowserPreviewWidget.meta.js
  src/BrowserPreviewWidget/BrowserPreviewWidget.st.css
  src/BrowserPreviewWidget/BrowserPreviewWidget.uni.driver.js
  src/BrowserPreviewWidget/constants.js
  src/BrowserPreviewWidget/docs/index.story.js
  src/BrowserPreviewWidget/index.d.ts
  src/BrowserPreviewWidget/index.js
  src/BrowserPreviewWidget/test/BrowserPreviewWidget.private.uni.driver.js
  src/BrowserPreviewWidget/test/BrowserPreviewWidget.spec.js
  src/BrowserPreviewWidget/test/BrowserPreviewWidget.visual.js
  src/BrowserPreviewWidget/test/storySettings.js
  src/index.js
  stories/index.js
  testkit/component-definitions.js
  testkit/enzyme.d.ts
  testkit/enzyme.js
  testkit/index.d.ts
  testkit/index.js
  testkit/protractor.d.ts
  testkit/protractor.js
  testkit/puppeteer.d.ts
  testkit/puppeteer.js
Labels: PR: unreviewed, WIP, type:new components

#4546 `<EllipsisHOC/>` - make sure that fallback element gets ellipsed before the hoc gets onLoaded
  src/common/EllipsisHOC/index.js
Labels: PR: unreviewed

#4550 `<MobilePreviewWidget/>`- adding scroll to large content
  src/MobilePreviewWidget/MobilePreviewWidget.st.css
  src/MobilePreviewWidget/docs/index.story.js
  src/MobilePreviewWidget/test/MobilePreviewWidget.visual.js
Labels: PR: unreviewed, WIP, type:new components

#4561 Revert "Buttons Family - migrate stylesheets to wsr & update disabled color according to specs"
  src/Button/Button.js
  src/Button/Button.st.css
  src/Button/Button.uni.driver.js
  src/Button/test/Button.visual.js
  src/CloseButton/CloseButton.js
  src/CloseButton/CloseButton.st.css
  src/CloseButton/test/CloseButton.visual.js
  src/FloatingNotification/FloatingNotification.js
  src/IconButton/IconButton.js
  src/IconButton/IconButton.st.css
  src/IconButton/test/IconButton.visual.js
  src/MessageBox/MarketerialLayout/MessageBoxMarketerialLayout.private.driver.js
  src/MessageBox/MarketerialLayout/MessageBoxMarketerialLayout.private.uni.driver.js
  src/MessageBox/MarketerialLayout/MessageBoxMarketerialLayout.spec.js
  src/TextButton/TextButton.js
  src/TextButton/TextButton.st.css
  src/TextButton/contstants.js
  src/TextButton/test/TextButton.visual.js
  src/utils/ButtonHelpers/index.js
  src/utils/generateDataAttr.js
  src/utils/generateDataAttr.spec.js
Labels: PR: unreviewed

#4562 Release 7.16.1
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#4559 Table: Enable setting origin for selection change event
  src/Table/BulkSelection/BulkSelection.js
  src/Table/Table.js
  src/Table/Table.spec.js
  src/Table/components/TableBulkSelectionCheckbox.js
  src/Table/docs/CONTEXT_README.API.md
Labels: PR: reviewed-approved

#4502 <Table /> - exposed virtualized table List ref
  src/DataTable/DataTable.js
  src/Table/Table.js
Labels: PR: unreviewed

#4560 <InputWithOptions/> - Fix some testkit methods not working in Puppeteer environment
  src/AutoComplete/tests/Autocomplete.spec.js
  src/Dropdown/Dropdown.uni.driver.js
  src/InputWithOptions/InputWithOptions.protractor.driver.js
  src/InputWithOptions/InputWithOptions.proxy.driver.js
  src/InputWithOptions/InputWithOptions.uni.driver.js
Labels: PR: unreviewed

#4566 <Sidebar/> - render borderRight only for light skin
  src/Sidebar/main.scss
Labels: PR: unreviewed, Sidebar

#4564 <AutoCompleteWithLabel /> - added isEditing state
  src/AutoCompleteWithLabel/AutoCompleteWithLabel.js
  src/AutoCompleteWithLabel/AutoCompleteWithLabel.uni.driver.js
  src/AutoCompleteWithLabel/test/AutoCompleteWithLabel.spec.js
Labels: PR: unreviewed

#4563 <SidebarSectionItem /> - change partial chevron opacity
  src/SidebarSectionItem/SidebarSectionItem.st.css
Labels: PR: reviewed-changes-requested

#4567 <AutoCompleteWithLabel /> - expose hasError in testkit
  src/AutoCompleteWithLabel/AutoCompleteWithLabel.uni.driver.js
Labels: PR: reviewed-approved

#4539 <Page /> <Page.Tail /> - when content overflows scrollbar appears fix
  src/Page/Page.js
  src/Page/constants.js
Labels: PR: reviewed-approved

#4571 <Checkbox/> - Fix children width
  src/Checkbox/Checkbox.scss
Labels: Checkbox, PR: unreviewed

#4456 modifications for <Selector /> component
  src/Selector/Selector.js
  src/Selector/Selector.scss
Labels: PR: reviewed-approved

#4574 <Checkbox/> - Fix children width
  src/Checkbox/Checkbox.scss
Labels: Checkbox, PR: unreviewed

#4558 <BrowserPreviewWidget/>,<PreviewWidget/>,<MobilePreviewWidget/> - docs fixes
  src/BrowserPreviewWidget/docs/index.story.js
  src/BrowserPreviewWidget/test/storySettings.js
  src/MobilePreviewWidget/test/storySettings.js
  src/PreviewWidget/PreviewWidget.js
  src/PreviewWidget/PreviewWidget.st.css
  src/PreviewWidget/docs/index.story.js
  src/PreviewWidget/test/storySettings.js
Labels: PR: unreviewed, type:new components

#4575 <AddItem/> - Fix onClick not triggering on first click
  src/AddItem/AddItem.js
  src/AddItem/AddItem.st.css
Labels: PR: reviewed-approved

#4438 improve ModalSelectorLayout
  src/ModalSelectorLayout/ModalSelectorLayout.js
Labels: PR: reviewed-approved

#4577 release(7.17.0)
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#4570 Adjust sidebar elements according to the spec
  src/Sidebar/colors.st.css
  src/Sidebar/docs/InnerMenuExample.js
  src/Sidebar/main.st.css
  src/SidebarBackButton/SidebarBackButton.st.css
  src/SidebarBackButton/docs/examples.js
  src/SidebarDivider/SidebarDivider.st.css
  src/SidebarDivider/docs/examples.js
  src/SidebarHeader/SidebarHeader.st.css
  src/SidebarHeader/docs/examples.js
  src/SidebarSectionItem/SidebarSectionItem.js
  src/SidebarSectionItem/SidebarSectionItem.st.css
  src/SidebarSectionItem/docs/examples.js
  src/SidebarSectionItem/docs/index.story.js
  src/SidebarSectionTitle/SidebarSectionTitle.js
  src/SidebarSectionTitle/SidebarSectionTitle.st.css
  src/SidebarSectionTitle/docs/examples.js
  src/SidebarSectionTitle/docs/index.story.js
  stories/Sidebar/examples.js
Labels: PR: reviewed-approved

#4581 Support keyboard navigation in sidebar
  src/SidebarBackButton/SidebarBackButton.js
  src/SidebarBackButton/SidebarBackButton.st.css
  src/SidebarSectionItem/SidebarSectionItem.js
  src/SidebarSectionItem/SidebarSectionItem.st.css
Labels: PR: unreviewed

#4586 Make TableActionCell use beta PopupMenu only with upgrade flag
  src/TableActionCell/TableActionCell.driver.js
  src/TableActionCell/TableActionCell.js
  src/TableActionCell/docs/index.story.js
  src/TableActionCell/test/TableActionCell.spec.js
Labels: PR: reviewed-approved, Table

#4587 chore: release v7.18.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#4588 Generator- adding types to generator
  .wuf/generator/templates/Component/index.d.ts
Labels: PR: unreviewed

#4580 `<Proportion>` - add new type to disabled aspectRation holder
  src/Proportion/Proportion.js
  src/Proportion/Proportion.uni.driver.js
  src/Proportion/docs/index.story.js
  src/Proportion/ratios.js
  src/Proportion/test/Proportion.spec.js
Labels: PR: unreviewed

#4576 <InputWithLabel />, <AutoCompleteWithLabel /> - added icon to error message
  src/AutoCompleteWithLabel/AutoCompleteWithLabel.js
  src/AutoCompleteWithLabel/AutoCompleteWithLabel.scss
  src/InputWithLabel/InputWithLabel.js
  src/InputWithLabel/InputWithLabel.st.css
  src/InputWithLabel/InputWithLabel.uni.driver.js
  src/LabelledElement/LabelledElement.scss
Labels: PR: reviewed-approved

#4592 add node to title types
  src/Selector/Selector.js
Labels: PR: reviewed-approved

#4579 `EmptyState` - Add textAlign prop to EmptyState component
  src/EmptyState/EmptyState.driver.js
  src/EmptyState/EmptyState.js
  src/EmptyState/EmptyState.scss
  src/EmptyState/EmptyState.spec.js
  src/EmptyState/EmptyState.uni.driver.js
  src/EmptyState/EmptyState.visual.js
  src/EmptyState/docs/index.story.js
Labels: PR: unreviewed

#4599 Fix TableActionCell testkit documentation
  src/TableActionCell/README.TESTKIT.md
Labels: PR: reviewed-approved

#4594 make marketial message box look good with no header/image components …
  src/MessageBox/MarketerialLayout/MarketrialLayout.visual.js
  src/MessageBox/MarketerialLayout/MessageBoxMarketerialLayout.js
  src/MessageBox/MarketerialLayout/MessageBoxMarketerialLayout.scss
  src/MessageBox/docs/Announcement.js
  src/MessageBox/docs/AnnouncementExamples/WithoutHeader.js
  src/MessageBox/test/MessageBox.visual.js
Labels: MessageBox, PR: reviewed-changes-requested, PR: unreviewed

#4602 release/7.19.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#4593 `<FillPreview/>` - expose aspectRation prop and fix broken stretch on display:flex
  src/FillPreview/FillPreview.js
  src/FillPreview/FillPreview.st.css
  src/InfoIcon/test/InfoIcon.visual.js
  src/MediaOverlay/docs/examples/content.js
Labels: PR: unreviewed

#4601 <SortableList/> - Fix issue where dragged preview item had the wrong width
  src/DragAndDrop/Draggable/components/DraggableSource.js
Labels: PR: unreviewed

#4557 <ListItemSelect/> - new component
  .wuf/components.json
  src/ListItemAction/docs/examples.js
  src/ListItemAction/docs/index.story.js
  src/ListItemSelect/ListItemSelect.js
  src/ListItemSelect/ListItemSelect.meta.js
  src/ListItemSelect/ListItemSelect.st.css
  src/ListItemSelect/ListItemSelect.uni.driver.js
  src/ListItemSelect/docs/index.story.js
  src/ListItemSelect/index.js
  src/ListItemSelect/test/ListItemSelect.private.uni.driver.js
  src/ListItemSelect/test/ListItemSelect.spec.js
  src/ListItemSelect/test/ListItemSelect.visual.js
  src/ListItemSelect/test/storySettings.js
  src/index.js
  stories/index.js
  testkit/enzyme.d.ts
  testkit/enzyme.js
  testkit/index.d.ts
  testkit/index.js
  testkit/protractor.d.ts
  testkit/protractor.js
  testkit/puppeteer.d.ts
  testkit/puppeteer.js
Labels: PR: unreviewed

#4610 refactor(Generator): improve sample test expectation
  .wuf/generator/templates/Component/test/Component.spec.js
Labels: PR: unreviewed

#4307 <TimeTable/> - new component
  .wuf/components.json
  .wuf/testkits/enzyme-typescript.template.ejs
  .wuf/testkits/vanilla-typescript.template.ejs
  perfer.config.js
  src/TimeTable/TimeTable.js
  src/TimeTable/TimeTable.meta.js
  src/TimeTable/TimeTable.st.css
  src/TimeTable/TimeTable.uni.driver.d.ts
  src/TimeTable/TimeTable.uni.driver.js
  src/TimeTable/components/Item.js
  src/TimeTable/components/Item.st.css
  src/TimeTable/constants.js
  src/TimeTable/docs/examples/customContent.js
  src/TimeTable/docs/examples/disabled.js
  src/TimeTable/docs/examples/header.js
  src/TimeTable/docs/examples/structure.js
  src/TimeTable/docs/index.story.js
  src/TimeTable/docs/playgroundData.js
  src/TimeTable/index.d.ts
  src/TimeTable/index.js
  src/TimeTable/test/TimeTable.private.uni.driver.js
  src/TimeTable/test/TimeTable.spec.js
  src/TimeTable/test/TimeTable.visual.js
  src/TimeTable/test/storySettings.js
  src/index.d.ts
  src/index.js
  stories/index.js
  test/types/TimeTable.tsx
  testkit/enzyme.d.ts
  testkit/enzyme.js
  testkit/index.d.ts
  testkit/index.js
  testkit/protractor.d.ts
  testkit/protractor.js
  testkit/puppeteer.d.ts
  testkit/puppeteer.js
Labels: PR: reviewed-approved

#4572 <ListItemSection/> - New component
  .wuf/components.json
  src/ListItemAction/docs/index.story.js
  src/ListItemSection/ListItemSection.js
  src/ListItemSection/ListItemSection.meta.js
  src/ListItemSection/ListItemSection.st.css
  src/ListItemSection/ListItemSection.uni.driver.js
  src/ListItemSection/docs/index.story.js
  src/ListItemSection/index.js
  src/ListItemSection/test/ListItemSection.private.uni.driver.js
  src/ListItemSection/test/ListItemSection.spec.js
  src/ListItemSection/test/ListItemSection.visual.js
  src/ListItemSection/test/storySettings.js
  src/ListItemSelect/ListItemSelect.js
  src/ListItemSelect/docs/index.story.js
  src/index.js
  stories/index.js
  testkit/enzyme.d.ts
  testkit/enzyme.js
  testkit/index.d.ts
  testkit/index.js
  testkit/protractor.d.ts
  testkit/protractor.js
  testkit/puppeteer.d.ts
  testkit/puppeteer.js
Labels: PR: unreviewed

#4596 Upgrade to eyes-storybook version 3
  applitools.config.js
  package.json
Labels: PR: unreviewed

#4607 <Card /> & <Card.Content /> controls and size props added
  src/Card/Card.js
  src/Card/Card.scss
  src/Card/Card.visual.js
  src/Card/Content/Content.js
  src/Card/Content/Content.scss
  src/Card/Content/index.d.ts
  src/Card/docs/CompoundComponents.md
  src/Card/docs/index.story.js
  src/Card/index.d.ts
Labels: PR: reviewed-approved

#4595 <MarketingLayout /> - new component
  .wuf/components.json
  src/CloseButton/index.js
  src/MarketingLayout/Content/Content.js
  src/MarketingLayout/Content/Description.js
  src/MarketingLayout/Content/Heading.js
  src/MarketingLayout/Content/index.js
  src/MarketingLayout/MarketingLayout.js
  src/MarketingLayout/MarketingLayout.meta.js
  src/MarketingLayout/MarketingLayout.st.css
  src/MarketingLayout/MarketingLayout.uni.driver.js
  src/MarketingLayout/constants.js
  src/MarketingLayout/dataHooks.js
  src/MarketingLayout/docs/examples.js
  src/MarketingLayout/docs/index.story.js
  src/MarketingLayout/index.d.ts
  src/MarketingLayout/index.js
  src/MarketingLayout/test/MarketingLayout.private.uni.driver.js
  src/MarketingLayout/test/MarketingLayout.spec.js
  src/MarketingLayout/test/MarketingLayout.visual.js
  src/MarketingLayout/test/storySettings.js
  src/index.js
  stories/index.js
  testkit/enzyme.d.ts
  testkit/enzyme.js
  testkit/index.d.ts
  testkit/index.js
  testkit/protractor.d.ts
  testkit/protractor.js
  testkit/puppeteer.d.ts
  testkit/puppeteer.js
Labels: PR: reviewed-approved

#4618 <LinearProgressBar /> bug fix: error tooltip is shown with empty content #4597
  src/LinearProgressBar/LinearProgressBar.js
  src/LinearProgressBar/test/LinearProgressBar.spec.js
Labels: PR: reviewed-approved

#4619 <ListItemSelect/> <ListItemSection/> - Update examples
  src/ListItemSection/docs/index.story.js
  src/ListItemSelect/ListItemSelect.js
  src/ListItemSelect/docs/index.story.js
Labels: PR: unreviewed

#4615 <TimeTable/> - Fix header color according to specs
  src/TimeTable/TimeTable.st.css
Labels: PR: reviewed-approved
