Repository wix/wix-style-react, pull requests merged in 2019-03, with the labels that each got.

#3048 <RichTextInputArea/> - add missing component tests
  src/RichTextArea/RichTextAreaLinkForm.js
  src/RichTextInputArea/RichTextInputArea.js
  src/RichTextInputArea/RichTextInputArea.private.driver.js
  src/RichTextInputArea/RichTextInputArea.spec.js
  src/RichTextInputArea/RichTextToolbar.driver.js
  src/RichTextInputArea/RichTextToolbar.js
  src/RichTextInputArea/RichTextToolbar.private.driver.js
  src/RichTextInputArea/RichTextToolbarButton.js
  src/RichTextInputArea/RichTextToolbarLinkButton.js
  testkit/protractor.js
  testkit/puppeteer.js
Labels: RichTextArea

#3060 <RichTextInputArea/> - align link form according to the design system
  src/RichTextInputArea/RichTextInputArea.spec.js
  src/RichTextInputArea/RichTextInputAreaForm.js
  src/RichTextInputArea/RichTextInputAreaForm.scss
  src/RichTextInputArea/RichTextInputAreaLinkForm.js
  src/RichTextInputArea/RichTextToolbar.private.driver.js
  src/RichTextInputArea/RichTextToolbarLinkButton.js
Labels: RichTextArea

#3065 <RichTextInputArea/> - fix minor styling issues related to link button
  src/RichTextInputArea/RichTextToolbar.js
  src/RichTextInputArea/RichTextToolbarButton.js
  src/RichTextInputArea/RichTextToolbarLinkButton.js
Labels: RichTextArea

#3064 `<PopoverMenu/>` - add `moveBy` prop
  src/PopoverMenu/PopoverMenu.js
Labels: popovermenu

#3070 <RichTextInputArea/> - apply active style on toggled buttons
  src/RichTextInputArea/RichTextInputArea.spec.js
  src/RichTextInputArea/RichTextToolbar.js
  src/RichTextInputArea/RichTextToolbar.private.driver.js
Labels: RichTextArea

#3073 <RichTextInputArea/> - support inserting links for existing text
  src/RichTextInputArea/RichTextInputAreaLinkForm.js
  src/RichTextInputArea/RichTextToolbar.js
  src/RichTextInputArea/RichTextToolbarLinkButton.js
Labels: RichTextArea

#3090 <RichTextInputArea/> - add missing unit tests
  src/RichTextInputArea/EditorUtilities.js
  src/RichTextInputArea/EditorUtilities.spec.js
  src/RichTextInputArea/RichTextInputArea.js
  src/RichTextInputArea/RichTextToolbar.js
Labels: RichTextArea

#3104 <RichTextInputArea> - organize the code and apply better structure
  src/RichTextInputArea/Form/RichTextInputAreaForm.js
  src/RichTextInputArea/Form/RichTextInputAreaForm.scss
  src/RichTextInputArea/Form/RichTextInputAreaLinkForm.js
  src/RichTextInputArea/RichTextInputArea.js
  src/RichTextInputArea/RichTextInputArea.private.driver.js
  src/RichTextInputArea/RichTextInputArea.spec.js
  src/RichTextInputArea/RichTextToolbar.driver.js
  src/RichTextInputArea/Toolbar/RichTextToolbar.js
  src/RichTextInputArea/Toolbar/RichTextToolbar.private.driver.js
  src/RichTextInputArea/Toolbar/RichTextToolbar.scss
  src/RichTextInputArea/Toolbar/RichTextToolbarButton.js
  src/RichTextInputArea/Toolbar/RichTextToolbarButton.scss
  src/RichTextInputArea/Toolbar/RichTextToolbarLinkButton.js
  testkit/protractor.js
  testkit/puppeteer.js
Labels: RichTextArea

#3072 <DateInput /> - new component
  src/DateInput/DateInput.js
  src/DateInput/DateInput.private.uni.driver.js
  src/DateInput/DateInput.uni.driver.js
  src/DateInput/docs/index.story.js
  src/DateInput/docs/storySettings.js
  src/DateInput/index.js
  src/DateInput/test/DateInput.e2e.js
  src/DateInput/test/DateInput.spec.js
  src/DateInput/test/storySettings.js
  src/DateInput/test/testStories.js
  src/DatePicker/DatePicker.driver.js
  src/DatePicker/DatePicker.js
  src/Input/IconAffix/IconAffix.js
  src/Input/IconAffix/IconAffix.scss
  src/index.js
  stories/index.js
  testkit/enzyme.js
  testkit/index.js
  testkit/protractor.js
  testkit/puppeteer.js
  testkit/testkit-definitions.js
Labels: Pending:Review

#3108 docs: remove UXStoryTemplate
  src/MultiSelect/docs/index.story.js
  src/Search/docs/examples/Expandable.js
  src/Search/docs/examples/Predicate.js
  src/Search/docs/index.story.js
  src/Typography/docs/BasicExample.js
  src/Typography/docs/TypographyClassesStory.js
  src/Typography/docs/TypographyStory.js
  src/Typography/docs/cssClasses.story.js
  src/Typography/docs/examples.js
  src/Typography/docs/index.story.js
  src/Typography/test/HeadingClassesExample.js
  src/Typography/test/TestStory.js
  src/Typography/test/TextClassesExample.js
  stories/TextArea/index.story.js
  stories/TextInput/index.story.js
  stories/UXStoryTemplate.js
  stories/index.js
  stories/utils/sections.js
Labels: Docs

#3109 component generator: update generated story.js with sections
  scripts/component-generator/__test__/__snapshots__/copy-templates.spec.js.snap
  scripts/component-generator/templates/component/src/Component/docs/index.story.js
  src/GeneratedTestComponent/docs/index.story.js
  stories/utils/LiveCodeExample/index.js
  stories/utils/allComponents.js
Labels: Docs

#3105 add minRows prop - works with autoGrow + test it
  src/InputArea/InputArea.e2e.js
  src/InputArea/InputArea.js
Labels: WIP

#3113 <RichTextInputAreaLinkForm/> - make component to be non-pure
  src/RichTextInputArea/Form/RichTextInputAreaLinkForm.js
Labels: RichTextArea

#3124 <RichTextToolbarLinkButton/> - improve component
  src/RichTextInputArea/Form/RichTextInputAreaLinkForm.js
  src/RichTextInputArea/Toolbar/RichTextToolbarLinkButton.js
Labels: RichTextArea

#3074 <EditableTitle/> - new component to compose in the PageHeader
  src/EditableTitle/EditableTitle.e2e.js
  src/EditableTitle/EditableTitle.js
  src/EditableTitle/EditableTitle.meta.js
  src/EditableTitle/EditableTitle.scss
  src/EditableTitle/EditableTitle.spec.js
  src/EditableTitle/EditableTitle.uni.driver.js
  src/EditableTitle/README.md
  src/EditableTitle/docs/index.story.js
  src/EditableTitle/docs/storySettings.js
  src/EditableTitle/index.js
  src/Heading/Heading.spec.js
  src/Input/Input.scss
  src/index.js
  stories/index.js
  testkit/enzyme.js
  testkit/index.js
  testkit/protractor.js
  testkit/puppeteer.js
  testkit/testkit-definitions.js
Labels: WIP

#3129 updated TextInput doc example
  stories/TextInput/index.story.js
Labels: Docs

#3125 Infra: implement eyes-storybook - initial commit (WIP)
  .gitignore
  .storybook-test/addons.js
  .storybook-test/config.js
  .storybook-test/stories.js
  .storybook-test/stories.scss
  .storybook-test/webpack.config.js
  applitools.config.js
  package.json
  src/AddItem/tests/AddItem.visual.js
Labels: WIP

#3154 <RichTextToolbar/> - improve component
  src/RichTextInputArea/Toolbar/RichTextToolbar.js
  src/RichTextInputArea/Toolbar/RichTextToolbar.private.driver.js
  src/RichTextInputArea/Toolbar/RichTextToolbarLinkButton.js
Labels: RichTextArea

#3153 `<Modal/>` (fix&change): Fix broken `zIndex` prop. Change default zIndex value from `11` to `5000`
  src/Modal/Modal.driver.js
  src/Modal/Modal.js
  src/Modal/Modal.spec.js
  src/ZIndex.js
Labels: Modal, bug

#3149 enable passing prop showOptionsIfEmptyInput to search
  src/Search/Search.js
  src/Search/Search.spec.js
Labels: Search

#3082 <IconButton/> - migrate to sections documentation
  src/IconButton/IconButton.e2e.js
  src/IconButton/IconButton.js
  src/IconButton/docs/examples.js
  src/IconButton/docs/examples/ButtonsSpacing.scss
  src/IconButton/docs/examples/ExamplesAnchor.js
  src/IconButton/docs/examples/ExamplesPrimary.js
  src/IconButton/docs/examples/ExamplesRouter.js
  src/IconButton/docs/examples/ExamplesSecondary.js
  src/IconButton/docs/examples/ExamplesSizes.js
  src/IconButton/docs/examples/index.js
  src/IconButton/docs/index.story.js
  src/IconButton/docs/testStory.js
  src/IconButton/docs/testkit.md
Labels: WIP

#3085 <CloseButton/> - migrate to sections documentation
  src/CloseButton/CloseButton.e2e.js
  src/CloseButton/docs/examples.js
  src/CloseButton/docs/examples/ButtonsSpacing.scss
  src/CloseButton/docs/examples/ExamplesCustomIcons.js
  src/CloseButton/docs/examples/ExamplesSizes.js
  src/CloseButton/docs/examples/ExamplesSkins.js
  src/CloseButton/docs/examples/index.js
  src/CloseButton/docs/index.story.js
  src/CloseButton/docs/testkit.md
Labels: WIP

#3157 <RichTextInputArea/> - make texts to be configurable
  src/RichTextInputArea/Form/RichTextInputAreaForm.js
  src/RichTextInputArea/Form/RichTextInputAreaLinkForm.js
  src/RichTextInputArea/RichTextInputArea.js
  src/RichTextInputArea/RichTextInputAreaContext.js
  src/RichTextInputArea/RichTextInputAreaTexts.js
  src/RichTextInputArea/Toolbar/RichTextToolbar.js
Labels: RichTextArea

#3175 <RichTextInputArea/> - improve component
  src/RichTextInputArea/EditorUtilities.js
  src/RichTextInputArea/Form/RichTextInputAreaLinkForm.js
  src/RichTextInputArea/RichTextInputArea.js
  src/RichTextInputArea/RichTextInputAreaTexts.js
Labels: RichTextArea

#3176 <EditableTitle/> minor style fix
  src/EditableTitle/EditableTitle.scss
Labels: EditableTitle

#3187 <RichTextInputArea/> - fix broken tests
  package.json
  src/RichTextInputArea/EditorUtilities.js
  src/RichTextInputArea/Form/RichTextInputAreaLinkForm.js
  src/RichTextInputArea/RichTextInputArea.e2e.js
  src/RichTextInputArea/RichTextInputArea.js
  src/RichTextInputArea/RichTextInputArea.spec.js
  src/RichTextInputArea/Toolbar/RichTextToolbar.private.driver.js
Labels: RichTextArea

#3197 <RichTextToolbar/> - apply active style when editor is focused
  src/RichTextInputArea/EditorUtilities.js
  src/RichTextInputArea/RichTextInputArea.spec.js
  src/RichTextInputArea/Toolbar/RichTextToolbar.js
  src/RichTextInputArea/Toolbar/RichTextToolbar.private.driver.js
Labels: RichTextArea, WIP

#3203 <RichTextInputArea/> - change `value` prop to `initialValue`
  src/RichTextInputArea/RichTextInputArea.js
  src/RichTextInputArea/RichTextInputArea.spec.js
  src/RichTextInputArea/docs/examples/ExampleRichTextInputArea.js
  src/RichTextInputArea/docs/index.story.js
Labels: RichTextArea
