Repository wix/wix-style-react, pull requests merged in 2019-02, with the labels that each got.

#2906 feat(SectionHelper): add preview theme
  src/SectionHelper/SectionHelper.driver.js
  src/SectionHelper/SectionHelper.spec.js
  src/SectionHelper/index.js
  src/SectionHelper/styles.scss
  src/Slider/Slider.scss
Labels: SectionHelper

#2914 <RichTextArea/> - implement basic input area with Draft.js
  package.json
  src/RichTextInputArea/RichTextInputArea.driver.js
  src/RichTextInputArea/RichTextInputArea.driver.private.js
  src/RichTextInputArea/RichTextInputArea.e2e.js
  src/RichTextInputArea/RichTextInputArea.js
  src/RichTextInputArea/RichTextInputArea.scss
  src/RichTextInputArea/RichTextInputArea.spec.js
  src/RichTextInputArea/index.js
  src/index.js
  stories/RichTextInputArea/index.story.js
  stories/RichTextInputArea/storySettings.js
  stories/index.js
  testkit/enzyme.js
  testkit/index.js
  testkit/protractor.js
  testkit/puppeteer.js
  testkit/testkit-definitions.js
Labels: RichTextArea

#2932 <RichTextInputArea/> - add e2e tests
  src/RichTextInputArea/RichTextInputArea.driver.js
  src/RichTextInputArea/RichTextInputArea.driver.private.js
  src/RichTextInputArea/RichTextInputArea.e2e.js
  src/RichTextInputArea/RichTextInputArea.spec.js
  stories/RichTextInputArea/examples/ExampleRichTextInputArea.js
  stories/RichTextInputArea/index.story.js
Labels: RichTextArea

#2943 <RichTextInputArea/> - use RichContentEditor instead of Draft.js
  package.json
  src/RichTextInputArea/RichTextInputArea.js
  src/RichTextInputArea/RichTextInputArea.scss
Labels: RichTextArea

#2944 Add e2e runtime tests against `dist` with GC and yoshi app
  .eslintignore
  package.json
  src/GeneratedTestComponent/GeneratedTestComponent.js
  src/GeneratedTestComponent/GeneratedTestComponent.spec.js
  stories/GeneratedTestComponent/index.story.js
  test/e2e-runtime/imports/.gitignore
  test/e2e-runtime/imports/index.js
  test/e2e-runtime/imports/jest-yoshi.config.js
  test/e2e-runtime/imports/package.json
  test/e2e-runtime/imports/src/cjs/App.js
  test/e2e-runtime/imports/src/cjs/index.js
  test/e2e-runtime/imports/src/es-named/App.js
  test/e2e-runtime/imports/src/es-named/index.js
  test/e2e-runtime/imports/src/es/App.js
  test/e2e-runtime/imports/src/es/index.js
  test/e2e-runtime/imports/src/index.vm
  test/e2e-runtime/imports/test/e2e/cjs.spec.js
  test/e2e-runtime/imports/test/e2e/es-named.spec.js
  test/e2e-runtime/imports/test/e2e/es.spec.js
  test/e2e-runtime/imports/velocity.data.json
  test/e2e-runtime/imports/vm.js
Labels: infrastructure

#2997 <RichTextAreaComposite /> - remove from storybook and deprecate the component
  CHANGELOG.md
  src/RichTextAreaComposite/RichTextAreaComposite.js
  stories/RichTextAreaComposite/RichTextAreaComposite.scss
  stories/RichTextAreaComposite/RichTextAreaCompositeExample.js
  stories/RichTextAreaComposite/RichTextAreaCompositeTemplate.js
  stories/RichTextAreaComposite/index.js
  stories/index.js
Labels: Docs

#2989 <RichTextArea> - separate current story page to index, api and test pages
  src/RichTextArea/RichTextArea.e2e.js
  stories/RichTextArea/RichTextArea.story.js
  stories/RichTextArea/RichTextAreaExample.js
  stories/RichTextArea/RichTextAreaExample.scss
  stories/RichTextArea/RichTextAreaTemplate.js
  stories/RichTextArea/api.story.js
  stories/RichTextArea/examples.js
  stories/RichTextArea/index.story.js
  stories/RichTextArea/storySettings.js
  stories/RichTextArea/testStory.js
  stories/index.js
Labels: Docs

#3007 < RichTextArea/> - improve index page examples
  stories/RichTextArea/examples.js
  stories/RichTextArea/index.story.js
Labels: Docs

#3014 `<Page/>` (Docs) Page Layout story - add buttons and PopoverMenu
  stories/PageLayout/ExampleGeneralLayout.js
  stories/PageLayout/ExampleSplitLayout.js
Labels: Docs, Page

#3030 <RichTextInputArea/> - create toolbar component (with bold, italic, underline & lists)
  src/RichTextInputArea/RichTextInputArea.js
  src/RichTextInputArea/RichTextInputArea.scss
  src/RichTextInputArea/RichTextToolbar.js
  src/RichTextInputArea/RichTextToolbar.scss
  src/RichTextInputArea/RichTextToolbarButton.js
  src/RichTextInputArea/RichTextToolbarButton.scss
Labels: RichTextArea

#3038 <RichTextToolbar/> - fix toggle style for toolbar buttons
  src/RichTextInputArea/RichTextToolbar.js
Labels: RichTextArea

#3040 <RichTextInputArea/> - use vanilla Draft.js instead of RCE
  package.json
  src/RichTextInputArea/RichTextInputArea.js
  src/RichTextInputArea/RichTextInputArea.scss
  src/RichTextInputArea/RichTextToolbar.js
Labels: RichTextArea

#3026 InputUniDriver - Unidriver migration/input
  src/Input/Input.driver.js
  src/Input/Input.js
  src/Input/Input.spec.js
  src/Input/Input.uni.driver.js
  test/utils/react/index.js
  test/utils/unidriver/ReactBase.js
Labels: WIP

#3047 <RichTextInputArea/> - add link button
  src/RichTextInputArea/RichTextInputArea.js
  src/RichTextInputArea/RichTextInputArea.scss
  src/RichTextInputArea/RichTextInputAreaTypes.js
  src/RichTextInputArea/RichTextToolbar.js
  src/RichTextInputArea/RichTextToolbarLinkButton.js
Labels: RichTextArea

#3012 (Unidriver): Add Some New Unidrivers
  src/Heading/Heading.spec.js
  src/Heading/Heading.uni.driver.js
  src/Input/Input.js
  src/Input/Input.spec.js
  src/Input/Input.uni.driver.js
  src/Popover/Popover.spec.js
  src/Text/Text.spec.js
  src/Text/Text.uni.driver.js
  src/Tooltip/Tooltip.spec.js
  src/Tooltip/Tooltip.uni.driver.js
  test/utils/react/index.js
  test/utils/unidriver/ReactBase.js
  test/utils/unidriver/StylableUnidriverUtil.js
  test/utils/unidriver/index.js
Labels: Unidriver, enhancement
