Repository wix/wix-style-react, pull requests merged in 2020-02, with the labels that each got.

#4940 <Calendar/> - fix faulty test
  src/Calendar/test/Calendar.spec.js
Labels: <Calendar/>, PR: unreviewed

#4936 <MarketingLayout/> - adjusted paddings, added image background
  src/MarketingLayout/MarketingLayout.js
  src/MarketingLayout/MarketingLayout.st.css
  src/MarketingLayout/components/Content.js
  src/MarketingLayout/docs/examples.js
  src/MarketingLayout/docs/index.story.js
  src/MarketingLayout/index.d.ts
  src/MarketingLayout/test/MarketingLayout.visual.js
  stories/Introduction/Cheatsheet/componentsFamilies/ContentWidgetsFamily.js
  stories/Introduction/Cheatsheet/componentsFamilies/InputFamily.js
  stories/Introduction/Cheatsheet/componentsFamilies/PickerFamily.js
  stories/Introduction/Cheatsheet/sharedComponents/Preview.js
  stories/symbolsComponentsMapping/components.js
  stories/symbolsComponentsMapping/families/contentWidgetsFamily.js
  stories/symbolsComponentsMapping/symbols.js
Labels: PR: unreviewed

#4943 Add missing index.d.ts prop type reexports
  src/index.d.ts
Labels: PR: unreviewed

#4944 Release 7.39.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#4945 Fix index.d.ts types
  src/index.d.ts
Labels: PR: unreviewed

#4946 Release 7.39.1
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#4941 CloseButton - add large size
  src/CloseButton/CloseButton.js
  src/CloseButton/CloseButton.private.uni.driver.js
  src/CloseButton/CloseButton.st.css
  src/CloseButton/constants.js
  src/CloseButton/docs/examples.js
  src/CloseButton/docs/index.story.js
  src/CloseButton/test/CloseButton.spec.js
Labels: PR: unreviewed

#4938 Chromatic - lets test them out
  .ci_config
  package.json
Labels: PR: unreviewed

#4947 Revert "Chromatic - lets test them out "
  .ci_config
  package.json
Labels: PR: unreviewed

#4949 <MarketingLayout/> - Fixed issue where background color would hide an image
  src/MarketingLayout/MarketingLayout.st.css
  src/MarketingLayout/test/MarketingLayout.visual.js
Labels: PR: reviewed-approved

#4932 `<Slider/>`- Changing css
  src/Slider/Slider.js
  src/Slider/Slider.scss
  src/Slider/SliderHandle.js
  src/Slider/SliderHandle.st.css
  wallaby.js
Labels: PR: unreviewed, WIP

#4948 Chromatic - add another visual testing provider to test them.
  .ci_config
  package.json
Labels: PR: unreviewed

#4793 <Accordion/> - change expand behavior to happen when title is clicked
  src/Accordion/Accordion.private.uni.driver.js
  src/Accordion/Accordion.spec.js
  src/Accordion/Accordion.uni.driver.js
  src/Accordion/AccordionItem/AccordionItem.js
  src/Accordion/AccordionItem/AccordionItem.st.css
  src/Accordion/test/Accordion.visual.js
Labels: PR: unreviewed

#4952 Component generator: add named exports to index.d.ts file
  .wuf/generator/codemods/index-ts-file.js
  .wuf/generator/codemods/index.js
Labels: PR: reviewed-approved

#4935 Side panel
  .wuf/components.json
  src/Card/Content/Content.js
  src/SidePanel/COMPOUND_README.API.md
  src/SidePanel/Content/Content.js
  src/SidePanel/Content/Content.st.css
  src/SidePanel/Content/index.d.ts
  src/SidePanel/Content/index.js
  src/SidePanel/Divider/Divider.js
  src/SidePanel/Divider/Divider.st.css
  src/SidePanel/Divider/index.d.ts
  src/SidePanel/Divider/index.js
  src/SidePanel/Footer/Footer.js
  src/SidePanel/Footer/Footer.st.css
  src/SidePanel/Footer/index.d.ts
  src/SidePanel/Footer/index.js
  src/SidePanel/Header/Header.js
  src/SidePanel/Header/Header.st.css
  src/SidePanel/Header/index.d.ts
  src/SidePanel/Header/index.js
  src/SidePanel/SidePanel.js
  src/SidePanel/SidePanel.meta.js
  src/SidePanel/SidePanel.st.css
  src/SidePanel/SidePanel.uni.driver.d.ts
  src/SidePanel/SidePanel.uni.driver.js
  src/SidePanel/SidePanelAPI.js
  src/SidePanel/constants.js
  src/SidePanel/docs/FixedPositionExample.js
  src/SidePanel/docs/index.story.js
  src/SidePanel/index.d.ts
  src/SidePanel/index.js
  src/SidePanel/test/SidePanel.private.uni.driver.js
  src/SidePanel/test/SidePanel.spec.js
  src/SidePanel/test/SidePanel.visual.js
  src/SidePanel/test/storySettings.js
  src/index.js
  stories/index.js
  testkit/enzyme.d.ts
  testkit/enzyme.js
  testkit/index.d.ts
  testkit/index.js
  testkit/protractor.d.ts
  testkit/protractor.js
  testkit/puppeteer.d.ts
  testkit/puppeteer.js
Labels: PR: unreviewed

#4956 Infra: Improve TS declaration type-checking
  package.json
  test/types/Tooltip.tsx
  tsconfig.declarations.json
Labels: PR: reviewed-approved

#4955 `<Slider/>`- changing tooltip color
  src/Slider/SliderHandle.js
  src/Slider/SliderHandle.st.css
Labels: PR: unreviewed

#4957 Release 7.40.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#4803 <Accordion/> - add light skin
  src/Accordion/Accordion.js
  src/Accordion/AccordionItem/AccordionItem.js
  src/Accordion/AccordionItem/AccordionItem.st.css
  src/Accordion/constants.js
  src/Accordion/docs/examples.js
  src/Accordion/docs/index.story.js
  src/Accordion/test/Accordion.visual.js
Labels: PR: unreviewed

#4920 Checkbox - Migrate to stylable
  perfer.config.js
  src/Checkbox/Checkbox.driver.js
  src/Checkbox/Checkbox.js
  src/Checkbox/Checkbox.protractor.driver.js
  src/Checkbox/Checkbox.scss
  src/Checkbox/Checkbox.st.css
  src/Checkbox/Checkbox.uni.driver.js
  src/Checkbox/constants.js
  src/Checkbox/test/Checkbox.private.uni.driver.js
Labels: <Checkbox/>, PR: reviewed-changes-requested, PR: unreviewed, Refactor

#4958 <SidePanel/> - Export TS types for testkits and add types to index.d.ts
  .wuf/testkits/enzyme-typescript.template.ejs
  .wuf/testkits/vanilla-typescript.template.ejs
  src/index.d.ts
  testkit/enzyme.d.ts
  testkit/index.d.ts
Labels: PR: reviewed-approved

#4950 named imports readme update
  README.md
Labels: PR: reviewed-approved

#4176 Update "3.12 Tag Input" story documentation
  stories/MultiSelect/examples.js
  stories/MultiSelect/index.story.js
  stories/MultiSelect/storySettings.js
Labels: PR: unreviewed

#4964 Fix grid css for chrome 80 problem
  src/ColorInput/tests/ColorInput.visual.js
  src/Layout/Layout/index.js
  src/Layout/Layout/index.spec.js
  src/Layout/Layout/styles.scss
  src/Layout/docs/examples/HolyGrail.js
Labels: PR: unreviewed

#4961 Generator - rearrange
  .wuf/generator/templates/$ComponentName/$ComponentName.js
  .wuf/generator/templates/$ComponentName/$ComponentName.uni.driver.js
  .wuf/generator/templates/$ComponentName/index.d.ts
  .wuf/generator/templates/$ComponentName/test/$ComponentName.private.uni.driver.js
Labels: Infrastructure, PR: unreviewed

#4960 Typography - fixed headings weights
  .storybook/e2e/stories.scss
  .storybook/stories.scss
  .storybook/visual/stories.scss
  src/Foundation/stylable/typography.st.css
  src/Heading/Heading.st.css
  src/typography-helpers.scss
Labels: PR: unreviewed, Typography

#4963 FontUpgrade + MadeforToggle addon
  .storybook/addons/MadeforToggle/index.js
  .storybook/addons/MadeforToggle/register.js
  .storybook/addons/MadeforToggle/shared.js
  .storybook/config.js
  .storybook/main.js
  .storybook/preview-head.html
  .storybook/stories.scss
  .wuf/components.json
  src/FontUpgrade/FontUpgrade.js
  src/FontUpgrade/FontUpgrade.meta.js
  src/FontUpgrade/FontUpgrade.scss
  src/FontUpgrade/FontUpgrade.uni.driver.d.ts
  src/FontUpgrade/FontUpgrade.uni.driver.js
  src/FontUpgrade/context.js
  src/FontUpgrade/docs/index.story.js
  src/FontUpgrade/index.d.ts
  src/FontUpgrade/index.js
  src/FontUpgrade/test/FontUpgrade.private.uni.driver.js
  src/FontUpgrade/test/FontUpgrade.spec.js
  src/FontUpgrade/test/storySettings.js
  src/index.d.ts
  src/index.js
  stories/index.js
  testkit/enzyme.d.ts
  testkit/enzyme.js
  testkit/index.d.ts
  testkit/index.js
  testkit/protractor.d.ts
  testkit/protractor.js
  testkit/puppeteer.d.ts
  testkit/puppeteer.js
Labels: Infrastructure, PR: unreviewed, Typography

#4966 Release 7.41.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#4954 <TableActionCell/> - add `divider` field for the secondary actions
  src/TableActionCell/TableActionCell.driver.js
  src/TableActionCell/TableActionCell.js
  src/TableActionCell/constants.js
  src/TableActionCell/docs/examples/SecondaryWithDividerExample.js
  src/TableActionCell/docs/index.story.js
  src/TableActionCell/test/TableActionCell.private.uni.driver.js
  src/TableActionCell/test/TableActionCell.visual.js
Labels: <TableActionCell/>, PR: unreviewed

#4962 `<Slider/>`- adding custom marks feature
  src/Slider/Slider.driver.js
  src/Slider/Slider.js
  src/Slider/Slider.protractor.driver.js
  src/Slider/Slider.spec.js
  src/Slider/Slider.uni.driver.js
  src/Slider/SliderHandle.js
  src/Slider/constants.js
  src/Slider/docs/examples.js
  src/Slider/docs/index.story.js
  src/Slider/tests/Slider.visual.js
Labels: <Slider/>, PR: unreviewed

#4969 <Avatar/> - Added onClick prop
  package.json
  src/Avatar/Avatar.js
  src/Avatar/Avatar.st.css
  src/Avatar/Avatar.uni.driver.d.ts
  src/Avatar/Avatar.uni.driver.js
  src/Avatar/constants.js
  src/Avatar/docs/examples.js
  src/Avatar/docs/index.story.js
  src/Avatar/index.d.ts
  src/Avatar/test/Avatar.spec.js
  test/types/Avatar.tsx
Labels: PR: unreviewed

#4970 release/7.42.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#4971 move the css variables to body
  .storybook/e2e/stories.scss
  .storybook/visual/stories.scss
  src/FontUpgrade/FontUpgrade.js
  src/FontUpgrade/FontUpgrade.scss
  src/Foundation/stylable/typography.st.css
Labels: PR: unreviewed, Typography

#4972 Add dynamic minutes step in <TimePicker />
  src/TimeInput/TimeInput.js
  src/TimeInput/test/TimeInput.spec.js
Labels: PR: reviewed-changes-requested

#4977 fix(scss): invalid comments
  src/Input/Input.scss
  src/Layout/Cell/styles.scss
  src/PageHeader/PageHeader.scss
Labels: PR: unreviewed, WIP

#4975 Revert body styles, fix types
  src/FontUpgrade/FontUpgrade.js
  src/FontUpgrade/FontUpgrade.scss
  src/FontUpgrade/index.d.ts
Labels: PR: reviewed-approved, Typography

#4979 <SidePanel/> - update types
  src/SidePanel/Header/index.d.ts
  src/SidePanel/index.d.ts
  test/types/SidePanel.tsx
Labels: PR: reviewed-approved

#4981 docs(Mobile Web): add guidelines
  docs/usage/MOBILE_WEB_GUIDELINES.md
Labels: Docs, PR: unreviewed

#4980 <Tag/> - Remove dependency on deprecated ButtonLayout component
  src/Tag/Tag.private.driver.js
  src/Tag/Tag.private.uni.driver.js
  src/Tag/tests/Tag.spec.js
Labels: PR: reviewed-approved

#4983 Playground - use initiallyOpen prop
  package.json
  stories/Playground/Playground.js
Labels: PR: reviewed-approved

#4965 `<ModalPreviewLayout/>`- adding tooltip props for close button & navigation buttons
  src/ModalPreviewLayout/ModalPreviewLayout.js
  src/ModalPreviewLayout/ModalPreviewLayout.st.css
  src/ModalPreviewLayout/NavigationButton/NavigationButton.js
  src/ModalPreviewLayout/docs/examples/MultipleContent.js
  src/ModalPreviewLayout/test/ModalPreviewLayout.private.uni.driver.js
  src/ModalPreviewLayout/test/ModalPreviewLayout.spec.js
  src/ModalPreviewLayout/test/testStory.js
Labels: <ModalPreviewLayout/>, PR: reviewed-approved, PR: unreviewed

#4986 <TextLink/> - Fix deprecation warning
  src/Deprecated/TextLink/TextLink.js
Labels: PR: reviewed-approved

#4984 release 7.43.0
  package.json
Labels: PR: unreviewed

#4988 <Tag/> - Remove dependency on deprecated Button component
  src/Tag/Tag.driver.js
Labels: PR: unreviewed

#4991 <Grid/> - Added visuals
  src/Grid/docs/ExampleAutoAdjustedRow.js
  src/Grid/test/Grid.visual.js
Labels: <Grid/>

#4987 Add listItemSelectBuilder types
  src/ListItemSelect/index.d.ts
  test/types/ListItemSelect.tsx
Labels: PR: unreviewed

#4933 Updated DropdownBase testkit docs
  src/DropdownBase/DropdownBase.uni.driver.js
Labels: PR: unreviewed

#4968 <RichTextInputArea/> - fix extra empty line-breaks
  src/RichTextInputArea/EditorUtilities.js
  src/RichTextInputArea/test/RichTextInputArea.spec.js
Labels: <RichTextInputArea/>, PR: unreviewed

#4992 <Grid/> - change hard codded class name
  src/Grid/Grid.js
  src/Grid/Grid.scss
Labels: <Grid/>

#4985 Add listItemSectionBuilder types
  src/ListItemSection/index.d.ts
  src/index.d.ts
  test/types/ListItemSection.tsx
Labels: PR: unreviewed

#4995 <Search/> - Story Page
  src/Search/Search.js
  src/Search/docs/examples.js
  src/Search/docs/examples/Expandable.js
  src/Search/docs/examples/Predicate.js
  src/Search/docs/examples/index.js
  src/Search/docs/index.story.js
  src/Search/docs/testStory.js
  src/Search/test/Search.e2e.js
  src/Search/test/Search.spec.js
  src/Search/test/Search.visual.js
  src/Search/test/storySettings.js
Labels: <Search/>

#5007 Counter badge
  .wuf/components.json
  .wuf/testkits/definitions.js
  perfer.config.js
  src/CounterBadge/CounterBadge.driver.js
  src/CounterBadge/CounterBadge.js
  src/CounterBadge/CounterBadge.meta.js
  src/CounterBadge/CounterBadge.protractor.driver.js
  src/CounterBadge/CounterBadge.st.css
  src/CounterBadge/CounterBadge.uni.driver.d.ts
  src/CounterBadge/CounterBadge.uni.driver.js
  src/CounterBadge/MIGRATION.md
  src/CounterBadge/constants.js
  src/CounterBadge/docs/Example.js
  src/CounterBadge/docs/examples.js
  src/CounterBadge/docs/index.story.js
  src/CounterBadge/index.d.ts
  src/CounterBadge/index.js
  src/CounterBadge/test/CounterBadge.private.uni.driver.js
  src/CounterBadge/test/CounterBadge.spec.js
  src/CounterBadge/test/CounterBadge.visual.js
  src/CounterBadge/test/storySettings.js
  testkit/enzyme.js
  testkit/index.js
  testkit/protractor.js
  testkit/puppeteer.js
Labels: <CounterBadge/>

#5010 <TimeInput/> - fix visuals
  src/TimeInput/test/TimeInput.visual.js
Labels: <TimeInput/>

#5024 <StatusIndicator/> - New component
  .wuf/components.json
  src/StatusIndicator/StatusIndicator.js
  src/StatusIndicator/StatusIndicator.meta.js
  src/StatusIndicator/StatusIndicator.st.css
  src/StatusIndicator/StatusIndicator.uni.driver.d.ts
  src/StatusIndicator/StatusIndicator.uni.driver.js
  src/StatusIndicator/constants.js
  src/StatusIndicator/docs/index.story.js
  src/StatusIndicator/index.d.ts
  src/StatusIndicator/index.js
  src/StatusIndicator/test/StatusIndicator.private.uni.driver.js
  src/StatusIndicator/test/StatusIndicator.spec.js
  src/StatusIndicator/test/StatusIndicator.visual.js
  src/StatusIndicator/test/storySettings.js
  src/index.d.ts
  src/index.js
  stories/index.js
  testkit/enzyme.d.ts
  testkit/enzyme.js
  testkit/index.d.ts
  testkit/index.js
  testkit/protractor.d.ts
  testkit/protractor.js
  testkit/puppeteer.d.ts
  testkit/puppeteer.js
Labels: <StatusIndicator/>

#5029 <StatusIndicator/> - change driver
  src/StatusIndicator/StatusIndicator.js
  src/StatusIndicator/StatusIndicator.uni.driver.d.ts
  src/StatusIndicator/StatusIndicator.uni.driver.js
  src/StatusIndicator/test/StatusIndicator.spec.js
Labels: <StatusIndicator/>

#5011 `<Slider/>`- adding startPoint feature
  package.json
  src/Slider/Slider.js
  src/Slider/Slider.spec.js
  src/Slider/docs/examples.js
  src/Slider/docs/index.story.js
  src/Slider/tests/Slider.visual.js
Labels: <Slider/>

#5006 <AutoCompleteWithLabel />, <InputWithLabel /> - style fix
  src/AutoCompleteWithLabel/AutoCompleteWithLabel.js
  src/AutoCompleteWithLabel/AutoCompleteWithLabel.scss
  src/InputWithLabel/InputWithLabel.js
  src/InputWithLabel/InputWithLabel.st.css
Labels: PR: unreviewed

#5034 (WSR8) <PopoverMenu/> - remove old component
  .wuf/components.json
  .wuf/testkits/definitions.js
  package.json
  perfer.config.js
  src/Page/docs/ExampleStickyTableWithGap.js
  src/Page/docs/PageChildren.js
  src/Page/docs/PageTestStories.js
  src/Page/test/Page.e2e.js
  src/Page/test/examples/testExamples.js
  src/PopoverMenu/PopoverMenu.driver.js
  src/PopoverMenu/PopoverMenu.js
  src/PopoverMenu/PopoverMenu.protractor.driver.js
  src/PopoverMenu/PopoverMenu.scss
  src/PopoverMenu/PopoverMenu.spec.js
  src/PopoverMenu/README.TESTKIT.md
  src/PopoverMenu/docs/PopoverMenuRegressionTest.js
  src/PopoverMenu/docs/index.story.js
  src/PopoverMenu/docs/storySettings.js
  src/PopoverMenu/index.js
  src/PopoverMenuItem/PopoverMenuItem.js
  src/PopoverMenuItem/PopoverMenuItem.scss
  src/PopoverMenuItem/index.js
  src/beta/PopoverMenu/PopoverMenu.meta.js
  src/index.d.ts
  src/index.js
  stories/Introduction/Cheatsheet/componentsFamilies/LayoutFamily/examples/PageExamples.js
  stories/PageLayout/ExampleGeneralLayout.js
  stories/PageLayout/ExampleSplitLayout.js
  stories/e2e.js
  stories/index.js
  testkit/enzyme.d.ts
  testkit/enzyme.js
  testkit/index.d.ts
  testkit/index.js
  testkit/protractor.d.ts
  testkit/protractor.js
  testkit/puppeteer.d.ts
Labels: PR: unreviewed

#5033 <ListItemSelect /> - added hovered prop
  src/ListItemAction/ListItemAction.js
  src/ListItemAction/ListItemAction.st.css
  src/ListItemAction/test/ListItemAction.visual.js
  src/ListItemSelect/ListItemSelect.js
  src/ListItemSelect/ListItemSelect.st.css
  src/ListItemSelect/test/ListItemSelect.visual.js
Labels: Discussion

#4997 `<Slider/>`- expanding clickable area and aligning Slider to spec constrains (#4997)
  src/Slider/Slider.js
  src/Slider/Slider.scss
  src/Slider/SliderHandle.js
  src/Slider/SliderHandle.st.css
  src/Slider/SliderThumb.js
  src/Slider/SliderThumb.st.css
  src/Slider/constants.js
  src/Slider/docs/examples.js
  src/Slider/tests/Slider.e2e.js
  src/Slider/tests/Slider.spec.js
Labels: <Slider/>

#5045 Madefor weights and colors adjustments
  src/Avatar/Avatar.js
  src/Avatar/Avatar.st.css
  src/Breadcrumbs/Breadcrumbs.js
  src/Button/Button.js
  src/Button/Button.st.css
  src/DataTable/DataTable.js
  src/EmptyState/EmptyState.js
  src/FontUpgrade/FontUpgrade.js
  src/FontUpgrade/utils.js
  src/Foundation/stylable/typography.st.css
  src/SectionHelper/SectionHelper.js
  src/SidebarSectionItem/SidebarSectionItem.js
Labels: Typography

#5052 <ImageViewer/> - Added props status and statusMessage
  .wuf/testkits/definitions.js
  src/ImageViewer/ImageViewer.driver.js
  src/ImageViewer/ImageViewer.js
  src/ImageViewer/ImageViewer.meta.js
  src/ImageViewer/ImageViewer.protractor.driver.js
  src/ImageViewer/ImageViewer.st.css
  src/ImageViewer/ImageViewer.uni.driver.js
  src/ImageViewer/README.TESTKIT.md
  src/ImageViewer/docs/ExampleStandard.js
  src/ImageViewer/docs/examples.js
  src/ImageViewer/docs/index.story.js
  src/ImageViewer/index.js
  src/ImageViewer/test/ImageViewer.private.driver.js
  src/ImageViewer/test/ImageViewer.private.uni.driver.js
  src/ImageViewer/test/ImageViewer.spec.js
  src/ImageViewer/test/ImageViewer.visual.js
  src/ImageViewer/test/storySettings.js
  testkit/protractor.js
Labels: <ImageViewer/>

#5055 <FontUpgrade/> - Added componentWillUnmount function
  src/FontUpgrade/FontUpgrade.js
Labels: Typography

#5070 <FontUpgrade/> - Fix problem with window not defined
  src/FontUpgrade/FontUpgrade.js
  src/FontUpgrade/utils.js
Labels: Typography

#5085 <Text/> - Fix types
  src/Text/index.d.ts
  test/types/Text.tsx
Labels: Types

#5086 Types fixes
  src/FloatingHelper/FloatingHelperContent/FloatingHelperContent.d.ts
  src/FloatingHelper/index.d.ts
  src/InputWithOptions/index.d.ts
  src/common/EllipsisHOC/index.d.ts
  test/types/FloatingHelper.tsx
  test/types/Text.tsx
Labels: Types

#5106 update Input.onFocus type definitions
  src/Input/index.d.ts
Labels: PR: reviewed-approved

#5084 typings: <Input /> add types for inputRef prop
  src/Input/index.d.ts
  test/types/Input.tsx
Labels: <Input/>, Types

#5094 Improve Notification.ActionButton type definition
  src/Notification/index.d.ts
  test/types/Notification.tsx
Labels: PR: unreviewed

#5107 <ColorPicker/> - types
  package.json
  src/ColorPicker/index.d.ts
  test/types/ColorPicker.tsx
Labels: Types
