Repository wix/wix-style-react, pull requests merged in 2020-04, with the labels that each got.

#5182 contribution stories conventions
  docs/contribution/DOCUMENTING_COMPONENTS.md
Labels: PR: unreviewed

#5310 wsr7: update sync-ts
  scripts/sync-ts.sh
Labels: PR: unreviewed

#5291 Pass RowDataType to TableColumn
  src/DataTable/index.d.ts
  src/Table/index.d.ts
  test/types/Table.tsx
Labels: PR: unreviewed

#5325 docs(AutoComplete): remove background color
  src/AutoComplete/docs/index.story.js
Labels: <AutoComplete/>, Docs

#5338 <Avatar/> - support single letter in size 24 (#5332)
  src/Avatar/Avatar.js
  src/Avatar/Avatar.st.css
  src/Avatar/test/Avatar.spec.js
Labels: PR: reviewed-approved

#5354 release: 7.56.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#5358 docs(*): fix link to testing guide
  .storybook/webpack.config.js
Labels: Docs

#5327 1.4 General Use Icons
  stories/Icons/AllIcons.js
  stories/Icons/CustomIconColor.js
  stories/Icons/CustomIconSize.js
  stories/Icons/README.md
  stories/Icons/RTLIcon.js
  stories/Icons/examples.js
  stories/Icons/index.js
  stories/Icons/index.story.js
  stories/Icons/style.scss
  stories/index.js
Labels: Docs, WIP

#5372 unpin react day picker version
  package.json
  src/Calendar/Calendar.js
Labels: <Calendar/>, <DatePicker/>

#5375 [version 7.x] change applitools baseline branch for eyes-storybook
  .ci_config
Labels: PR: unreviewed

#5187 1.1 Colors
  src/Foundation/stylable/mixins/rgba_to_hex8.js
  src/colors.scss
  stories/Colors/index.story.js
  stories/Colors/storySettings.js
  stories/Introduction/Cheatsheet/componentsFamilies/FoundationFamily.js
  stories/index.js
  stories/symbolsComponentsMapping/symbols.js
Labels: Docs, PR: unreviewed, Requires UX review, WIP

#5370 <AutoCompleteWithLabel /> - fix hasError in testkit
  src/AutoCompleteWithLabel/AutoCompleteWithLabel.uni.driver.js
  src/AutoCompleteWithLabel/test/AutoCompleteWithLabel.spec.js
  src/Input/DataAttr.js
  src/Input/Input.driver.js
  src/Input/Input.uni.driver.js
  src/Input/ThemedInput.js
  src/MultiSelect/InputWithTags.js
  src/NoBorderInput/NoBorderInput.js
Labels: auto pr

#5348 <ListItemEditable/> - new component
  .wuf/components.json
  perfer.config.js
  src/ListItemEditable/ListItemEditable.js
  src/ListItemEditable/ListItemEditable.meta.js
  src/ListItemEditable/ListItemEditable.st.css
  src/ListItemEditable/ListItemEditable.uni.driver.d.ts
  src/ListItemEditable/ListItemEditable.uni.driver.js
  src/ListItemEditable/constants.js
  src/ListItemEditable/docs/examples.js
  src/ListItemEditable/docs/index.story.js
  src/ListItemEditable/index.d.ts
  src/ListItemEditable/index.js
  src/ListItemEditable/test/ListItemEditable.private.uni.driver.js
  src/ListItemEditable/test/ListItemEditable.spec.js
  src/ListItemEditable/test/ListItemEditable.tsx
  src/ListItemEditable/test/ListItemEditable.visual.js
  src/ListItemEditable/test/storySettings.js
  src/index.d.ts
  src/index.js
  stories/index.js
  testkit/component-definitions.js
  testkit/enzyme.d.ts
  testkit/enzyme.js
  testkit/index.d.ts
  testkit/index.js
  testkit/protractor.d.ts
  testkit/protractor.js
  testkit/puppeteer.d.ts
  testkit/puppeteer.js
Labels: PR: unreviewed

#5404 <Tooltip/> - wrap content with FontUpgrade
  CHANGELOG.md
  package.json
  perfer.config.js
  src/Modal/Modal.js
  src/Tooltip/TooltipNext/Tooltip.js
Labels: PR: unreviewed, wsr7

#4890 <MultiSelectCheckbox/> - Replaced list item with <ListItemSelect/>
  src/ListItemSelect/ListItemSelect.st.css
  src/ListItemSelect/index.d.ts
  src/MultiSelectCheckbox/MultiSelectCheckbox.js
  src/MultiSelectCheckbox/MultiSelectCheckbox.st.css
Labels: <MultiSelectCheckbox/>, PR: unreviewed

#5097 <TimePicker/> - Custom suffix
  src/TimeInput/TimeInput.driver.d.ts
  src/TimeInput/TimeInput.driver.js
  src/TimeInput/TimeInput.js
  src/TimeInput/TimeInput.scss
  src/TimeInput/TimeInput.uni.driver.d.ts
  src/TimeInput/TimeInput.uni.driver.js
  src/TimeInput/constants.js
  src/TimeInput/docs/index.story.js
  src/TimeInput/index.d.ts
  src/TimeInput/test/TimeInput.spec.js
  src/TimeInput/test/TimeInput.visual.js
  test/types/TimeInput.tsx
Labels: PR: unreviewed, wsr7

#5387 <Timeline/> - new component
  .wuf/components.json
  perfer.config.js
  src/Timeline/Timeline.js
  src/Timeline/Timeline.meta.js
  src/Timeline/Timeline.st.css
  src/Timeline/Timeline.uni.driver.d.ts
  src/Timeline/Timeline.uni.driver.js
  src/Timeline/TimelineItem.js
  src/Timeline/TimelineItem.st.css
  src/Timeline/constants.js
  src/Timeline/docs/examples.js
  src/Timeline/docs/index.story.js
  src/Timeline/index.d.ts
  src/Timeline/index.js
  src/Timeline/test/Timeline.private.uni.driver.js
  src/Timeline/test/Timeline.spec.js
  src/Timeline/test/Timeline.tsx
  src/Timeline/test/Timeline.visual.js
  src/Timeline/test/storySettings.js
  src/index.d.ts
  src/index.js
  stories/index.js
  testkit/component-definitions.js
  testkit/enzyme.d.ts
  testkit/enzyme.js
  testkit/index.d.ts
  testkit/index.js
  testkit/protractor.d.ts
  testkit/protractor.js
  testkit/puppeteer.d.ts
  testkit/puppeteer.js
Labels: DO NOT MERGE, WIP

#5401 Madefor font story page
  README.md
  src/Text/docs/index.story.js
  stories/Introduction/index.js
  stories/MadeforFont/index.story.js
Labels: Docs

#5400 <ToggleButton /> - Updates
  src/ToggleButton/ToggleButton.js
  src/ToggleButton/ToggleButton.st.css
  src/ToggleButton/constants.js
  src/ToggleButton/docs/examples.js
  src/ToggleButton/docs/index.story.js
  src/ToggleButton/index.d.ts
  src/ToggleButton/test/ToggleButton.spec.js
  src/ToggleButton/test/ToggleButton.tsx
  src/ToggleButton/test/ToggleButton.visual.js
Labels: DO NOT MERGE, WIP

#5423 docs(Playground): use wix-storybook-utils Playground with save/load functionality
  stories/Playground/Playground.js
Labels: Docs
