Repository wix/wix-style-react, pull requests merged in 2020-12, with the labels that each got.

#6195 <DatePicker/> - expose theming capabilities
  .wuf/components.json
  perfer.config.js
  src/Calendar/Calendar.driver.js
  src/Calendar/Calendar.js
  src/Calendar/Calendar.protractor.driver.js
  src/Calendar/Calendar.st.css
  src/Calendar/Calendar.uni.driver.js
  src/Calendar/DatePickerDropdown/DatePickerDropdown.js
  src/Calendar/DatePickerDropdown/DatePickerDropdown.st.css
  src/Calendar/DatePickerDropdown/index.js
  src/Calendar/DatePickerHead/DatePickerHead.js
  src/Calendar/DatePickerHead/DatePickerHead.st.css
  src/Calendar/DatePickerHead/MonthDropdown/MonthDropdown.js
  src/Calendar/DatePickerHead/MonthDropdown/MonthDropdown.st.css
  src/Calendar/DatePickerHead/MonthDropdown/index.js
  src/Calendar/DatePickerHead/YearDropdown/YearDropdown.js
  src/Calendar/DatePickerHead/YearDropdown/YearDropdown.st.css
  src/Calendar/DatePickerHead/YearDropdown/index.js
  src/Calendar/DatePickerHead/index.js
  src/Calendar/docs/examples.js
  src/Calendar/test/Calendar.spec.js
  src/Calendar/test/Calendar.visual.js
  src/DatePicker/DateInput/DatePicker.protractor.driver.js
  src/DatePicker/DatePicker.js
  src/DatePicker/DatePicker.protractor.driver.js
  src/DatePicker/DatePicker.st.css
  src/DatePicker/index.d.ts
  src/DatePicker/test/DatePicker.tsx
  src/DropdownBase/DropdownBase.js
  src/DropdownBase/DropdownBase.st.css
  src/DropdownLayout/DropdownLayout.js
  src/DropdownLayout/DropdownLayout.st.css
  src/DropdownLayout/index.d.ts
  src/DropdownLayout/test/DropdownLayout.tsx
Labels: PR: reviewed-approved

#6256 Typography- add medium weight to madefor typography and update components accordingly
  .storybook/preview-head.html
  .storybook/visual/preview-head.html
  perfer.config.js
  src/FontUpgrade/FontUpgrade.st.css
  src/Foundation/stylable/typography.st.css
  src/Input/Affix/Affix.js
  src/Input/Affix/Affix.st.css
  src/Input/Input.st.css
  src/Input/ThemedInput.js
  src/InputArea/InputArea.js
  src/InputArea/InputArea.st.css
  src/LabelledElement/LabelledElement.js
  src/ListItemAction/ListItemAction.js
  src/ListItemSelect/ListItemSelect.js
  src/ModalMobileLayout/docs/examples/FullscreenModal.js
  src/ModalMobileLayout/docs/examples/MobileModal.js
  src/ModalMobileLayout/docs/examples/Plain.js
  src/NoBorderInput/NoBorderInput.js
  src/NoBorderInput/NoBorderInput.st.css
  src/Notification/TextLabel/TextLabel.spec.js
  src/Notification/TextLabel/index.js
  src/Popover/docs/examples/ExampleAppendTo.js
  src/Popover/docs/examples/ExampleFixed.js
  src/Popover/docs/examples/ExampleFlip.js
  src/Popover/docs/examples/ExampleInteractive.js
  src/RichTextInputArea/RichTextInputArea.js
  src/RichTextInputArea/RichTextInputArea.st.css
  src/SegmentedToggle/ToggleButton/ToggleButton.js
  src/SidebarBackButton/SidebarBackButton.js
  src/StarsRatingBar/StarsRatingBar.js
  src/Stepper/components/Step.js
  src/Stepper/components/Step.st.css
  src/Stepper/components/StepMarker.st.css
  src/Tabs/core/TabItem/index.js
  src/Tag/Tag.js
  src/Tag/test/Tag.spec.js
  src/TimeInput/TimeInput.js
  src/TimeTable/TimeTable.js
  src/TimeTable/TimeTable.st.css
  src/Timeline/TimelineItem.js
  src/Timeline/docs/examples.js
  src/Tooltip/Tooltip.js
  src/VariableInput/EditorUtilities.js
  src/VariableInput/VariableInput.js
  src/VariableInput/VariableInput.st.css
  src/VerticalTabsItem/VerticalTabsItem.js
  stories/ModalMobileLayout/examples.js
Labels: PR: unreviewed, Typography

#6343 release 9.47.0
  CHANGELOG.md
  package.json
  perfer.config.js
Labels: PR: unreviewed

#6346 <TimeTable/>- small styles fix
  src/TimeTable/TimeTable.st.css
Labels: PR: unreviewed

#6348 release 9.47.1
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#6345 Update index.d.ts - missing props in selector list
  src/SelectorList/index.d.ts
Labels: PR: unreviewed

#6338 Themes | Business Dashboard - fixed PopoverMenu without arrow padding
  src/Themes/businessDashboard/components/PopoverMenu.st.css
Labels: PR: unreviewed

#6333 Learning - integrate swimm and training unit to create a themed component
  .swm/5owq4tf2APg5pkjyTIh6.swm
  .swm/DK3mVXm7wI5XScVZMM0m.swm
  .swm/Ihto9Xh1Br5iqEMMuNYT.swm
  .swm/NJvXK4cMwYi6UjktKU2i.swm
  .swm/NMulqUwDNJJNDs33AmbS.swm
  .swm/Pobr82y9fE8RjfS4KxDW.swm
  .swm/SGCCd6gH8RLVGOJtbk1Y.swm
  .swm/XXLoP4BpZB8vOT25orFD.swm
  .swm/XgUtlCAwgIMVtzNsUg4W.swm
  .swm/ZGD6okSinjGTY6qBvOou.swm
  .swm/ng1oByXSARd2YpgDLi34.swm
  .swm/sHMyh1VB1GB3jIdPhRtC.swm
  .swm/swimm.json
  .swm/ttiUx4QooJQTjVnsDSsS.swm
  package.json
  scripts/get-swimm.sh
  scripts/run-swimm.sh
Labels: PR: unreviewed

#6347 Fix un-needed `import as` syntax to fix compatibility issue with webpack v5
  src/MessageBox/FunctionalLayout/FooterLayout.js
  src/MessageBox/MarketerialLayout/MessageBoxMarketerialLayout.js
Labels: PR: reviewed-approved

#6352 <Sidebar/> - Fix missing scrollbar on inner menus
  src/Sidebar/Sidebar.js
Labels: PR: reviewed-approved

#6355 <Cell/> - add rows prop
  src/Layout/Cell/index.js
  src/Layout/Cell/index.spec.js
  src/Layout/docs/examples.js
  src/Layout/docs/index.story.js
  src/Layout/index.d.ts
  src/Layout/test/Layout.tsx
Labels: PR: unreviewed

#6208 <Collapse/> - implement with wix-animations
  package.json
  perfer.config.js
  src/Card/docs/index.story.js
  src/Collapse/Collapse.js
  src/Collapse/Collapse.spec.js
  src/Collapse/Collapse.st.css
Labels: PR: unreviewed

#6349 <Page/> - add fixed footer
  src/Page/FixedFooter.js
  src/Page/Page.js
  src/Page/Page.st.css
  src/Page/docs/examples.js
  src/Page/docs/index.story.js
  src/Page/test/Page.e2e.js
  src/Page/test/Page.e2eStory.js
Labels: PR: merged

#6357 Release 9.49.0
  package.json
  perfer.config.js
Labels: PR: unreviewed

#6354 <SelectorList/> - [types] update renderToggleAllCheckbox name in type
  src/SelectorList/index.d.ts
Labels: PR: partially-approved

#6351 <DropdownBase/>- expose lazy loading props
  src/DropdownBase/DropdownBase.js
  src/DropdownBase/index.d.ts
  src/DropdownBase/test/DropdownBase.tsx
  src/DropdownLayout/DropdownLayout.js
Labels: PR: unreviewed

#6358 Hide slick-track if it's width is undetermined
  src/Carousel/Carousel.st.css
Labels: PR: unreviewed

#6335 <NestableList/> - fix issue with position fixed inside parent with transform
  src/NestableList/DragLayer.js
Labels: PR: unreviewed

#6092 <ListItemSection/>- suffix fix
  src/ListItemSection/ListItemSection.js
  src/ListItemSection/ListItemSection.st.css
  src/ListItemSection/docs/index.story.js
  src/ListItemSection/test/ListItemSection.spec.js
  src/ListItemSection/test/ListItemSection.visual.js
Labels: PR: reviewed-approved

#6264 Adding support readme file
  README.md
  SUPPORT.md
  docs/FAQ/README.md
  docs/assets/GitHub-Mark-32px.png
  docs/assets/generatedLink.png
  docs/assets/playgroundSaveButton.png
  docs/usage/Troubleshooting.md
  package.json
  stories/Introduction/index.js
  stories/storiesHierarchy.js
Labels: Docs, PR: draft, PR: partially-approved, PR: reviewed-changes-requested, PR: unreviewed, WIP

#6344 useCopyClipboard - new custom hook
  package.json
  src/providers/index.js
  src/providers/useCopyClipboard/createToggleSelection.js
  src/providers/useCopyClipboard/index.d.ts
  src/providers/useCopyClipboard/index.js
  src/providers/useCopyClipboard/test/storySettings.js
  src/providers/useCopyClipboard/test/useCopyClipboard.e2e.js
  src/providers/useCopyClipboard/test/useCopyClipboard.e2eStory.js
  src/providers/useCopyClipboard/test/useCopyClipboard.spec.js
  src/providers/useCopyClipboard/useCopyClipboard.js
Labels: <CopyClipboard/>, PR: reviewed-approved, PR: unreviewed

#6363 <Page/> - [types] fix FixedFooter type
  src/Page/index.d.ts
  src/Page/test/Page.tsx
Labels: PR: unreviewed

#6361 release 9.50.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#6364 useCopyClipboard - fix and update hook
  src/providers/useCopyClipboard/test/useCopyClipboard.e2eStory.js
  src/providers/useCopyClipboard/useCopyClipboard.js
Labels: <CopyClipboard/>, PR: reviewed-approved, PR: unreviewed

#6362 Themes | Business Dashboard - Set default font weight to regular
  src/Themes/businessDashboard/components/TextButton.st.css
Labels: PR: partially-approved, Themes - Business Dashboard

#6191 <AddressInputItem/> - new component
  .wuf/components.json
  src/AddressInput/AddressInput.js
  src/AddressInputItem/AddressInputItem.js
  src/AddressInputItem/AddressInputItem.meta.js
  src/AddressInputItem/AddressInputItem.st.css
  src/AddressInputItem/AddressInputItem.uni.driver.d.ts
  src/AddressInputItem/AddressInputItem.uni.driver.js
  src/AddressInputItem/constants.js
  src/AddressInputItem/docs/examples.js
  src/AddressInputItem/docs/index.story.js
  src/AddressInputItem/index.d.ts
  src/AddressInputItem/index.js
  src/AddressInputItem/test/AddressInputItem.private.uni.driver.js
  src/AddressInputItem/test/AddressInputItem.spec.js
  src/AddressInputItem/test/AddressInputItem.tsx
  src/AddressInputItem/test/AddressInputItem.visual.js
  src/AddressInputItem/test/storySettings.js
  src/DropdownLayout/docs/index.story.js
  src/ListItemSelect/ListItemSelect.js
  src/ListItemSelect/ListItemSelect.st.css
  src/index.d.ts
  src/index.js
  stories/index.js
Labels: PR: unreviewed

#6180 <Page/> - Add scrollTo function
  src/Page/Page.js
  src/Page/docs/examples.js
  src/Page/docs/index.story.js
Labels: POC, PR: draft, PR: reviewed-approved, PR: unreviewed

#6367 <CopyClipboard/> - add new component
  .wuf/components.json
  perfer.config.js
  src/CopyClipboard/CopyClipboard.js
  src/CopyClipboard/CopyClipboard.meta.js
  src/CopyClipboard/CopyClipboard.uni.driver.d.ts
  src/CopyClipboard/CopyClipboard.uni.driver.js
  src/CopyClipboard/docs/examples.js
  src/CopyClipboard/docs/index.story.js
  src/CopyClipboard/docs/storySettings.js
  src/CopyClipboard/index.d.ts
  src/CopyClipboard/index.js
  src/CopyClipboard/test/CopyClipboard.tsx
  src/index.d.ts
  src/index.js
  stories/index.js
  testkit/component-definitions.js
Labels: <CopyClipboard/>, New Component, PR: reviewed-approved, PR: unreviewed

#6326 <Radio /> - new component
  .wuf/components.json
  perfer.config.js
  src/AddressInputItem/AddressInputItem.js
  src/Radio/Radio.js
  src/Radio/Radio.meta.js
  src/Radio/Radio.st.css
  src/Radio/Radio.uni.driver.d.ts
  src/Radio/Radio.uni.driver.js
  src/Radio/docs/examples.js
  src/Radio/docs/index.story.js
  src/Radio/index.d.ts
  src/Radio/index.js
  src/Radio/test/Radio.private.uni.driver.js
  src/Radio/test/Radio.tsx
  src/Radio/test/Radio.visual.js
  src/Radio/test/storySettings.js
  src/index.d.ts
  src/index.js
  stories/index.js
Labels: PR: partially-approved

#6324 Use places autocomplete
  src/providers/index.js
  src/providers/useDebouncedCallback/index.d.ts
  src/providers/useDebouncedCallback/index.js
  src/providers/useDebouncedCallback/useDebouncedCallback.js
  src/providers/useDebouncedCallback/useDebouncedCallback.spec.js
  src/providers/useIsMounted/index.d.ts
  src/providers/useIsMounted/index.js
  src/providers/useIsMounted/useIsMounted.js
  src/providers/useIsMounted/useIsMounted.spec.js
  src/providers/usePlacesAutocomplete/autocompleteClient.d.ts
  src/providers/usePlacesAutocomplete/index.d.ts
  src/providers/usePlacesAutocomplete/index.js
  src/providers/usePlacesAutocomplete/usePlacesAutocomplete.js
  src/providers/usePlacesAutocomplete/usePlacesAutocomplete.spec.js
  test/utils/unit/debounce.js
  test/utils/unit/index.js
Labels: PR: unreviewed

#6370 Update CHANGELOG.md
  CHANGELOG.md
Labels: PR: unreviewed

#6371 update CHANGELOG.md
  CHANGELOG.md
Labels: PR: unreviewed

#6115 <DropdownBase/> and <DropdownLayout /> - add "getSelectedOptionId" to testkit
  src/DropdownBase/DropdownBase.uni.driver.d.ts
  src/DropdownBase/DropdownBase.uni.driver.js
  src/DropdownBase/test/DropdownBase.spec.js
  src/DropdownLayout/DataAttr.js
  src/DropdownLayout/DropdownLayout.driver.d.ts
  src/DropdownLayout/DropdownLayout.driver.js
  src/DropdownLayout/DropdownLayout.js
  src/DropdownLayout/DropdownLayout.uni.driver.d.ts
  src/DropdownLayout/DropdownLayout.uni.driver.js
  src/DropdownLayout/test/DropdownLayout.spec.js
Labels: PR: reviewed-approved

#6374 Add missing semicolon that breaks the rendering
  src/Page/Page.st.css
Labels: PR: unreviewed

#6375 Themes | Business Dashboard - add perfer bundle size test
  .perfer/yoshi.config.js
  perfer.config.js
  src/Themes/businessDashboard/perfer-tests/theme/index.js
Labels: PR: unreviewed, Themes - Business Dashboard

#6330 <BadgeSelectItem/> remove extra margin-right when subtitle is enabled and expose size and suffix props
  src/BadgeSelectItem/BadgeSelectItem.js
  src/BadgeSelectItem/BadgeSelectItem.st.css
  src/BadgeSelectItem/docs/examples.js
  src/BadgeSelectItem/docs/index.story.js
  src/BadgeSelectItem/index.d.ts
  src/BadgeSelectItem/test/BadgeSelectItem.visual.js
  src/BadgeSelectItem/test/BadgeSelectItemBuilder.tsx
  src/ListItemSelect/ListItemSelect.js
Labels: PR: unreviewed

#6378 <Card/> - Expose divider props
  src/Card/Divider/index.js
Labels: PR: unreviewed

#6310 <EditableSelector> and <Selector> - scss to stylable
  src/EditableSelector/EditableRow/EditableRow.js
  src/EditableSelector/EditableSelector.js
  src/EditableSelector/EditableSelector.scss
  src/EditableSelector/EditableSelector.st.css
  src/Selector/Selector.js
  src/Selector/Selector.scss
  src/Selector/Selector.st.css
  src/Selector/Selector.uni.driver.js
  src/Selector/constants.js
  src/Selector/index.d.ts
  src/Selector/test/Selector.tsx
Labels: PR: reviewed-approved

#6380 <CustomModal/> - Expose title typography
  src/BaseModalLayout/LayoutBlocks/Header/Header.js
  src/BaseModalLayout/LayoutBlocks/Header/index.d.ts
  src/BaseModalLayout/test/BaseModalLayout.tsx
  src/CustomModalLayout/CustomModalLayout.js
  src/CustomModalLayout/docs/examples/PageExample.js
  src/CustomModalLayout/docs/index.story.js
  src/CustomModalLayout/index.d.ts
  src/CustomModalLayout/test/CustomModalLayout.tsx
Labels: PR: unreviewed

#6382 <Search/> - add a condition to update the on change function
  src/Search/Search.js
Labels: PR: unreviewed

#6385 Revert "<Search/> - add a condition to update the on change function"
  src/Search/Search.js
Labels: PR: unreviewed

#6388 <BadgeSelect/> - add missing method types to BadgeSelectUniDriver
  src/BadgeSelect/BadgeSelect.uni.driver.d.ts
Labels: PR: reviewed-approved

#6386 <Search/> - add a condition to update the on change function
  src/Search/Search.js
  src/Search/test/Search.spec.js
Labels: PR: unreviewed

#6372 <ToggleButton/> - add new skins
  src/ToggleButton/ToggleButton.js
  src/ToggleButton/ToggleButton.st.css
  src/ToggleButton/constants.js
  src/ToggleButton/docs/index.story.js
  src/ToggleButton/index.d.ts
  src/ToggleButton/test/ToggleButton.visual.js
Labels: <ToggleButton/>, PR: reviewed-approved, PR: unreviewed

#6391 Update CHANGELOG.md
  CHANGELOG.md
Labels: PR: unreviewed

#6377 Add Atlas autocomplete client
  package.json
  src/providers/index.js
  src/providers/useAtlasClient/index.d.ts
  src/providers/useAtlasClient/index.js
  src/providers/useAtlasClient/useAtlasClient.js
  src/providers/useAtlasClient/useAtlasClient.spec.js
  src/providers/usePlacesAutocomplete/autocompleteClient.d.ts
  test/jest-setup.js
Labels: PR: reviewed-approved

#6389 learning - review the swimm verify command
  package.json
Labels: PR: unreviewed

#6394 <Radio /> - fixed stylable warning
  src/Radio/Radio.st.css
Labels: PR: reviewed-approved

#6395 <CustomModalLayout/> - [types] fix subtitle type
  src/CustomModalLayout/index.d.ts
Labels: PR: unreviewed

#6397 Release to 9.54.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#6379 <Image/> - showBorder prop
  src/Foundation/stylable/colors.st.css
  src/Image/Image.js
  src/Image/Image.st.css
  src/Image/docs/examples/examples.js
  src/Image/docs/examples/fit.js
  src/Image/docs/examples/lazy.js
  src/Image/docs/examples/position.js
  src/Image/docs/examples/size.js
  src/Image/docs/examples/source.js
  src/Image/docs/index.story.js
  src/Image/index.d.ts
  src/Image/test/Image.tsx
  src/Image/test/Image.visual.js
Labels: PR: reviewed-approved

#6387 `<Dropdown/>`- improve story page
  src/Dropdown/docs/examples.js
  src/Dropdown/docs/index.story.js
Labels: PR: unreviewed

#6393 infra - remove scss tokens from unneeded file and update perfer
  .wuf/generator/codemods/perfer-config-file.js
  perfer.config.js
  src/Box/Box.js
  src/MarketingLayout/MarketingLayout.js
Labels: PR: reviewed-approved

#6268 <MultiSelect/> - add onOptionsShow/Hide to prop-types
  src/InputWithOptions/InputWithOptions.js
  src/MultiSelect/MultiSelect.js
Labels: Docs, PR: reviewed-approved, PR: unreviewed

#6392 <FormField/> - fix label placement
  src/FormField/FormField.st.css
  src/FormField/test/FormField.visual.js
Labels: <FormField/>, PR: reviewed-approved, PR: unreviewed

#6402 Update CHANGELOG.md
  CHANGELOG.md
Labels: PR: unreviewed

#6401 Revert "Add Atlas autocomplete client"
  package.json
  src/providers/index.js
  src/providers/useAtlasClient/index.d.ts
  src/providers/useAtlasClient/index.js
  src/providers/useAtlasClient/useAtlasClient.js
  src/providers/useAtlasClient/useAtlasClient.spec.js
  test/jest-setup.js
Labels: PR: unreviewed

#6398 Update Madefor section (storybook)
  src/assets/madefor_example1.png
  stories/MadeforFont/index.story.js
Labels: PR: partially-approved

#6381 <AddItem /> - test getTooltipContent in unit tests
  src/AddItem/AddItem.spec.js
  src/AddItem/test/AddItem.private.uni.driver.js
Labels: PR: unreviewed

#6384 <Image/> - border radius prop
  src/Image/Image.js
  src/Image/Image.st.css
  src/Image/docs/examples/examples.js
  src/Image/docs/index.story.js
  src/Image/index.d.ts
  src/Image/test/Image.tsx
  src/Image/test/Image.visual.js
Labels: PR: reviewed-approved

#6399 Add 'small' vertical row padding support to table/data table
  src/Table/DataTable/DataTable.js
  src/Table/DataTable/DataTable.scss
  src/Table/DataTable/README.md
  src/Table/DataTable/index.d.ts
  src/Table/Table.js
Labels: PR: reviewed-approved

#6405 Release 9.55.0
  CHANGELOG.md
  package.json
  src/Table/DataTable/DataTable.js
  src/Table/Table.js
Labels: PR: unreviewed

#6406 infra - break storybook build if a stylable warning is thrown
  .storybook/webpack.config.js
Labels: PR: unreviewed

#6413 <InputWithOptions/> - improve documentation
  src/InputWithOptions/InputWithOptions.js
Labels: PR: unreviewed

#6360 <Heading/>- new spacing specification and <WixStyleReactProvider/> - new component
  .wuf/components.json
  perfer.config.js
  src/BaseModalLayout/LayoutBlocks/Header/ModalHeading/ModalHeading.st.css
  src/Foundation/stylable/typography.st.css
  src/Heading/Heading.js
  src/Heading/Heading.st.css
  src/Heading/test/Heading.visual.js
  src/WixStyleReactProvider/WixStyleReactProvider.js
  src/WixStyleReactProvider/WixStyleReactProvider.meta.js
  src/WixStyleReactProvider/WixStyleReactProvider.uni.driver.d.ts
  src/WixStyleReactProvider/WixStyleReactProvider.uni.driver.js
  src/WixStyleReactProvider/constants.js
  src/WixStyleReactProvider/context.js
  src/WixStyleReactProvider/docs/examples.js
  src/WixStyleReactProvider/docs/index.story.js
  src/WixStyleReactProvider/index.d.ts
  src/WixStyleReactProvider/index.js
  src/WixStyleReactProvider/test/WixStyleReactProvider.private.uni.driver.js
  src/WixStyleReactProvider/test/WixStyleReactProvider.spec.js
  src/WixStyleReactProvider/test/WixStyleReactProvider.tsx
  src/WixStyleReactProvider/test/storySettings.js
  src/index.d.ts
  src/index.js
  stories/index.js
Labels: <Heading/>, PR: draft, PR: merged, PR: partially-approved, PR: reviewed-changes-requested, PR: unreviewed, WIP

#6409 <Input/> - refactor component
  src/Input/Input.js
  src/Input/index.d.ts
  src/Input/test/Input.spec.js
  src/Input/test/Input.tsx
Labels: PR: unreviewed

#6390 <MarketingLayout/> - update padding of size tiny with badge
  src/MarketingLayout/MarketingLayout.st.css
Labels: PR: partially-approved

#6312 <AnalyticsSummaryCard/> - new component
  .wuf/components.json
  perfer.config.js
  src/AnalyticsSummaryCard/AnalyticsSummaryCard.js
  src/AnalyticsSummaryCard/AnalyticsSummaryCard.meta.js
  src/AnalyticsSummaryCard/AnalyticsSummaryCard.st.css
  src/AnalyticsSummaryCard/AnalyticsSummaryCard.uni.driver.d.ts
  src/AnalyticsSummaryCard/AnalyticsSummaryCard.uni.driver.js
  src/AnalyticsSummaryCard/constants.js
  src/AnalyticsSummaryCard/docs/examples.js
  src/AnalyticsSummaryCard/docs/index.story.js
  src/AnalyticsSummaryCard/index.d.ts
  src/AnalyticsSummaryCard/index.js
  src/AnalyticsSummaryCard/test/AnalyticsSummaryCard.private.uni.driver.js
  src/AnalyticsSummaryCard/test/AnalyticsSummaryCard.spec.js
  src/AnalyticsSummaryCard/test/AnalyticsSummaryCard.tsx
  src/AnalyticsSummaryCard/test/AnalyticsSummaryCard.visual.js
  src/AnalyticsSummaryCard/test/storySettings.js
  src/index.d.ts
  src/index.js
  stories/index.js
  testkit/component-definitions.js
Labels: New Component, PR: reviewed-changes-requested, PR: unreviewed

#6350 <StatisticsWidget/> - add ellipsis to description for size tiny
  src/StatisticsWidget/StatisticsItem/StatisticsItem.js
Labels: PR: partially-approved

#6417 Storybook addon - Spacing
  .storybook/addons/MadeforToggle/index.js
  .storybook/addons/MadeforToggle/register.js
  src/Heading/docs/examples.js
Labels: PR: unreviewed

#6078 Section helper story update
  src/SectionHelper/SectionHelper.js
  src/SectionHelper/SectionHelper.uni.driver.js
  src/SectionHelper/docs/examples.js
  src/SectionHelper/docs/index.story.js
Labels: PR: unreviewed

#6418 Add Atlas autocomplete client (v2)
  package.json
  src/providers/index.js
  src/providers/useAtlasClient/index.d.ts
  src/providers/useAtlasClient/index.js
  src/providers/useAtlasClient/useAtlasClient.js
  src/providers/useAtlasClient/useAtlasClient.spec.js
  test/jest-setup.js
Labels: PR: unreviewed

#6420 Radio add unidriver
  package.json
  src/Radio/Radio.js
  src/Radio/Radio.st.css
  src/Radio/Radio.uni.driver.d.ts
  src/Radio/Radio.uni.driver.js
  src/Radio/index.d.ts
Labels: PR: reviewed-approved

#6423 Update changelog
  CHANGELOG.md
Labels: PR: unreviewed

#6422 Themes | Business Dashboard - updated circular progress bar colors
  .wuf/components.json
  src/Themes/businessDashboard/components/CircularProgressBar.st.css
  src/Themes/businessDashboard/foundations/colors.st.css
Labels: PR: reviewed-approved, Themes - Business Dashboard

#6424 <Collapse/> - skip mount transition
  package.json
  src/Collapse/Collapse.js
Labels: PR: reviewed-approved

#6421 Move `eslint-config-yoshi` from dependencies to dev dependencies
  package.json
Labels: PR: unreviewed

#6408 <RadioGroup /> - add `selectionAreaSkin` and `selectionAreaPadding` props
  src/RadioGroup/RadioButton/RadioButton.js
  src/RadioGroup/RadioGroup.js
  src/RadioGroup/RadioGroup.st.css
  src/RadioGroup/docs/examples.js
  src/RadioGroup/docs/index.story.js
  src/RadioGroup/index.d.ts
  src/RadioGroup/test/RadioGroup.tsx
Labels: PR: reviewed-approved

#6403 <Checkbox/> - add `selectionAreaSkin` and `selectionAreaPadding` props
  src/Checkbox/Checkbox.js
  src/Checkbox/Checkbox.st.css
  src/Checkbox/docs/examples.js
  src/Checkbox/docs/index.story.js
  src/Checkbox/index.d.ts
  src/Checkbox/test/Checkbox.tsx
Labels: PR: reviewed-approved, auto pr

#6425 Add documentation yaml to collect documentation for internal DOCs too
  documentation.yaml
Labels: PR: partially-approved

#6426 `<BounceAnimation/>` and `<Animate/>` components refactor
  .wuf/components.json
  perfer.config.js
  src/Animate/Animate.js
  src/Animate/Animate.uni.driver.d.ts
  src/Animate/Animate.uni.driver.js
  src/Animate/index.d.ts
  src/Animate/test/Animate.spec.js
  src/Animate/test/Animate.tsx
  src/BounceAnimation/BounceAnimation.js
  src/BounceAnimation/BounceAnimation.meta.js
  src/BounceAnimation/BounceAnimation.st.css
  src/BounceAnimation/BounceAnimation.uni.driver.d.ts
  src/BounceAnimation/BounceAnimation.uni.driver.js
  src/BounceAnimation/constants.js
  src/BounceAnimation/docs/examples.js
  src/BounceAnimation/docs/index.story.js
  src/BounceAnimation/index.d.ts
  src/BounceAnimation/index.js
  src/BounceAnimation/test/Bounce.private.uni.driver.js
  src/BounceAnimation/test/BounceAnimation.tsx
  src/BounceAnimation/test/storySettings.js
  src/index.d.ts
  src/index.js
  stories/index.js
  testkit/component-definitions.js
Labels: PR: unreviewed

#6412 Documentation improvements
  src/BaseModalLayout/BaseModalLayout.uni.driver.js
  src/CardGalleryItem/CardGalleryItem.uni.driver.js
  src/Checkbox/Checkbox.uni.driver.js
  src/Checkbox/README.TESTKIT.md
  src/CircularProgressBar/CircularProgressBar.uni.driver.js
  src/CircularProgressBar/docs/index.story.js
  src/CloseButton/CloseButton.uni.driver.js
  src/CloseButton/docs/index.story.js
  src/CloseButton/docs/testkit.md
  src/Collapse/Collapse.js
  src/ColorInput/ColorInput.js
  src/ColorInput/ColorInput.uni.driver.js
  src/ColorPicker/ColorPicker.js
  src/ColorPicker/ColorPicker.uni.driver.js
  src/CustomModalLayout/CustomModalLayout.uni.driver.js
Labels: PR: reviewed-approved

#6438 <Checkbox/> - errorMessage depricate, tooltipContent and tooltipProps was added
  perfer.config.js
  src/Checkbox/Checkbox.driver.d.ts
  src/Checkbox/Checkbox.driver.js
  src/Checkbox/Checkbox.js
  src/Checkbox/Checkbox.uni.driver.d.ts
  src/Checkbox/Checkbox.uni.driver.js
  src/Checkbox/docs/examples.js
  src/Checkbox/docs/index.story.js
  src/Checkbox/index.d.ts
  src/Checkbox/test/Checkbox.spec.js
  src/Checkbox/test/Checkbox.tsx
Labels: PR: unreviewed

#6440 Lint - add arrowParens=avoid
  .prettierrc.js
  package.json
Labels: PR: unreviewed

#6434 <SelectorList> - change padding when there is no search bar
  src/SelectorList/SelectorList.st.css
  src/SelectorList/test/SelectorList.visual.js
Labels: PR: reviewed-approved

#6368 <Layouter/> - new component
  .wuf/components.json
  perfer.config.js
  src/AnalyticsLayout/AnalyticsLayout.js
  src/AnalyticsLayout/AnalyticsLayout.meta.js
  src/AnalyticsLayout/AnalyticsLayout.st.css
  src/AnalyticsLayout/AnalyticsLayout.uni.driver.d.ts
  src/AnalyticsLayout/AnalyticsLayout.uni.driver.js
  src/AnalyticsLayout/Cell/Cell.js
  src/AnalyticsLayout/Cell/Cell.st.css
  src/AnalyticsLayout/Cell/Index.js
  src/AnalyticsLayout/Cell/index.ts
  src/AnalyticsLayout/constants.js
  src/AnalyticsLayout/docs/index.story.js
  src/AnalyticsLayout/index.d.ts
  src/AnalyticsLayout/index.js
  src/AnalyticsLayout/test/AnalyticsLayout.private.uni.driver.js
  src/AnalyticsLayout/test/AnalyticsLayout.spec.js
  src/AnalyticsLayout/test/AnalyticsLayout.tsx
  src/AnalyticsLayout/test/AnalyticsLayout.visual.js
  src/AnalyticsLayout/test/storySettings.js
  src/AtlasAddressInput/AtlasAddressInput.js
  src/AtlasAddressInput/docs/index.story.js
  src/AtlasAddressInput/test/AtlasAddressInput.private.uni.driver.js
  src/BaseModalLayout/BaseModalLayout.uni.driver.js
  src/Checkbox/Checkbox.js
  src/Checkbox/Checkbox.uni.driver.js
  src/Checkbox/docs/index.story.js
  src/Checkbox/test/Checkbox.spec.js
  src/RadioGroup/docs/index.story.js
  src/index.d.ts
  src/index.js
  stories/index.js
  testkit/component-definitions.js
Labels: New Component, PR: unreviewed

#6446 Editable selector- adding visuals
  src/EditableSelector/EditableRow/EditableRow.js
  src/EditableSelector/EditableRow/EditableRow.uni.driver.js
  src/EditableSelector/EditableRow/constants.js
  src/EditableSelector/EditableSelector.js
  src/EditableSelector/EditableSelector.uni.driver.js
  src/EditableSelector/constants.js
  src/EditableSelector/test/EditableSelector.visual.js
Labels: PR: unreviewed

#6449 <AddItem/> - remove pointer events on disabled
  src/AddItem/AddItem.js
  src/AddItem/AddItem.st.css
Labels: PR: unreviewed

#6448 <Input/> - trigger blur onWheel event when type=number
  src/Input/Input.js
  src/Input/Input.uni.driver.d.ts
  src/Input/Input.uni.driver.js
  src/Input/test/Input.spec.js
  src/NumberInput/NumberInput.js
  test/utils/unidriver/ReactBase.js
Labels: PR: unreviewed

#6450 LocaleUtils - change the imports to cherry-pick
  perfer.config.js
  src/LocaleUtils.js
Labels: PR: partially-approved

#6451 <AtlasAddressInput/> - remove export from index
  src/index.d.ts
  src/index.js
Labels: PR: unreviewed

#6453 Release 9.59.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#6416 <StyledNestableList/> UI fixes, a11ty
  src/NestableList/Container.js
  src/NestableList/Item.js
  src/NestableList/NestableList.js
  src/NestableList/NestableList.spec.js
  src/NestableList/test/utils.spec.js
  src/NestableList/utils.js
  src/StyledNestableList/Arrow.js
  src/StyledNestableList/StyledNestableList.js
  src/StyledNestableList/StyledNestableList.st.css
  src/StyledNestableList/docs/getExampleSource.js
  src/StyledNestableList/docs/index.story.js
  src/StyledNestableList/index.d.ts
  src/StyledNestableList/test/StyledNestableList.visual.js
  src/TableListItem/TableListItem.js
  src/TableListItem/TableListItem.st.css
  src/TableListItem/index.d.ts
Labels: PR: unreviewed, WIP

#6456 <AnalyticsLayout/> - fix Cell export
  src/AnalyticsLayout/Cell/index.d.ts
Labels: PR: unreviewed

#6442 <Accordion/> - introduce builders
  src/Accordion/Accordion.js
  src/Accordion/Accordion.private.uni.driver.js
  src/Accordion/Accordion.uni.driver.js
  src/Accordion/AccordionItem/AccordionItem.js
  src/Accordion/AccordionItem/index.d.ts
  src/Accordion/AccordionSectionItem/AccordionSectionItem.js
  src/Accordion/AccordionSectionItem/AccordionSectionItem.st.css
  src/Accordion/AccordionSectionItem/index.d.ts
  src/Accordion/AccordionSectionItem/index.js
  src/Accordion/docs/examples.js
  src/Accordion/docs/index.story.js
  src/Accordion/index.d.ts
  src/Accordion/index.js
  src/Accordion/test/Accordion.spec.js
  src/Accordion/test/Accordion.tsx
  src/Accordion/test/Accordion.visual.js
  src/index.js
Labels: PR: unreviewed

#6459 <Accordion/> - Add a 'node' button type
  src/Accordion/Accordion.js
  src/Accordion/AccordionItem/AccordionItem.js
  src/Accordion/AccordionItem/index.d.ts
  src/Accordion/constants.js
  src/Accordion/docs/examples.js
  src/Accordion/docs/index.story.js
  src/Accordion/test/Accordion.visual.js
Labels: PR: unreviewed

#6457 <FunnelChart> - add new prop - displayValue
  src/FunnelChart/FunnelChart.js
  src/FunnelChart/FunnelLabel/FunnelLabel.js
  src/FunnelChart/FunnelLabel/index.d.ts
  src/FunnelChart/index.d.ts
  src/FunnelChart/test/FunnelChart.spec.js
  src/FunnelChart/test/FunnelChart.visual.js
  src/utils/numberFormatters.js
Labels: PR: reviewed-approved

#6455 <AtlasAddressInput/> - don't use deprecated `listPredictions` atlas method
  .storybook/mocks/atlas.js
  package.json
  src/AtlasAddressInput/test/AtlasAddressInput.spec.js
  src/providers/useAtlasClient/index.d.ts
  src/providers/useAtlasClient/useAtlasClient.js
  src/providers/useAtlasClient/useAtlasClient.spec.js
Labels: PR: unreviewed

#6436 <Accordion /> - Add items size prop
  src/Accordion/Accordion.js
  src/Accordion/Accordion.st.css
  src/Accordion/AccordionItem/AccordionItem.js
  src/Accordion/AccordionItem/AccordionItem.st.css
  src/Accordion/AccordionItem/index.d.ts
  src/Accordion/AccordionSectionItem/AccordionSectionItem.js
  src/Accordion/AccordionSectionItem/index.d.ts
  src/Accordion/constants.js
  src/Accordion/docs/examples.js
  src/Accordion/docs/index.story.js
  src/Accordion/index.d.ts
  src/Accordion/test/Accordion.tsx
  src/Accordion/test/Accordion.visual.js
Labels: PR: reviewed-approved

#6464 <StatisticWidget/>- adding visuals
  src/StatisticsWidget/test/StatisticsWidget.visual.js
Labels: PR: unreviewed

#6465 <SelectorList/> - css fix
  src/SelectorList/SelectorList.st.css
Labels: PR: unreviewed

#6463 Update @babel/plugin-transform-runtime
  package.json
Labels: PR: unreviewed

#6461 Update @testing-library/react
  package.json
Labels: PR: unreviewed

#6468 <TableListItem/>- adding visuals
  src/TableListItem/test/TableListItem.visual.js
Labels: PR: unreviewed

#6476 <TableActionCell/> - expose puppeteer testkit
  .wuf/testkits/definitions.js
Labels: PR: unreviewed
