Repository wix/wix-style-react, pull requests merged in 2020-06, with the labels that each got.

#5499 <InputWithOptions/> - fix use of excludeClass prop
  src/InputWithOptions/InputWithOptions.js
Labels: Infrastructure

#5506 Fixed react-modal to 3.10.1 to enable tabs in modals
  package.json
  src/Modal/test/Modal.e2e.js
  src/Modal/test/Modal.e2eStory.js
  src/Modal/test/storySettings.js
Labels: <Modal/>, Accessibility

#5519 DSM-538/Using scrollable container in modal layouts
  perfer.config.js
  src/BaseModalLayout/LayoutBlocks/Content/Content.js
  src/BaseModalLayout/LayoutBlocks/Content/Content.st.css
  src/BaseModalLayout/LayoutBlocks/Content/index.d.ts
  src/CustomModalLayout/CustomModalLayout.js
  src/MessageModalLayout/MessageModalLayout.js
  src/MessageModalLayout/MessageModalLayout.st.css
  src/common/ScrollableContainer/index.js
  src/common/ScrollableContainer/test/ScrollableContainer.visual.js
Labels: PR: unreviewed

#5583 fix(package.json): use TAR_PUBLISH as value check of NPM_PUBLISH_TYPE
  package.json
Labels: Infrastructure

#5512 <RichTextArea/> -update min height
  src/RichTextInputArea/RichTextInputArea.scss
Labels: WIP

#5594 integrate janet for storybook publishing
  MIGRATION.md
  README.md
  docs/contribution/DOCUMENTING_COMPONENTS.md
  docs/usage/MOBILE_WEB_GUIDELINES.md
  janet.json
  package.json
  scripts/zeit-deploy.js
Labels: Docs, Infrastructure

#5614 Docs/jest cache faq
  docs/FAQ/README.md
Labels: Docs

#5613 Adding missing `throttle.cancel()` invocations on component unmount
  src/MessageBox/FunctionalLayout/MessageBoxFunctionalLayout.js
  src/common/ScrollableContainer/ScrollableContainer.js
Labels: PR: ready-for-review :pray:

#5610 <InputArea/> - Tests noise fixes
  src/InputArea/InputArea.js
Labels: <InputArea/>

#5605 <ScrollableContainer/> - Adding support for passing in data-attribute…
  src/common/ScrollableContainer/ScrollableContainer.js
  src/utils/extractAttributes.js
  src/utils/extractAttributes.spec.js
Labels: PR: ready-for-review :pray:

#5622 <Ellipsis/> - [internal] - New component to replace EllipsisHOC
  perfer.config.js
  src/Text/RawText.js
  src/Text/Text.js
  src/Text/index.d.ts
  src/Text/test/Text.tsx
  src/Tooltip/Tooltip.js
  src/common/Ellipsis/Ellipsis.js
  src/common/Ellipsis/Ellipsis.st.css
  src/common/Ellipsis/EllipsisUtils.js
  src/common/Ellipsis/index.d.ts
  src/common/Ellipsis/index.js
  src/common/Ellipsis/test/Ellipsis.e2e.js
  src/common/Ellipsis/test/Ellipsis.e2eStory.js
  src/common/Ellipsis/test/Ellipsis.tsx
Labels: Internal
