Repository wix/wix-style-react, pull requests merged in 2020-03, with the labels that each got.

#5057 `<FloatingHelper/>`- migration from backoffice
  src/FloatingHelper/ClosablePopover/ClosablePopover.driver.d.ts
  src/FloatingHelper/ClosablePopover/ClosablePopover.driver.js
  src/FloatingHelper/ClosablePopover/ClosablePopover.js
  src/FloatingHelper/ClosablePopover/ClosablePopover.protractor.driver.js
  src/FloatingHelper/ClosablePopover/constants.js
  src/FloatingHelper/ClosablePopover/test/ClosablePopover.spec.js
  src/FloatingHelper/FloatingHelper.driver.d.ts
  src/FloatingHelper/FloatingHelper.driver.js
  src/FloatingHelper/FloatingHelper.js
  src/FloatingHelper/FloatingHelper.protractor.driver.js
  src/FloatingHelper/FloatingHelper.st.css
  src/FloatingHelper/FloatingHelperContent/FloatingHelperContent.d.ts
  src/FloatingHelper/FloatingHelperContent/FloatingHelperContent.driver.d.ts
  src/FloatingHelper/FloatingHelperContent/FloatingHelperContent.driver.js
  src/FloatingHelper/FloatingHelperContent/FloatingHelperContent.js
  src/FloatingHelper/FloatingHelperContent/FloatingHelperContent.protractor.driver.js
  src/FloatingHelper/FloatingHelperContent/FloatingHelperContent.st.css
  src/FloatingHelper/FloatingHelperContent/docs/index.story.js
  src/FloatingHelper/FloatingHelperContent/index.d.ts
  src/FloatingHelper/FloatingHelperContent/test/FloatingHelperContent.spec.js
  src/FloatingHelper/docs/index.story.js
  src/FloatingHelper/index.d.ts
  src/FloatingHelper/test/FloatingHelper.spec.js
  src/FloatingHelper/test/storySettings.js
  test/types/FloatingHelper.tsx
Labels: <FloatingHelper/>, PR: unreviewed

#5130 <FloatingHelper/> - Tiny tweaks to TypeScript types
  src/FloatingHelper/FloatingHelperContent/index.d.ts
  src/FloatingHelper/index.d.ts
  test/types/FloatingHelper.tsx
Labels: PR: unreviewed

#5126 Tiny changes
  src/Badge/docs/ExampleBadges.js
  src/Badge/docs/index.story.js
  src/Box/docs/examples/ExampleEventItem.js
  src/Box/docs/propExplanations.js
  src/Carousel/docs/examples.js
  src/Carousel/docs/index.story.js
  src/DropdownBase/docs/examples/ExampleControlledMouse.js
  src/FormField/docs/examples.js
  src/ListItemSelect/docs/index.story.js
Labels: PR: unreviewed

#5136 <Table/> - add missing type for table puppeteer driver
  src/Table/Table.puppeteer.driver.d.ts
Labels: <Table/>, PR: unreviewed

#5134 <Table/> - support `React.RefObject` type for `scrollElement` prop
  src/DataTable/index.d.ts
  test/types/DataTable.tsx
  test/types/Table.tsx
Labels: PR: unreviewed

#5131 docs(RichTextInputArea, SocialButton, Sidebar): use example section
  src/RichTextInputArea/docs/examples/SetValue.js
  src/RichTextInputArea/docs/index.story.js
  src/Sidebar/docs/index.story.js
  src/SocialButton/docs/index.story.js
Labels: <RichTextInputArea/>, <Sidebar/>, <SocialButton/>, Docs, PR: reviewed-approved

#5138 Update CREATING_COMPONENTS.md
  docs/contribution/CREATING_COMPONENTS.md
Labels: PR: reviewed-approved

#5139 docs(*): use `allComponents` instead of `baseScope`
  src/AddItem/docs/index.story.js
  src/AutoComplete/docs/index.story.js
  src/AutoCompleteWithLabel/docs/index.story.js
  src/Avatar/docs/index.story.js
  src/Button/docs/index.story.js
  src/Card/Subheader/docs/index.story.js
  src/Card/docs/index.story.js
  src/Carousel/docs/index.story.js
  src/Checkbox/docs/index.story.js
  src/DateInput/docs/index.story.js
  src/DatePicker/docs/index.story.js
  src/Dropdown/docs/index.story.js
  src/FloatingNotification/docs/index.story.js
  src/FormField/docs/index.story.js
  src/IconButton/docs/index.story.js
  src/Input/docs/index.story.js
  src/Loader/docs/index.story.js
  src/MessageBox/FunctionalLayout/docs/index.story.js
  src/NumberInput/docs/index.story.js
  src/Page/docs/index.story.js
  src/PageHeader/docs/index.story.js
  src/Palette/docs/index.story.js
  src/RadioGroup/docs/index.story.js
  src/SectionHelper/docs/index.story.js
  src/Skeleton/docs/index.story.js
  src/Slider/docs/index.story.js
  src/Table/docs/index.story.js
  src/Tabs/docs/index.story.js
  src/Tag/docs/index.story.js
  src/Thumbnail/docs/index.story.js
  src/ToggleButton/docs/index.story.js
  src/Tooltip/TooltipNext/docs/index.story.js
  src/Typography/docs/index.story.js
  stories/CardLayout/index.story.js
  stories/ModalMobileLayout/index.story.js
  stories/MultiSelect/index.story.js
  stories/PageLayout/index.story.js
  stories/PopoverMenu/index.story.js
  stories/RichTextArea/index.story.js
  stories/SegmentedToggle/index.story.js
  stories/Sidebar/index.story.js
  stories/Slider/index.story.js
  stories/TextArea/index.story.js
  stories/TextInput/index.story.js
  stories/Tooltip/index.story.js
  stories/VariableInput/index.story.js
  stories/utils/LiveCodeExample/index.js
Labels: Docs, PR: unreviewed

#5137 chore(generator/templates): update story with example section
  .wuf/generator/templates/$ComponentName/docs/index.story.js
Labels: Infrastructure, PR: unreviewed

#5140 docs(storybook/inputs): use example section
  stories/MultiSelect/index.story.js
  stories/NumberInput/index.story.js
  stories/RichTextArea/index.story.js
  stories/TextArea/index.story.js
  stories/TextInput/index.story.js
  stories/VariableInput/index.story.js
Labels: Docs, PR: unreviewed

#5143 Release 7.48.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#5142 docs(): use example section part 3
  src/Slider/docs/index.story.js
  stories/ModalMobileLayout/index.story.js
  stories/PopoverMenu/index.story.js
  stories/SegmentedToggle/index.story.js
  stories/Tooltip/index.story.js
Labels: Docs, PR: unreviewed

#5144 docs(): use example section part 4
  src/Accordion/docs/index.story.js
  src/AddItem/docs/index.story.js
  src/Avatar/docs/index.story.js
  src/BarChart/docs/index.story.js
  src/Breadcrumbs/docs/index.story.js
  src/BrowserPreviewWidget/docs/index.story.js
  src/Button/docs/index.story.js
  src/CardGalleryItem/docs/index.story.js
  src/CloseButton/docs/index.story.js
  src/ColorInput/docs/index.story.js
  src/CounterBadge/docs/index.story.js
  src/Divider/docs/index.story.js
  src/Dropdown/docs/index.story.js
  src/FormField/docs/index.story.js
  src/GooglePreview/docs/index.story.js
Labels: Docs, PR: unreviewed

#5145 `<SideBar/>, <TimeTable/>` - migrate from dist/src backoffice usage
  src/Sidebar/colors.st.css
  src/TimeTable/TimeTable.st.css
Labels: PR: reviewed-approved

#5146 docs(): use example section part 5
  src/IconButton/docs/index.story.js
  src/Image/docs/index.story.js
  src/ImageViewer/docs/index.story.js
  src/InfoIcon/docs/index.story.js
  src/InputWithLabel/docs/index.story.js
  src/ListItemAction/docs/index.story.js
  src/ListItemSection/docs/index.story.js
  src/ListItemSelect/docs/index.story.js
  src/Loader/docs/index.story.js
  src/MediaOverlay/docs/index.story.js
  src/Modal/docs/index.story.js
  src/ModalMobileLayout/docs/index.story.js
  src/ModalPreviewLayout/docs/index.story.js
  src/PageHeader/docs/index.story.js
  src/PreviewWidget/docs/index.story.js
  src/Search/docs/index.story.js
  src/SectionHelper/docs/index.story.js
  src/SidebarBackButton/docs/index.story.js
  src/SidebarDivider/docs/index.story.js
  src/SidebarHeader/docs/index.story.js
  src/SidebarSectionItem/docs/index.story.js
  src/SidebarSectionTitle/docs/index.story.js
Labels: Docs, PR: unreviewed

#5147 docs(): use example section part 6
  src/ModalPreviewLayout/test/ModalPreviewLayout.visual.js
  src/Palette/docs/index.story.js
  src/SidePanel/docs/index.story.js
  src/Skeleton/docs/index.story.js
  src/StatisticsWidget/docs/index.story.js
  src/StatusIndicator/docs/index.story.js
  src/Tabs/docs/index.story.js
  src/Tag/docs/index.story.js
  src/Text/docs/index.story.js
  src/TextButton/docs/index.story.js
  src/TimeTable/docs/index.story.js
  src/ToggleButton/docs/index.story.js
  src/ToggleSwitch/docs/index.story.js
  src/VariableInput/docs/index.story.js
Labels: Docs, PR: unreviewed

#5148 TableActionCell testkit: Enable getVisibleActionsCount to return 0
  src/TableActionCell/TableActionCell.driver.js
  src/TableActionCell/test/TableActionCell.spec.js
Labels: PR: reviewed-approved

#5128 `css-modules` - fix ssr issues when used with named-imports
  package.json
  scripts/transpile.js
  scripts/transpile/__tests__/babel-plugin-src-to-es.spec.js
  scripts/transpile/__tests__/babel-plugins-sass-to-es.spec.js
  scripts/transpile/__tests__/tasks.spec.js
  scripts/transpile/index.js
  scripts/transpile/plugins/babel-plugin-sass-to-es.js
  scripts/transpile/plugins/babel-plugin-src-to-es.js
  scripts/transpile/tasks/clean-dist.js
  scripts/transpile/tasks/replace-stylable-imports.js
  scripts/transpile/tasks/transpile-copy-files.js
  scripts/transpile/tasks/transpile-src.js
  scripts/transpile/tasks/utils/index.js
  scripts/transpileSrc.js
Labels: PR: unreviewed

#5149 `<LinearProgressBar/>`, `<CircularProgressBar/>`, `<Loader/>` - migrate to use internal tooltip to avoid duplicate namespaces issues on ssr
  perfer.config.js
  src/CircularProgressBar/CircularProgressBar.js
  src/LinearProgressBar/LinearProgressBar.js
  src/Loader/Loader.js
Labels: PR: unreviewed

#5150 <RichTextInputArea/> - Upgrade tooltip in toolbar buttons
  src/RichTextInputArea/Form/RichTextInputAreaForm.js
  src/RichTextInputArea/Form/RichTextInputAreaForm.scss
  src/RichTextInputArea/RichTextInputArea.scss
  src/RichTextInputArea/Toolbar/RichTextToolbar.js
  src/RichTextInputArea/Toolbar/RichTextToolbar.scss
  src/RichTextInputArea/Toolbar/RichTextToolbarButton.js
  src/RichTextInputArea/test/RichTextInputArea.visual.js
Labels: <RichTextInputArea/>, PR: unreviewed

#5153 <Tabs/> - upgrade tooltip
  src/Tabs/Tabs.scss
  src/Tabs/core/TabItem/index.js
  src/Tabs/core/withTooltip/index.js
  src/Tabs/core/withTooltip/withTooltip.spec.js
Labels: <Tabs/>, PR: reviewed-approved, PR: unreviewed

#5157 [Docs] - Update readme for new types
  README.md
Labels: PR: reviewed-approved

#5156 wix-storybook-utils - update package.json to require the new version …
  package.json
Labels: PR: reviewed-approved

#5141 `<FloatingHelper/>`- improving FloatingHelper components stories
  src/FloatingHelper/ClosablePopover/ClosablePopover.js
  src/FloatingHelper/FloatingHelper.js
  src/FloatingHelper/FloatingHelperContent/docs/examples.js
  src/FloatingHelper/FloatingHelperContent/docs/index.story.js
  src/FloatingHelper/docs/ControlledExample.js
  src/FloatingHelper/docs/FullExample.js
  src/FloatingHelper/docs/ProgrammaticExample.js
  src/FloatingHelper/docs/SimpleExample.js
  src/FloatingHelper/docs/examples.js
  src/FloatingHelper/docs/index.story.js
Labels: <FloatingHelper/>, PR: reviewed-changes-requested, PR: unreviewed

#5161 SSR support - patch stylable to unify classnames
  package.json
  perfer.config.js
  scripts/transpile/index.js
  scripts/transpile/tasks/patch-ssr-stylable.js
  test-runtime/imports/.storybook/component-definitions.js
  test-runtime/imports/.storybook/es-named.story.js
Labels: PR: unreviewed

#5166 <ColorInput/> - error to status - preparation to wsr8
  src/ColorInput/ColorInput.js
  src/ColorInput/ColorInput.spec.js
  src/ColorInput/ColorInput.uni.driver.d.ts
  src/ColorInput/ColorInput.uni.driver.js
  src/ColorInput/docs/examples.js
  src/ColorInput/docs/index.story.js
  src/ColorInput/index.d.ts
  test/types/ColorInput.tsx
Labels: <ColorInput/>, PR: unreviewed

#5165 <SocialButton /> - add youtube skin
  package.json
  src/SocialButton/SocialButton.js
  src/SocialButton/SocialButton.st.css
  src/SocialButton/docs/examples.js
  src/SocialButton/docs/index.story.js
  src/SocialButton/index.d.ts
  src/SocialButton/test/SocialButton.visual.js
Labels: PR: unreviewed

#5164 Remove wix-ui-backoffice dependency
  src/Badge/Badge.driver.d.ts
  src/BadgeSelect/docs/index.story.js
  src/CounterBadge/CounterBadge.driver.d.ts
Labels: PR: unreviewed

#5152 `<FloatingHelper/>`- adding unidriver and refactoring tests accordingly
  src/FloatingHelper/ClosablePopover/ClosablePopover.uni.driver.d.ts
  src/FloatingHelper/ClosablePopover/ClosablePopover.uni.driver.js
  src/FloatingHelper/ClosablePopover/test/ClosablePopover.spec.js
  src/FloatingHelper/FloatingHelper.uni.driver.d.ts
  src/FloatingHelper/FloatingHelper.uni.driver.js
  src/FloatingHelper/FloatingHelperContent/FloatingHelperContent.uni.driver.d.ts
  src/FloatingHelper/FloatingHelperContent/FloatingHelperContent.uni.driver.js
  src/FloatingHelper/FloatingHelperContent/test/FloatingHelperContent.spec.js
  src/FloatingHelper/README.md
  src/FloatingHelper/constants.js
  src/FloatingHelper/test/FloatingHelper.spec.js
  test/types/FloatingHelper.tsx
Labels: PR: unreviewed

#5163 [FloatingNotification] add "dark" type to types
  src/FloatingNotification/index.d.ts
Labels: PR: unreviewed

#5162 [Tag] fix types for onClick prop
  src/Tag/index.d.ts
Labels: PR: unreviewed

#5160 [Tag] allow Tag to accept any type of children
  src/Tag/index.d.ts
Labels: PR: unreviewed

#5041 Cheatsheet fixes
  stories/Introduction/Cheatsheet/componentsFamilies/ButtonFamily.js
  stories/Introduction/Cheatsheet/componentsFamilies/ContentWidgetsFamily.js
  stories/Introduction/Cheatsheet/componentsFamilies/InputFamily.js
  stories/Introduction/Cheatsheet/componentsFamilies/LayoutFamily/LayoutFamily.js
  stories/Introduction/Cheatsheet/componentsFamilies/LayoutFamily/examples/SidePanelExamples.js
  stories/Introduction/Cheatsheet/componentsFamilies/NavigationFamily.js
  stories/Introduction/Cheatsheet/componentsFamilies/OtherFamily.js
  stories/Introduction/Cheatsheet/componentsFamilies/SelectionFamily.js
  stories/symbolsComponentsMapping/components.js
  stories/symbolsComponentsMapping/families/buttonsFamily.js
  stories/symbolsComponentsMapping/families/contentWidgetsFamily.js
  stories/symbolsComponentsMapping/families/inputsFamily.js
  stories/symbolsComponentsMapping/families/layoutFamily.js
  stories/symbolsComponentsMapping/families/navigationFamily.js
  stories/symbolsComponentsMapping/families/otherFamily.js
  stories/symbolsComponentsMapping/storybookMapping.js
  stories/symbolsComponentsMapping/symbols.js
Labels: PR: unreviewed

#5155 Announcement modal layout
  .wuf/components.json
  src/AnnouncementModalLayout/AnnouncementModalLayout.js
  src/AnnouncementModalLayout/AnnouncementModalLayout.meta.js
  src/AnnouncementModalLayout/AnnouncementModalLayout.st.css
  src/AnnouncementModalLayout/AnnouncementModalLayout.uni.driver.d.ts
  src/AnnouncementModalLayout/AnnouncementModalLayout.uni.driver.js
  src/AnnouncementModalLayout/constants.js
  src/AnnouncementModalLayout/docs/examples/BasicExample.js
  src/AnnouncementModalLayout/docs/examples/FootnoteExample.js
  src/AnnouncementModalLayout/docs/examples/NoIllustrationExample.js
  src/AnnouncementModalLayout/docs/examples/SecondaryButtonExample.js
  src/AnnouncementModalLayout/docs/examples/ThemeExample.js
  src/AnnouncementModalLayout/docs/index.story.js
  src/AnnouncementModalLayout/index.d.ts
  src/AnnouncementModalLayout/index.js
  src/AnnouncementModalLayout/test/AnnouncementModalLayout.private.uni.driver.js
  src/AnnouncementModalLayout/test/AnnouncementModalLayout.spec.js
  src/AnnouncementModalLayout/test/AnnouncementModalLayout.visual.js
  src/AnnouncementModalLayout/test/storySettings.js
  src/BaseModalLayout/BaseModalLayout.js
  src/BaseModalLayout/BaseModalLayout.st.css
  src/BaseModalLayout/index.d.ts
  src/CustomModalLayout/CustomModalLayout.st.css
  src/CustomModalLayout/docs/index.story.js
  src/CustomModalLayout/index.d.ts
  src/CustomModalLayout/test/CustomModalLayout.visual.js
  src/MessageModalLayout/MessageModalLayout.js
  src/MessageModalLayout/MessageModalLayout.st.css
  src/MessageModalLayout/MessageModalLayout.uni.driver.js
  src/MessageModalLayout/docs/examples/BasicExample.js
  src/MessageModalLayout/docs/examples/FootnoteExample.js
  src/MessageModalLayout/docs/index.story.js
  src/MessageModalLayout/index.d.ts
  src/MessageModalLayout/test/MessageModalLayout.spec.js
  src/MessageModalLayout/test/MessageModalLayout.visual.js
  src/MessageModalLayout/test/data/base64Image.js
  src/assets/announcement_illustration.svg
  src/index.d.ts
  src/index.js
  stories/index.js
  testkit/component-definitions.js
  testkit/enzyme.d.ts
  testkit/enzyme.js
  testkit/index.d.ts
  testkit/index.js
  testkit/protractor.d.ts
  testkit/protractor.js
  testkit/puppeteer.d.ts
  testkit/puppeteer.js
Labels: PR: unreviewed

#5189 Release 7.49.1
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#5179 Component types tests verification script
  package.json
  src/AnnouncementModalLayout/index.d.ts
  src/BaseModalLayout/BaseModalLayout.js
  src/BaseModalLayout/index.d.ts
  src/Breadcrumbs/index.d.ts
  src/BrowserPreviewWidget/index.d.ts
  src/CustomModalLayout/index.d.ts
  src/Divider/index.d.ts
  src/LabelledElement/index.d.ts
  src/MessageModalLayout/index.d.ts
  src/Palette/index.d.ts
  src/PreviewWidget/index.d.ts
  test/components-types.js
  test/types/Accordion.tsx
  test/types/AnnouncementModalLayout.tsx
  test/types/AutoCompleteComposite.tsx
  test/types/BarChart.tsx
  test/types/BaseModalLayout.tsx
  test/types/Breadcrumbs.tsx
  test/types/BrowserPreviewWidget.tsx
  test/types/CustomModalLayout.tsx
  test/types/DatePicker.tsx
  test/types/Divider.tsx
  test/types/FontUpgrade.tsx
  test/types/GoogleAddressInputWithLabel.tsx
  test/types/LabelledElement.tsx
  test/types/MarketingLayout.tsx
  test/types/MessageModalLayout.tsx
  test/types/MobilePreviewWidget.tsx
  test/types/MultiSelectComposite.tsx
  test/types/Palette.tsx
  test/types/PreviewWidget.tsx
  test/types/StatsWidget.tsx
  test/types/WarningIndicator.tsx
Labels: PR: unreviewed

#5185 <InputArea> - propagate onEnterPressed event
  src/InputArea/InputArea.js
  src/InputArea/index.d.ts
  test/types/InputArea.tsx
Labels: <InputArea/>, PR: unreviewed

#5186 `<Datepicker/>` - migrate to popover
  package.json
  src/DateInput/DatePicker.protractor.driver.js
  src/DatePicker/DatePicker.driver.js
  src/DatePicker/DatePicker.js
  src/DatePicker/DatePicker.scss
  src/DatePicker/index.d.ts
  src/DatePicker/test/DatePicker.spec.js
  src/common.d.ts
  src/commonProps.js
  test/types/DatePicker.tsx
Labels: PR: unreviewed

#5178 `<Checkbox/>`- replacing <Label> with <label> & <Text>
  src/Checkbox/Checkbox.driver.d.ts
  src/Checkbox/Checkbox.driver.js
  src/Checkbox/Checkbox.js
  src/Checkbox/Checkbox.uni.driver.d.ts
  src/Checkbox/Checkbox.uni.driver.js
  src/Checkbox/constants.js
  src/Checkbox/docs/examples.js
  src/Checkbox/docs/index.story.js
  src/Checkbox/index.d.ts
  src/Checkbox/test/Checkbox.spec.js
  src/Text/Text.driver.js
Labels: PR: unreviewed

#5192 Remove unnecessary upgrades
  src/DropdownBase/docs/examples/ExampleUncontrolledClick.js
  src/MultiSelect/docs/ExampleForHeader.js
  src/MultiSelect/docs/ExampleReorderable.js
  src/MultiSelect/docs/ExampleSelectAutocomplete.js
  src/MultiSelect/docs/ExampleSelectSimple.js
  src/MultiSelect/docs/ExampleSuggestions.js
  src/MultiSelect/docs/ExampleTagInput.js
  src/MultiSelect/docs/ExampleTagInputSelection.js
  src/MultiSelect/docs/MultiSelectPlaygroundConfig.js
  src/MultiSelect/docs/testStory.js
  src/MultiSelect/docs/tests/Reorderable.js
  src/MultiSelect/docs/tests/StateSelection.js
  src/MultiSelect/docs/tests/TestTabsSwitches.js
  src/MultiSelect/test/MultiSelect.visual.js
  src/StatisticsWidget/docs/examples/InteractiveCard.js
Labels: PR: unreviewed

#5195 Perfer && Generator - add css bundles entry
  .wuf/generator/codemods/perfer-config-file.js
  perfer.config.js
Labels: PR: unreviewed

#5199 Remove unnecessary <Label/> component from examples
  src/Calendar/docs/ExampleStandard.js
  src/Tabs/docs/TabsExample.js
Labels: PR: unreviewed

#5198 <Table/> - change internal toolbar label to be native
  src/TableToolbar/Toolbar.js
Labels: PR: unreviewed

#5200 [docs] Add missing named-imports migration
  src/MessageBox/docs/Alert.js
  src/MessageBox/docs/Announcement.js
  src/MessageBox/docs/DestructiveAlert.js
  src/MessageBox/docs/PremiumModal.js
  stories/PopoverMenu/examples.js
Labels: PR: unreviewed

#5171 Build cleanup script
  package.json
  scripts/build-cleanup.sh
Labels: Internal, PR: unreviewed

#5201 Generator - add types test
  .wuf/generator/templates/$ComponentName/test/$ComponentName.tsx
  package.json
  test/components-types.js
  tsconfig.declarations.json
Labels: Internal, PR: reviewed-approved, PR: unreviewed

#5203 <LinearProgressBar/>- removing wix-ui-backoffice dependency from driver
  src/LinearProgressBar/LinearProgressBar.driver.js
Labels: PR: unreviewed

#5204 <CircularProgressBar />- removing wix-ui-backoffice dependency from driver
  src/CircularProgressBar/CircularProgressBar.driver.js
Labels: PR: unreviewed

#5207 Release 7.50.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#5209 Dynamic Chunks - naming
  src/CircularProgressBar/CircularProgressBar.js
  src/LinearProgressBar/LinearProgressBar.js
  src/Loader/Loader.js
  src/common/EllipsisHOC/index.js
Labels: PR: unreviewed

#5214 `<Carousel/> - add sideEffect to Carousel
  package.json
Labels: PR: unreviewed

#5197 <Range/>- removing <Label/> usage and improving documentation
  .wuf/components.json
  src/Composite/index.d.ts
  src/Range/README.md
  src/Range/Range.js
  src/Range/Range.protractor.driver.js
  src/Range/RangeInputWithLabelComposite/RangeInputWithLabelComposite.js
  src/Range/RangeInputWithLabelComposite/RangeInputWithLabelComposite.protractor.driver.js
  src/Range/RangeInputWithLabelComposite/RangeInputWithLabelComposite.scss
  src/Range/RangeInputWithLabelComposite/RangeInputWithLabelComposite.spec.js
  src/Range/RangeInputWithLabelComposite/RangeWithLabelComposite.driver.js
  src/Range/docs/ExampleStandard.js
  src/Range/docs/ExampleStandard.scss
  src/Range/docs/examples.js
  src/Range/docs/index.js
  src/Range/docs/index.story.js
  src/Range/docs/testStory.js
  src/Range/test/Range.spec.js
  src/Range/test/RangeTemplate.js
  stories/index.js
  test/types/Range.tsx
Labels: PR: unreviewed

#5219 Add *.global.scss as side effects for tree-shaking
  package.json
Labels: PR: unreviewed

#5220 Release 7.50.1
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#5217 Made sure testkits can get null element
  src/AutoCompleteComposite/AutoCompleteComposite.driver.js
  src/BadgeSelect/BadgeSelect.driver.js
  src/Card/Header/Header.driver.js
  src/Composite/InputAreaWithLabelComposite/InputAreaWithLabelComposite.driver.js
  src/EditableSelector/EditableRow/EditableRow.driver.js
  src/FormField/FormField.driver.js
  src/ImageViewer/ImageViewer.driver.js
  src/InputArea/InputArea.driver.js
  src/RadioGroup/RadioButton/RadioButton.driver.js
  src/RadioGroup/RadioGroup.driver.js
  src/Range/Range.driver.js
Labels: PR: unreviewed

#5222 Perfer - add missing baselines
  perfer.config.js
Labels: PR: unreviewed

#5224 `<Checkbox/>`- improving component story
  src/Checkbox/docs/examples.js
  src/Checkbox/docs/index.story.js
Labels: PR: unreviewed

#5225 tooltipProps - migrate to common d.ts and proptypes
  perfer.config.js
  src/AddItem/AddItem.js
  src/AddItem/index.d.ts
  src/DataTable/DataTable.js
  src/DataTable/index.d.ts
  src/FillButton/FillButton.js
  src/FillButton/index.d.ts
  src/FormField/FormField.js
  src/FormField/index.d.ts
  src/ImageViewer/ImageViewer.js
  src/ImageViewer/index.d.ts
  src/InfoIcon/InfoIcon.js
  src/InfoIcon/index.d.ts
  src/SidePanel/Header/Header.js
  src/SidePanel/Header/index.d.ts
  src/Table/Table.js
  src/Table/index.d.ts
Labels: PR: unreviewed

#5226 <Table/>/<DataTable /> - fix table sorting arrows direction
  src/DataTable/DataTable.js
Labels: <Table/>, PR: unreviewed

#5230 `<Heading/>` - migrating regular driver to not use stylable stylesheet for testing
  src/Heading/Heading.driver.js
Labels: PR: unreviewed

#5229 `<Badge/>` - migrate regular testkit to not use stylable && deprecate getSufixIcon and getPrefixIcon
  src/Badge/Badge.driver.js
  src/Badge/Badge.js
  src/Badge/Badge.private.driver.js
  src/Badge/Badge.spec.js
  src/Badge/Badge.uni.driver.js
Labels: PR: unreviewed

#5193 <MessageModalLayout /> <AnnouncementModalLayout /> <CustomModalLayout…
  src/AnnouncementModalLayout/docs/examples/FootnoteExample.js
  src/CustomModalLayout/docs/examples/BasicExample.js
  src/CustomModalLayout/docs/examples/FootnoteExample.js
  src/CustomModalLayout/docs/examples/MarketingExample.js
  src/CustomModalLayout/docs/examples/ModalExample.js
  src/CustomModalLayout/docs/examples/NoHeaderExample.js
  src/CustomModalLayout/docs/examples/TableExample.js
  src/MessageModalLayout/docs/examples/FootnoteExample.js
Labels: PR: reviewed-approved

#5231 `<Text/>` - migrate regular driver to not use stylesheet for testing
  src/Text/Text.driver.js
Labels: PR: unreviewed

#5232 `<ToggleSwitch/>` - migrate regular driver to not use stylableDomUtil
  package.json
  src/ToggleSwitch/ToggleSwitch.driver.js
  src/ToggleSwitch/ToggleSwitch.js
Labels: PR: unreviewed

#5242 <AddItem/> - Added deprecation log
  src/AddItem/AddItem.js
Labels: PR: unreviewed

#5243 <GoogleAddressInput/> - Added deprecation log and documentation
  src/AutoCompleteWithLabel/index.d.ts
  src/ColorInput/index.d.ts
  src/GoogleAddressInput/GoogleAddressInput.js
  src/GoogleAddressInput/index.d.ts
  src/ImageViewer/index.d.ts
  src/InputWithLabel/index.d.ts
  test/types/GoogleAddressInput.tsx
Labels: PR: unreviewed

#5248 <ImageViewer/> - Improved visuals: removed deprecated props and added…
  src/ImageViewer/test/ImageViewer.visual.js
Labels: PR: reviewed-approved

#5249 <CustomModal /> - subtitle color should be lighter (secondary text)
  src/BaseModalLayout/BaseModalLayout.js
Labels: Bug, PR: unreviewed

#5257 <DropdownBase/> - add testkit function - optionContentAt
  src/DropdownBase/DropdownBase.uni.driver.d.ts
  src/DropdownBase/DropdownBase.uni.driver.js
  src/DropdownBase/test/DropdownBase.spec.js
Labels: PR: unreviewed

#5259 release 7.51.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#5260 Generator - do not generate commonjs imports in story.js
  .wuf/generator/templates/$ComponentName/docs/index.story.js
Labels: PR: reviewed-approved

#5262 `<PopoverMenu.MenuItem/>`- adding itemContentAt to driver
  src/beta/PopoverMenu/PopoverMenu.uni.driver.d.ts
  src/beta/PopoverMenu/PopoverMenu.uni.driver.js
  src/beta/PopoverMenu/test/PopoverMenu.spec.js
Labels: PR: unreviewed

#5261 <MultiSelectCheckBox/> - selectedId type fix
  src/MultiSelectCheckbox/index.d.ts
  test/types/MultiSelectCheckbox.tsx
Labels: PR: unreviewed

#5264 <FillButton/> - Added deprecation logs
  src/FillButton/FillButton.js
  src/FillButton/docs/examples.js
  src/FillButton/docs/index.story.js
  src/FillButton/test/FillButton.spec.js
Labels: PR: unreviewed

#5234 Take content out of selection area in RadioButton
  src/RadioGroup/RadioButton/RadioButton.driver.d.ts
  src/RadioGroup/RadioButton/RadioButton.driver.js
  src/RadioGroup/RadioButton/RadioButton.js
  src/RadioGroup/RadioGroup.driver.js
  src/RadioGroup/RadioGroup.protractor.driver.js
  src/RadioGroup/RadioGroup.scss
  src/RadioGroup/docs/examples.js
  src/RadioGroup/docs/index.story.js
  src/RadioGroup/test/RadioGroup.visual.js
Labels: PR: reviewed-approved, WIP

#5269 <ToggleButton/>: fix disabled prop and pass it also to <ButtonNext/>
  src/ToggleButton/ToggleButton.js
  src/ToggleButton/test/ToggleButton.spec.js
Labels: PR: reviewed-approved

#5274 <GoogleAddressInput/> - fix type
  src/GoogleAddressInput/index.d.ts
Labels: PR: reviewed-approved

#5263 Added deprecation logs
  src/AddItem/AddItem.js
  src/AutoComplete/AutoComplete.js
  src/AutoComplete/docs/examples.js
  src/ColorInput/ColorInput.js
  src/DatePicker/DatePicker.js
  src/Dropdown/Dropdown.js
  src/DropdownLayout/DropdownLayout.js
  src/GoogleAddressInput/GoogleAddressInput.js
  src/ImageViewer/ImageViewer.js
  src/Input/Input.js
  src/Input/InputErrorSuffix.js
  src/Input/InputHelpSuffix.js
  src/Input/InputLoaderSuffix.js
  src/Input/InputWarningSuffix.js
  src/InputArea/InputArea.js
  src/InputArea/docs/ExampleControlled.js
  src/InputArea/docs/index.story.js
  src/InputWithOptions/InputWithOptions.js
  src/MultiSelect/MultiSelect.js
  src/MultiSelectCheckbox/MultiSelectCheckbox.js
  src/NumberInput/NumberInput.js
  src/Range/docs/examples.js
  src/Search/Search.js
Labels: PR: unreviewed

#5268 Migrate from PopoverCommonProps to TooltipCommonProps
  perfer.config.js
  src/AddItem/AddItem.js
  src/AddItem/index.d.ts
  src/DataTable/DataTable.js
  src/DataTable/index.d.ts
  src/DatePicker/DatePicker.js
  src/FillButton/FillButton.js
  src/FillButton/index.d.ts
  src/FormField/FormField.js
  src/FormField/index.d.ts
  src/ImageViewer/ImageViewer.js
  src/ImageViewer/index.d.ts
  src/InfoIcon/InfoIcon.js
  src/InfoIcon/index.d.ts
  src/InputWithOptions/index.d.ts
  src/SidePanel/Header/Header.js
  src/SidePanel/Header/index.d.ts
  src/Table/Table.js
  src/common.d.ts
  src/common/PropTypes/PopoverCommon.js
  src/common/PropTypes/TooltipCommon.js
  test/types/Dropdown.tsx
  test/types/InputWithOptions.tsx
Labels: PR: unreviewed

#5266 Added deprecation logs 2
  perfer.config.js
  src/AddItem/docs/examples.js
  src/BarChart/BarChart.js
  src/CircularProgressBar/CircularProgressBar.js
  src/ComposerHeader/docs/examples.js
  src/ComposerHeader/docs/index.story.js
  src/ImageViewer/ImageViewer.js
  src/LinearProgressBar/LinearProgressBar.js
  src/Loader/Loader.js
  src/RadioGroup/RadioGroup.js
  src/Swatches/AddColor.js
  src/Tag/Tag.js
  src/ToggleButton/ToggleButton.js
  src/ToggleButton/docs/examples.js
Labels: PR: reviewed-approved

#5279 `<ToggleButton/>` - migrate to TooltipCommonProps instead
  src/ToggleButton/ToggleButton.js
  src/ToggleButton/index.d.ts
Labels: PR: unreviewed

#5283 `<Calender/>`- removing example with tooltip
  src/Calendar/docs/ExampleTooltip.js
  src/Calendar/docs/index.story.js
Labels: PR: unreviewed

#5190 Avoid "any" in Table types
  src/DataTable/index.d.ts
  src/Table/index.d.ts
  test/types/DataTable.tsx
  test/types/Table.tsx
Labels: PR: unreviewed

#5286 `<ToggleButton/>` - make tooltipProps.disabled work
  src/ToggleButton/ToggleButton.js
  src/ToggleButton/ToggleButton.private.uni.driver.js
  src/ToggleButton/ToggleButton.uni.driver.js
  src/ToggleButton/test/ToggleButton.private.uni.driver.js
  src/ToggleButton/test/ToggleButton.spec.js
Labels: PR: unreviewed

#5256 `<Pagination/> - new component
  .wuf/components.json
  perfer.config.js
  src/Pagination/Pagination.js
  src/Pagination/Pagination.meta.js
  src/Pagination/Pagination.st.css
  src/Pagination/Pagination.uni.driver.d.ts
  src/Pagination/Pagination.uni.driver.js
  src/Pagination/docs/examples.js
  src/Pagination/docs/index.story.js
  src/Pagination/index.d.ts
  src/Pagination/index.js
  src/Pagination/test/Pagination.private.uni.driver.js
  src/Pagination/test/Pagination.spec.js
  src/Pagination/test/Pagination.visual.js
  src/Pagination/test/storySettings.js
  src/Typography/docs/styles.scss
  src/index.d.ts
  src/index.js
  stories/index.js
  testkit/enzyme.d.ts
  testkit/enzyme.js
  testkit/index.d.ts
  testkit/index.js
  testkit/protractor.d.ts
  testkit/protractor.js
  testkit/puppeteer.d.ts
  testkit/puppeteer.js
Labels: PR: reviewed-approved

#5287 Release 7.53.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#4939 docs(FAQ) - update importing component docs
  docs/FAQ/README.md
Labels: PR: unreviewed

#5278 Added emptyStateMessage to AutoComplete definition
  src/AutoComplete/AutoComplete.js
  src/AutoComplete/index.d.ts
  test/types/AutoComplete.tsx
Labels: PR: unreviewed

#5292 <StatisticsWidget/> - fix clickable cursor on badge area
  src/StatisticsWidget/StatisticsItem/StatisticsItem.js
  src/StatisticsWidget/StatisticsItem/StatisticsItem.st.css
Labels: DO NOT MERGE, PR: unreviewed

#5194 <Box/> - Enable passing numeric sizing values
  src/Box/Box.js
  src/Box/test/Box.spec.js
  src/Box/test/Box.visual.js
Labels: PR: unreviewed

#5290 Fix radio group driver to expose Node interface object
  src/RadioGroup/RadioGroup.driver.js
  src/RadioGroup/RadioGroup.protractor.driver.js
Labels: PR: unreviewed

#5285 <Search/> + <InputWithOptions/> - Clear value in controlled mode
  src/InputWithOptions/InputWithOptions.js
  src/InputWithOptions/InputWithOptions.spec.js
  src/Search/Search.js
  src/Search/docs/testStory.js
  src/Search/test/Search.e2e.js
Labels: PR: reviewed-changes-requested

#5296 chore(generator): use decorated code section in component generator
  .wuf/generator/templates/$ComponentName/docs/index.story.js
Labels: Docs, Infrastructure

#5307 [version 7] - zeit deploy to wix-style-react-v7 && sync-ts base branch
  package.json
  scripts/zeit-deploy.js
Labels: PR: unreviewed

#5308 [version_7.x] Release 7.54.0-alpha
  package.json
Labels: PR: unreviewed

#5281 sync-ts - exclude docs examples path
  package.json
  scripts/sync-ts.sh
Labels: PR: unreviewed

#5311 [version 7.x] Readme.md update & other docs
  README.md
  docs/contribution/COMPONENT_GUIDELINES.md
Labels: PR: unreviewed

#5284 `<Page/>`- remove warning messages from <Page/> story page
  src/Page/docs/ExampleStickyTableWithGap.js
  src/Page/docs/PageChildren.js
  src/Page/docs/PageTestStories.js
  src/Page/docs/PageTestStoriesDeprecated.js
  src/Page/docs/index.story.js
  src/Page/test/Page.e2e.js
  stories/PopoverMenu/examples.js
Labels: PR: unreviewed
