Repository wix/wix-style-react, pull requests merged in 2020-11, with the labels that each got.

#6155 <Text/> - add skin primary to definitions
  src/Text/RawText.js
  src/Text/constants.js
Labels: PR: unreviewed

#6037 <CardFolderTabs/> - new component
  .wuf/components.json
  perfer.config.js
  src/CardFolderTabs/CardFolderTabs.js
  src/CardFolderTabs/CardFolderTabs.meta.js
  src/CardFolderTabs/CardFolderTabs.st.css
  src/CardFolderTabs/CardFolderTabs.uni.driver.d.ts
  src/CardFolderTabs/CardFolderTabs.uni.driver.js
  src/CardFolderTabs/Tab/Tab.js
  src/CardFolderTabs/Tab/index.d.ts
  src/CardFolderTabs/Tab/index.js
  src/CardFolderTabs/constants.js
  src/CardFolderTabs/docs/examples.js
  src/CardFolderTabs/docs/index.story.js
  src/CardFolderTabs/index.d.ts
  src/CardFolderTabs/index.js
  src/CardFolderTabs/test/CardFolderTabs.private.uni.driver.js
  src/CardFolderTabs/test/CardFolderTabs.spec.js
  src/CardFolderTabs/test/CardFolderTabs.tsx
  src/CardFolderTabs/test/CardFolderTabs.visual.js
  src/CardFolderTabs/test/storySettings.js
  src/index.d.ts
  src/index.js
  stories/index.js
  testkit/component-definitions.js
Labels: New Component, PR: partially-approved, PR: reviewed-changes-requested, PR: unreviewed

#6154 Fix typo
  src/ImageViewer/docs/index.story.js
Labels: PR: reviewed-approved

#6153 <SectionHelper/> - Added text button example to a story
  src/SectionHelper/docs/examples.js
  src/SectionHelper/docs/index.story.js
Labels: PR: partially-approved

#6151 list builders- adding "overrideOptionStyle" prop
  perfer.config.js
  src/DropdownLayout/DropdownLayout.js
  src/DropdownLayout/DropdownLayout.st.css
  src/DropdownLayout/docs/examples.js
  src/DropdownLayout/index.d.ts
  src/DropdownLayout/test/DropdownLayout.visual.js
  src/ListItemAction/ListItemAction.js
  src/ListItemAction/index.d.ts
  src/ListItemAction/test/ListItemAction.tsx
  src/ListItemEditable/ListItemEditable.js
  src/ListItemEditable/index.d.ts
  src/ListItemEditable/test/ListItemEditable.tsx
  src/ListItemSection/ListItemSection.js
  src/ListItemSection/index.d.ts
  src/ListItemSection/test/ListItemSection.tsx
  src/ListItemSelect/ListItemSelect.js
  src/ListItemSelect/index.d.ts
  src/ListItemSelect/test/ListItemSelect.tsx
Labels: PR: unreviewed

#6156 <ListItemSection/> - Removed redundant margin
  src/ListItemSection/ListItemSection.st.css
Labels: <ListItemSection/>, PR: reviewed-approved, PR: unreviewed

#6157 Business dashboard theming for Heading, Text & TextButton
  src/Heading/test/Heading.visual.js
  src/Text/test/Text.visual.js
  src/TextButton/test/TextButton.visual.js
  src/Themes/businessDashboard/BusinessDashboard.st.css
  src/Themes/businessDashboard/components/Heading.st.css
  src/Themes/businessDashboard/components/Text.st.css
  src/Themes/businessDashboard/components/TextButton.st.css
  src/Themes/businessDashboard/docs/businessDashboard.story.js
  src/Themes/businessDashboard/docs/components/Heading.js
  src/Themes/businessDashboard/docs/components/Text.js
  src/Themes/businessDashboard/docs/components/TextButton.js
  src/Themes/businessDashboard/foundations/colors.st.css
  src/Themes/businessDashboard/foundations/typography.st.css
  src/Themes/businessDashboard/test/businessDashboard.visual.js
Labels: PR: reviewed-approved

#6158 <TimeInput/> - refactor story page
  src/TimeInput/TimeInput.uni.driver.d.ts
  src/TimeInput/TimeInput.uni.driver.js
  src/TimeInput/docs/examples.js
  src/TimeInput/docs/index.story.js
Labels: PR: reviewed-approved

#6167 Release 9.32.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#6098 <SelectorList/> - new component
  .wuf/components.json
  perfer.config.js
  src/CustomModalLayout/CustomModalLayout.js
  src/CustomModalLayout/index.d.ts
  src/CustomModalLayout/test/CustomModalLayout.tsx
  src/SelectorList/Content/Content.js
  src/SelectorList/Content/Content.st.css
  src/SelectorList/Content/index.d.ts
  src/SelectorList/Content/index.js
  src/SelectorList/SelectorList.helpers.js
  src/SelectorList/SelectorList.js
  src/SelectorList/SelectorList.meta.js
  src/SelectorList/SelectorList.private.uni.driver.js
  src/SelectorList/SelectorList.st.css
  src/SelectorList/SelectorList.uni.driver.d.ts
  src/SelectorList/SelectorList.uni.driver.js
  src/SelectorList/ToggleAllCheckbox/ToggleAllCheckbox.js
  src/SelectorList/ToggleAllCheckbox/index.d.ts
  src/SelectorList/ToggleAllCheckbox/index.js
  src/SelectorList/docs/examples.js
  src/SelectorList/docs/index.story.js
  src/SelectorList/docs/storySettings.js
  src/SelectorList/index.d.ts
  src/SelectorList/index.js
  src/SelectorList/test/SelectorList.spec.js
  src/SelectorList/test/SelectorList.tsx
  src/SelectorList/test/SelectorList.visual.js
  src/Timeline/test/Timeline.visual.js
  src/index.d.ts
  src/index.js
  stories/index.js
  stories/symbolsComponentsMapping/components.js
  stories/symbolsComponentsMapping/families/pickerFamily.js
  test-runtime/imports/.storybook/component-definitions.js
  testkit/component-definitions.js
Labels: PR: reviewed-approved

#6150 Deprecate old modals
  src/MessageBox/FunctionalLayout/MessageBoxFunctionalLayout.js
  src/MessageBox/FunctionalLayout/docs/storySettings.js
  src/MessageBox/docs/index.js
  src/MessageModalLayout/docs/index.story.js
  src/ModalSelectorLayout/ModalSelectorLayout.js
  src/ModalSelectorLayout/docs/storySettings.js
Labels: PR: reviewed-approved

#6136 Theme bm linear progress bar
  src/LinearProgressBar/test/LinearProgressBar.visual.js
  src/Themes/businessDashboard/BusinessDashboard.st.css
  src/Themes/businessDashboard/components/LinearProgressBar.st.css
  src/Themes/businessDashboard/docs/businessDashboard.story.js
  src/Themes/businessDashboard/docs/components/Button.js
  src/Themes/businessDashboard/docs/components/Carousel.js
  src/Themes/businessDashboard/docs/components/CircularProgressBar.js
  src/Themes/businessDashboard/docs/components/Heading.js
  src/Themes/businessDashboard/docs/components/LinearProgressBar.js
  src/Themes/businessDashboard/docs/components/Text.js
  src/Themes/businessDashboard/docs/components/TextButton.js
  src/Themes/businessDashboard/foundations/colors.st.css
  src/Themes/businessDashboard/test/businessDashboard.visual.js
Labels: PR: unreviewed

#6173 Business dashboard theme Text & TextButton adjustments
  src/Themes/businessDashboard/components/Text.st.css
  src/Themes/businessDashboard/components/TextButton.st.css
  src/Themes/businessDashboard/docs/components/Text.js
  src/Themes/businessDashboard/docs/components/TextButton.js
  src/Themes/businessDashboard/foundations/colors.st.css
Labels: PR: unreviewed

#6164 <Carousel/> - Add controlsPosition prop
  src/BadgeSelect/test/BadgeSelect.visual.js
  src/Carousel/Carousel.js
  src/Carousel/Carousel.st.css
  src/Carousel/Carousel.uni.driver.js
  src/Carousel/Pagination/Pagination.st.css
  src/Carousel/docs/examples.js
  src/Carousel/docs/index.story.js
  src/Carousel/index.d.ts
  src/Carousel/test/Carousel.tsx
  src/Carousel/test/Carousel.visual.js
  src/Carousel/test/storySettings.js
Labels: PR: unreviewed

#6174 <Search/> - Add highlight prop
  src/InputWithOptions/InputWithOptions.js
  src/Search/Search.js
  src/Search/test/Search.tsx
Labels: PR: unreviewed

#6170 <Range /> - add unidriver
  .wuf/testkits/definitions.js
  src/Range/Range.driver.js
  src/Range/Range.uni.driver.d.ts
  src/Range/Range.uni.driver.js
  src/Range/RangeInputWithLabelComposite/RangeInputWithLabelComposite.js
  src/Range/constants.js
  src/Range/test/Range.spec.js
Labels: PR: reviewed-approved

#6176 <SparklineChart/> - Add animationDuration prop
  src/SparklineChart/SparklineChart.js
  src/SparklineChart/index.d.ts
  src/SparklineChart/test/SparklineChart.tsx
  src/SparklineChart/test/SparklineChart.visual.js
Labels: PR: unreviewed

#6178 <SparklineChart/> - add onHover prop
  src/SparklineChart/SparklineChart.js
  src/SparklineChart/docs/index.story.js
  src/SparklineChart/index.d.ts
  src/SparklineChart/test/SparklineChart.tsx
Labels: PR: reviewed-approved

#6181 <SelectableAccordion/> - Fix testkit types
  src/SelectableAccordion/SelectableAccordion.uni.driver.d.ts
Labels: PR: reviewed-approved

#6179 Business dashboard theme - circular progress bar adjustments
  src/Themes/businessDashboard/components/CircularProgressBar.st.css
  src/Themes/businessDashboard/docs/components/CircularProgressBar.js
Labels: PR: unreviewed

#6169 <Search/> - fix value on blur
  src/Search/Search.js
  src/Search/test/Search.spec.js
Labels: <Search/>, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed

#6177 <TimeInput/> replace css with stylable
  src/TimeInput/TimeInput.driver.js
  src/TimeInput/TimeInput.js
  src/TimeInput/TimeInput.scss
  src/TimeInput/TimeInput.st.css
Labels: PR: reviewed-approved

#6171 <ModalSelectorLayout/> - implement using the new <SelectorList/>
  src/ModalSelectorLayout/ModalSelectorLayout.driver.js
  src/ModalSelectorLayout/ModalSelectorLayout.helpers.js
  src/ModalSelectorLayout/ModalSelectorLayout.js
  src/ModalSelectorLayout/ModalSelectorLayout.protractor.driver.js
  src/ModalSelectorLayout/ModalSelectorLayout.scss
  src/ModalSelectorLayout/ModalSelectorLayout.uni.driver.js
  src/SelectorList/SelectorList.helpers.js
  src/SelectorList/SelectorList.js
  src/SelectorList/SelectorList.st.css
  src/SelectorList/index.d.ts
Labels: PR: reviewed-approved

#6186 <TimeInput/> - added showSeconds prop
  src/TimeInput/TimeInput.driver.d.ts
  src/TimeInput/TimeInput.driver.js
  src/TimeInput/TimeInput.js
  src/TimeInput/TimeInput.st.css
  src/TimeInput/TimeInput.uni.driver.d.ts
  src/TimeInput/TimeInput.uni.driver.js
  src/TimeInput/docs/examples.js
  src/TimeInput/docs/index.story.js
  src/TimeInput/index.d.ts
  src/TimeInput/test/TimeInput.spec.js
  src/TimeInput/test/TimeInput.tsx
  src/TimeInput/test/TimeInput.visual.js
Labels: PR: unreviewed

#6193 release(9.34.0)
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#6192 Adding circular progress bar label
  src/CircularProgressBar/CircularProgressBar.js
  src/CircularProgressBar/CircularProgressBar.st.css
  src/CircularProgressBar/docs/examples.js
  src/CircularProgressBar/docs/index.story.js
  src/CircularProgressBar/index.d.ts
  src/CircularProgressBar/test/CircularProgressBar.visual.js
  src/Themes/businessDashboard/components/CircularProgressBar.st.css
  src/Themes/businessDashboard/docs/components/CircularProgressBar.js
Labels: PR: unreviewed

#6189 <DatePicker/> - add the public methods to the index.d.ts file
  src/DatePicker/DatePicker.js
  src/DatePicker/index.d.ts
Labels: PR: reviewed-approved

#6149 <CustomModalLayout/> - fix top and bottom dividers
  src/AnnouncementModalLayout/AnnouncementModalLayout.js
  src/BaseModalLayout/LayoutBlocks/Content/Content.js
  src/BaseModalLayout/LayoutBlocks/Content/index.d.ts
  src/BaseModalLayout/test/BaseModalLayout.tsx
  src/CustomModalLayout/CustomModalLayout.js
  src/CustomModalLayout/CustomModalLayout.st.css
  src/CustomModalLayout/docs/examples/PageExample.js
  src/CustomModalLayout/docs/examples/PersistentDividersExample.js
  src/CustomModalLayout/docs/index.story.js
  src/CustomModalLayout/index.d.ts
  src/CustomModalLayout/test/CustomModalLayout.tsx
  src/MessageModalLayout/MessageModalLayout.js
Labels: PR: reviewed-approved

#6168 Don't clear value when entering text into rich text inputs
  test/utils/unidriver/DraftJS.js
Labels: PR: reviewed-approved

#6196 BadgeSelectItem- adding visuals to builder and fix types
  src/BadgeSelect/index.d.ts
  src/BadgeSelect/test/BadgeSelect.tsx
  src/BadgeSelectItemBuilder/BadgeSelectItemBuilder.js
  src/BadgeSelectItemBuilder/constants.js
  src/BadgeSelectItemBuilder/index.d.ts
  src/BadgeSelectItemBuilder/test/BadgeSelectItem.visual.js
Labels: PR: reviewed-approved

#6199 release 9.35.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#6184 <DropdownLayout/>- align driver and uni driver
  src/DropdownLayout/DataAttr.js
  src/DropdownLayout/DropdownLayout.driver.d.ts
  src/DropdownLayout/DropdownLayout.driver.js
  src/DropdownLayout/DropdownLayout.js
  src/DropdownLayout/DropdownLayout.uni.driver.d.ts
  src/DropdownLayout/DropdownLayout.uni.driver.js
  src/DropdownLayout/test/DropdownLayout.spec.js
Labels: PR: unreviewed

#6187 Added business dashboard theming for IconButton component
  src/IconButton/test/IconButton.visual.js
  src/Themes/businessDashboard/BusinessDashboard.st.css
  src/Themes/businessDashboard/components/IconButton.st.css
  src/Themes/businessDashboard/docs/businessDashboard.story.js
  src/Themes/businessDashboard/docs/components/IconButton.js
  src/Themes/businessDashboard/test/businessDashboard.visual.js
Labels: PR: unreviewed

#6200 Improve smoke tests
  src/Modal/Modal.uni.driver.js
  testkit/testkit-smoke.test.js
Labels: PR: unreviewed, Testkit

#6201 release 9.36.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#6182 <Carousel/> - Added controlsSize prop
  src/Carousel/Carousel.js
  src/Carousel/Carousel.st.css
  src/Carousel/SliderArrow/SliderArrow.js
  src/Carousel/docs/examples.js
  src/Carousel/docs/index.story.js
  src/Carousel/index.d.ts
Labels: PR: unreviewed

#6205 <Proportion/> - updating storybook
  src/Proportion/Proportion.js
  src/Proportion/Proportion.uni.driver.js
  src/Proportion/README.md
  src/Proportion/docs/ExampleComponent.js
  src/Proportion/docs/examples.js
  src/Proportion/docs/index.story.js
  src/Proportion/docs/storySettings.js
Labels: PR: reviewed-approved

#6209 <CardHeader/> - remove redundant div
  src/Card/Header/Header.js
  src/Card/Header/Header.st.css
Labels: PR: unreviewed

#6206 BusinessDashboard Theme: Fix FontUpgrade not matching theme active state
  src/Themes/businessDashboard/BusinessDashboard.js
Labels: PR: partially-approved

#6188 Business dashboard theme Heading, Text & TextButton adjustments following UX feedback
  src/Themes/businessDashboard/components/Heading.st.css
  src/Themes/businessDashboard/components/Text.st.css
  src/Themes/businessDashboard/components/TextButton.st.css
  src/Themes/businessDashboard/docs/components/Text.js
  src/Themes/businessDashboard/docs/components/TextButton.js
Labels: PR: unreviewed

#6211 infra - lower the specific yoshi-stylable-dependencies minor version to a public one
  package.json
Labels: PR: reviewed-approved

#6203 Adjusted business dashboard Button theme
  src/Themes/businessDashboard/components/Button.st.css
  src/Themes/businessDashboard/docs/components/Button.js
Labels: PR: unreviewed

#6204 scripts cleanup
  package.json
  scripts/unidriver-migration/src/make-async/README.md
  scripts/unidriver-migration/src/make-async/__testfixtures__/make-async.input.js
  scripts/unidriver-migration/src/make-async/__testfixtures__/make-async.output.js
  scripts/unidriver-migration/src/make-async/__tests__/make-async-test.js
  scripts/unidriver-migration/src/make-async/make-async.js
Labels: Infrastructure, PR: draft, PR: unreviewed, WIP

#6190 integrate webpack config from `yoshi-flow-library`
  .autotools/webpack.config.js
  .storybook/visual/webpack.config.js
  .storybook/webpack.config.js
  package.json
Labels: Infrastructure, PR: draft, PR: unreviewed

#6210 <Popover/> - Rearrange testkit docs
  src/BadgeSelect/BadgeSelect.private.uni.driver.js
  src/BadgeSelect/BadgeSelect.uni.driver.js
  src/ColorInput/ColorInput.private.uni.driver.js
  src/FilePicker/FilePicker.uni.driver.js
  src/FileUpload/FileUpload.uni.driver.js
  src/FillButton/FillButton.uni.driver.js
  src/FloatingHelper/ClosablePopover/ClosablePopover.uni.driver.d.ts
  src/FloatingHelper/ClosablePopover/ClosablePopover.uni.driver.js
  src/FloatingHelper/FloatingHelper.uni.driver.js
  src/InputWithOptions/InputWithOptions.protractor.driver.js
  src/InputWithOptions/InputWithOptions.uni.driver.js
  src/Popover/Popover.uni.driver.js
  src/Popover/test/Popover.visual.js
  src/Swatches/test/Swatches.private.uni.driver.js
Labels: PR: reviewed-approved

#6213 LinearProgressBar - remove flaky test
  src/LinearProgressBar/test/LinearProgressBar.visual.js
Labels: PR: unreviewed

#6194 Themes | Business Dashboard - Add Carousel theme
  src/Carousel/Carousel.js
  src/Carousel/Pagination/Pagination.js
  src/Carousel/test/Carousel.visual.js
  src/Themes/businessDashboard/BusinessDashboard.st.css
  src/Themes/businessDashboard/components/Carousel.st.css
  src/Themes/businessDashboard/docs/components/Carousel.js
  src/Themes/businessDashboard/test/businessDashboard.visual.js
Labels: PR: unreviewed

#6218 Preload Madefor in visual tests
  .storybook/visual/preview-head.html
Labels: PR: unreviewed

#6166 <BadgeOption/> and badgeSelectItemBuilder- adding selected, hovered and disabled styles and builder fixes
  perfer.config.js
  src/BadgeSelect/BadgeSelect.js
  src/BadgeSelectItemBuilder/BadgeSelectItem.st.css
  src/BadgeSelectItemBuilder/BadgeSelectItemBuilder.js
  src/BadgeSelectItemBuilder/docs/README.md
  src/BadgeSelectItemBuilder/index.d.ts
  src/BadgeSelectItemBuilder/test/BadgeSelectItem.visual.js
  src/BadgeSelectItemBuilder/test/BadgeSelectItemBuilder.tsx
Labels: PR: partially-approved

#6165 <Text/> - Added listStyle prop
  src/Text/RawText.js
  src/Text/Text.js
  src/Text/Text.st.css
  src/Text/docs/examples.js
  src/Text/docs/index.story.js
  src/Text/index.d.ts
  src/Text/test/Text.tsx
  src/Text/test/Text.visual.js
Labels: PR: unreviewed

#6221 release 9.37.0
  CHANGELOG.md
  package.json
  perfer.config.js
Labels: PR: unreviewed

#6214 <Filepicker/> - update storybook
  src/FilePicker/FilePicker.js
  src/FilePicker/docs/examples.js
  src/FilePicker/docs/index.story.js
Labels: PR: unreviewed

#6223 <Carousel/> - Add size tiny to controls
  src/Carousel/Carousel.js
  src/Carousel/Carousel.st.css
  src/Carousel/docs/index.story.js
  src/Carousel/index.d.ts
Labels: PR: unreviewed

#6212 <Heading/> - updating storybook
  src/Heading/Heading.js
  src/Heading/README.TESTKIT.md
  src/Heading/docs/ExampleEllipsis.js
  src/Heading/docs/ExampleTypography.js
  src/Heading/docs/examples.js
  src/Heading/docs/index.story.js
  src/Heading/docs/storySettings.js
  src/Heading/docs/styles.scss
Labels: PR: unreviewed

#6224 <EditableSelector/> - storybook updates
  src/EditableSelector/EditableSelector.js
  src/EditableSelector/EditableSelector.uni.driver.js
  src/EditableSelector/docs/CardWithEditableSelector.js
  src/EditableSelector/docs/PopoverWithEditableSelector.js
  src/EditableSelector/docs/examples.js
  src/EditableSelector/docs/index.story.js
Labels: PR: unreviewed

#6222 <Search/> - migrate to Stylable
  src/Search/Search.driver.js
  src/Search/Search.js
  src/Search/Search.scss
  src/Search/Search.st.css
  src/Search/Search.uni.driver.js
  src/Search/constants.js
Labels: PR: unreviewed

#6225 <FloatingNotification/> - storybook updates
  src/FloatingNotification/FloatingNotification.js
  src/FloatingNotification/FloatingNotification.uni.driver.js
  src/FloatingNotification/docs/index.story.js
Labels: PR: unreviewed

#6219 <SparklineChart/> - fix highlightedAreaEffect issue
  src/SparklineChart/SparklineChart.js
Labels: PR: reviewed-approved

#6217 <AutoCompleteWithLabel/> - Added maxHeightPixel property
  src/AutoCompleteWithLabel/AutoCompleteWithLabel.js
  src/AutoCompleteWithLabel/index.d.ts
  src/AutoCompleteWithLabel/test/AutoCompleteWithLabel.tsx
Labels: PR: reviewed-approved

#6146 SidebarSectionItem suffix 30% to support madeFor font
  src/SidebarSectionItem/SidebarSectionItem.st.css
  src/SidebarSectionItem/test/SidebarSectionItem.visual.js
Labels: PR: unreviewed

#6229 chore(package): use last public babel-preset-yoshi
  package.json
Labels: Infrastructure, PR: unreviewed

#6230 <TimeInput/> - fix hover/focus styles
  src/TimeInput/TimeInput.st.css
Labels: PR: unreviewed

#6236 <Search/> - migrate to Stylable - fix css for small
  src/Search/Search.st.css
  src/Search/test/Search.visual.js
Labels: PR: unreviewed

#6198 Themes | Business Dashboard - Add Sidebar theme
  src/Sidebar/Sidebar.js
  src/Sidebar/Sidebar.st.css
  src/Sidebar/colors.st.css
  src/Sidebar/main.scss
  src/Sidebar/main.st.css
  src/Sidebar/test/Sidebar.visual.js
  src/SidebarBackButton/SidebarBackButton.js
  src/SidebarBackButton/SidebarBackButton.st.css
  src/SidebarBackButton/test/SidebarBackButton.visual.js
  src/SidebarDivider/SidebarDivider.st.css
  src/SidebarDivider/test/SidebarDivider.visual.js
  src/SidebarHeader/SidebarHeader.st.css
  src/SidebarHeader/test/SidebarHeader.visual.js
  src/SidebarSectionItem/SidebarSectionItem.st.css
  src/SidebarSectionItem/test/SidebarSectionItem.visual.js
  src/SidebarSectionTitle/SidebarSectionTitle.st.css
  src/SidebarSectionTitle/test/SidebarSectionTitle.visual.js
  src/Themes/businessDashboard/BusinessDashboard.js
  src/Themes/businessDashboard/BusinessDashboard.st.css
  src/Themes/businessDashboard/components/Sidebar.st.css
  src/Themes/businessDashboard/components/SidebarBackButton.st.css
  src/Themes/businessDashboard/components/SidebarDivider.st.css
  src/Themes/businessDashboard/components/SidebarHeader.st.css
  src/Themes/businessDashboard/components/SidebarSectionItem.st.css
  src/Themes/businessDashboard/components/SidebarSectionTitle.st.css
  src/Themes/businessDashboard/docs/businessDashboard.story.js
  src/Themes/businessDashboard/docs/components/Sidebar.js
  src/Themes/businessDashboard/foundations/colors.st.css
  src/Themes/businessDashboard/test/businessDashboard.visual.js
Labels: PR: unreviewed

#6234 <GenericModalLayout/> - storybook updates
  src/GenericModalLayout/GenericModalLayout.js
  src/GenericModalLayout/GenericModalLayout.uni.driver.js
  src/GenericModalLayout/README.TESTKIT.md
  src/GenericModalLayout/docs/ExampleFullscreen.js
  src/GenericModalLayout/docs/ExampleFullscreen.scss
  src/GenericModalLayout/docs/ExampleGeneric.js
  src/GenericModalLayout/docs/ExampleGeneric.scss
  src/GenericModalLayout/docs/ExampleStandard.js
  src/GenericModalLayout/docs/ExampleStandard.scss
  src/GenericModalLayout/docs/examples.js
  src/GenericModalLayout/docs/index.story.js
  src/GenericModalLayout/docs/modalWrapper.js
Labels: PR: reviewed-approved

#6237 <SegmentedTogle/> - storybook updates
  src/SegmentedToggle/SegmentedToggle.uni.driver.js
  src/SegmentedToggle/docs/examples.js
  src/SegmentedToggle/docs/index.story.js
Labels: PR: reviewed-approved

#6226 Adding size tiny to carousel and removing bottom
  src/Themes/businessDashboard/components/Carousel.st.css
  src/Themes/businessDashboard/docs/components/Carousel.js
Labels: PR: reviewed-approved

#6207 Business dashboard theming - Card
  src/Card/Card.visual.js
  src/Card/Header/Header.js
  src/Card/Header/Header.st.css
  src/Themes/businessDashboard/BusinessDashboard.st.css
  src/Themes/businessDashboard/components/Card/Content.st.css
  src/Themes/businessDashboard/components/Card/Header.st.css
  src/Themes/businessDashboard/docs/businessDashboard.story.js
  src/Themes/businessDashboard/docs/components/Card.js
  src/Themes/businessDashboard/test/businessDashboard.visual.js
Labels: PR: unreviewed

#6239 <Thumbnail/> - storybook updates
  src/Thumbnail/Thumbnail.uni.driver.js
  src/Thumbnail/docs/exampleControlled.js
  src/Thumbnail/docs/examples.js
  src/Thumbnail/docs/index.story.js
Labels: PR: reviewed-approved

#6215 <PageFooter/> - new component
  .wuf/components.json
  perfer.config.js
  src/PageFooter/Center/Center.js
  src/PageFooter/Center/Center.st.css
  src/PageFooter/Center/index.d.ts
  src/PageFooter/Center/index.js
  src/PageFooter/End/End.js
  src/PageFooter/End/End.st.css
  src/PageFooter/End/index.d.ts
  src/PageFooter/End/index.js
  src/PageFooter/PageFooter.js
  src/PageFooter/PageFooter.meta.js
  src/PageFooter/PageFooter.st.css
  src/PageFooter/PageFooter.uni.driver.d.ts
  src/PageFooter/PageFooter.uni.driver.js
  src/PageFooter/Start/Start.js
  src/PageFooter/Start/Start.st.css
  src/PageFooter/Start/index.d.ts
  src/PageFooter/Start/index.js
  src/PageFooter/docs/examples.js
  src/PageFooter/docs/index.story.js
  src/PageFooter/index.d.ts
  src/PageFooter/index.js
  src/PageFooter/test/PageFooter.private.uni.driver.js
  src/PageFooter/test/PageFooter.spec.js
  src/PageFooter/test/PageFooter.tsx
  src/PageFooter/test/PageFooter.visual.js
  src/PageFooter/test/storySettings.js
  src/index.d.ts
  src/index.js
  stories/index.js
Labels: New Component, PR: reviewed-approved, PR: unreviewed

#6240 Dashboard theme adjustments for Text & Button
  src/Themes/businessDashboard/components/Button.st.css
  src/Themes/businessDashboard/components/Card/Content.st.css
  src/Themes/businessDashboard/components/Text.st.css
  src/Themes/businessDashboard/docs/components/Button.js
  src/Themes/businessDashboard/docs/components/Text.js
Labels: PR: unreviewed

#6242 <Popover/> - storybook updates
  src/DropdownBase/DropdownBase.uni.driver.js
  src/Popover/Popover.common.driver.js
  src/Popover/Popover.js
  src/Popover/README.TESTKIT.md
  src/Popover/README.md
  src/Popover/docs/examples.js
  src/Popover/docs/examples/ExampleAppendTo.js
  src/Popover/docs/examples/ExampleFixed.js
  src/Popover/docs/examples/ExampleFlip.js
  src/Popover/docs/examples/ExampleInteractive.js
  src/Popover/docs/examples/ExamplePositioning.js
  src/Popover/docs/index.story.js
  src/PopoverMenu/PopoverMenu.uni.driver.js
  src/PopoverMenu/test/PopoverMenu.private.uni.driver.js
Labels: <Popover/>, PR: draft, PR: unreviewed, WIP

#6246 Revert "SidebarSectionItem suffix 30% to support madeFor font"
  CHANGELOG.md
  src/SidebarSectionItem/SidebarSectionItem.st.css
  src/SidebarSectionItem/test/SidebarSectionItem.visual.js
Labels: PR: unreviewed

#6245 <Input/> - fix overflow (FF only)
  src/Input/Input.st.css
Labels: PR: unreviewed

#6243 <Highlighter/> - storybook updates
  .wuf/testkits/definitions.js
  src/Highlighter/Highlighter.uni.driver.d.ts
  src/Highlighter/Highlighter.uni.driver.js
  src/Highlighter/README.TESTKIT.md
  src/Highlighter/docs/examples.js
  src/Highlighter/docs/index.story.js
  src/Highlighter/test/Highlighter.spec.js
Labels: PR: reviewed-approved, WIP

#6247 Fixed wrong value of D70 color for business dashboard theme
  src/Themes/businessDashboard/foundations/colors.st.css
Labels: PR: reviewed-approved

#6233 <NumberInput /> - add hideStepper property
  src/Input/Input.uni.driver.js
  src/NumberInput/NumberInput.js
  src/NumberInput/NumberInput.uni.driver.js
  src/NumberInput/docs/examples.js
  src/NumberInput/docs/index.story.js
  src/NumberInput/index.d.ts
  src/NumberInput/test/NumberInput.tsx
  src/NumberInput/test/NumberInput.visual.js
Labels: PR: reviewed-approved

#6248 <Accordion/> - remove unwanted color background color
  src/Accordion/AccordionItem/AccordionItem.st.css
Labels: PR: unreviewed

#6163 <DropdownLayout/>- convert option to ListItemSelect
  perfer.config.js
  src/DropdownBase/DropdownBase.js
  src/DropdownBase/DropdownBase.uni.driver.js
  src/DropdownLayout/DataAttr.js
  src/DropdownLayout/DropdownLayout.js
  src/DropdownLayout/DropdownLayout.st.css
  src/DropdownLayout/DropdownLayout.uni.driver.js
  src/DropdownLayout/test/DropdownLayout.spec.js
Labels: PR: unreviewed

#6253 release 9.39.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#6238 CheckToggle - add to cheatsheet
  stories/Introduction/Cheatsheet/componentsFamilies/SelectionFamily.js
  stories/symbolsComponentsMapping/components.js
  stories/symbolsComponentsMapping/families/selectionFamily.js
Labels: <CheckToggle/>, PR: reviewed-approved, PR: unreviewed

#6232 Updated font version in stylesheet imports
  .storybook/preview-head.html
  .storybook/visual/preview-head.html
Labels: PR: reviewed-approved

#6241 <Page/> - migrate to Stylable
  src/Foundation/stylable/z-index.st.css
  src/Page/Page.js
  src/Page/Page.protractor.driver.js
  src/Page/Page.scss
  src/Page/Page.st.css
  src/Page/PageSticky.js
  src/Page/constants.js
Labels: <Page/>, PR: draft, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed

#6235 Business dashboard theming ListItemSelect
  src/ListItemSelect/ListItemSelect.js
  src/ListItemSelect/ListItemSelect.st.css
  src/ListItemSelect/test/ListItemSelect.visual.js
  src/Themes/businessDashboard/BusinessDashboard.st.css
  src/Themes/businessDashboard/components/ListItemSelect.st.css
  src/Themes/businessDashboard/docs/businessDashboard.story.js
  src/Themes/businessDashboard/docs/components/ListItemSelect.js
  src/Themes/businessDashboard/test/businessDashboard.visual.js
Labels: PR: unreviewed

#6254 <Tooltip /> - add data-size attribute and test it
  src/Tooltip/Tooltip.js
  src/Tooltip/Tooltip.uni.driver.d.ts
  src/Tooltip/Tooltip.uni.driver.js
  src/Tooltip/constants.js
  src/Tooltip/docs/README.TESTKIT.md
  src/Tooltip/test/Tooltip.spec.js
Labels: <Tooltip/>, PR: reviewed-approved, PR: unreviewed

#6220 Themes | Business Dashboard - Add Tooltip theme
  perfer.config.js
  src/ThemeProvider/ThemeProvider.js
  src/ThemeProvider/ThemeProviderConsumerBackwardCompatible.js
  src/Themes/businessDashboard/BusinessDashboard.st.css
  src/Themes/businessDashboard/components/Tooltip.st.css
  src/Themes/businessDashboard/docs/businessDashboard.story.js
  src/Themes/businessDashboard/docs/components/Tooltip.js
  src/Tooltip/Tooltip.js
Labels: PR: unreviewed

#6250 Caption - ditch the Text component from internal usage
  src/Text/Caption.js
  src/Text/Caption.st.css
Labels: PR: unreviewed

#6251 Added an option to theme the CircularProgressBar success icon
  src/CircularProgressBar/CircularProgressBar.js
  src/ThemeProvider/index.d.ts
  src/ThemeProvider/test/ThemeProvider.tsx
  src/Themes/businessDashboard/BusinessDashboard.js
  src/Themes/businessDashboard/icons/CircleLoaderCheck.js
  src/Themes/businessDashboard/icons/index.js
Labels: PR: unreviewed, Themes - Business Dashboard

#6260 infra: remove sync-ts
  package.json
Labels: PR: unreviewed

#6259 Themes | Business Dashboard - add Badge theme
  src/Badge/test/Badge.visual.js
  src/Themes/businessDashboard/BusinessDashboard.st.css
  src/Themes/businessDashboard/components/Badge.st.css
  src/Themes/businessDashboard/docs/businessDashboard.story.js
  src/Themes/businessDashboard/docs/components/Badge.js
  src/Themes/businessDashboard/test/businessDashboard.visual.js
Labels: PR: unreviewed, Themes - Business Dashboard

#6228 Business dashboard theming for ListItemAction & ListItemSection
  src/ListItemAction/test/ListItemAction.visual.js
  src/Popover/Popover.js
  src/Themes/businessDashboard/BusinessDashboard.st.css
  src/Themes/businessDashboard/components/DropdownLayout.st.css
  src/Themes/businessDashboard/components/ListItemAction.st.css
  src/Themes/businessDashboard/components/ListItemSection.st.css
  src/Themes/businessDashboard/components/PopoverMenu.st.css
  src/Themes/businessDashboard/docs/businessDashboard.story.js
  src/Themes/businessDashboard/docs/components/ListItemAction.js
  src/Themes/businessDashboard/docs/components/PopoverMenu.js
  src/Themes/businessDashboard/test/businessDashboard.visual.js
  test/utils/visual/utils.js
Labels: PR: unreviewed, Themes - Business Dashboard

#6258 <GoogleAdreesInput/>- adding id to option
  src/GoogleAddressInput/GoogleAddressInput.js
Labels: PR: partially-approved

#6267 Adjusted text button alignment
  src/Themes/businessDashboard/components/TextButton.st.css
Labels: PR: unreviewed, Themes - Business Dashboard

#6257 <Card/> - add withShadow prop
  src/Card/Card.js
  src/Card/Card.st.css
  src/Card/Card.visual.js
  src/Card/index.d.ts
  src/Card/test/Card.tsx
Labels: PR: reviewed-approved

#6270 <PageFooter/> - update an icon in visual test
  src/PageFooter/test/PageFooter.visual.js
Labels: PR: reviewed-approved

#6266 <Modal/> - migrate to stylable
  src/Foundation/stylable/easing.st.css
  src/LabelledElement/LabelledElement.st.css
  src/Modal/Modal.driver.d.ts
  src/Modal/Modal.driver.js
  src/Modal/Modal.js
  src/Modal/Modal.scss
  src/Modal/Modal.st.css
  src/Modal/Modal.uni.driver.d.ts
  src/Modal/Modal.uni.driver.js
  src/Modal/index.d.ts
  src/Modal/test/Modal.spec.js
  src/Modal/test/Modal.tsx
Labels: PR: unreviewed, Themes - Business Dashboard

#6231 <StyledNestableList/> - new component
  .wuf/components.json
  perfer.config.js
  src/NestableList/Container.js
  src/NestableList/DragLayer.js
  src/NestableList/Item.js
  src/NestableList/NestableList.js
  src/NestableList/index.d.ts
  src/NestableList/utils.js
  src/StyledNestableList/Arrow.js
  src/StyledNestableList/NestableListTheme.st.css
  src/StyledNestableList/StyledNestableList.js
  src/StyledNestableList/StyledNestableList.meta.js
  src/StyledNestableList/StyledNestableList.st.css
  src/StyledNestableList/StyledNestableList.uni.driver.d.ts
  src/StyledNestableList/StyledNestableList.uni.driver.js
  src/StyledNestableList/constants.js
  src/StyledNestableList/docs/examplesConstants.js
  src/StyledNestableList/docs/getExampleSource.js
  src/StyledNestableList/docs/index.story.js
  src/StyledNestableList/index.d.ts
  src/StyledNestableList/index.js
  src/StyledNestableList/test/StyledNestableList.private.uni.driver.js
  src/StyledNestableList/test/StyledNestableList.spec.js
  src/StyledNestableList/test/StyledNestableList.tsx
  src/StyledNestableList/test/StyledNestableList.visual.js
  src/StyledNestableList/test/storySettings.js
  src/index.d.ts
  src/index.js
  stories/index.js
Labels: New Component, PR: draft, PR: unreviewed, WIP

#6272 <Image/> - Add className prop
  src/Image/Image.js
  src/Image/index.d.ts
  src/Image/test/Image.tsx
Labels: PR: unreviewed

#6271 <TableListItem/> - fix width/align not working
  src/TableListItem/TableListItem.js
  src/TableListItem/TableListItem.st.css
Labels: PR: unreviewed

#6261 <Text /> - added tooltipProps as a new prop
  src/Text/Text.js
  src/Text/index.d.ts
  src/common.d.ts
  src/common/PropTypes/TooltipCommon.js
Labels: PR: reviewed-approved

#6262 Themes | Business Dashboard - add EmptyState theme
  src/EmptyState/EmptyState.js
  src/EmptyState/EmptyState.st.css
  src/EmptyState/docs/examples.js
  src/EmptyState/test/EmptyState.visual.js
  src/Themes/businessDashboard/BusinessDashboard.st.css
  src/Themes/businessDashboard/components/Button.st.css
  src/Themes/businessDashboard/components/EmptyState.st.css
  src/Themes/businessDashboard/docs/businessDashboard.story.js
  src/Themes/businessDashboard/docs/components/EmptyState.js
  src/Themes/businessDashboard/foundations/spacing.st.css
  src/Themes/businessDashboard/test/businessDashboard.visual.js
Labels: PR: unreviewed, Themes - Business Dashboard

#6265 Themes | Business Dashboard - add Input theme
  src/Input/Input.st.css
  src/Input/InputSuffix.js
  src/Input/test/Input.visual.js
  src/Themes/businessDashboard/BusinessDashboard.st.css
  src/Themes/businessDashboard/components/Input/IconAffix.st.css
  src/Themes/businessDashboard/components/Input/Input.st.css
  src/Themes/businessDashboard/docs/businessDashboard.story.js
  src/Themes/businessDashboard/docs/components/Input.js
  src/Themes/businessDashboard/docs/components/Search.js
  src/Themes/businessDashboard/test/businessDashboard.visual.js
Labels: PR: unreviewed, Themes - Business Dashboard

#6277 Themes | Business Dashboard - add Loader theme
  src/Loader/test/Loader.visual.js
  src/Themes/businessDashboard/BusinessDashboard.st.css
  src/Themes/businessDashboard/components/Loader.st.css
  src/Themes/businessDashboard/docs/businessDashboard.story.js
  src/Themes/businessDashboard/docs/components/Loader.js
  src/Themes/businessDashboard/test/businessDashboard.visual.js
  test/utils/visual/utils.js
Labels: PR: unreviewed, Themes - Business Dashboard

#6278 Release/9.41.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#6263 Themes | Business Dashboard - added box-shadow theming
  src/Avatar/Avatar.st.css
  src/Foundation/stylable/shadows.st.css
  src/Themes/businessDashboard/BusinessDashboard.st.css
  src/Themes/businessDashboard/components/DropdownLayout.st.css
  src/Themes/businessDashboard/components/PopoverMenu.st.css
  src/Themes/businessDashboard/foundations/colors.st.css
  src/Tooltip/Tooltip.st.css
Labels: PR: reviewed-approved, Themes - Business Dashboard

#6276 <Ellipsis/> - add size prop
  src/Text/docs/examples.js
  src/Text/docs/index.story.js
  src/common/Ellipsis/Ellipsis.js
Labels: PR: reviewed-approved

#6279 Themes | Business Dashboard - UX fixes to CircularProgressBar, EmptyState, ListItemSelect, Tooltip, Loader & colors
  src/Themes/businessDashboard/components/CircularProgressBar.st.css
  src/Themes/businessDashboard/components/EmptyState.st.css
  src/Themes/businessDashboard/components/ListItemSelect.st.css
  src/Themes/businessDashboard/components/Tooltip.st.css
  src/Themes/businessDashboard/docs/components/Loader.js
  src/Themes/businessDashboard/foundations/colors.st.css
Labels: PR: unreviewed, Themes - Business Dashboard

#6274 Themes | Business Dashboard - Modal
  src/Modal/Modal.js
  src/Modal/Modal.st.css
  src/Themes/businessDashboard/BusinessDashboard.st.css
  src/Themes/businessDashboard/components/Modal.st.css
  src/Themes/businessDashboard/docs/businessDashboard.story.js
  src/Themes/businessDashboard/docs/components/Modal.js
Labels: PR: unreviewed, Themes - Business Dashboard

#6280 <BadgeSelect/> - [docs] fix testkit page crash
  src/AddressInput/AddressInput.uni.driver.js
  src/AutoCompleteWithLabel/AutoCompleteWithLabel.uni.driver.js
  src/AutoCompleteWithLabel/docs/index.story.js
  src/Avatar/README.md
  src/Avatar/docs/index.story.js
  src/BadgeSelect/BadgeSelect.uni.driver.js
Labels: PR: unreviewed

#6282 Themes | Business Dashboard - changed focus ring color of Button, IconButton, TextButton
  src/Themes/businessDashboard/components/Button.st.css
  src/Themes/businessDashboard/components/IconButton.st.css
  src/Themes/businessDashboard/components/TextButton.st.css
Labels: PR: unreviewed, Themes - Business Dashboard

#6288 Themes | Business Dashboard - changed ListItemSelect color back to D20
  src/Themes/businessDashboard/components/ListItemSelect.st.css
Labels: PR: reviewed-approved, Themes - Business Dashboard

#6275 <MarketingLayout/> - add alignItems prop
  src/MarketingLayout/MarketingLayout.js
  src/MarketingLayout/MarketingLayout.st.css
  src/MarketingLayout/components/Content.js
  src/MarketingLayout/docs/examples.js
  src/MarketingLayout/docs/index.story.js
  src/MarketingLayout/index.d.ts
  src/MarketingLayout/test/MarketingLayout.spec.js
  src/MarketingLayout/test/MarketingLayout.tsx
  src/MarketingLayout/test/MarketingLayout.visual.js
Labels: PR: reviewed-approved

#6291 Themes | Business Dashboard - adjusted TextButton dark disabled color & light hover color
  src/Themes/businessDashboard/components/TextButton.st.css
Labels: PR: reviewed-approved, Themes - Business Dashboard

#6124 `<BadgeSelectItem/>`- adding a uni driver
  .wuf/components.json
  .wuf/testkits/definitions.js
  src/BadgeSelect/BadgeSelect.js
  src/BadgeSelect/index.d.ts
  src/BadgeSelect/test/BadgeSelect.tsx
  src/BadgeSelectItem/BadgeSelectItem.js
  src/BadgeSelectItem/BadgeSelectItem.st.css
  src/BadgeSelectItem/BadgeSelectItem.uni.driver.d.ts
  src/BadgeSelectItem/BadgeSelectItem.uni.driver.js
  src/BadgeSelectItem/constants.js
  src/BadgeSelectItem/docs/ElipsisExample.js
  src/BadgeSelectItem/docs/Example.js
  src/BadgeSelectItem/docs/README.md
  src/BadgeSelectItem/docs/index.js
  src/BadgeSelectItem/index.d.ts
  src/BadgeSelectItem/index.js
  src/BadgeSelectItem/test/BadgeSelectItem.spec.js
  src/BadgeSelectItem/test/BadgeSelectItem.visual.js
  src/BadgeSelectItem/test/BadgeSelectItemBuilder.tsx
  src/BadgeSelectItemBuilder/index.js
  src/index.d.ts
  src/index.js
  stories/index.js
  testkit/component-definitions.js
Labels: PR: unreviewed

#6287 Themes | Business Dashboard - Changing Carousel icons size and pagination color
  src/Carousel/Carousel.js
  src/Carousel/Pagination/Pagination.st.css
  src/Themes/businessDashboard/BusinessDashboard.st.css
  src/Themes/businessDashboard/components/Carousel.st.css
  src/Themes/businessDashboard/components/Pagination.st.css
Labels: PR: reviewed-approved, Themes - Business Dashboard

#6289 Themes | Business Dashboard - improve Button's default skin specificity
  src/Button/Button.st.css
  src/Themes/businessDashboard/components/Button.st.css
Labels: PR: reviewed-approved, Themes - Business Dashboard

#6286 fix nestable list drag and drop
  src/NestableList/NestableList.js
  src/NestableList/utils.js
  src/StyledNestableList/StyledNestableList.js
Labels: PR: unreviewed, WIP

#6249 <SidebarSectionItem/> - adjust and limit suffix size
  src/SidebarSectionItem/SidebarSectionItem.js
  src/SidebarSectionItem/SidebarSectionItem.st.css
  src/SidebarSectionItem/test/SidebarSectionItem.visual.js
Labels: PR: unreviewed

#6292 <ListItemSelect /> - implement styling using css instead of js
  src/ListItemSelect/ListItemSelect.js
  src/ListItemSelect/ListItemSelect.st.css
Labels: PR: reviewed-approved

#6284 Small refactor - removing classnames
  src/Avatar/Avatar.js
  src/BaseModalLayout/LayoutBlocks/Content/Content.js
  src/BaseModalLayout/LayoutBlocks/Footer/Footer.js
  src/BaseModalLayout/LayoutBlocks/Footnote/Footnote.js
  src/BaseModalLayout/LayoutBlocks/Header/Header.js
  src/BaseModalLayout/LayoutBlocks/Illustration/Illustration.js
  src/Calendar/DatePickerHead/index.js
  src/MultiSelect/MultiSelect.js
  src/RadioGroup/RadioGroup.js
Labels: PR: unreviewed

#6293 <InputArea/> - migrate to Stylable
  src/Input/Input.st.css
  src/InputArea/InputArea.driver.js
  src/InputArea/InputArea.js
  src/InputArea/InputArea.scss
  src/InputArea/InputArea.st.css
  src/InputArea/InputArea.uni.driver.js
  src/InputArea/InputAreaMixins.scss
  src/InputArea/constants.js
  src/InputArea/index.d.ts
  src/InputArea/test/InputArea.spec.js
  src/InputArea/test/InputArea.tsx
  src/NestableList/NestableList.js
  src/VariableInput/VariableInput.st.css
Labels: PR: unreviewed

#6255 <Table/> - deprecate hideHeader prop
  src/Table/Table.js
  src/Table/docs/examples/TableHideHeaderExample.js
  src/Table/docs/index.story.js
Labels: PR: reviewed-approved

#6298 <SidebarBackButton> - add light skin visual test
  src/SidebarBackButton/test/SidebarBackButton.visual.js
Labels: PR: unreviewed

#6295 Themes | Business Dashboard - Misc Sidebar Fixes
  src/SidebarBackButton/SidebarBackButton.js
  src/SidebarBackButton/SidebarBackButton.st.css
  src/Themes/businessDashboard/components/SidebarBackButton.st.css
  src/Themes/businessDashboard/components/SidebarHeader.st.css
  src/Themes/businessDashboard/components/SidebarSectionItem.st.css
  src/Themes/businessDashboard/components/SidebarSectionTitle.st.css
  src/Themes/businessDashboard/foundations/colors.st.css
Labels: PR: reviewed-approved

#6273 <MarketingLayout/> - add badge and hiddenBadge props
  src/MarketingLayout/MarketingLayout.js
  src/MarketingLayout/MarketingLayout.st.css
  src/MarketingLayout/docs/examples.js
  src/MarketingLayout/docs/index.story.js
  src/MarketingLayout/index.d.ts
  src/MarketingLayout/test/MarketingLayout.tsx
  src/MarketingLayout/test/MarketingLayout.visual.js
Labels: PR: reviewed-approved

#6285 <Page/> - move content of `public.scss` file to Grid
  src/Grid/Grid.js
  src/Grid/Grid.scss
  src/Page/Page.public.scss
Labels: <Page/>, PR: draft, PR: unreviewed

#6269 <MarketingLayout/> - add size tiny
  src/MarketingLayout/MarketingLayout.js
  src/MarketingLayout/MarketingLayout.st.css
  src/MarketingLayout/components/Content.js
  src/MarketingLayout/components/Title.js
  src/MarketingLayout/constants.js
  src/MarketingLayout/docs/examples.js
  src/MarketingLayout/docs/index.story.js
  src/MarketingLayout/index.d.ts
  src/MarketingLayout/test/MarketingLayout.visual.js
Labels: PR: reviewed-approved

#6302 <InputArea/> - fix rtl css
  src/InputArea/InputArea.st.css
Labels: PR: unreviewed

#6023 <PageHeader /> - convert scss to stylable
  src/PageHeader/PageHeader.driver.js
  src/PageHeader/PageHeader.js
  src/PageHeader/PageHeader.scss
  src/PageHeader/PageHeader.st.css
Labels: PR: partially-approved

#6301 <Carousel/> - add showControlsShadow prop
  src/Carousel/Carousel.js
  src/Carousel/Carousel.st.css
  src/Carousel/SliderArrow/SliderArrow.js
  src/Carousel/docs/examples.js
  src/Carousel/docs/index.story.js
  src/Carousel/index.d.ts
  src/Carousel/test/Carousel.tsx
  src/Carousel/test/Carousel.visual.js
Labels: PR: reviewed-approved

#6304 Fix Storybook theme
  .storybook/addons/ThemeWSR/index.js
  src/Themes/floatingPanels/index.d.ts
Labels: PR: unreviewed

#6306 Themes | Business Dashboard - Fix visuals
  src/Badge/test/Badge.visual.js
  src/EmptyState/test/EmptyState.visual.js
  src/ListItemAction/test/ListItemAction.visual.js
  src/ListItemSelect/test/ListItemSelect.visual.js
  src/Loader/test/Loader.visual.js
Labels: PR: unreviewed, Themes - Business Dashboard

#6299 <Layout> - refactor from scss to stylable
  src/Layout/Cell/index.spec.js
  src/Layout/docs/examples/Form.js
  src/Layout/docs/examples/ListOfCards.js
  src/Layout/docs/examples/MainAndSide.js
  src/Layout/docs/index.story.js
  src/Layout/docs/styles.st.css
Labels: PR: reviewed-approved

#6307 Themes | Business Dashboard - Adjustments to DropdownLayout & PopoverMenu
  src/Themes/businessDashboard/components/DropdownLayout.st.css
  src/Themes/businessDashboard/components/PopoverMenu.st.css
Labels: PR: unreviewed, Themes - Business Dashboard

#6303 <Carousel/> - Set 'clickNext' and 'clickPrevious' as public to driver's consumers [Testkit].
  src/Carousel/Carousel.driver.d.ts
  src/Carousel/Carousel.driver.js
  src/Carousel/Carousel.private.driver.js
  src/Carousel/Carousel.private.uni.driver.js
  src/Carousel/Carousel.uni.driver.d.ts
  src/Carousel/Carousel.uni.driver.js
Labels: PR: unreviewed

#6305 <TrendIndicator/> - add new component
  .wuf/components.json
  perfer.config.js
  src/DropdownBase/DropdownBase.uni.driver.js
  src/Foundation/stylable/typography.st.css
  src/Themes/businessDashboard/icons/CircleLoaderCheck.js
  src/TrendIndicator/TrendIndicator.js
  src/TrendIndicator/TrendIndicator.meta.js
  src/TrendIndicator/TrendIndicator.st.css
  src/TrendIndicator/TrendIndicator.uni.driver.d.ts
  src/TrendIndicator/TrendIndicator.uni.driver.js
  src/TrendIndicator/constants.js
  src/TrendIndicator/docs/examples.js
  src/TrendIndicator/docs/index.story.js
  src/TrendIndicator/index.d.ts
  src/TrendIndicator/index.js
  src/TrendIndicator/test/TrendIndicator.private.uni.driver.js
  src/TrendIndicator/test/TrendIndicator.spec.js
  src/TrendIndicator/test/TrendIndicator.tsx
  src/TrendIndicator/test/TrendIndicator.visual.js
  src/TrendIndicator/test/storySettings.js
  src/index.d.ts
  src/index.js
  stories/index.js
  testkit/component-definitions.js
Labels: PR: reviewed-approved

#6300 <Carousel/> - add controlsStartEnd prop
  src/Carousel/Carousel.js
  src/Carousel/SliderArrow/SliderArrow.js
  src/Carousel/docs/examples.js
  src/Carousel/docs/index.story.js
  src/Carousel/index.d.ts
  src/Carousel/test/Carousel.tsx
  src/Carousel/test/Carousel.visual.js
Labels: PR: reviewed-approved

#6316 <StatisticsWidget/> - use TrendIndicator component
  src/StatisticsWidget/StatisticsItem/StatisticsItem.js
  src/StatisticsWidget/StatisticsItem/StatisticsItem.st.css
  src/StatisticsWidget/StatisticsWidget.uni.driver.d.ts
  src/StatisticsWidget/StatisticsWidget.uni.driver.js
  src/StatisticsWidget/dataAttrs.js
  src/StatisticsWidget/dataHooks.js
  src/StatisticsWidget/test/StatisticsWidget.spec.js
  src/TrendIndicator/TrendIndicator.st.css
Labels: PR: reviewed-approved

#6313 <RadioGroup/> - add name prop
  src/RadioGroup/RadioButton/RadioButton.js
  src/RadioGroup/RadioGroup.driver.d.ts
  src/RadioGroup/RadioGroup.driver.js
  src/RadioGroup/RadioGroup.js
  src/RadioGroup/RadioGroup.uni.driver.d.ts
  src/RadioGroup/RadioGroup.uni.driver.js
  src/RadioGroup/index.d.ts
  src/RadioGroup/test/RadioGroup.spec.js
  src/RadioGroup/test/RadioGroup.tsx
Labels: PR: reviewed-approved

#6308 Easing definitions
  perfer.config.js
  src/AddItem/AddItem.st.css
  src/Animate/Animate.st.css
  src/AreaChart/AreaChart.st.css
  src/Avatar/Avatar.st.css
  src/BaseModalLayout/LayoutBlocks/Content/Content.st.css
  src/BaseModalLayout/LayoutBlocks/Footer/Footer.st.css
  src/Button/Button.st.css
  src/Calendar/DatePickerHead/styles.st.css
  src/CloseButton/CloseButton.st.css
  src/Collapse/Collapse.st.css
  src/DragAndDrop/docs/SortableList/MultiAreaListWithSortableColumnsWithAnimations/MultiAreaListWithSortableColumnsWithAnimations.js
  src/DragAndDrop/docs/SortableList/SingleAreaListWithAnimation/SingleAreaListWithAnimation.js
  src/Foundation/stylable/easing.st.css
  src/HorizontalTimeline/HorizontalTimelineIcons.st.css
  src/IconButton/IconButton.st.css
  src/ImageViewer/ImageViewer.st.css
  src/LinearProgressBar/LinearProgressBar.st.css
  src/Loader/Loader.st.css
  src/MediaOverlay/MediaOverlay.st.css
  src/NoBorderInput/NoBorderInput.st.css
  src/Popover/Popover.st.css
  src/Sidebar/Sidebar.st.css
  src/SidebarBackButton/SidebarBackButton.st.css
  src/Skeleton/Skeleton.st.css
  src/Slider/Slider.st.css
  src/Slider/SliderHandle.st.css
  src/StatisticsWidget/StatisticsItem/StatisticsItem.st.css
  src/TextButton/TextButton.st.css
  src/TimeTable/TimeTable.js
  src/ToggleButton/ToggleButton.st.css
  src/Tooltip/Tooltip.st.css
Labels: PR: unreviewed

#6318 Themes | Business Dashboard - feat(TextButton): add premium theme
  src/Themes/businessDashboard/components/TextButton.st.css
  src/Themes/businessDashboard/docs/components/TextButton.js
Labels: PR: unreviewed, Themes - Business Dashboard

#6315 <Table/> - [types] Add `content`to `infoTooltipProps`
  src/Table/DataTable/index.d.ts
  src/Table/test/Table.tsx
Labels: PR: reviewed-approved, auto pr

#6281 <Box/> - support space-separated spacing tokens
  perfer.config.js
  src/Box/Box.js
  src/Box/Box.scss
  src/Box/Box.st.css
  src/Box/constants.js
  src/Box/test/Box.spec.js
  src/spacing.js
  stories/Spacing/index.story.js
Labels: PR: reviewed-approved

#6321 <BadgeSelectItem /> - refactor storybook page
  src/BadgeSelectItem/BadgeSelectItem.js
  src/BadgeSelectItem/docs/ElipsisExample.js
  src/BadgeSelectItem/docs/Example.js
  src/BadgeSelectItem/docs/examples.js
  src/BadgeSelectItem/docs/index.js
  src/BadgeSelectItem/docs/index.story.js
  src/BadgeSelectItem/test/storySettings.js
  src/DropdownLayout/docs/index.story.js
  stories/index.js
Labels: PR: unreviewed

#6325 Themes | Business Dashboard - add TrendIndicator component
  src/Themes/businessDashboard/BusinessDashboard.st.css
  src/Themes/businessDashboard/components/TrendIndicator.st.css
  src/Themes/businessDashboard/docs/businessDashboard.story.js
  src/Themes/businessDashboard/docs/components/TrendIndicator.js
  src/Themes/businessDashboard/foundations/colors.st.css
  src/Themes/businessDashboard/test/businessDashboard.visual.js
  src/TrendIndicator/test/TrendIndicator.visual.js
Labels: PR: reviewed-approved, Themes - Business Dashboard

#6323 Themes | Business Dashboard - Keep color when hovering dark disabled ButtonText
  src/Themes/businessDashboard/components/TextButton.st.css
Labels: PR: partially-approved, Themes - Business Dashboard

#6319 <Tag/> - add lightOutlined theme
  src/Tag/Tag.js
  src/Tag/Tag.scss
  src/Tag/docs/examples.js
  src/Tag/index.d.ts
  src/Tag/test/Tag.spec.js
Labels: <Tag/>, PR: partially-approved, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed

#6332 release 9.45.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#6320 Introducing providers folder for hooks
  src/providers/index.js
Labels: PR: unreviewed

#6328 <Carousel/> - add `imagesPosition` and `imagesFit` props
  src/Carousel/Carousel.js
  src/Carousel/Carousel.st.css
  src/Carousel/docs/examples.js
  src/Carousel/docs/index.story.js
  src/Carousel/index.d.ts
  src/Carousel/test/Carousel.tsx
Labels: PR: unreviewed
