Repository wix/wix-style-react, pull requests merged in 2020-10, with the labels that each got.

#5890 FAQ and Troubleshooting article
  docs/FAQ/README.md
  docs/assets/storybook_snippet_url.png
  docs/usage/Troubleshooting.md
Labels: PR: unreviewed

#6046 <Avatar/> - remove unused e2e story
  src/Avatar/docs/AvatarStory.scss
  src/Avatar/test/Avatar.e2eStory.js
Labels: PR: unreviewed

#5999 <DropdownLayout /> - refactor story page
  .wuf/components.json
  src/DropdownLayout/DropdownLayout.js
  src/DropdownLayout/DropdownLayout.st.css
  src/DropdownLayout/DropdownLayout.uni.driver.d.ts
  src/DropdownLayout/DropdownLayout.uni.driver.js
  src/DropdownLayout/README.TESTKIT.md
  src/DropdownLayout/README.md
  src/DropdownLayout/docs/ExampleBuilder.js
  src/DropdownLayout/docs/ExampleControlled.js
  src/DropdownLayout/docs/ExampleControlledInContainer.js
  src/DropdownLayout/docs/ExampleManyOptions.js
  src/DropdownLayout/docs/ExampleReactElements.js
  src/DropdownLayout/docs/ExampleStandard.js
  src/DropdownLayout/docs/examples.js
  src/DropdownLayout/docs/index.js
  src/DropdownLayout/docs/index.story.js
  src/DropdownLayout/test/DropdownLayout.e2e.js
  src/DropdownLayout/test/DropdownLayout.e2eStory.js
  src/DropdownLayout/test/ExampleInfiniteScroll.js
  src/DropdownLayout/test/TestTabSwitches.js
  src/DropdownLayout/test/storySettings.js
  stories/index.js
Labels: PR: unreviewed

#6052 <GoogleAddressInput/> - change docs to sections
  src/GoogleAddressInput/docs/index.story.js
Labels: PR: unreviewed

#6056 <Card />: fix typo in docs
  src/Card/docs/index.story.js
Labels: PR: partially-approved

#6053 <Grid/> - AutoAdjustedColumns - Ignore falsy children
  src/Grid/Grid.js
  src/Grid/Grid.spec.js
  src/Grid/README.md
Labels: PR: reviewed-approved

#6055 add listItemEditableBuilder to .d.ts file
  src/ListItemEditable/ListItemEditable.js
  src/ListItemEditable/index.d.ts
  src/ListItemEditable/test/ListItemEditable.tsx
Labels: PR: unreviewed

#5987 <SelectableAccordion/> - new component
  .wuf/components.json
  perfer.config.js
  src/RadioGroup/RadioGroup.st.css
  src/SelectableAccordion/Item/Item.js
  src/SelectableAccordion/Item/Item.st.css
  src/SelectableAccordion/Item/index.d.ts
  src/SelectableAccordion/Item/index.js
  src/SelectableAccordion/SelectableAccordion.js
  src/SelectableAccordion/SelectableAccordion.meta.js
  src/SelectableAccordion/SelectableAccordion.st.css
  src/SelectableAccordion/SelectableAccordion.uni.driver.d.ts
  src/SelectableAccordion/SelectableAccordion.uni.driver.js
  src/SelectableAccordion/constants.js
  src/SelectableAccordion/docs/examples.js
  src/SelectableAccordion/docs/index.story.js
  src/SelectableAccordion/index.d.ts
  src/SelectableAccordion/index.js
  src/SelectableAccordion/test/SelectableAccordion.private.uni.driver.js
  src/SelectableAccordion/test/SelectableAccordion.spec.js
  src/SelectableAccordion/test/SelectableAccordion.tsx
  src/SelectableAccordion/test/SelectableAccordion.visual.js
  src/SelectableAccordion/test/storySettings.js
  src/SelectableAccordion/utils.js
  src/index.d.ts
  src/index.js
  stories/index.js
Labels: PR: unreviewed, WIP

#6024 <Ellipsis/> - tooltip value is not updated when changing the text content
  perfer.config.js
  src/common/Ellipsis/Ellipsis.js
  src/common/Ellipsis/test/Ellipsis.e2e.js
  src/common/Ellipsis/test/Ellipsis.e2eStory.js
Labels: <Ellipsis/>, Bug, PR: reviewed-approved, PR: unreviewed

#6059 Release/9.18.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#6061 <Dropzone /> - Fix Bug
  src/Dropzone/Dropzone.js
Labels: PR: reviewed-approved

#6058 test(protractor): balance protractor tests
  package.json
  protractor1.conf.js
  protractor2.conf.js
  test/components-for-e2e-tests.js
Labels: Infrastructure, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed

#6062 <Text/> - rearrange docs
  perfer.config.js
  src/Text/README.TESTKIT.md
  src/Text/README.md
  src/Text/RawText.js
  src/Text/Text.js
  src/Text/Text.meta.js
  src/Text/Text.uni.driver.js
Labels: PR: unreviewed

#6063 <Page/> - fix image blurry edges
  src/Page/Page.scss
Labels: PR: unreviewed

#6057 <BadgeSelect /> - Added subtitle
  perfer.config.js
  src/BadgeSelect/BadgeSelect.js
  src/BadgeSelect/docs/examples.js
  src/BadgeSelect/docs/index.story.js
  src/BadgeSelect/test/BadgeSelect.visual.js
  src/BadgeSelectItemBuilder/BadgeSelectItem.st.css
  src/BadgeSelectItemBuilder/BadgeSelectItemBuilder.js
  src/BadgeSelectItemBuilder/index.d.ts
  src/BadgeSelectItemBuilder/test/BadgeSelectItemBuilder.tsx
Labels: PR: unreviewed

#6000 <SparklineChart/> - creating SparklineChart component
  .wuf/components.json
  package.json
  perfer.config.js
  src/SparklineChart/ChartTooltip.js
  src/SparklineChart/ChartTooltip.st.css
  src/SparklineChart/SparklineChart.js
  src/SparklineChart/SparklineChart.meta.js
  src/SparklineChart/SparklineChart.uni.driver.d.ts
  src/SparklineChart/SparklineChart.uni.driver.js
  src/SparklineChart/constants.js
  src/SparklineChart/docs/index.story.js
  src/SparklineChart/index.d.ts
  src/SparklineChart/index.js
  src/SparklineChart/test/SparklineChart.private.uni.driver.js
  src/SparklineChart/test/SparklineChart.spec.js
  src/SparklineChart/test/SparklineChart.tsx
  src/SparklineChart/test/SparklineChart.visual.js
  src/SparklineChart/test/storySettings.js
  src/index.d.ts
  src/index.js
  stories/index.js
  testkit/component-definitions.js
Labels: PR: reviewed-approved

#5902 <StackedBarChart/> - new component
  .wuf/components.json
  perfer.config.js
  src/StackedBarChart/StackedBarChart.js
  src/StackedBarChart/StackedBarChart.meta.js
  src/StackedBarChart/StackedBarChart.st.css
  src/StackedBarChart/StackedBarChart.uni.driver.d.ts
  src/StackedBarChart/StackedBarChart.uni.driver.js
  src/StackedBarChart/constants.js
  src/StackedBarChart/docs/index.story.js
  src/StackedBarChart/index.d.ts
  src/StackedBarChart/index.js
  src/StackedBarChart/test/StackedBarChart.private.uni.driver.js
  src/StackedBarChart/test/StackedBarChart.spec.js
  src/StackedBarChart/test/StackedBarChart.tsx
  src/StackedBarChart/test/StackedBarChart.visual.js
  src/StackedBarChart/test/storySettings.js
  src/index.d.ts
  src/index.js
  stories/index.js
Labels: New Component, PR: unreviewed

#6067 <AddItem/> - Add a className for the Text and use it.
  src/AddItem/AddItem.js
  src/AddItem/AddItem.st.css
Labels: PR: reviewed-approved

#6073 List item builders visual tests
  src/ListItemAction/test/ListItemAction.visual.js
  src/ListItemEditable/test/ListItemEditable.visual.js
  src/ListItemSection/test/ListItemSection.visual.js
  src/ListItemSelect/test/ListItemSelect.visual.js
Labels: PR: unreviewed

#6072 ListActionItem - Add margin:0 to root class
  src/ListItemAction/ListItemAction.st.css
Labels: PR: unreviewed

#6074  <BadgeSelect/> - Add subtitle to BadgeSelectOptionType
  src/BadgeSelect/index.d.ts
  src/BadgeSelect/test/BadgeSelect.tsx
Labels: PR: unreviewed

#6064 <Page/> - Change container to be flex
  src/Page/Page.scss
Labels: PR: unreviewed

#6066 Cheatsheet- render tests
  stories/Introduction/Cheatsheet/ComponentsCheatsheet.spec.js
  stories/Introduction/Cheatsheet/componentsFamilies/ButtonFamily.js
  stories/Introduction/Cheatsheet/componentsFamilies/InputFamily.js
  stories/Introduction/Cheatsheet/componentsFamilies/InternalFamily.js
  stories/Introduction/Cheatsheet/componentsFamilies/ModalFamily.js
  stories/Introduction/Cheatsheet/componentsFamilies/NavigationFamily.js
  stories/Introduction/Cheatsheet/componentsFamilies/OtherFamily.js
  stories/Introduction/Cheatsheet/componentsFamilies/PickerFamily.js
  stories/Introduction/Cheatsheet/componentsFamilies/SelectionFamily.js
Labels: PR: unreviewed

#6075 <StackedBarChart/> - Add more custom props
  .wuf/components.json
  perfer.config.js
  src/ListItemAction/docs/index.story.js
  src/StackedBarChart/StackedBarChart.js
  src/StackedBarChart/docs/index.story.js
  src/StackedBarChart/index.d.ts
  src/StackedBarChart/test/StackedBarChart.tsx
Labels: PR: reviewed-approved

#6077 <Table/> - filter selected items when items are deleted
  src/Table/BulkSelection/BulkSelection.js
  src/Table/BulkSelection/BulkSelection.spec.js
Labels: PR: reviewed-approved

#6068 cheatsheet- adding new components
  stories/Introduction/Cheatsheet/componentsFamilies/ContentWidgetsFamily.js
  stories/symbolsComponentsMapping/components.js
  stories/symbolsComponentsMapping/families/contentWidgetsFamily.js
  stories/symbolsComponentsMapping/symbols.js
Labels: PR: unreviewed

#6065 `<DropdownLayout/>`- align design of title and divider
  perfer.config.js
  src/DropdownLayout/DataAttr.js
  src/DropdownLayout/DropdownLayout.driver.js
  src/DropdownLayout/DropdownLayout.js
  src/DropdownLayout/DropdownLayout.st.css
  src/DropdownLayout/DropdownLayout.uni.driver.js
  src/DropdownLayout/docs/examples.js
  src/DropdownLayout/docs/index.story.js
  src/DropdownLayout/test/DropdownLayout.spec.js
Labels: PR: partially-approved

#6080 <StackedBarChart/> - Y axis format
  src/StackedBarChart/StackedBarChart.js
  src/StackedBarChart/docs/examples.js
  src/StackedBarChart/docs/index.story.js
  src/StackedBarChart/index.d.ts
  src/StackedBarChart/test/StackedBarChart.tsx
Labels: PR: unreviewed

#6084 <Carousel/> - migrate to Stylable
  package.json
  src/Carousel/Carousel.js
  src/Carousel/Carousel.private.driver.js
  src/Carousel/Carousel.private.uni.driver.js
  src/Carousel/Carousel.scss
  src/Carousel/Carousel.st.css
  src/Carousel/Pagination/Pagination.js
  src/Carousel/Pagination/Pagination.scss
  src/Carousel/Pagination/Pagination.st.css
Labels: PR: unreviewed

#6083 <Tabs/> - added size small
  src/Tabs/Tabs.js
  src/Tabs/Tabs.st.css
  src/Tabs/core/TabItem/index.js
  src/Tabs/core/TabItems/index.js
  src/Tabs/core/constants/tab-types.js
  src/Tabs/docs/examples.js
  src/Tabs/docs/index.story.js
  src/Tabs/index.d.ts
  src/Tabs/test/Tabs.tsx
  src/Tabs/test/Tabs.visual.js
Labels: PR: reviewed-approved

#6087 <StatisticsWidget/> - add margin left to description info icon
  src/StatisticsWidget/StatisticsItem/StatisticsItem.st.css
Labels: PR: unreviewed

#6089 WSR version 9.22.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#6094 <Animate/>- fix
  src/Animate/Animate.js
  src/Animate/docs/index.story.js
Labels: PR: unreviewed

#6093 BadgeSelectBuilder | Add elipsis
  src/BadgeSelect/test/BadgeSelect.visual.js
  src/BadgeSelectItemBuilder/BadgeSelectItem.st.css
  src/BadgeSelectItemBuilder/BadgeSelectItemBuilder.js
  src/BadgeSelectItemBuilder/docs/ElipsisExample.js
  src/BadgeSelectItemBuilder/docs/index.js
  src/BadgeSelectItemBuilder/index.d.ts
  src/BadgeSelectItemBuilder/test/BadgeSelectItemBuilder.tsx
  src/Carousel/Carousel.st.css
Labels: PR: unreviewed

#6091 <InputArea/> - Remove flaky tests
  src/InputArea/InputArea.js
  src/InputArea/InputAreaSuffix.js
  src/InputArea/README.TESTKIT.md
  src/InputArea/test/InputArea.visual.js
Labels: PR: unreviewed

#6096 <ModalMobileLayout/> - tiny refactor
  src/ModalMobileLayout/ModalMobileLayout.js
  src/ModalMobileLayout/ModalMobileLayout.st.css
  src/ModalMobileLayout/ModalMobileLayout.uni.driver.js
  src/ModalMobileLayout/index.d.ts
  src/ModalMobileLayout/test/ModalMobileLayout.tsx
Labels: PR: unreviewed

#6099 <DropdownLayout/> - adding visual tests
  src/DropdownLayout/DropdownLayout.st.css
  src/DropdownLayout/test/DropdownLayout.visual.js
Labels: PR: unreviewed

#6082 Theming - Create a "Business Dashboard" theme
  .storybook/e2e/stories.scss
  .storybook/visual/preview-head.html
  .storybook/visual/stories.scss
  src/Button/test/Button.visual.js
  src/CircularProgressBar/test/CircularProgressBar.visual.js
  src/ThemeProvider/ThemeProvider.js
  src/ThemeProvider/index.d.ts
  src/ThemeProvider/test/ThemeProvider.tsx
  src/Themes/businessDashboard/BusinessDashboard.js
  src/Themes/businessDashboard/BusinessDashboard.st.css
  src/Themes/businessDashboard/components/Button.st.css
  src/Themes/businessDashboard/components/CircularProgressBar.st.css
  src/Themes/businessDashboard/docs/businessDashboard.story.js
  src/Themes/businessDashboard/docs/components/Button.js
  src/Themes/businessDashboard/docs/components/Carousel.js
  src/Themes/businessDashboard/docs/components/CircularProgressBar.js
  src/Themes/businessDashboard/docs/index.js
  src/Themes/businessDashboard/docs/storySettings.js
  src/Themes/businessDashboard/foundations/colors.st.css
  src/Themes/businessDashboard/index.d.ts
  src/Themes/businessDashboard/index.js
  src/Themes/businessDashboard/test/businessDashboard.visual.js
  stories/index.js
  stories/storiesHierarchy.js
  stories/utils/allComponents.js
  themes/businessDashboard/package.json
Labels: PR: unreviewed

#6079 <AddItem/> - Support customising icons with theming mechanism
  src/AddItem/AddItem.js
  src/AddItem/AddItem.spec.js
  src/AddItem/AddItem.st.css
  src/AddItem/constants.js
  src/AddItem/index.d.ts
  src/AddItem/test/AddItem.tsx
  src/AddItem/test/AddItem.visual.js
  src/ThemeProvider/index.d.ts
  src/ThemeProvider/test/ThemeProvider.tsx
Labels: PR: unreviewed, WIP

#6103 Release/9.24.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#6070 Update React version to ^16.13.1
  README.md
  package.json
  test-runtime/imports/src/index.vm
Labels: DO NOT MERGE, POC, PR: partially-approved, PR: unreviewed

#6107 <BadgeSelect/> - fix flaky visual tests
  src/BadgeSelect/test/BadgeSelect.visual.js
Labels: PR: unreviewed

#6106 <ListItemSelect/>- fix on hover& select styles
  src/ListItemSelect/ListItemSelect.st.css
  src/ListItemSelect/test/ListItemSelect.visual.js
Labels: PR: unreviewed

#6041 <VariableInput/> - implement `enterText ` UniDriver method for puppeteer
  src/RichTextInputArea/RichTextInputArea.private.uni.driver.js
  src/RichTextInputArea/RichTextInputArea.uni.driver.js
  src/VariableInput/VariableInput.uni.driver.js
  test/utils/unidriver/DraftJS.js
Labels: PR: reviewed-approved

#6111 <Input/> - fix unidriver trigger change method
  src/Input/Input.uni.driver.js
  src/Input/test/Input.spec.js
Labels: Bug, PR: draft, PR: reviewed-approved

#6097 <SectionHelper/> - unify paddings with no close button
  src/SectionHelper/SectionHelper.js
  src/SectionHelper/test/SectionHelper.visual.js
Labels: <SectionHelper/>, PR: reviewed-approved

#6101 <Input/> - fix testkit `enterValue` method for uncontrolled inputs
  src/Input/test/Input.spec.js
  src/MultiSelect/test/MultiSelect.spec.js
Labels: PR: unreviewed

#6109 badgeSelectBuilder and listItemSelectBuilder- fix builders and some types fixes
  src/BadgeSelect/BadgeSelect.js
  src/BadgeSelect/index.d.ts
  src/BadgeSelect/test/BadgeSelect.tsx
  src/BadgeSelectItemBuilder/BadgeSelectItem.st.css
  src/BadgeSelectItemBuilder/BadgeSelectItemBuilder.js
  src/BadgeSelectItemBuilder/index.d.ts
  src/BadgeSelectItemBuilder/test/BadgeSelectItemBuilder.tsx
  src/ListItemSelect/ListItemSelect.js
Labels: PR: reviewed-approved

#6113 Charts utils - remove Intl
  perfer.config.js
  src/utils/numberFormatters.js
  src/utils/numberFormatters.spec.js
Labels: PR: unreviewed

#6116 release 9.26.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#6117 badgeSelectBuilder- fix docs and example
  src/BadgeSelectItemBuilder/docs/ElipsisExample.js
  src/BadgeSelectItemBuilder/docs/README.md
Labels: PR: unreviewed

#6108 <AddItem/> - add ariaLabel and ariaLabelledBy props for a11y
  src/AddItem/AddItem.js
  src/AddItem/index.d.ts
  src/AddItem/test/AddItem.tsx
Labels: PR: reviewed-approved

#6118 <TableToolbar/> - fix import warning
  src/TableToolbar/docs/index.story.js
  src/TableToolbar/index.d.ts
Labels: PR: unreviewed

#6095 <FontUpgrade/> - migrate to Stylable
  src/Avatar/Avatar.js
  src/Breadcrumbs/Breadcrumbs.js
  src/Button/Button.js
  src/EmptyState/EmptyState.js
  src/FontUpgrade/FontUpgrade.js
  src/FontUpgrade/FontUpgrade.st.css
  src/FontUpgrade/FontUpgrade.uni.driver.js
  src/FontUpgrade/test/FontUpgrade.spec.js
  src/Modal/Modal.js
  src/Popover/Popover.js
  src/SectionHelper/SectionHelper.js
  src/SidebarSectionItem/SidebarSectionItem.js
  src/Tooltip/Tooltip.js
Labels: PR: unreviewed

#6119 release 9.27.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#6120 fix(DropdownBase): add `className` to typings
  src/DropdownBase/index.d.ts
  src/DropdownBase/test/DropdownBase.tsx
Labels: <DropdownBase/>, PR: unreviewed

#6121 badgeSelectItemBuilder - fix style
  src/BadgeSelectItemBuilder/BadgeSelectItem.st.css
  src/BadgeSelectItemBuilder/BadgeSelectItemBuilder.js
Labels: PR: reviewed-approved

#6102 <Modal/> - fix testkit when there's more than one modal
  src/Modal/Modal.driver.js
  src/Modal/Modal.js
  src/Modal/Modal.uni.driver.js
  src/Modal/test/Modal.spec.js
Labels: PR: reviewed-approved

#6114 <Multiselect/> - tags change color on hover #4041
  src/Tag/Tag.js
  src/Tag/Tag.private.driver.js
  src/Tag/Tag.private.uni.driver.js
  src/Tag/Tag.scss
  src/Tag/test/Tag.spec.js
Labels: <Tag/>, PR: reviewed-approved, PR: unreviewed

#6112 <Timeline/> - fix suffix
  src/Timeline/TimelineItem.js
  src/Timeline/TimelineItem.st.css
  src/Timeline/test/Timeline.visual.js
Labels: PR: reviewed-approved

#6123 feat(puppeteer-typescript): add `wrapper` argument
  .wuf/testkits/puppeteer-typescript.template.ejs
Labels: Infrastructure, PR: unreviewed, Testkit

#6126 Update Input.st.css
  src/Input/Input.st.css
Labels: PR: unreviewed

#6127 release 9.28.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#6088 <DropdownLayout/>- using builder for selectable option
  perfer.config.js
  src/DropdownBase/DropdownBase.uni.driver.js
  src/DropdownLayout/DataAttr.js
  src/DropdownLayout/DropdownLayout.driver.d.ts
  src/DropdownLayout/DropdownLayout.driver.js
  src/DropdownLayout/DropdownLayout.js
  src/DropdownLayout/DropdownLayout.st.css
  src/DropdownLayout/DropdownLayout.uni.driver.d.ts
  src/DropdownLayout/DropdownLayout.uni.driver.js
  src/DropdownLayout/docs/examples.js
  src/DropdownLayout/test/DropdownLayout.spec.js
  src/DropdownLayout/test/DropdownLayout.visual.js
  src/ListItemSelect/ListItemSelect.uni.driver.d.ts
  src/ListItemSelect/ListItemSelect.uni.driver.js
Labels: PR: unreviewed

#6128 release 9.29.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#6131 Getting build alerts in Slack
  pom.xml
Labels: PR: unreviewed

#6130 <DropdownLayout/>- revert ddl
  perfer.config.js
  src/DropdownBase/DropdownBase.uni.driver.js
  src/DropdownLayout/DataAttr.js
  src/DropdownLayout/DropdownLayout.driver.d.ts
  src/DropdownLayout/DropdownLayout.driver.js
  src/DropdownLayout/DropdownLayout.js
  src/DropdownLayout/DropdownLayout.st.css
  src/DropdownLayout/DropdownLayout.uni.driver.d.ts
  src/DropdownLayout/DropdownLayout.uni.driver.js
  src/DropdownLayout/docs/examples.js
  src/DropdownLayout/test/DropdownLayout.spec.js
  src/DropdownLayout/test/DropdownLayout.visual.js
  src/ListItemSelect/ListItemSelect.uni.driver.d.ts
  src/ListItemSelect/ListItemSelect.uni.driver.js
Labels: PR: unreviewed

#6133 Release 9.29.1
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#6137 Fix stores broken builds
  src/Modal/Modal.driver.js
Labels: PR: unreviewed

#6134 `<CounterBadge/>` - fix medium counter badge content
  src/CounterBadge/CounterBadge.js
  src/CounterBadge/CounterBadge.uni.driver.js
  src/CounterBadge/constants.js
  src/CounterBadge/test/CounterBadge.spec.js
Labels: PR: reviewed-approved

#6144 Themes - publish entry files
  package.json
Labels: PR: unreviewed

#6145 Release/9.29.3
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#6049 <AddressInput /> – New component added
  .wuf/components.json
  perfer.config.js
  src/AddressInput/AddressInput.js
  src/AddressInput/AddressInput.meta.js
  src/AddressInput/AddressInput.uni.driver.d.ts
  src/AddressInput/AddressInput.uni.driver.js
  src/AddressInput/docs/index.story.js
  src/AddressInput/index.d.ts
  src/AddressInput/index.js
  src/AddressInput/test/AddressInput.private.uni.driver.js
  src/AddressInput/test/AddressInput.spec.js
  src/AddressInput/test/AddressInput.tsx
  src/AddressInput/test/AddressInput.visual.js
  src/AddressInput/test/storySettings.js
  src/index.d.ts
  src/index.js
  stories/index.js
Labels: New Component, PR: reviewed-approved, PR: unreviewed

#6135 <Layout/> - Add rowHeight prop
  src/Layout/Cell/index.js
  src/Layout/Cell/styles.st.css
  src/Layout/Layout/index.js
  src/Layout/Layout/index.spec.js
  src/Layout/Layout/styles.st.css
  src/Layout/docs/examples.js
  src/Layout/docs/index.story.js
  src/Layout/index.d.ts
  src/Layout/test/Layout.tsx
  src/Layout/test/storySettings.js
Labels: PR: unreviewed

#6147 Updated business dashboard theme color foundations
  src/Themes/businessDashboard/foundations/colors.st.css
Labels: PR: unreviewed

#6148 <VerticalTabs/> - refactor story page
  src/VerticalTabs/VerticalTabs.js
  src/VerticalTabs/VerticalTabs.uni.driver.js
  src/VerticalTabs/docs/index.story.js
  src/VerticalTabs/docs/storySettings.js
Labels: <VerticalTabs/>, PR: partially-approved, PR: reviewed-changes-requested, PR: unreviewed

#6138 <Dropdown/> - change cursor type to pointer on input field
  src/Dropdown/Dropdown.st.css
Labels: PR: reviewed-approved

#6132 <CustomModalLayout/> - Remove 3px content padding
  src/CustomModalLayout/CustomModalLayout.st.css
  src/CustomModalLayout/docs/examples/DropdownExample.js
  src/CustomModalLayout/docs/examples/InputExample.js
  src/CustomModalLayout/docs/index.story.js
Labels: PR: partially-approved

#6129 <DatePicker/> - RTL support
  src/Calendar/Calendar.js
  src/Calendar/index.d.ts
  src/Calendar/test/Calendar.tsx
  src/DatePicker/DateInput/index.d.ts
  src/DatePicker/DatePicker.driver.js
  src/DatePicker/DatePicker.js
  src/DatePicker/DatePicker.st.css
  src/DatePicker/constants.js
  src/DatePicker/test/DatePicker.spec.js
  src/DatePicker/test/DatePicker.visual.js
Labels: PR: unreviewed
