Repository wix/wix-style-react, pull requests merged in 2020-09, with the labels that each got.

#5900 <Notification/> - fix ellipsis tooltip positioning
  src/Notification/TextLabel/index.js
  src/Notification/docs/README.md
  src/Notification/index.d.ts
Labels: <Notification/>, Bug

#5843 <Breadcrumbs /> - show ellipsis for long texts
  src/Breadcrumbs/Breadcrumbs.js
  src/Breadcrumbs/Breadcrumbs.st.css
  src/Breadcrumbs/docs/examples/BreadcrumbsEllipsis.js
  src/Breadcrumbs/docs/index.story.js
  src/Breadcrumbs/index.d.ts
  src/Breadcrumbs/test/Breadcrumbs.tsx
  src/Breadcrumbs/test/Breadcrumbs.visual.js
Labels: <Breadcrumbs/>

#5909 <MarketingPageLayout/> - new component
  .wuf/components.json
  perfer.config.js
  src/Foundation/stylable/spacing.st.css
  src/MarketingPageLayout/MarketingPageLayout.js
  src/MarketingPageLayout/MarketingPageLayout.meta.js
  src/MarketingPageLayout/MarketingPageLayout.st.css
  src/MarketingPageLayout/MarketingPageLayout.uni.driver.d.ts
  src/MarketingPageLayout/MarketingPageLayout.uni.driver.js
  src/MarketingPageLayout/constants.js
  src/MarketingPageLayout/docs/examples.js
  src/MarketingPageLayout/docs/index.story.js
  src/MarketingPageLayout/index.d.ts
  src/MarketingPageLayout/index.js
  src/MarketingPageLayout/test/MarketingPageLayout.private.uni.driver.js
  src/MarketingPageLayout/test/MarketingPageLayout.spec.js
  src/MarketingPageLayout/test/MarketingPageLayout.tsx
  src/MarketingPageLayout/test/MarketingPageLayout.visual.js
  src/MarketingPageLayout/test/storySettings.js
  src/index.d.ts
  src/index.js
  stories/Introduction/Cheatsheet/componentsFamilies/LayoutFamily/LayoutFamily.js
  stories/Introduction/Cheatsheet/componentsFamilies/LayoutFamily/examples/MarketingPageLayoutExample.js
  stories/index.js
  stories/symbolsComponentsMapping/components.js
  stories/symbolsComponentsMapping/families/layoutFamily.js
  stories/symbolsComponentsMapping/symbols.js
Labels: New Component

#5951 update playground link in github issue template
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
Labels: Docs, PR: unreviewed

#5957 <BadgeSelect /> - refactor story page and some improvements
  src/BadgeSelect/BadgeSelect.js
  src/BadgeSelect/docs/ControlledComponentExample.js
  src/BadgeSelect/docs/examples.js
  src/BadgeSelect/docs/index.story.js
  src/BadgeSelect/index.d.ts
  src/BadgeSelect/test/BadgeSelect.tsx
  src/BadgeSelect/test/storySettings.js
  testkit/component-definitions.js
Labels: PR: reviewed-approved

#5956 <PageHeader /> - BackButton support - RTL
  src/PageHeader/PageHeader.scss
Labels: PR: reviewed-approved

#5959 release 9.9.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#5958 <BaseModalLayout /> - support nodes as button's children
  src/BaseModalLayout/LayoutBlocks/Footer/Footer.js
  src/BaseModalLayout/test/BaseModalLayout.spec.js
Labels: PR: unreviewed

#5885 `<Ellipsis/>` - adding "maxLines" prop
  src/Text/RawText.js
  src/Text/Text.js
  src/Text/docs/examples.js
  src/Text/docs/index.story.js
  src/Text/test/Text.visual.js
  src/common/Ellipsis/Ellipsis.js
  src/common/Ellipsis/Ellipsis.st.css
  src/common/Ellipsis/EllipsisUtils.js
  src/common/Ellipsis/index.d.ts
  src/common/Ellipsis/test/Ellipsis.tsx
Labels: <Text/>, PR: partially-approved, PR: unreviewed

#5964 <Pageheader/>- subtitle of 2 lines
  src/PageHeader/PageHeader.driver.js
  src/PageHeader/PageHeader.js
  src/PageHeader/PageHeader.uni.driver.js
  src/PageHeader/constants.js
  src/PageHeader/docs/examples.js
  src/PageHeader/docs/index.story.js
  src/PageHeader/test/PageHeader.visual.js
Labels: PR: unreviewed

#5966 <BaseModalLayout/> - Fix button content type
  src/BaseModalLayout/LayoutBlocks/Footer/index.d.ts
Labels: PR: unreviewed

#5967 <Layout/> - remove documentation warning
  src/Layout/Layout/README.md
Labels: <Layout/>, Docs, PR: reviewed-approved, PR: unreviewed

#5831 <ModalSelectorLayout/> - use new <CustomModalLayout/>
  src/BaseModalLayout/BaseModalLayout.legacy.driver.js
  src/CustomModalLayout/CustomModalLayout.js
  src/CustomModalLayout/CustomModalLayout.st.css
  src/ModalSelectorLayout/ModalSelectorLayout.driver.d.ts
  src/ModalSelectorLayout/ModalSelectorLayout.driver.js
  src/ModalSelectorLayout/ModalSelectorLayout.helpers.js
  src/ModalSelectorLayout/ModalSelectorLayout.js
  src/ModalSelectorLayout/ModalSelectorLayout.scss
  src/ModalSelectorLayout/ModalSelectorLayout.uni.driver.d.ts
  src/ModalSelectorLayout/ModalSelectorLayout.uni.driver.js
  src/ModalSelectorLayout/docs/index.story.js
  src/ModalSelectorLayout/test/ModalSelectorLayout.spec.js
  src/ModalSelectorLayout/test/ModalSelectorLayout.tsx
Labels: PR: reviewed-approved

#5969 Revert "<ModalSelectorLayout/> - use new <CustomModalLayout/>"
  CHANGELOG.md
  src/BaseModalLayout/BaseModalLayout.legacy.driver.js
  src/CustomModalLayout/CustomModalLayout.js
  src/CustomModalLayout/CustomModalLayout.st.css
  src/ModalSelectorLayout/ModalSelectorLayout.driver.d.ts
  src/ModalSelectorLayout/ModalSelectorLayout.driver.js
  src/ModalSelectorLayout/ModalSelectorLayout.helpers.js
  src/ModalSelectorLayout/ModalSelectorLayout.js
  src/ModalSelectorLayout/ModalSelectorLayout.scss
  src/ModalSelectorLayout/ModalSelectorLayout.uni.driver.d.ts
  src/ModalSelectorLayout/ModalSelectorLayout.uni.driver.js
  src/ModalSelectorLayout/docs/index.story.js
  src/ModalSelectorLayout/test/ModalSelectorLayout.spec.js
  src/ModalSelectorLayout/test/ModalSelectorLayout.tsx
Labels: PR: unreviewed

#5971 release 9.10.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#5972 Revert "Revert "<ModalSelectorLayout/> - use new <CustomModalLayout/>""
  CHANGELOG.md
  src/BaseModalLayout/BaseModalLayout.legacy.driver.js
  src/CustomModalLayout/CustomModalLayout.js
  src/CustomModalLayout/CustomModalLayout.st.css
  src/ModalSelectorLayout/ModalSelectorLayout.driver.d.ts
  src/ModalSelectorLayout/ModalSelectorLayout.driver.js
  src/ModalSelectorLayout/ModalSelectorLayout.helpers.js
  src/ModalSelectorLayout/ModalSelectorLayout.js
  src/ModalSelectorLayout/ModalSelectorLayout.scss
  src/ModalSelectorLayout/ModalSelectorLayout.uni.driver.d.ts
  src/ModalSelectorLayout/ModalSelectorLayout.uni.driver.js
  src/ModalSelectorLayout/docs/index.story.js
  src/ModalSelectorLayout/test/ModalSelectorLayout.spec.js
  src/ModalSelectorLayout/test/ModalSelectorLayout.tsx
Labels: PR: unreviewed

#5974 <Slider/> - fix tooltip typography
  src/Slider/SliderHandle.st.css
Labels: PR: unreviewed

#5904 <FunnelChart/> - new component
  .wuf/components.json
  perfer.config.js
  src/FunnelChart/FunnelBadge/FunnelBadge.js
  src/FunnelChart/FunnelBadge/FunnelBadge.st.css
  src/FunnelChart/FunnelBadge/index.d.ts
  src/FunnelChart/FunnelBadge/index.js
  src/FunnelChart/FunnelBar/FunnelBar.js
  src/FunnelChart/FunnelBar/FunnelBar.st.css
  src/FunnelChart/FunnelBar/index.js
  src/FunnelChart/FunnelChart.js
  src/FunnelChart/FunnelChart.meta.js
  src/FunnelChart/FunnelChart.st.css
  src/FunnelChart/FunnelChart.uni.driver.d.ts
  src/FunnelChart/FunnelChart.uni.driver.js
  src/FunnelChart/FunnelLabel/FunnelLabel.js
  src/FunnelChart/FunnelLabel/FunnelLabel.st.css
  src/FunnelChart/FunnelLabel/index.d.ts
  src/FunnelChart/FunnelLabel/index.js
  src/FunnelChart/FunnelStep/FunnelStep.js
  src/FunnelChart/FunnelStep/FunnelStep.st.css
  src/FunnelChart/FunnelStep/index.js
  src/FunnelChart/constants.js
  src/FunnelChart/docs/index.story.js
  src/FunnelChart/index.d.ts
  src/FunnelChart/index.js
  src/FunnelChart/test/FunnelChart.private.uni.driver.js
  src/FunnelChart/test/FunnelChart.spec.js
  src/FunnelChart/test/FunnelChart.tsx
  src/FunnelChart/test/FunnelChart.visual.js
  src/FunnelChart/test/storySettings.js
  src/FunnelChart/utils/numberFormatters.js
  src/FunnelChart/utils/numberFormatters.spec.js
  src/index.d.ts
  src/index.js
  stories/index.js
  testkit/component-definitions.js
Labels: New Component, PR: draft, PR: reviewed-changes-requested, PR: unreviewed

#5978 Revert "<ModalSelectorLayout/> - use new <CustomModalLayout/> (#5831)"
  src/BaseModalLayout/BaseModalLayout.legacy.driver.js
  src/CustomModalLayout/CustomModalLayout.js
  src/CustomModalLayout/CustomModalLayout.st.css
  src/ModalSelectorLayout/ModalSelectorLayout.driver.d.ts
  src/ModalSelectorLayout/ModalSelectorLayout.driver.js
  src/ModalSelectorLayout/ModalSelectorLayout.helpers.js
  src/ModalSelectorLayout/ModalSelectorLayout.js
  src/ModalSelectorLayout/ModalSelectorLayout.scss
  src/ModalSelectorLayout/ModalSelectorLayout.uni.driver.d.ts
  src/ModalSelectorLayout/ModalSelectorLayout.uni.driver.js
  src/ModalSelectorLayout/docs/index.story.js
  src/ModalSelectorLayout/test/ModalSelectorLayout.spec.js
  src/ModalSelectorLayout/test/ModalSelectorLayout.tsx
Labels: PR: unreviewed

#5986 <ModalSelectorLayout/> - use new <CustomModalLayout/>
  src/BaseModalLayout/BaseModalLayout.legacy.driver.js
  src/CustomModalLayout/CustomModalLayout.js
  src/CustomModalLayout/CustomModalLayout.st.css
  src/ModalSelectorLayout/ModalSelectorLayout.driver.d.ts
  src/ModalSelectorLayout/ModalSelectorLayout.driver.js
  src/ModalSelectorLayout/ModalSelectorLayout.helpers.js
  src/ModalSelectorLayout/ModalSelectorLayout.js
  src/ModalSelectorLayout/ModalSelectorLayout.scss
  src/ModalSelectorLayout/ModalSelectorLayout.uni.driver.d.ts
  src/ModalSelectorLayout/ModalSelectorLayout.uni.driver.js
  src/ModalSelectorLayout/docs/index.story.js
  src/ModalSelectorLayout/test/ModalSelectorLayout.spec.js
  src/ModalSelectorLayout/test/ModalSelectorLayout.tsx
Labels: PR: unreviewed

#5977 <ListItemAction/> - improve visual tests
  src/ListItemAction/test/ListItemAction.visual.js
Labels: PR: unreviewed

#5962 remove `yoshi test` and use `jest` directly
  .gitignore
  babel.config.js
  jest.config.js
  package.json
  scripts/transpile/tasks/transpile-src.js
Labels: Infrastructure, PR: unreviewed

#5983 CustomModalLayout - Adding support for `showFooterDivider`
  src/CustomModalLayout/CustomModalLayout.js
  src/CustomModalLayout/index.d.ts
  src/CustomModalLayout/test/CustomModalLayout.tsx
  src/CustomModalLayout/test/CustomModalLayout.visual.js
Labels: PR: partially-approved

#5984 <Collapse /> - refactor story page
  src/Collapse/docs/examples.js
  src/Collapse/docs/index.story.js
  src/Collapse/test/storySettings.js
Labels: PR: partially-approved

#5990 <Text/> | add primary to TextSkin type
  src/Text/index.d.ts
Labels: PR: reviewed-approved

#5960 <PopoverMenu.MenuItem/> <ListItemAction/> - add subtitle property
  perfer.config.js
  src/ListItemAction/ListItemAction.js
  src/ListItemAction/ListItemAction.st.css
  src/ListItemAction/ListItemAction.uni.driver.d.ts
  src/ListItemAction/ListItemAction.uni.driver.js
  src/ListItemAction/docs/README.md
  src/ListItemAction/docs/examples.js
  src/ListItemAction/docs/index.story.js
  src/ListItemAction/index.d.ts
  src/ListItemAction/test/ListItemAction.spec.js
  src/ListItemAction/test/ListItemAction.tsx
  src/ListItemAction/test/ListItemAction.visual.js
  src/PopoverMenu/PopoverMenu.js
  src/PopoverMenu/docs/compound.md
  src/PopoverMenu/docs/index.story.js
  src/PopoverMenu/index.d.ts
  src/PopoverMenu/test/PopoverMenu.tsx
Labels: PR: unreviewed

#5989 <Timeline /> - ordered list
  src/Timeline/Timeline.js
  src/Timeline/docs/index.story.js
Labels: PR: reviewed-approved

#5979 <EmptyState/> - refactor story page
  src/EmptyState/docs/examples.js
  src/EmptyState/docs/index.story.js
  src/EmptyState/test/storySettings.js
Labels: PR: reviewed-approved

#5993 <FunnelChart/>- adding to cheatsheet
  stories/Introduction/Cheatsheet/componentsFamilies/ContentWidgetsFamily.js
  stories/symbolsComponentsMapping/components.js
  stories/symbolsComponentsMapping/families/contentWidgetsFamily.js
  stories/symbolsComponentsMapping/symbols.js
Labels: <FunnelChart/>, Docs, PR: unreviewed

#5991 <Button /> - inverted-skin color fix
  src/Button/Button.st.css
Labels: PR: reviewed-approved

#5992 <TableActionCell/> - Fix menu items get cut
  src/TableActionCell/TableActionCell.st.css
Labels: PR: unreviewed

#5963 <TableActionCell/>- adding uni driver
  .wuf/testkits/definitions.js
  src/TableActionCell/README.TESTKIT.md
  src/TableActionCell/TableActionCell.driver.js
  src/TableActionCell/TableActionCell.js
  src/TableActionCell/TableActionCell.protractor.driver.js
  src/TableActionCell/TableActionCell.uni.driver.d.ts
  src/TableActionCell/TableActionCell.uni.driver.js
  src/TableActionCell/constants.js
  src/TableActionCell/test/TableActionCell.private.driver.js
  src/TableActionCell/test/TableActionCell.private.uni.driver.js
  src/TableActionCell/test/TableActionCell.spec.js
  src/TableActionCell/test/TableActionCell.visual.js
Labels: <TableActionCell/>, PR: unreviewed, Unidriver

#5995 release 9.12.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#5914 <Button/> - add ellipsis prop
  package.json
  perfer.config.js
  src/Button/Button.js
  src/Button/Button.st.css
  src/Button/docs/examples.js
  src/Button/docs/index.story.js
  src/Button/index.d.ts
  src/Button/test/Button.tsx
  src/Button/test/Button.visual.js
Labels: <Button/>, PR: reviewed-approved

#5945 <TextButton/> - add ellipsis prop
  perfer.config.js
  src/DropdownBase/docs/examples.js
  src/TextButton/TextButton.js
  src/TextButton/TextButton.st.css
  src/TextButton/docs/examples.js
  src/TextButton/docs/index.story.js
  src/TextButton/index.d.ts
  src/TextButton/test/TextButton.tsx
  src/TextButton/test/TextButton.visual.js
Labels: <TextButton/>, PR: unreviewed

#5973 <MultiSelectCheckbox /> - add option for controlled value
  src/MultiSelectCheckbox/MultiSelectCheckbox.js
  src/MultiSelectCheckbox/docs/examples.js
  src/MultiSelectCheckbox/docs/index.story.js
  src/MultiSelectCheckbox/test/MultiSelectCheckbox.spec.js
Labels: <MultiSelectCheckbox/>, PR: reviewed-approved, PR: unreviewed

#5994 chore(janet.json): add customUrls to support dedicated domain
  janet.json
Labels: Docs, Infrastructure

#5998 Revert "<ModalSelectorLayout/> - use new <CustomModalLayout/> (#5986)"
  src/BaseModalLayout/BaseModalLayout.legacy.driver.js
  src/CustomModalLayout/CustomModalLayout.js
  src/CustomModalLayout/CustomModalLayout.st.css
  src/ModalSelectorLayout/ModalSelectorLayout.driver.d.ts
  src/ModalSelectorLayout/ModalSelectorLayout.driver.js
  src/ModalSelectorLayout/ModalSelectorLayout.helpers.js
  src/ModalSelectorLayout/ModalSelectorLayout.js
  src/ModalSelectorLayout/ModalSelectorLayout.scss
  src/ModalSelectorLayout/ModalSelectorLayout.uni.driver.d.ts
  src/ModalSelectorLayout/ModalSelectorLayout.uni.driver.js
  src/ModalSelectorLayout/docs/index.story.js
  src/ModalSelectorLayout/test/ModalSelectorLayout.spec.js
  src/ModalSelectorLayout/test/ModalSelectorLayout.tsx
Labels: PR: unreviewed

#6001 remove `yoshi lint`, use `eslint` directly
  package.json
Labels: Infrastructure, PR: unreviewed

#6004 Remove Public Exposure from Janet
  janet.json
Labels: PR: reviewed-approved

#5988 <Text/> - change ellipsis example
  src/Text/docs/examples.js
  src/Text/docs/index.story.js
Labels: PR: unreviewed

#5981 <RadioGroup/> - added RadioButtonDriver types to getRadioAtIndex driv…
  src/RadioGroup/RadioGroup.driver.d.ts
  src/RadioGroup/RadioGroup.uni.driver.d.ts
Labels: PR: unreviewed

#6006 <CounterBadge/> - align inner text
  src/CounterBadge/CounterBadge.st.css
Labels: PR: unreviewed

#6007 performance: add a FailWhale to indicate when bundling without tree-shaking
  .wuf/components.json
  .wuf/testkits/definitions.js
  src/ComposerSidebar/ComposerSidebar.js
  src/FailWhale/FailWhale.js
  src/FailWhale/index.js
  src/index.js
Labels: PR: unreviewed

#6010 Release/9.13.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#6012 <DropdownLayout/>- adding to cheatsheet
  stories/Introduction/Cheatsheet/componentsFamilies/InternalFamily.js
  stories/symbolsComponentsMapping/components.js
  stories/symbolsComponentsMapping/families/internalComponentsFamily.js
  stories/symbolsComponentsMapping/symbols.js
Labels: PR: unreviewed

#6013 <Proportion/> - convert scss to stylable
  perfer.config.js
  src/Proportion/Proportion.js
  src/Proportion/Proportion.scss
  src/Proportion/Proportion.st.css
Labels: PR: unreviewed

#5911 <TableActionCell/> - Add size to actions
  src/TableActionCell/TableActionCell.js
  src/TableActionCell/docs/examples/SmallButtonsExample.js
  src/TableActionCell/docs/index.story.js
  src/TableActionCell/index.d.ts
  src/TableActionCell/test/TableActionCell.e2e.js
  src/TableActionCell/test/TableActionCell.e2eStory.js
  src/TableActionCell/test/TableActionCell.tsx
  src/TableActionCell/test/TableActionCell.visual.js
Labels: PR: unreviewed

#6008 <InputArea /> - refactor story page
  src/InputArea/docs/ExampleControlled.js
  src/InputArea/docs/ExampleError.js
  src/InputArea/docs/ExampleRefs.js
  src/InputArea/docs/ExampleSizes.js
  src/InputArea/docs/ExampleStandard.js
  src/InputArea/docs/ExampleWarning.js
  src/InputArea/docs/examples.js
  src/InputArea/docs/index.story.js
  src/InputArea/test/InputArea.e2e.js
  src/InputArea/test/InputArea.e2eStory.js
  src/InputArea/test/storySettings.js
Labels: PR: reviewed-approved

#6014 <StatisticsWidget/> - add datahook for description
  src/StatisticsWidget/StatisticsItem/StatisticsItem.js
  src/StatisticsWidget/StatisticsWidget.js
Labels: PR: reviewed-approved

#6003 <CounterBadge /> Add "light" skin
  src/CounterBadge/CounterBadge.js
  src/CounterBadge/CounterBadge.st.css
  src/CounterBadge/docs/examples.js
  src/CounterBadge/index.d.ts
  src/CounterBadge/test/CounterBadge.visual.js
Labels: PR: unreviewed

#5901 <AreaChart/> - new component
  .wuf/components.json
  jest.config.js
  package.json
  perfer.config.js
  src/AreaChart/AreaChart.js
  src/AreaChart/AreaChart.meta.js
  src/AreaChart/AreaChart.st.css
  src/AreaChart/AreaChart.uni.driver.d.ts
  src/AreaChart/AreaChart.uni.driver.js
  src/AreaChart/chartOptions.js
  src/AreaChart/constants.js
  src/AreaChart/docs/examples.js
  src/AreaChart/docs/index.story.js
  src/AreaChart/index.d.ts
  src/AreaChart/index.js
  src/AreaChart/test/AreaChart.private.uni.driver.js
  src/AreaChart/test/AreaChart.spec.js
  src/AreaChart/test/AreaChart.tsx
  src/AreaChart/test/AreaChart.visual.js
  src/AreaChart/test/storySettings.js
  src/FunnelChart/FunnelChart.js
  src/FunnelChart/FunnelLabel/FunnelLabel.js
  src/FunnelChart/FunnelStep/FunnelStep.js
  src/index.d.ts
  src/index.js
  src/utils/numberFormatters.js
  src/utils/numberFormatters.spec.js
  stories/index.js
  testkit/component-definitions.js
Labels: New Component, PR: draft, PR: unreviewed

#6022 contactItemBuilder and <ContactItem/> deprecation
  src/ContactItemBuilder/ContactItemBuilder.js
  src/ContactItemBuilder/docs/index.js
Labels: PR: unreviewed

#6017 [DOCS] use wix-ui-icons-common icon list in storybook
  package.json
  src/index.js
  stories/Icons/AllIcons.js
  stories/Icons/index.story.js
Labels: Docs, PR: unreviewed

#6005 VariableInput: add readOnly prop
  src/VariableInput/VariableInput.js
  src/VariableInput/VariableInput.st.css
  src/VariableInput/docs/examples.js
  src/VariableInput/docs/index.story.js
  src/VariableInput/index.d.ts
  src/VariableInput/test/VariableInput.spec.js
  src/VariableInput/test/VariableInput.tsx
  src/VariableInput/test/VariableInput.visual.js
Labels: PR: reviewed-approved

#6025 AreaChart- adding to the cheatsheet
  stories/Introduction/Cheatsheet/componentsFamilies/ContentWidgetsFamily.js
  stories/symbolsComponentsMapping/components.js
  stories/symbolsComponentsMapping/families/contentWidgetsFamily.js
  stories/symbolsComponentsMapping/symbols.js
Labels: PR: unreviewed

#5982 infra: cancel files deletion in the build task
  package.json
  scripts/build-cleanup.sh
Labels: PR: unreviewed

#6019 <RichTextInputArea /> - convert scss to stylable
  src/RichTextInputArea/Form/RichTextInputAreaForm.js
  src/RichTextInputArea/Form/RichTextInputAreaForm.st.css
  src/RichTextInputArea/RichTextInputArea.js
  src/RichTextInputArea/RichTextInputArea.scss
  src/RichTextInputArea/RichTextInputArea.st.css
  src/RichTextInputArea/Toolbar/RichTextToolbar.private.uni.driver.js
  src/RichTextInputArea/Toolbar/RichTextToolbarButton.js
  src/RichTextInputArea/Toolbar/RichTextToolbarButton.scss
  src/RichTextInputArea/Toolbar/RichTextToolbarButton.st.css
  src/RichTextInputArea/index.d.ts
  src/RichTextInputArea/test/RichTextInputArea.spec.js
  src/RichTextInputArea/test/RichTextInputArea.tsx
Labels: PR: unreviewed

#6030 <RichTextInputArea - fix typo
  src/RichTextInputArea/index.d.ts
  src/RichTextInputArea/test/RichTextInputArea.tsx
Labels: PR: reviewed-approved

#6032 testing guide- fix link #2
  .storybook/webpack.config.js
Labels: PR: unreviewed

#6034 Infra: replace createReactContext polyfill with the native one
  package.json
  src/FontUpgrade/context.js
  src/Input/InputContext.js
  src/NestableList/NestableListContext.js
  src/Page/PageContext.js
  src/RichTextInputArea/RichTextInputAreaContext.js
  src/SidePanel/SidePanelAPI.js
  src/Sidebar/SidebarAPI.js
  src/Table/BulkSelection/BulkSelection.js
  src/Table/TableContext.js
Labels: PR: unreviewed

#6035 infra: create a separate entry file per theme
  .storybook/addons/ThemeWSR/index.js
  src/ThemeProvider/docs/index.story.js
  src/ThemeProvider/test/ThemeProvider.tsx
  src/ThemeProvider/test/ThemeProvider.visual.js
  src/Themes/floatingPanels/floatingPanels.js
  src/Themes/floatingPanels/index.d.ts
  src/Themes/floatingPanels/index.js
  src/Themes/floatingPanels/utils.js
  src/Themes/index.js
  src/index.d.ts
  src/index.js
  stories/utils/allComponents.js
  testkit/all-components.js
  themes/floatingPanels/package.json
Labels: PR: unreviewed

#6026 <CustomModalLayout/> - add dropdown example for storybook
  src/CustomModalLayout/docs/examples/DropdownExample.js
  src/CustomModalLayout/docs/index.story.js
Labels: PR: unreviewed

#6029 Stylable lint plugin
  package.json
  src/AutoCompleteWithLabel/AutoCompleteWithLabel.js
  src/DropdownLayout/DropdownLayout.js
  src/RadioGroup/RadioButton/RadioButton.js
  src/TableActionCell/TableActionCell.js
  src/VariableInput/EditorUtilities.js
Labels: PR: unreviewed

#6036 release 9.15.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#6021 <FunnelChart/> - fixes
  src/FunnelChart/FunnelChart.js
  src/FunnelChart/FunnelChart.uni.driver.js
  src/FunnelChart/FunnelStep/FunnelStep.js
  src/FunnelChart/docs/index.story.js
  src/FunnelChart/index.d.ts
  src/FunnelChart/test/FunnelChart.spec.js
  src/FunnelChart/test/FunnelChart.tsx
Labels: PR: reviewed-approved

#6027 <Table/> - fix page sticky top calculation when there's no header
  src/Page/Page.js
  src/Page/test/Page.e2e.js
  src/Page/test/Page.e2eStory.js
Labels: PR: reviewed-approved

#6038 Themes - create an EditorX theme
  perfer.config.js
  src/BaseModalLayout/BaseModalLayout.js
  src/BaseModalLayout/BaseModalLayout.st.css
  src/CloseButton/CloseButton.js
  src/CustomModalLayout/test/CustomModalLayout.visual.js
  src/ThemeProvider/ThemeContext/ThemeContext.js
  src/ThemeProvider/ThemeContext/index.js
  src/ThemeProvider/ThemeProvider.js
  src/ThemeProvider/ThemeProviderConsumerBackwardCompatible.js
  src/ThemeProvider/index.d.ts
  src/ThemeProvider/test/ThemeProvider.tsx
  src/Themes/editorX/components/CustomModalLayout.st.css
  src/Themes/editorX/docs/editorX.story.js
  src/Themes/editorX/docs/examples.js
  src/Themes/editorX/docs/index.js
  src/Themes/editorX/docs/storySettings.js
  src/Themes/editorX/editorX.js
  src/Themes/editorX/editorX.st.css
  src/Themes/editorX/foundations/colors.st.css
  src/Themes/editorX/foundations/typography.st.css
  src/Themes/editorX/icons/Close.js
  src/Themes/editorX/icons/Help.js
  src/Themes/editorX/icons/index.js
  src/Themes/editorX/index.d.ts
  src/Themes/editorX/index.js
  src/Themes/editorX/test/editorX.visual.js
  stories/index.js
  stories/storiesHierarchy.js
  stories/utils/allComponents.js
  themes/editorX/package.json
Labels: PR: unreviewed

#6040 <CounterBadge/> - improve visuals
  src/CounterBadge/test/CounterBadge.visual.js
Labels: PR: unreviewed

#6031 <CounterBadge/> - add size prop
  src/CounterBadge/CounterBadge.js
  src/CounterBadge/CounterBadge.st.css
  src/CounterBadge/docs/examples.js
  src/CounterBadge/docs/index.story.js
  src/CounterBadge/index.d.ts
  src/CounterBadge/test/CounterBadge.tsx
  src/CounterBadge/test/CounterBadge.visual.js
Labels: PR: reviewed-approved

#6042 DatePicker - remove the interactive example from doc and generator
  .wuf/generator/templates/$ComponentName/docs/index.story.js
  src/DatePicker/docs/index.story.js
Labels: PR: unreviewed

#6043 Release 9.16.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#6033 remove yoshi webpack config from `npm run autotools` & `npm run storybook:visual`
  .autotools/webpack.config.js
  .storybook/visual/webpack.config.js
  scripts/webpack-config/common-webpack.config.js
  scripts/webpack-config/style-loader.config.js
  scripts/webpack-config/svg-loader.config.js
Labels: Infrastructure, PR: reviewed-approved, PR: unreviewed

#5975 <ModalSelectorLayout /> - update storybook page
  src/ModalSelectorLayout/ModalSelectorLayout.uni.driver.js
  src/ModalSelectorLayout/README.TESTKIT.md
  src/ModalSelectorLayout/docs/examples.js
  src/ModalSelectorLayout/docs/index.story.js
Labels: PR: unreviewed

#6048 Cheatsheet- funnelChart example fix
  stories/Introduction/Cheatsheet/componentsFamilies/ContentWidgetsFamily.js
Labels: PR: unreviewed, WIP

#6047 <DropdownBase/> - fix flaky test
  src/DropdownBase/test/DropdownBase.visual.js
Labels: PR: unreviewed
