Repository wix/wix-style-react, pull requests merged in 2020-05, with the labels that each got.

#5437 Refactor e2e stories
  .storybook/e2e/config.js
  src/Avatar/test/Avatar.e2eStory.js
  src/CardGalleryItem/test/CardGalleryItem.e2eStory.js
  src/DatePicker/test/DatePicker.e2eStory.js
  src/Dropdown/test/Dropdown.e2eStory.js
  src/DropdownLayout/docs/testStory.js
  src/DropdownLayout/test/DropdownLayout.e2eStory.js
  src/EditableSelector/test/EditableSelector.e2e.js
  src/EditableSelector/test/EditableSelector.e2eStory.js
  src/EditableSelector/test/EditableSelector.private.driver.js
  src/EditableSelector/test/EditableSelector.private.uni.driver.js
  src/EditableSelector/test/EditableSelector.spec.js
  src/FilePicker/test/FilePicker.e2eStory.js
  src/InputArea/test/InputArea.e2eStory.js
  src/InputWithOptions/test/InputWithOptions.e2e.js
  src/InputWithOptions/test/InputWithOptions.e2eStory.js
  src/InputWithOptions/test/InputWithOptions.private.uni.driver.js
  src/InputWithOptions/test/InputWithOptions.spec.js
  src/MessageBox/test/MessageBox.e2eStory.js
  src/ModalPreviewLayout/test/storySettings.js
  src/ModalPreviewLayout/test/testStory.js
  src/MultiSelect/test/MultiSelect.e2eStory.js
  src/MultiSelectCheckbox/test/MultiSelectCheckbox.e2eStory.js
  src/Page/test/Page.e2eStory.js
  src/PageHeader/test/PageHeader.e2eStory.js
  src/RadioGroup/test/RadioGroup.e2eStory.js
  src/Range/test/Range.e2eStory.js
  src/RichTextInputArea/test/RichTextInputArea.e2eStory.js
  src/Search/test/Search.e2eStory.js
  src/Slider/test/Slider.e2eStory.js
  src/StatisticsWidget/test/StatisticsWidget.e2eStory.js
  src/Stepper/test/Stepper.e2eStory.js
  src/Stepper/test/StepperWindowResizeTest.js
  src/Table/DataTable/test/DataTable.e2eStory.js
  src/Table/test/Table.e2eStory.js
  src/TableActionCell/test/TableActionCell.e2eStory.js
  src/Tabs/test/Tabs.e2eStory.js
  stories/e2e.js
Labels: Infrastructure

#5441 docs(Playground): update UI and example code
  stories/Playground/Playground.js
  stories/Playground/Playground.story.js
  stories/Playground/example.js
  stories/index.js
Labels: Docs

#5419 <AudioPlayer/> - new component
  .wuf/components.json
  package.json
  perfer.config.js
  src/AudioPlayer/AudioManager/AudioManager.js
  src/AudioPlayer/AudioPlayer.js
  src/AudioPlayer/AudioPlayer.meta.js
  src/AudioPlayer/AudioPlayer.st.css
  src/AudioPlayer/AudioPlayer.uni.driver.d.ts
  src/AudioPlayer/AudioPlayer.uni.driver.js
  src/AudioPlayer/constants.js
  src/AudioPlayer/docs/index.story.js
  src/AudioPlayer/index.d.ts
  src/AudioPlayer/index.js
  src/AudioPlayer/test/AudioPlayer.e2e.js
  src/AudioPlayer/test/AudioPlayer.e2eStory.js
  src/AudioPlayer/test/AudioPlayer.private.uni.driver.js
  src/AudioPlayer/test/AudioPlayer.spec.js
  src/AudioPlayer/test/AudioPlayer.tsx
  src/AudioPlayer/test/AudioPlayer.visual.js
  src/AudioPlayer/test/storySettings.js
  src/AudioPlayer/utils.js
  src/assets/audio-test-file.mp3
  src/index.d.ts
  src/index.js
  stories/e2e.js
  stories/index.js
  testkit/component-definitions.js
Labels: WIP

#5432 `<Table/>`- Add TableActionCell support for a table with horizontal scroll
  src/Table/DataTable/DataTable.js
  src/Table/DataTable/DataTable.scss
  src/Table/DataTable/index.d.ts
  src/Table/Table.js
  src/Table/docs/examples/TableStickyScrollExample.js
  src/Table/test/Table.tsx
Labels: WIP

#5459 <RadioGroup/> - Adding uni driver
  .wuf/testkits/definitions.js
  src/RadioGroup/README.TESTKIT.md
  src/RadioGroup/RadioButton/RadioButton.driver.js
  src/RadioGroup/RadioButton/RadioButton.js
  src/RadioGroup/RadioButton/RadioButton.private.uni.driver.js
  src/RadioGroup/RadioButton/RadioButton.protractor.driver.js
  src/RadioGroup/RadioButton/RadioButton.spec.js
  src/RadioGroup/RadioButton/RadioButton.uni.driver.d.ts
  src/RadioGroup/RadioButton/RadioButton.uni.driver.js
  src/RadioGroup/RadioButton/constants.js
  src/RadioGroup/RadioButton/test/RadioButton.spec.js
  src/RadioGroup/RadioGroup.driver.js
  src/RadioGroup/RadioGroup.js
  src/RadioGroup/RadioGroup.protractor.driver.js
  src/RadioGroup/RadioGroup.scss
  src/RadioGroup/RadioGroup.uni.driver.d.ts
  src/RadioGroup/RadioGroup.uni.driver.js
  src/RadioGroup/constants.js
  src/RadioGroup/test/RadioGroup.private.uni.driver.js
  src/RadioGroup/test/RadioGroup.spec.js
  src/Selector/Selector.driver.js
  src/Selector/Selector.uni.driver.js
Labels: <RadioButton/>, Unidriver
