Repository wix/wix-style-react, pull requests merged in 2020-01, with the labels that each got.

#4773 Infra: remove .st.css and .scss imports from drivers
  src/Badge/Badge.js
  src/Badge/Badge.uni.driver.js
  src/Button/Button.js
  src/Button/Button.uni.driver.js
  src/CircularProgressBar/CircularProgressBar.js
  src/CircularProgressBar/CircularProgressBar.uni.driver.js
  src/ColorInput/ColorInput.private.uni.driver.js
  src/ColorInput/components/ColorViewer.js
  src/ColorInput/components/Hash.js
  src/Deprecated/SideMenu/DrillView/DrillView.uni.driver.js
  src/Deprecated/SideMenu/core/SideMenu.uni.driver.js
  src/DropdownLayout/DropdownLayout.uni.driver.js
  src/Heading/Heading.js
  src/Heading/Heading.uni.driver.js
  src/Input/Input.uni.driver.js
  src/InputArea/InputArea.uni.driver.js
  src/InputWithLabel/InputWithLabel.js
  src/InputWithLabel/InputWithLabel.uni.driver.js
  src/ListItemAction/ListItemAction.js
  src/ListItemAction/ListItemAction.uni.driver.js
  src/MediaOverlay/MediaOverlay.js
  src/MediaOverlay/test/MediaOverlay.private.uni.driver.js
  src/MessageBox/FunctionalLayout/MessageBoxFunctionalLayout.uni.driver.js
  src/SectionHelper/SectionHelper.uni.driver.js
  src/SegmentedToggle/ToggleButton/ToggleButton.js
  src/SegmentedToggle/ToggleButton/ToggleButton.private.uni.driver.js
  src/SegmentedToggle/ToggleIcon/ToggleIcon.js
  src/SegmentedToggle/ToggleIcon/ToggleIcon.private.uni.driver.js
  src/SidebarDivider/SidebarDivider.js
  src/SidebarDivider/SidebarDivider.uni.driver.js
  src/SidebarSectionItem/SidebarSectionItem.js
  src/SidebarSectionItem/test/SidebarSectionItem.private.uni.driver.js
  src/Tabs/Tabs.uni.driver.js
  src/Text/Text.js
  src/Text/Text.uni.driver.js
  src/Thumbnail/Thumbnail.js
  src/Thumbnail/Thumbnail.uni.driver.js
  src/TimeInput/TimeInput.uni.driver.js
Labels: PR: reviewed-approved

#4714 `<ModalPreviewLayout/>`- support navigation
  src/ModalPreviewLayout/ModalPreviewLayout.js
  src/ModalPreviewLayout/ModalPreviewLayout.st.css
  src/ModalPreviewLayout/ModalPreviewLayout.uni.driver.js
  src/ModalPreviewLayout/NavigationButton/NavigationButton.js
  src/ModalPreviewLayout/constants.js
  src/ModalPreviewLayout/docs/examples/MultipleContent.js
  src/ModalPreviewLayout/docs/index.story.js
  src/ModalPreviewLayout/test/ModalPreviewLayout.private.uni.driver.js
  src/ModalPreviewLayout/test/ModalPreviewLayout.spec.js
  src/ModalPreviewLayout/test/ModalPreviewLayout.visual.js
Labels: PR: reviewed-approved

#4779 Release v7.29.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#4759 add onEditClick prop and use it for selection
  src/DataTable/DataTable.driver.js
  src/DataTable/DataTable.js
  src/DataTable/DataTable.uni.driver.js
  src/DataTable/README.md
  src/DataTable/test/DataTable.spec.js
  src/Table/Table.driver.js
  src/Table/Table.js
  src/Table/Table.st.css
  src/Table/Table.uni.driver.js
Labels: PR: unreviewed

#4778 Fixed disabled state css
  src/SidebarSectionItem/SidebarSectionItem.st.css
Labels: <Sidebar/>, PR: unreviewed

#4780 Release v7.29.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#4781 Infra: fix incorrect drivers import
  src/ListItemSection/DataHooks.js
  src/ListItemSection/ListItemSection.js
  src/ListItemSection/ListItemSection.uni.driver.js
  src/ListItemSelect/DataHooks.js
  src/ListItemSelect/ListItemSelect.js
  src/ListItemSelect/ListItemSelect.uni.driver.js
  src/Thumbnail/Thumbnail.uni.driver.js
  src/Thumbnail/test/Thumbnail.spec.js
Labels: PR: unreviewed

#4783 Infra: avoid importing stylesheets in unidrivers
  docs/contribution/TEST_DRIVERS_GUIDELINES.md
  package.json
Labels: PR: unreviewed

#4614 Remove WixComponent
  src/Accordion/Accordion.js
  src/AddItem/AddItem.js
  src/AutoCompleteWithLabel/AutoCompleteWithLabel.js
  src/Avatar/Avatar.js
  src/Badge/Badge.js
  src/BadgeSelect/BadgeSelect.js
  src/Breadcrumbs/Breadcrumbs.js
  src/Calendar/Calendar.js
  src/Card/Content/Content.js
  src/Card/Header/Header.js
  src/Card/Subheader/Subheader.js
  src/Checkbox/Checkbox.js
  src/ColorPicker/ColorPicker.js
  src/DataTable/DataTable.js
  src/Highlighter/HighlightedItem.js
  src/Highlighter/Highlighter.js
  src/InputArea/InputArea.js
  src/Loader/Loader.js
  src/Modal/Modal.js
  src/RadioGroup/RadioButton/RadioButton.js
  src/SectionHelper/index.js
  src/Selector/ProgressBar/ProgressBar.js
  src/Selector/Selector.js
  src/Skeleton/Skeleton.js
  src/StatsWidget/StatsWidget.js
  src/Tag/Tag.js
Labels: PR: unreviewed, Refactor

#4787 <ColorPicker/> - Remove use of WixComponent
  src/ColorPicker/ColorPicker.const.js
  src/ColorPicker/ColorPicker.driver.js
  src/ColorPicker/ColorPicker.js
  src/ColorPicker/ColorPicker.private.driver.js
  src/ColorPicker/ColorPicker.private.uni.driver.js
  src/ColorPicker/ColorPicker.protractor.driver.js
  src/ColorPicker/ColorPicker.uni.driver.js
  src/ColorPicker/ColorPickerActions.js
  src/ColorPicker/ColorPickerConverterViewer.js
  src/ColorPicker/ColorPickerHistory.js
  src/ColorPicker/ColorPickerHsb.js
  src/ColorPicker/ColorPickerHue.js
Labels: <ColorPicker/>, PR: reviewed-changes-requested, PR: unreviewed, Refactor

#4792 Remove use of WixComponent
  src/Avatar/Avatar.js
  src/Avatar/Avatar.uni.driver.js
  src/Avatar/constants.js
  src/Avatar/docs/index.story.js
  src/Avatar/string-to-color.js
  src/ColorPicker/ColorPicker.driver.js
  src/ColorPicker/ColorPicker.js
  src/ColorPicker/ColorPicker.private.driver.js
  src/ColorPicker/ColorPicker.private.uni.driver.js
  src/ColorPicker/ColorPicker.protractor.driver.js
  src/ColorPicker/ColorPicker.uni.driver.js
  src/ColorPicker/ColorPickerActions.js
  src/ColorPicker/ColorPickerConverterViewer.js
  src/ColorPicker/ColorPickerHistory.js
  src/ColorPicker/constants.js
  src/ImageViewer/ImageViewer.driver.js
  src/ImageViewer/ImageViewer.private.driver.js
  src/ImageViewer/ImageViewer.uni.driver.js
  src/ImageViewer/constants.js
Labels: <ColorPicker/>, PR: unreviewed

#4784 Infra: add a sanity E2E test for puppeteer testkit import
  test-runtime/imports/package.json
  test-runtime/imports/src/puppeteer-testkit/App.js
  test-runtime/imports/src/puppeteer-testkit/index.js
  test-runtime/imports/test/e2e/puppeteer-testkit.e2e.js
Labels: PR: unreviewed

#4789 <PopoverMenu/> - deprecate story
  package.json
  src/PopoverMenu/PopoverMenu.e2e.js
  src/PopoverMenu/docs/ExampleBasic.js
  src/PopoverMenu/docs/ExampleDisabled.js
  src/PopoverMenu/docs/ExampleDisabledLarge.js
  src/PopoverMenu/docs/ExampleWithDivider.js
  src/PopoverMenu/docs/index.story.js
  src/PopoverMenu/docs/storySettings.js
  src/beta/index.js
  stories/utils/allComponents.js
Labels: PR: reviewed-approved

#4785 Fix clickRowCheckbox in <Table> teskit
  src/Table/Table.driver.js
Labels: PR: unreviewed

#4786 <Stepper/> - New features, updated to latest design specs
  src/ComposerHeader/ComposerHeader.st.css
  src/Stepper/Consts.js
  src/Stepper/Step/Step.js
  src/Stepper/Step/Step.st.css
  src/Stepper/Step/StepCircle/StepCircle.js
  src/Stepper/Step/StepCircle/StepCircle.st.css
  src/Stepper/Stepper.js
  src/Stepper/Stepper.st.css
  src/Stepper/Stepper.uni.driver.js
  src/Stepper/components/Step.js
  src/Stepper/components/Step.st.css
  src/Stepper/components/StepMarker.js
  src/Stepper/components/StepMarker.st.css
  src/Stepper/constants.js
  src/Stepper/dataHooks.js
  src/Stepper/docs/examples/FourSteps.js
  src/Stepper/docs/examples/ManySteps.js
  src/Stepper/docs/examples/StepTypes.js
  src/Stepper/docs/examples/card.js
  src/Stepper/docs/examples/composerHeader.js
  src/Stepper/docs/examples/fitModes.js
  src/Stepper/docs/examples/responsive.js
  src/Stepper/docs/examples/stepTypes.js
  src/Stepper/docs/examples/stepperTypes.js
  src/Stepper/docs/index.story.js
  src/Stepper/docs/testkit.md
  src/Stepper/test/Stepper.e2e.js
  src/Stepper/test/Stepper.spec.js
  src/Stepper/test/Stepper.visual.js
  src/Stepper/test/StepperAccessibilityTest.js
  src/Stepper/test/StepperWindowResizeTest.js
  src/Stepper/utils.js
Labels: PR: reviewed-approved

#4794 release/v7.30.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#4791 Variable input
  .wuf/components.json
  src/VariableInput/EditorUtilities.js
  src/VariableInput/VariableInput.js
  src/VariableInput/VariableInput.meta.js
  src/VariableInput/VariableInput.st.css
  src/VariableInput/VariableInput.uni.driver.d.ts
  src/VariableInput/VariableInput.uni.driver.js
  src/VariableInput/constants.js
  src/VariableInput/docs/index.story.js
  src/VariableInput/index.d.ts
  src/VariableInput/index.js
  src/VariableInput/test/EditorUtilities.spec.js
  src/VariableInput/test/VariableInput.private.uni.driver.js
  src/VariableInput/test/VariableInput.spec.js
  src/VariableInput/test/VariableInput.visual.js
  src/VariableInput/test/storySettings.js
  src/index.js
  stories/index.js
  test/utils/unidriver/ReactBase.js
  testkit/enzyme.d.ts
  testkit/enzyme.js
  testkit/index.d.ts
  testkit/index.js
  testkit/protractor.d.ts
  testkit/protractor.js
  testkit/puppeteer.d.ts
  testkit/puppeteer.js
Labels: PR: unreviewed

#4735 <ImageViewer/> - do not render img html at all when imageUrl prop is not defined
  src/AddItem/components/TooltipHOC.st.css
  src/ImageViewer/ImageViewer.driver.js
  src/ImageViewer/ImageViewer.js
  src/ImageViewer/ImageViewer.uni.driver.js
Labels: PR: reviewed-approved

#4797 Perfer - rise threshold values for components that uses Popover
  perfer.config.js
Labels: PR: unreviewed

#4798 Add font definitions
  .storybook/stories.scss
  .storybook/visual/stories.scss
  src/Foundation/stylable/fonts/helvetica.st.css
  src/Text/Text.st.css
  src/fonts.scss
  src/typography-helpers.scss
Labels: PR: unreviewed, Typography

#4017 <ColorInput/> - remove manual testkit docs
  src/ColorInput/ColorInput.uni.driver.js
  src/ColorInput/docs/README.TESTKIT.md
  src/ColorInput/docs/index.story.js
Labels: <ColorInput/>, Docs, PR: reviewed-approved, Testkit

#4790 Generator- adding constants file
  .wuf/generator/templates/Component/Component.js
  .wuf/generator/templates/Component/Component.st.css
  .wuf/generator/templates/Component/Component.uni.driver.js
  .wuf/generator/templates/Component/constants.js
Labels: PR: reviewed-approved

#4805 fix(Heading): update color for appearance=H5 light
  src/Heading/Heading.st.css
Labels: <Heading/>, PR: unreviewed

#4807 <Badge/> - Added missing constants to TypeScript typings
  src/Badge/index.d.ts
  test/types/Badge.tsx
Labels: PR: reviewed-approved

#4806 `<IconButton/>` - migrate stylesheet && update disabled styles && fix inverted color
  src/IconButton/IconButton.js
  src/IconButton/IconButton.st.css
  src/IconButton/test/IconButton.visual.js
  src/utils/ButtonHelpers/index.js
  src/utils/generateDataAttr.js
  src/utils/generateDataAttr.spec.js
Labels: PR: unreviewed

#4811 chore(ToggleIcon.st.css): update disabled icon & border colors
  src/SegmentedToggle/ToggleIcon/ToggleIcon.st.css
Labels: <SegmentedToggle/>, PR: unreviewed

#4809 <FloatingNotification/> - change `minWidth`
  src/FloatingNotification/FloatingNotification.scss
Labels: <FloatingNotification/>, PR: unreviewed

#4808 <SocialButton/> - Horizontally align text to center
  src/SocialButton/SocialButton.st.css
  src/SocialButton/test/SocialButton.visual.js
Labels: PR: reviewed-approved

#4813 <Tooltip/> - change `textAlign` default value
  src/Tooltip/TooltipNext/Tooltip.js
  src/Tooltip/TooltipNext/docs/index.story.js
Labels: <Tooltip/>, PR: unreviewed

#4815 <ColorPicker/> - Fix Transparent color swatch
  src/ColorPicker/ColorPicker.js
Labels: <ColorPicker/>, PR: unreviewed

#4814 <FormField/> - add new prop labelAlignment
  src/FormField/FormField.js
  src/FormField/FormField.scss
  src/FormField/docs/examples.js
  src/FormField/docs/index.story.js
  src/FormField/test/FormField.visual.js
  stories/TextArea/examples.js
Labels: PR: unreviewed

#4816 <ListItemSection/> & <ListItemSelect/> - Set tooltip delay
  src/ListItemSection/ListItemSection.js
  src/ListItemSection/ListItemSection.uni.driver.js
  src/ListItemSection/constants.js
  src/ListItemSelect/ListItemSelect.js
  src/ListItemSelect/ListItemSelect.uni.driver.js
  src/ListItemSelect/constants.js
Labels: <ListItemSection/>, <ListItemSelect/>, PR: unreviewed

#4819 Perfer - rise threshold values for EditableSelector & FilePicker
  perfer.config.js
Labels: PR: unreviewed

#4821 <MultiSelectCheckbox/> - fix missing cursor style
  src/MultiSelectCheckbox/MultiSelectCheckbox.scss
Labels: <MultiSelectCheckbox/>, PR: unreviewed

#4820 <RichTextInputArea/> - Expose plain text value with onChange event
  src/RichTextInputArea/RichTextInputArea.js
  src/RichTextInputArea/test/RichTextInputArea.spec.js
Labels: PR: unreviewed

#4824 fix(Notification.ActionButton): remove default onClick
  src/Notification/ActionButton/ActionButton.js
Labels: <Notification/>, PR: reviewed-approved, PR: unreviewed

#4818 <TextButton/> - migrate styesheet && update disabled styling && fix transition issues
  src/TextButton/TextButton.js
  src/TextButton/TextButton.st.css
  src/TextButton/constants.js
  src/TextButton/test/TextButton.visual.js
Labels: PR: unreviewed

#4817 <TimeInput/> - Fix margin
  src/TimeInput/TimeInput.driver.js
  src/TimeInput/TimeInput.js
  src/TimeInput/TimeInput.scss
  src/TimeInput/TimeInput.uni.driver.js
  src/TimeInput/constants.js
Labels: <TimePicker/>, PR: unreviewed

#4810 <Thumbnail/>- replacing checked icon and updating dataHooks in drivers
  src/Thumbnail/Thumbnail.js
  src/Thumbnail/Thumbnail.private.uni.driver.js
  src/Thumbnail/Thumbnail.st.css
  src/Thumbnail/Thumbnail.uni.driver.js
  src/Thumbnail/constants.js
Labels: PR: unreviewed

#4822 <AddItem/> - Remove empty tooltip
  src/AddItem/AddItem.driver.js
  src/AddItem/AddItem.js
  src/AddItem/AddItem.uni.driver.js
  src/AddItem/components/TooltipHOC.js
  src/AddItem/constants.js
  src/AddItem/tests/AddItem.private.driver.js
  src/AddItem/tests/AddItem.private.uni.driver.js
Labels: <AddItem/>, PR: unreviewed

#4801 VariableInput - onChange prop
  src/VariableInput/VariableInput.js
  src/VariableInput/VariableInput.uni.driver.js
  src/VariableInput/index.d.ts
  src/VariableInput/test/VariableInput.spec.js
Labels: PR: reviewed-approved

#4802 VariableInput - placeholder prop
  src/VariableInput/VariableInput.js
  src/VariableInput/VariableInput.st.css
  src/VariableInput/VariableInput.uni.driver.js
  src/VariableInput/docs/index.story.js
  src/VariableInput/index.d.ts
  src/VariableInput/test/VariableInput.private.uni.driver.js
  src/VariableInput/test/VariableInput.spec.js
  src/VariableInput/test/VariableInput.visual.js
Labels: PR: unreviewed

#4826 <Checkbox/> - Enable visual error tooltip test
  src/Checkbox/Checkbox.uni.driver.js
  src/Checkbox/test/Checkbox.private.uni.driver.js
  src/Checkbox/test/Checkbox.visual.js
Labels: PR: reviewed-approved

#4831 Update Perfer config values
  perfer.config.js
Labels: PR: unreviewed

#4800 VariableInput - disabled prop
  src/VariableInput/EditorUtilities.js
  src/VariableInput/VariableInput.js
  src/VariableInput/VariableInput.st.css
  src/VariableInput/VariableInput.uni.driver.d.ts
  src/VariableInput/VariableInput.uni.driver.js
  src/VariableInput/docs/index.story.js
  src/VariableInput/index.d.ts
  src/VariableInput/test/VariableInput.spec.js
  src/VariableInput/test/VariableInput.visual.js
Labels: PR: unreviewed

#4726 <Text/> - add default styling for nested <ul> lists
  package.json
  perfer.config.js
  src/Stepper/Stepper.meta.js
  src/Text/Text.js
  src/Text/Text.scss
  src/Text/docs/examples.js
  src/Text/docs/index.story.js
  src/Text/test/Text.visual.js
Labels: PR: reviewed-approved

#4827 fix(InputArea): fix scrollbar style
  src/InputArea/InputArea.scss
  src/InputArea/test/InputArea.visual.js
Labels: PR: reviewed-approved

#4828 <MultiSelect/> - Replace error and errorMessage with status and statu…
  src/MultiSelect/InputWithTags.js
  src/MultiSelect/InputWithTags.scss
  src/MultiSelect/MultiSelect.js
  src/MultiSelect/test/MultiSelect.visual.js
Labels: <MultiSelect/>, PR: unreviewed

#4834 <CloseButton/> - migrate stylesheet && update disabled styling
  src/CloseButton/CloseButton.js
  src/CloseButton/CloseButton.st.css
  src/CloseButton/test/CloseButton.visual.js
  src/MessageBox/MarketerialLayout/MessageBoxMarketerialLayout.private.driver.js
  src/MessageBox/MarketerialLayout/MessageBoxMarketerialLayout.private.uni.driver.js
  src/MessageBox/MarketerialLayout/MessageBoxMarketerialLayout.spec.js
Labels: PR: unreviewed

#4833 <Button/> - migrate Button stylesheet && update disabled styling && add new premium-light skin
  src/Button/Button.js
  src/Button/Button.st.css
  src/Button/test/Button.visual.js
Labels: PR: unreviewed

#4836 `<TextButton/>` - add destructive skin
  src/TextButton/TextButton.st.css
  src/TextButton/constants.js
  src/TextButton/docs/examples.js
Labels: PR: unreviewed

#4837 `<Slider/>` - make marks occupy space
  src/Slider/Slider.js
  src/Slider/Slider.scss
  src/Slider/tests/Slider.visual.js
Labels: <Slider/>, PR: reviewed-approved, PR: unreviewed

#4825 Variable input - rows & size
  src/VariableInput/EditorUtilities.js
  src/VariableInput/VariableInput.js
  src/VariableInput/VariableInput.st.css
  src/VariableInput/constants.js
  src/VariableInput/docs/examples.js
  src/VariableInput/docs/index.story.js
  src/VariableInput/index.d.ts
  src/VariableInput/test/VariableInput.private.uni.driver.js
  src/VariableInput/test/VariableInput.spec.js
  src/VariableInput/test/VariableInput.visual.js
Labels: PR: unreviewed

#4839 `<Calendar/>` - introduce isDayActive testkit method
  src/Calendar/Calendar.driver.js
  src/Calendar/Calendar.uni.driver.js
  src/Calendar/test/Calendar.spec.js
Labels: PR: unreviewed

#4830 Variable input/status
  src/VariableInput/EditorUtilities.js
  src/VariableInput/VariableInput.js
  src/VariableInput/VariableInput.st.css
  src/VariableInput/VariableInput.uni.driver.js
  src/VariableInput/constants.js
  src/VariableInput/docs/examples.js
  src/VariableInput/docs/index.story.js
  src/VariableInput/test/VariableInput.spec.js
  src/VariableInput/test/VariableInput.visual.js
Labels: PR: unreviewed

#4842 <VariableInput/> - use `ReactBase` in testkit
  src/VariableInput/VariableInput.uni.driver.js
Labels: PR: reviewed-approved

#4843 change InputArea background from transparent to white
  src/InputArea/InputAreaMixins.scss
  src/InputArea/test/InputArea.e2e.js
Labels: PR: reviewed-approved

#4845 <ColorInput/> - renamed file visuals.js to visual.js
  src/ColorInput/tests/ColorInput.visual.js
Labels: <ColorInput/>, PR: unreviewed

#4846 <RichTextInputArea/> - remove redundant Draft's import
  src/RichTextInputArea/RichTextInputArea.scss
Labels: <RichTextInputArea/>, PR: unreviewed

#4840 Typography API
  src/Avatar/Avatar.st.css
  src/Badge/Badge.st.css
  src/Button/Button.st.css
  src/CircularProgressBar/CircularProgressBar.st.css
  src/ColorInput/components/Hash.st.css
  src/Foundation/stylable/fonts/helvetica.st.css
  src/Foundation/stylable/typography.st.css
  src/Heading/Heading.st.css
  src/LinearProgressBar/LinearProgressBar.st.css
  src/SidebarHeader/SidebarHeader.st.css
  src/Stepper/components/StepMarker.st.css
  src/Text/Text.st.css
  src/TextButton/TextButton.st.css
  src/TimeTable/TimeTable.st.css
  src/TimeTable/components/Item.st.css
  src/Tooltip/TooltipNext/Tooltip.st.css
  src/VariableInput/VariableInput.st.css
Labels: PR: reviewed-approved, Typography

#4848 <ListItemSection/> - Disable click propogation on divider ans whitespace
  src/ListItemSection/ListItemSection.js
  src/ListItemSection/ListItemSection.st.css
  src/ListItemSection/test/ListItemSection.spec.js
Labels: <ListItemSection/>, PR: reviewed-approved, PR: unreviewed

#4854 Fix places without explicit font declaration
  .storybook/config.js
  .storybook/visual/config.js
  src/Checkbox/Checkbox.driver.js
  src/Checkbox/Checkbox.js
  src/Checkbox/Checkbox.protractor.driver.js
  src/Checkbox/Checkbox.scss
  src/Checkbox/Checkbox.uni.driver.js
  src/Checkbox/constants.js
  src/Checkbox/test/Checkbox.private.uni.driver.js
  src/Slider/Slider.js
  src/Slider/tests/Slider.visual.js
Labels: PR: unreviewed, Typography

#4777 `<ModalPreviewLayout/>`- adding white tooltips to common control
  src/ModalPreviewLayout/ModalPreviewLayout.js
  src/ModalPreviewLayout/ModalPreviewLayout.st.css
  src/ModalPreviewLayout/NavigationButton/NavigationButton.js
  src/ModalPreviewLayout/constants.js
  src/ModalPreviewLayout/test/ModalPreviewLayout.private.uni.driver.js
  src/ModalPreviewLayout/test/ModalPreviewLayout.visual.js
Labels: PR: unreviewed

#4856 <ModalPreviewLayout/> - Fix perfer
  perfer.config.js
Labels: PR: unreviewed

#4857 <Tag/> - fix height when tiny and unremovable
  src/Tag/Tag.scss
Labels: <Tag/>, PR: unreviewed

#4855 Release 7.31.0
  package.json
Labels: PR: unreviewed

#4858 Revert <Button/> - disabled styling
  src/Button/Button.js
  src/Button/Button.st.css
Labels: PR: unreviewed

#4860 Remove yoshi hooks dependency in our build runner
  .autotools/node-require-hooks.js
Labels: PR: unreviewed

#4861 Release 7.31.0
  package.json
Labels: PR: unreviewed

#4844 <VariableInput /> - UX page
  src/VariableInput/VariableInput.js
  src/VariableInput/VariableInput.st.css
  src/VariableInput/docs/index.story.js
  src/VariableInput/test/storySettings.js
  stories/Introduction/Cheatsheet/componentsFamilies/InputFamily.js
  stories/VariableInput/examples.js
  stories/VariableInput/index.story.js
  stories/VariableInput/storySettings.js
  stories/index.js
  stories/symbolsComponentsMapping/components.js
  stories/symbolsComponentsMapping/families/inputsFamily.js
  stories/symbolsComponentsMapping/symbols.js
Labels: PR: reviewed-approved

#4850 <MarketingLayout/> - Use grid for responsive layout
  src/MarketingLayout/Content/Content.js
  src/MarketingLayout/Content/index.js
  src/MarketingLayout/MarketingLayout.js
  src/MarketingLayout/MarketingLayout.st.css
  src/MarketingLayout/components/Content.js
  src/MarketingLayout/components/Description.js
  src/MarketingLayout/components/Title.js
  src/MarketingLayout/docs/examples.js
  src/MarketingLayout/docs/index.story.js
Labels: PR: unreviewed

#4863 chore(.wuf/generator): rename folders to use variables
  .wuf/generator/templates/$ComponentName/$ComponentName.js
  .wuf/generator/templates/$ComponentName/$ComponentName.meta.js
  .wuf/generator/templates/$ComponentName/$ComponentName.st.css
  .wuf/generator/templates/$ComponentName/$ComponentName.uni.driver.d.ts
  .wuf/generator/templates/$ComponentName/$ComponentName.uni.driver.js
  .wuf/generator/templates/$ComponentName/constants.js
  .wuf/generator/templates/$ComponentName/docs/index.story.js
  .wuf/generator/templates/$ComponentName/index.d.ts
  .wuf/generator/templates/$ComponentName/index.js
  .wuf/generator/templates/$ComponentName/test/$ComponentName.private.uni.driver.js
  .wuf/generator/templates/$ComponentName/test/$ComponentName.spec.js
  .wuf/generator/templates/$ComponentName/test/$ComponentName.visual.js
  .wuf/generator/templates/$ComponentName/test/storySettings.js
  .wuf/generator/templates/Component/Component.meta.js
  .wuf/generator/templates/Component/constants.js
  .wuf/generator/templates/Component/index.d.ts
  .wuf/generator/templates/Component/index.js
  .wuf/generator/templates/Component/test/Component.private.uni.driver.js
Labels: Infrastructure, PR: unreviewed

#4865 Revert "<Text/> - add default styling for nested <ul> lists"
  package.json
  perfer.config.js
  src/Stepper/Stepper.meta.js
  src/Text/Text.js
  src/Text/Text.scss
  src/Text/docs/examples.js
  src/Text/docs/index.story.js
  src/Text/test/Text.visual.js
Labels: PR: unreviewed

#4866 Release 7.33.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#4859 `<ModalPreviewLayout/>` - adding more visual tests
  src/ModalPreviewLayout/test/ModalPreviewLayout.visual.js
Labels: PR: unreviewed

#4862 Added first Swimm Units
  .swm/5owq4tf2APg5pkjyTIh6.swm
  .swm/DK3mVXm7wI5XScVZMM0m.swm
  .swm/NJvXK4cMwYi6UjktKU2i.swm
  .swm/SGCCd6gH8RLVGOJtbk1Y.swm
  .swm/XXLoP4BpZB8vOT25orFD.swm
  .swm/XgUtlCAwgIMVtzNsUg4W.swm
  .swm/sHMyh1VB1GB3jIdPhRtC.swm
Labels: PR: unreviewed

#4867 Cheat sheet readme/file structure
  CONTRIBUTING.md
  docs/assets/cheatsheet-ui-elements.png
  docs/contribution/CHEATSHEET_GUIDLINES.md
Labels: PR: reviewed-approved

#4727 <Input/> - align affixes margins according to definitions
  src/AutoCompleteWithLabel/AutoCompleteWithLabel.js
  src/AutoCompleteWithLabel/AutoCompleteWithLabel.scss
  src/AutoCompleteWithLabel/test/AutoCompleteWithLabel.visual.js
  src/Input/Affix/Affix.js
  src/Input/Affix/Affix.scss
  src/Input/IconAffix/IconAffix.scss
  src/Input/Input.scss
  src/Input/InputSuffix.js
  src/Input/tests/AllInputs.js
  src/Input/tests/Input.visual.js
  src/MultiSelect/InputWithTags.scss
Labels: PR: unreviewed

#4864 VariableInput - multilne prop
  src/VariableInput/EditorUtilities.js
  src/VariableInput/VariableInput.js
  src/VariableInput/VariableInput.st.css
  src/VariableInput/docs/examples.js
  src/VariableInput/docs/index.story.js
  src/VariableInput/index.d.ts
  src/VariableInput/test/EditorUtilities.spec.js
  src/VariableInput/test/VariableInput.visual.js
Labels: PR: unreviewed

#4874 Fix a few lint warnings
  src/AutoComplete/tests/Autocomplete.spec.js
  src/BarChart/test/BarChart.private.uni.driver.js
  src/Breadcrumbs/test/Breadcrumbs.visual.js
  src/BrowserPreviewWidget/docs/index.story.js
  src/ColorPicker/tests/ColorPicker.visual.js
  src/Dropdown/tests/Dropdown.spec.js
  src/InputArea/test/InputArea.visual.js
  src/Modal/docs/index.story.js
  src/PreviewWidget/docs/index.story.js
  src/RichTextInputArea/Toolbar/RichTextToolbarButton.js
  stories/Introduction/Cheatsheet/ComponentsCheatsheet.js
  stories/Introduction/Cheatsheet/componentsFamilies/LayoutFamily/examples/CardExamples.js
  stories/Introduction/Cheatsheet/componentsFamilies/LayoutFamily/examples/PageExamples.js
  stories/Introduction/Cheatsheet/componentsFamilies/LayoutFamily/examples/TableExamples.js
  stories/Introduction/Cheatsheet/componentsFamilies/NotificationFamily.js
  stories/Introduction/Cheatsheet/componentsFamilies/PickerFamily.js
  stories/Introduction/Cheatsheet/componentsFamilies/TooltipFamily.js
Labels: PR: unreviewed, Refactor

#4872 Improve typography visuals
  src/Typography/docs/styles.scss
  src/Typography/test/HeadingClassesExample.js
  src/Typography/test/TextClassesExample.js
  src/Typography/test/Typography.visual.js
Labels: PR: unreviewed, Refactor, Typography

#4676 <MessageBoxMarketerialLayout/> - primaryButtonNode
  src/MessageBox/MarketerialLayout/MessageBoxMarketerialLayout.driver.js
  src/MessageBox/MarketerialLayout/MessageBoxMarketerialLayout.js
  src/MessageBox/MarketerialLayout/MessageBoxMarketerialLayout.spec.js
  src/MessageBox/MarketerialLayout/MessageBoxMarketerialLayout.uni.driver.js
  src/MessageBox/docs/Announcement.js
  src/MessageBox/docs/AnnouncementExamples/PrimaryButtonNode.js
Labels: PR: unreviewed

#4877 fix(generator): use `locals` for dashed name
  .wuf/generator/templates/$ComponentName/test/storySettings.js
Labels: Infrastructure, PR: reviewed-approved, PR: unreviewed

#4878 <MessageBoxMarketerialLayout/> - add width prop
  src/MessageBox/MarketerialLayout/MarketrialLayout.visual.js
  src/MessageBox/MarketerialLayout/MessageBoxMarketerialLayout.js
  src/MessageBox/MarketerialLayout/MessageBoxMarketerialLayout.scss
Labels: PR: reviewed-approved

#4880 Cheatsheet reference
  CONTRIBUTING.md
  docs/contribution/DOCUMENTING_COMPONENTS.md
Labels: PR: unreviewed

#4881 <MessageBoxMarketerialLayout/> - Update API documentation
  src/MessageBox/MarketerialLayout/MessageBoxMarketerialLayout.js
  src/MessageBox/README.md
Labels: PR: unreviewed

#4882 <MessageBoxMarketerialLayout/> - add noBodyPadding prop
  src/MessageBox/MarketerialLayout/MarketrialLayout.visual.js
  src/MessageBox/MarketerialLayout/MessageBoxMarketerialLayout.js
  src/MessageBox/MarketerialLayout/MessageBoxMarketerialLayout.scss
  src/MessageBox/README.md
Labels: PR: reviewed-approved

#4883 Release 7.34.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#4875 <ModalPreviewLayout/>- tooltips & navigation buttons tests
  src/ModalPreviewLayout/test/ModalPreviewLayout.e2e.js
  src/ModalPreviewLayout/test/ModalPreviewLayout.private.uni.driver.js
  src/ModalPreviewLayout/test/ModalPreviewLayout.visual.js
  src/ModalPreviewLayout/test/storySettings.js
  src/ModalPreviewLayout/test/testStory.js
  src/RichTextInputArea/test/RichTextInputArea.e2e.js
  stories/e2e.js
Labels: PR: unreviewed

#4889 <MultiSelectCheckbox/> - Upgraded story page + added visuals
  src/ListItemSelect/docs/index.story.js
  src/MultiSelectCheckbox/docs/ExampleStandard.js
  src/MultiSelectCheckbox/docs/ExampleStandard.scss
  src/MultiSelectCheckbox/docs/MultiSelectCheckboxTest.js
  src/MultiSelectCheckbox/docs/examples.js
  src/MultiSelectCheckbox/docs/index.story.js
  src/MultiSelectCheckbox/docs/multiSelectOptions.js
  src/MultiSelectCheckbox/test/MultiSelectCheckbox.visual.js
Labels: <MultiSelectCheckbox/>, PR: unreviewed, Refactor

#4892 <Checkbox/> - Stopped propagation on children
  src/Checkbox/Checkbox.js
Labels: <Checkbox/>, PR: reviewed-approved, PR: unreviewed

#4886 `<Button/>` - migrate to new disabled color
  src/Button/Button.js
  src/Button/Button.st.css
  src/Button/docs/examples.js
Labels: PR: unreviewed

#4893 Release 7.35.0
  package.json
Labels: PR: unreviewed

#4788 Infrastructure: fix named-importing issues
  package.json
  scripts/replaceStylableImports.js
  src/AddItem/AddItem.st.css
  src/Avatar/Avatar.st.css
  src/Badge/Badge.st.css
  src/Button/Button.st.css
  src/CloseButton/CloseButton.st.css
  src/ColorPicker/ColorPickerConverter.st.css
  src/DropdownBase/DropdownBase.st.css
  src/FillButton/FillButton.st.css
  src/FillPreview/FillPreview.st.css
  src/GoogleAddressInput/GoogleAddressInput.spec.js
  src/GoogleAddressInput/gmapsTestClient.js
  src/IconButton/IconButton.st.css
  src/ImageViewer/ImageViewer.st.css
  src/ListItemAction/ListItemAction.st.css
  src/MediaOverlay/MediaOverlay.st.css
  src/SegmentedToggle/ToggleButton/ToggleButton.st.css
  src/SegmentedToggle/ToggleIcon/ToggleIcon.st.css
  src/SidebarBackButton/SidebarBackButton.st.css
  src/SidebarSectionItem/SidebarSectionItem.st.css
  src/Slider/SliderHandle.st.css
  src/SocialButton/SocialButton.st.css
  src/StatisticsWidget/StatisticsItem/StatisticsItem.st.css
  src/Stepper/components/Step.st.css
  src/TableActionCell/TableActionCell.st.css
  src/TableToolbar/TableToolbar.js
  src/TextButton/TextButton.st.css
  src/Thumbnail/Thumbnail.st.css
  src/ToggleButton/ToggleButton.st.css
  src/common/EllipsisHOC/EllipsisHOC.st.css
  test-runtime/imports/.storybook/config.js
  test-runtime/imports/.storybook/es-named.story.js
  test-runtime/imports/.storybook/webpack.config.js
  test-runtime/imports/package.json
  testkit/component-definitions.js
Labels: PR: unreviewed

#4841 <Search/> - Add support for right to left expansion
  src/Search/Search.js
  src/Search/Search.scss
  src/Search/docs/examples/Expandable.js
  src/Search/test/Search.visual.js
Labels: PR: reviewed-approved

#4876 <Text/> - add default styling for nested <ul> lists
  perfer.config.js
  src/Text/Text.st.css
  src/Text/docs/examples.js
  src/Text/docs/index.story.js
  src/Text/test/Text.visual.js
Labels: PR: reviewed-approved

#4898 Release 7.36.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#4894 <VariableInput /> - onBlur and onChange issues
  src/VariableInput/EditorUtilities.js
  src/VariableInput/VariableInput.js
  src/VariableInput/VariableInput.uni.driver.d.ts
Labels: PR: reviewed-approved

#4887 <FormField/> - add `suffix` prop
  src/FormField/FormField.driver.js
  src/FormField/FormField.js
  src/FormField/FormField.scss
  src/FormField/FormField.uni.driver.js
  src/FormField/constants.js
  src/FormField/docs/examples.js
  src/FormField/docs/index.story.js
  src/FormField/test/FormField.spec.js
  src/FormField/test/FormField.visual.js
Labels: <FormField/>, PR: reviewed-approved, PR: unreviewed

#4901 <VariableInput/> - change composition to use FormField's suffix
  stories/VariableInput/examples.js
  stories/VariableInput/index.story.js
Labels: <VariableInput/>, PR: unreviewed

#4904 <imageViewer/>- reverting using dataHooks
  src/ImageViewer/ImageViewer.js
  src/ImageViewer/ImageViewer.private.driver.js
  src/ImageViewer/ImageViewer.protractor.driver.js
  src/ImageViewer/ImageViewer.spec.js
  src/ImageViewer/ImageViewer.visual.js
  src/ImageViewer/constants.js
  src/ImageViewer/docs/storySettings.js
Labels: PR: unreviewed

#4903 release/7.37.0
  package.json
Labels: PR: unreviewed

#4905 <Text/> - Fix nested <ul> styles being applied to incorrect elements
  src/Text/Text.st.css
Labels: PR: unreviewed

#4908 Release 7.37.1
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#4909 GooglePreview - fix broken playground
  src/GooglePreview/docs/index.story.js
Labels: PR: reviewed-approved

#4910 Typography - Remove use of Stylable and SCSS in the same component
  src/DropdownLayout/DropdownLayout.scss
  src/FormField/FormField.scss
  src/MessageBox/FunctionalLayout/MessageBoxFunctionalLayout.js
  src/MessageBox/FunctionalLayout/MessageBoxFunctionalLayout.scss
  src/Slider/Slider.js
  src/Slider/Slider.scss
  src/Typography/docs/BasicClassesSassExample.scss
Labels: PR: unreviewed, Typography

#4906 <Cell/> Layout - Fix Firefox bug on grid text overflow
  src/Layout/Cell/styles.scss
Labels: PR: reviewed-approved

#4911 <Dropdown/> - Improve dropdown list constraints documentation
  src/Dropdown/docs/examples.js
  src/Dropdown/docs/index.story.js
Labels: PR: reviewed-approved

#4914 SidebarSectionTitle - set cursor to default
  src/SidebarSectionTitle/SidebarSectionTitle.st.css
Labels: <Sidebar/>, PR: reviewed-approved, PR: unreviewed

#4921 <Input /> fixing statusMessage type
  src/ErrorIndicator/ErrorIndicator.js
  src/Input/InputErrorSuffix.js
Labels: PR: reviewed-approved

#4924 add to readme the min required yoshi version
  README.md
Labels: PR: unreviewed

#4884 Improve rich text area story
  stories/RichTextArea/examples.js
  stories/RichTextArea/index.story.js
  stories/RichTextArea/storySettings.js
  stories/index.js
Labels: PR: reviewed-approved

#4926 fix wallaby js
  wallaby.js
Labels: PR: unreviewed

#4928 Release 7.38.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#4925 `<Sidebar/>`- changing scrollbar colors
  src/Sidebar/Sidebar.js
  src/Sidebar/main.scss
  src/Sidebar/test/Sidebar.visual.js
  src/colors.scss
Labels: PR: unreviewed

#4912 <Tag/> - changed children type from string to node
  src/Tag/Tag.js
Labels: PR: reviewed-approved

#4930 named-imports - export missing components
  src/index.d.ts
  src/index.js
Labels: PR: reviewed-approved

#4931 Release 7.38.1
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#4915 <Tag/> - changed onClick callback call to pass 'event' as second parameter
  src/Tag/Tag.js
  src/Tag/Tag.spec.js
Labels: PR: unreviewed

#4927 <Image/> - new component
  .wuf/components.json
  .wuf/testkits/enzyme-typescript.template.ejs
  .wuf/testkits/vanilla-typescript.template.ejs
  package.json
  perfer.config.js
  src/CardGalleryItem/docs/examples.js
  src/Image/Image.js
  src/Image/Image.meta.js
  src/Image/Image.st.css
  src/Image/Image.uni.driver.d.ts
  src/Image/Image.uni.driver.js
  src/Image/docs/examples/fit.js
  src/Image/docs/examples/lazy.js
  src/Image/docs/examples/position.js
  src/Image/docs/examples/size.js
  src/Image/docs/examples/source.js
  src/Image/docs/index.story.js
  src/Image/index.d.ts
  src/Image/index.js
  src/Image/test/Image.private.uni.driver.js
  src/Image/test/Image.spec.js
  src/Image/test/Image.visual.js
  src/Image/test/storySettings.js
  src/MediaOverlay/docs/examples/basic.js
  src/MediaOverlay/docs/examples/header.js
  src/MediaOverlay/docs/examples/hoverSkin.js
  src/MediaOverlay/docs/examples/placement.js
  src/MediaOverlay/docs/examples/skin.js
  src/MediaOverlay/docs/examples/useCase1.js
  src/MediaOverlay/docs/examples/useCase2.js
  src/MediaOverlay/docs/examples/useCase3.js
  src/MediaOverlay/docs/examples/useCase4.js
  src/MediaOverlay/docs/examples/useCase5.js
  src/MediaOverlay/docs/index.story.js
  src/assets/example.jpg
  src/index.d.ts
  src/index.js
  stories/Introduction/Cheatsheet/componentsFamilies/ContentWidgetsFamily.js
  stories/Introduction/Cheatsheet/componentsFamilies/OtherFamily.js
  stories/PageLayout/ExampleGalleryLayout.js
  stories/index.js
  stories/symbolsComponentsMapping/components.js
  stories/symbolsComponentsMapping/families/otherFamily.js
  stories/symbolsComponentsMapping/symbols.js
  test/types/Image.tsx
  testkit/enzyme.d.ts
  testkit/enzyme.js
  testkit/index.d.ts
  testkit/index.js
  testkit/protractor.d.ts
  testkit/protractor.js
  testkit/puppeteer.d.ts
  testkit/puppeteer.js
Labels: PR: reviewed-approved

#4937 Fix broken CI builds
  .autotools/node-require-hooks.js
  package.json
Labels: PR: reviewed-approved
