Repository wix/wix-style-react, pull requests merged in 2021-02, with the labels that each got.

#6678 <TableActionCell/> - fix testkit initialization
  packages/wix-style-react/src/TableActionCell/TableActionCell.uni.driver.js
Labels: PR: unreviewed, WSR

#6680 Release 9.75.0
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
Labels: PR: unreviewed, WSR

#6681 <MarketingLayout/> - made root flex when align items stretch
  packages/wix-style-react/src/MarketingLayout/MarketingLayout.st.css
Labels: PR: reviewed-approved, WSR

#6670 <InputWithOptions/> - fix unable to focus editable option
  packages/wix-style-react/src/Input/Input.uni.driver.js
  packages/wix-style-react/src/InputWithOptions/InputWithOptions.js
  packages/wix-style-react/src/InputWithOptions/docs/storySettings.js
  packages/wix-style-react/src/InputWithOptions/docs/tests/TestFocus.js
  packages/wix-style-react/src/InputWithOptions/test/InputWithOptions.e2e.js
  packages/wix-style-react/src/ListItemEditable/test/ListItemEditable.private.uni.driver.js
  packages/wix-style-react/test/utils/unidriver/index.js
Labels: PR: unreviewed, WSR

#6668 Reduce spacing corrections
  packages/wix-style-react/src/SelectableAccordion/Item/Item.st.css
  packages/wix-style-react/src/Table/DataTable/DataTable.js
  packages/wix-style-react/src/Table/DataTable/DataTable.scss
  packages/wix-style-react/src/TableListItem/TableListItem.st.css
Labels: PR: reviewed-approved, Reduced Spacing & Improved Layout, WSR

#6655 <Calendar/> - Add A11Y example and make some changes according to Neil's review
  packages/wix-style-react/src/Calendar/DatePickerDropdown/DatePickerDropdown.js
  packages/wix-style-react/src/Calendar/DatePickerHead/DatePickerHead.js
  packages/wix-style-react/src/Calendar/docs/examples.js
  packages/wix-style-react/src/Calendar/docs/index.story.js
  packages/wix-style-react/src/TextButton/TextButton.js
  packages/wix-style-react/src/TextButton/index.d.ts
  packages/wix-style-react/src/TextButton/test/TextButton.tsx
Labels: PR: reviewed-approved, WSR

#6694 Fix theme panel initialization
  packages/wix-style-react/.storybook/addons/ThemeWSR/StylePanel.js
  packages/wix-style-react/.storybook/addons/ThemeWSR/index.js
Labels: PR: unreviewed

#6695 <Input/> - fix prefix/suffix break line
  packages/wix-style-react/src/Input/Affix/Affix.st.css
Labels: PR: unreviewed, WSR

#6697 Release 9.76.0
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
Labels: PR: unreviewed, WSR

#6696 <CustomModalLayout/> - deprecate hideContentDividers prop
  packages/wix-style-react/src/CustomModalLayout/CustomModalLayout.js
  packages/wix-style-react/src/CustomModalLayout/test/CustomModalLayout.visual.js
Labels: PR: unreviewed, WSR

#6698 <MarketingLayout/> - fix height and width when align items stretch
  packages/wix-style-react/src/MarketingLayout/MarketingLayout.st.css
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, WSR

#6666 <AddItem /> - added possibility to show tooltip for all themes
  packages/wix-style-react/src/AddItem/AddItem.driver.js
  packages/wix-style-react/src/AddItem/AddItem.js
  packages/wix-style-react/src/AddItem/AddItem.uni.driver.js
  packages/wix-style-react/src/AddItem/constants.js
  packages/wix-style-react/src/AddItem/docs/examples.js
  packages/wix-style-react/src/AddItem/docs/index.story.js
  packages/wix-style-react/src/AddItem/test/AddItem.private.driver.js
  packages/wix-style-react/src/AddItem/test/AddItem.private.uni.driver.js
  packages/wix-style-react/src/TimeTable/TimeTable.uni.driver.js
Labels: PR: reviewed-approved, WSR

#6649 <RadioGroup/> - refactor to use <Radio /> component
  packages/wix-style-react/src/RadioGroup/RadioButton/RadioButton.js
  packages/wix-style-react/src/RadioGroup/RadioButton/RadioButton.st.css
  packages/wix-style-react/src/RadioGroup/RadioGroup.driver.js
  packages/wix-style-react/src/RadioGroup/RadioGroup.js
  packages/wix-style-react/src/RadioGroup/RadioGroup.protractor.driver.js
  packages/wix-style-react/src/RadioGroup/RadioGroup.st.css
  packages/wix-style-react/src/RadioGroup/RadioGroup.uni.driver.d.ts
  packages/wix-style-react/src/RadioGroup/RadioGroup.uni.driver.js
  packages/wix-style-react/src/RadioGroup/constants.js
  packages/wix-style-react/src/RadioGroup/sharedDriverMethods.js
  packages/wix-style-react/src/RadioGroup/test/RadioGroup.private.uni.driver.js
  packages/wix-style-react/src/RadioGroup/test/RadioGroup.spec.js
  packages/wix-style-react/src/RadioGroup/test/RadioGroup.visual.js
Labels: PR: unreviewed, WSR

#6700 [DSM-1201] - <Tooltip/> - scope classnames targeting to immediate child
  packages/wix-style-react/src/Tooltip/Tooltip.st.css
Labels: PR: reviewed-approved, WSR

#6693 <TimeInputWip /> - new component
  packages/wix-style-react/.wuf/components.json
  packages/wix-style-react/perfer.config.js
  packages/wix-style-react/src/TimeInputWip/TimeInputWip.js
  packages/wix-style-react/src/TimeInputWip/TimeInputWip.meta.js
  packages/wix-style-react/src/TimeInputWip/TimeInputWip.st.css
  packages/wix-style-react/src/TimeInputWip/TimeInputWip.uni.driver.d.ts
  packages/wix-style-react/src/TimeInputWip/TimeInputWip.uni.driver.js
  packages/wix-style-react/src/TimeInputWip/constants.js
  packages/wix-style-react/src/TimeInputWip/docs/index.story.js
  packages/wix-style-react/src/TimeInputWip/index.d.ts
  packages/wix-style-react/src/TimeInputWip/index.js
  packages/wix-style-react/src/TimeInputWip/test/TimeInputWip.private.uni.driver.js
  packages/wix-style-react/src/TimeInputWip/test/TimeInputWip.spec.js
  packages/wix-style-react/src/TimeInputWip/test/TimeInputWip.tsx
  packages/wix-style-react/src/TimeInputWip/test/TimeInputWip.visual.js
  packages/wix-style-react/src/TimeInputWip/test/storySettings.js
  packages/wix-style-react/src/index.d.ts
  packages/wix-style-react/src/index.js
  packages/wix-style-react/stories/index.js
Labels: Contribution, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed, WSR

#6703 <SelectorList/> - fix testkit docs
  packages/wix-style-react/src/SelectorList/SelectorList.uni.driver.js
Labels: PR: unreviewed, WSR

#6702 <SelectableAccordion/> - migrate to use <Radio/>
  packages/wix-style-react/src/SelectableAccordion/Item/Item.js
Labels: PR: reviewed-approved, WSR

#6684 <DatePicker/> - implement localization fixes
  packages/wix-style-react/src/Calendar/Calendar.js
  packages/wix-style-react/src/Calendar/DatePickerHead/DatePickerHead.js
  packages/wix-style-react/src/Calendar/index.d.ts
  packages/wix-style-react/src/Calendar/test/Calendar.spec.js
  packages/wix-style-react/src/Calendar/test/Calendar.visual.js
  packages/wix-style-react/src/CalendarPanel/CalendarPanel.js
  packages/wix-style-react/src/CalendarPanel/index.d.ts
  packages/wix-style-react/src/DatePicker/DateInput/DateInput.js
  packages/wix-style-react/src/DatePicker/DateInput/index.d.ts
  packages/wix-style-react/src/DatePicker/DatePicker.js
  packages/wix-style-react/src/DatePicker/docs/index.story.js
  packages/wix-style-react/src/DatePicker/index.d.ts
  packages/wix-style-react/src/DatePicker/test/DatePicker.spec.js
  packages/wix-style-react/src/LocaleUtils.js
Labels: PR: unreviewed, WSR

#6707 <TimeInputWip/> - remove failing visual test temporarily
  packages/wix-style-react/src/TimeInputWip/test/TimeInputWip.visual.js
Labels: PR: reviewed-approved, WSR

#6704 Release 9.78.0
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
Labels: PR: unreviewed, WSR

#6711 getting 404 - So update the new storybook URL
  packages/wix-style-react/README.md
Labels: Contribution, PR: partially-approved, PR: unreviewed, WSR

#6712 <RadioGroup/> - [testkit] - fix legacy testkit
  packages/wix-style-react/perfer.config.js
  packages/wix-style-react/src/RadioGroup/RadioGroup.driver.js
Labels: PR: unreviewed, WSR

#6714 <CounterBadge/> - fix general skin css
  packages/wix-style-react/src/CounterBadge/CounterBadge.st.css
Labels: PR: unreviewed, WSR

#6706 Add id prop to generator
  packages/wix-style-react/.wuf/generator/templates/$ComponentName/$ComponentName.js
  packages/wix-style-react/.wuf/generator/templates/$ComponentName/index.d.ts
  packages/wix-style-react/.wuf/generator/templates/$ComponentName/test/$ComponentName.tsx
  packages/wix-style-react/src/Input/Input.js
  packages/wix-style-react/src/Input/index.d.ts
  packages/wix-style-react/src/ToggleSwitch/ToggleSwitch.js
  packages/wix-style-react/src/ToggleSwitch/index.d.ts
Labels: PR: unreviewed, WSR

#6715 <DropdownLayout/> - Add focusOnOption prop
  packages/wix-style-react/src/DropdownBase/DropdownBase.js
  packages/wix-style-react/src/DropdownBase/index.d.ts
  packages/wix-style-react/src/DropdownBase/test/DropdownBase.tsx
  packages/wix-style-react/src/DropdownLayout/DropdownLayout.js
  packages/wix-style-react/src/DropdownLayout/index.d.ts
  packages/wix-style-react/src/DropdownLayout/test/DropdownLayout.spec.js
  packages/wix-style-react/src/DropdownLayout/test/DropdownLayout.tsx
  packages/wix-style-react/src/DropdownLayout/test/DropdownLayout.visual.js
Labels: PR: unreviewed, WSR

#6710 <CounterBadge />- Change style for newDashboard theme
  packages/wix-style-react/src/Themes/businessDashboard/BusinessDashboard.st.css
  packages/wix-style-react/src/Themes/businessDashboard/components/CounterBadge.st.css
  packages/wix-style-react/src/Themes/businessDashboard/docs/businessDashboard.story.js
  packages/wix-style-react/src/Themes/businessDashboard/docs/components/CounterBadge.js
  packages/wix-style-react/src/Themes/businessDashboard/foundations/colors.st.css
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, Themes - Business Dashboard, WSR

#6716 <Calendar /> - add an onMonthChange prop (register a listener to setMonth event)
  packages/wix-style-react/src/Calendar/Calendar.js
  packages/wix-style-react/src/Calendar/index.d.ts
  packages/wix-style-react/src/Calendar/test/Calendar.spec.js
  packages/wix-style-react/src/Calendar/test/Calendar.tsx
  packages/wix-style-react/src/FormField/FormField.js
Labels: Contribution, PR: reviewed-changes-requested, PR: unreviewed, WSR

#6718 Revert "<RadioGroup/> - [testkit] - fix legacy testkit"
  packages/wix-style-react/src/RadioGroup/RadioGroup.driver.js
Labels: PR: unreviewed, WSR

#6719 Revert "<RadioGroup/> - refactor to use <Radio /> component"
  packages/wix-style-react/src/RadioGroup/RadioButton/RadioButton.js
  packages/wix-style-react/src/RadioGroup/RadioButton/RadioButton.st.css
  packages/wix-style-react/src/RadioGroup/RadioGroup.driver.js
  packages/wix-style-react/src/RadioGroup/RadioGroup.js
  packages/wix-style-react/src/RadioGroup/RadioGroup.protractor.driver.js
  packages/wix-style-react/src/RadioGroup/RadioGroup.st.css
  packages/wix-style-react/src/RadioGroup/RadioGroup.uni.driver.d.ts
  packages/wix-style-react/src/RadioGroup/RadioGroup.uni.driver.js
  packages/wix-style-react/src/RadioGroup/constants.js
  packages/wix-style-react/src/RadioGroup/sharedDriverMethods.js
  packages/wix-style-react/src/RadioGroup/test/RadioGroup.private.uni.driver.js
  packages/wix-style-react/src/RadioGroup/test/RadioGroup.spec.js
  packages/wix-style-react/src/RadioGroup/test/RadioGroup.visual.js
Labels: PR: unreviewed, WSR

#6720 Release 9.79.0
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
Labels: PR: unreviewed, WSR

#6722 <TimeInput/> - skip tests because of flakey
  packages/wix-style-react/src/TimeInputWip/test/TimeInputWip.visual.js
Labels: PR: unreviewed

#6723 add `wix-ui-tpa` to the root readme
  README.md
Labels: Docs, PR: unreviewed

#6721 <CounterBadge />: add missing stylable rule to `newDashboard` theme
  packages/wix-style-react/src/Themes/businessDashboard/BusinessDashboard.st.css
Labels: Contribution, PR: unreviewed, WSR

#6724 move wix-ui-tpa visual tests to separate parallel build
  package.json
  packages/wix-ui-tpa/package.json
Labels: Infrastructure, PR: unreviewed, WUT

#6727 move codeowners file to root + adjust content
  CODEOWNERS
  packages/wix-ui-tpa/CODEOWNERS
Labels: PR: reviewed-approved

#6691 <MarketingLayout/> - adding direction prop
  packages/wix-style-react/src/MarketingLayout/MarketingLayout.js
  packages/wix-style-react/src/MarketingLayout/constants.js
  packages/wix-style-react/src/MarketingLayout/docs/examples.js
  packages/wix-style-react/src/MarketingLayout/docs/index.story.js
  packages/wix-style-react/src/MarketingLayout/index.d.ts
  packages/wix-style-react/src/MarketingLayout/test/MarketingLayout.tsx
  packages/wix-style-react/src/MarketingLayout/test/MarketingLayout.visual.js
Labels: PR: unreviewed, WSR

#6729 docs(wix-ui-tpa): fix links
  packages/wix-ui-tpa/.storybook-test/config.js
  packages/wix-ui-tpa/.storybook/config.js
  packages/wix-ui-tpa/.swm/716IERM4vXmxo7cq5a2H.swm
  packages/wix-ui-tpa/.swm/K0mxbUGC2ZjCGkGNgYQW.swm
  packages/wix-ui-tpa/.wuf/generator/templates/Component/Component.tsx
  packages/wix-ui-tpa/README.md
  packages/wix-ui-tpa/docs/CONTRIBUTION.md
  packages/wix-ui-tpa/docs/HOW_TO_OVERRIDE_STYLES_PROPERLY.md
  packages/wix-ui-tpa/package.json
  packages/wix-ui-tpa/webpack.config.storybook.js
Labels: Contribution, PR: partially-approved, PR: unreviewed, WUT

#6728 Fix wut release script
  packages/wix-ui-tpa/package.json
  packages/wix-ui-tpa/scripts/tag.js
Labels: PR: unreviewed, WUT

#6656 <PulseAnimation/> - Add new component
  packages/wix-style-react/.wuf/components.json
  packages/wix-style-react/perfer.config.js
  packages/wix-style-react/src/Animate/Animate.js
  packages/wix-style-react/src/Animate/index.d.ts
  packages/wix-style-react/src/Animate/test/Animate.tsx
  packages/wix-style-react/src/Foundation/stylable/easing.st.css
  packages/wix-style-react/src/PulseAnimation/PulseAnimation.js
  packages/wix-style-react/src/PulseAnimation/PulseAnimation.meta.js
  packages/wix-style-react/src/PulseAnimation/PulseAnimation.st.css
  packages/wix-style-react/src/PulseAnimation/PulseAnimation.uni.driver.d.ts
  packages/wix-style-react/src/PulseAnimation/PulseAnimation.uni.driver.js
  packages/wix-style-react/src/PulseAnimation/constants.js
  packages/wix-style-react/src/PulseAnimation/docs/examples.js
  packages/wix-style-react/src/PulseAnimation/docs/index.story.js
  packages/wix-style-react/src/PulseAnimation/index.d.ts
  packages/wix-style-react/src/PulseAnimation/index.js
  packages/wix-style-react/src/PulseAnimation/test/PulseAnimation.private.uni.driver.js
  packages/wix-style-react/src/PulseAnimation/test/PulseAnimation.tsx
  packages/wix-style-react/src/PulseAnimation/test/storySettings.js
  packages/wix-style-react/src/index.d.ts
  packages/wix-style-react/src/index.js
  packages/wix-style-react/stories/index.js
  packages/wix-style-react/testkit/component-definitions.js
Labels: Contribution, PR: draft, PR: partially-approved, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed, WSR

#6732 build(Monorepo tags): add contributor
  .github/workflows/main.yml
Labels: PR: unreviewed

#6730 <Animate/>- small fixes
  packages/wix-style-react/src/Animate/Animate.js
  packages/wix-style-react/src/Animate/index.d.ts
  packages/wix-style-react/src/Animate/test/Animate.tsx
  packages/wix-style-react/src/Animate/utils.js
  packages/wix-style-react/src/BounceAnimation/BounceAnimation.js
  packages/wix-style-react/src/PulseAnimation/PulseAnimation.js
Labels: PR: unreviewed, WSR

#6734 Release 9.80.0
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
Labels: PR: unreviewed, WSR

#6737 move wut scripts to root package.json (well aliases actually)
  package.json
Labels: PR: partially-approved

#6736 [wix-ui-tpa]: publish storybook
  package.json
  packages/wix-ui-tpa/package.json
Labels: Docs, Infrastructure, PR: unreviewed, WUT

#6742 <PulseAnimation/> - fix click on children
  packages/wix-style-react/src/PulseAnimation/PulseAnimation.st.css
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, WSR

#6738 feat(Image): implement `focalPoint` prop
  packages/wix-ui-tpa/src/components/Image/Image.tsx
  packages/wix-ui-tpa/src/components/Image/Image.visual.tsx
  packages/wix-ui-tpa/src/components/Image/ImageUtils.spec.tsx
  packages/wix-ui-tpa/src/components/Image/ImageUtils.tsx
  packages/wix-ui-tpa/src/components/Image/RelativeMediaImage/RelativeMediaImage.tsx
  packages/wix-ui-tpa/src/components/Image/docs/examples.ts
  packages/wix-ui-tpa/src/components/Image/docs/index.story.tsx
  packages/wix-ui-tpa/src/components/Image/types.ts
Labels: PR: partially-approved, WUT

#6733 <CheckToggle/> - add animate prop
  packages/wix-style-react/src/CheckToggle/CheckToggle.js
  packages/wix-style-react/src/CheckToggle/docs/examples.js
  packages/wix-style-react/src/CheckToggle/docs/index.story.js
  packages/wix-style-react/src/CheckToggle/index.d.ts
  packages/wix-style-react/src/CheckToggle/test/CheckToggle.tsx
Labels: Contribution, PR: partially-approved, PR: reviewed-approved, PR: unreviewed, WSR

#6735 feat(wix-ui-tpa)dropdown-fixes
  packages/wix-ui-tpa/src/components/Dropdown/Dropdown.st.css
  packages/wix-ui-tpa/src/components/Dropdown/docs/DropdownExtendedExample.st.css
Labels: Contribution, PR: unreviewed, WUT

#6746 [wix-ui-tpa] release: v2.22.0
  packages/wix-ui-tpa/CHANGELOG.md
  packages/wix-ui-tpa/package.json
Labels: PR: partially-approved, WUT

#6748 Revert "<CheckToggle/> - add animate prop"
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/src/CheckToggle/CheckToggle.js
  packages/wix-style-react/src/CheckToggle/docs/examples.js
  packages/wix-style-react/src/CheckToggle/docs/index.story.js
  packages/wix-style-react/src/CheckToggle/index.d.ts
  packages/wix-style-react/src/CheckToggle/test/CheckToggle.tsx
Labels: PR: unreviewed, WSR

#6752 TPA generator fixes
  packages/wix-ui-tpa/.wuf/generator/templates/Component/docs/ComponentWiringExample.st.css
  packages/wix-ui-tpa/.wuf/generator/templates/Component/docs/index.story.tsx
Labels: PR: partially-approved

#6756 allow `rm .wuf/components.json` to fail gracefully
  packages/wix-ui-tpa/.wuf/update-components.sh
Labels: Infrastructure, PR: unreviewed, WUT

#6760 Add --stream to test9
  package.json
Labels: PR: unreviewed

#6749 <InputWithOptions /> - add missing disabled prop to native select
  packages/wix-style-react/src/InputWithOptions/InputWithOptions.js
  packages/wix-style-react/src/InputWithOptions/test/InputWithOptions.spec.js
  packages/wix-style-react/test/utils/unidriver/ReactBase.js
Labels: Bug, Contribution, PR: partially-approved, PR: unreviewed, WSR

#6763 [wix-ui-tpa] bump image perfer bundle size
  packages/wix-ui-tpa/perfer.config.js
Labels: PR: reviewed-approved, WUT

#6762 Pinned the wix-animations version to "1.0.405"
  packages/wix-style-react/package.json
Labels: PR: reviewed-approved, WSR

#6765 release
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
Labels: PR: unreviewed, WSR

#6686 <PageSection/>- new component
  packages/wix-style-react/.wuf/components.json
  packages/wix-style-react/perfer.config.js
  packages/wix-style-react/src/Page/Page.js
  packages/wix-style-react/src/PageSection/PageSection.js
  packages/wix-style-react/src/PageSection/PageSection.meta.js
  packages/wix-style-react/src/PageSection/PageSection.st.css
  packages/wix-style-react/src/PageSection/PageSection.uni.driver.d.ts
  packages/wix-style-react/src/PageSection/PageSection.uni.driver.js
  packages/wix-style-react/src/PageSection/constants.js
  packages/wix-style-react/src/PageSection/docs/examples.js
  packages/wix-style-react/src/PageSection/docs/index.story.js
  packages/wix-style-react/src/PageSection/index.d.ts
  packages/wix-style-react/src/PageSection/index.js
  packages/wix-style-react/src/PageSection/test/PageSection.private.uni.driver.js
  packages/wix-style-react/src/PageSection/test/PageSection.spec.js
  packages/wix-style-react/src/PageSection/test/PageSection.tsx
  packages/wix-style-react/src/PageSection/test/PageSection.visual.js
  packages/wix-style-react/src/PageSection/test/storySettings.js
  packages/wix-style-react/src/index.d.ts
  packages/wix-style-react/src/index.js
  packages/wix-style-react/stories/index.js
  packages/wix-style-react/stories/symbolsComponentsMapping/components.js
  packages/wix-style-react/stories/symbolsComponentsMapping/families/layoutFamily.js
  packages/wix-style-react/stories/symbolsComponentsMapping/storybookMapping.js
  packages/wix-style-react/testkit/component-definitions.js
Labels: PR: partially-approved, WSR

#6740 fix(DatePicker): add aria props and some adjustments for the WSR fixes
  packages/wix-style-react/src/Calendar/DatePickerHead/DatePickerHead.st.css
  packages/wix-style-react/src/Calendar/index.d.ts
  packages/wix-style-react/src/Calendar/test/Calendar.tsx
  packages/wix-style-react/src/DatePicker/test/DatePicker.tsx
  packages/wix-ui-tpa/package.json
  packages/wix-ui-tpa/src/components/DatePicker/DatePicker.meta.tsx
  packages/wix-ui-tpa/src/components/DatePicker/DatePicker.st.css
  packages/wix-ui-tpa/src/components/DatePicker/DatePicker.tsx
  packages/wix-ui-tpa/src/components/DatePicker/docs/examples.ts
  packages/wix-ui-tpa/src/components/DatePicker/docs/index.story.tsx
  packages/wix-ui-tpa/src/components/DatePickerInput/DatePickerInput.meta.tsx
  packages/wix-ui-tpa/src/components/DatePickerInput/DatePickerInput.tsx
  packages/wix-ui-tpa/tsconfig.json
Labels: PR: unreviewed, WSR, WUT

#6759 <DatePicker/> - style fixes
  packages/wix-ui-tpa/src/components/DatePicker/DatePicker.st.css
  packages/wix-ui-tpa/src/components/DatePicker/docs/DatePickerWiringExample.st.css
  packages/wix-ui-tpa/src/components/DatePicker/docs/index.story.tsx
Labels: PR: partially-approved, WUT

#6747 Adjusting wut scripts, so that prebuild is called
  package.json
  packages/wix-ui-tpa/docs/CONTRIBUTION.md
  packages/wix-ui-tpa/docs/internal/VERSION_RELEASE.md
  packages/wix-ui-tpa/package.json
  run-package-command.sh
Labels: PR: reviewed-approved, WUT

#6757 Counter component - Adding aria-live attribute on input element
  packages/wix-ui-tpa/src/components/Counter/Counter.tsx
Labels: Contribution, PR: partially-approved, PR: unreviewed, WUT

#6774 release/9.82.0
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
Labels: PR: unreviewed, WSR

#6777 <PreviewWidget /> - Add `none` option for contentOutline
  packages/wix-style-react/src/PreviewWidget/PreviewWidget.js
  packages/wix-style-react/src/PreviewWidget/PreviewWidget.st.css
  packages/wix-style-react/src/PreviewWidget/constants.js
  packages/wix-style-react/src/PreviewWidget/docs/index.story.js
  packages/wix-style-react/src/PreviewWidget/index.d.ts
  packages/wix-style-react/src/PreviewWidget/test/PreviewWidget.visual.js
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, WSR

#6690 dnd-styles - migrate to Stylable
  packages/wix-style-react/src/DragAndDrop/docs/SortableList/ListWithDelay/ListWithDelay.scss
  packages/wix-style-react/src/DragAndDrop/docs/SortableList/NestableListExample/NestableList.scss
  packages/wix-style-react/src/DragAndDrop/docs/SortableList/SingleAreaList/SingleAreaList.scss
  packages/wix-style-react/src/DragAndDrop/docs/SortableList/SingleAreaListWithAnimation/SingleAreaListWithAnimation.scss
  packages/wix-style-react/src/dnd-styles/dnd-styles.js
  packages/wix-style-react/src/dnd-styles/dnd-styles.scss
  packages/wix-style-react/src/dnd-styles/dnd-styles.st.css
Labels: PR: unreviewed, WSR

#6768 <VariableInput /> - Fix emoji utf splitting issue
  packages/wix-style-react/src/VariableInput/EditorUtilities.js
  packages/wix-style-react/src/VariableInput/VariableInput.uni.driver.js
  packages/wix-style-react/src/VariableInput/test/VariableInput.private.uni.driver.js
  packages/wix-style-react/src/VariableInput/test/VariableInput.spec.js
  packages/wix-style-react/src/VariableInput/test/VariableInput.visual.js
  packages/wix-style-react/test/utils/unidriver/DraftJS.js
Labels: Contribution, PR: ready-for-review :pray:, PR: reviewed-approved, PR: unreviewed, WSR

#6775 <Modal/> - added typings screen prop
  packages/wix-style-react/src/Modal/index.d.ts
Labels: PR: reviewed-approved, WSR

#6778 <ListItemSelect/> - fix type
  packages/wix-style-react/src/ListItemSelect/index.d.ts
  packages/wix-style-react/src/ListItemSelect/test/ListItemSelect.tsx
Labels: PR: unreviewed, WSR

#6739 <Timeline/> - add gap prop
  packages/wix-style-react/src/Timeline/Timeline.js
  packages/wix-style-react/src/Timeline/TimelineItem.js
  packages/wix-style-react/src/Timeline/TimelineItem.st.css
  packages/wix-style-react/src/Timeline/index.d.ts
  packages/wix-style-react/src/Timeline/test/Timeline.tsx
  packages/wix-style-react/src/Timeline/test/Timeline.visual.js
Labels: Contribution, PR: partially-approved, PR: reviewed-approved, PR: unreviewed, WSR

#6772 [WUT] - <DatePicker/> - fix border radius issue
  packages/wix-ui-tpa/src/components/DatePicker/DatePicker.st.css
Labels: PR: partially-approved, WUT

#6782 release: version 2.23.0
  packages/wix-ui-tpa/CHANGELOG.md
  packages/wix-ui-tpa/package.json
Labels: PR: reviewed-approved, WUT

#6780 wix-animations - unpin the version
  packages/wix-style-react/package.json
Labels: PR: unreviewed, WSR

#6743 <CounterBadge /> - Revert overrides
  packages/wix-style-react/src/Themes/businessDashboard/BusinessDashboard.st.css
  packages/wix-style-react/src/Themes/businessDashboard/components/CounterBadge.st.css
  packages/wix-style-react/src/Themes/businessDashboard/docs/businessDashboard.story.js
  packages/wix-style-react/src/Themes/businessDashboard/docs/components/CounterBadge.js
  packages/wix-style-react/src/Themes/businessDashboard/foundations/colors.st.css
Labels: Contribution, PR: partially-approved, PR: reviewed-approved, PR: unreviewed, WSR

#6776 Improve local package bootstrapping
  docs/working-with-monorepo.md
  package.json
  scripts/post-install.sh
  scripts/run-package-command.sh
Labels: Infrastructure, PR: partially-approved, PR: unreviewed

#6755 Adding 'aria-*' to <Text/>
  packages/wix-ui-tpa/src/components/Text/Text.tsx
Labels: Contribution, PR: partially-approved, PR: reviewed-changes-requested, PR: unreviewed, WUT

#6781 <Breadcrumbs /> - fix color contrast issue when using with Madefor font
  packages/wix-style-react/src/Breadcrumbs/Breadcrumbs.js
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, WSR

#6784 release 9.83.0
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
Labels: PR: unreviewed, WSR

#6699 <AddItem/> - add subtitle prop
  packages/wix-style-react/src/AddItem/AddItem.driver.d.ts
  packages/wix-style-react/src/AddItem/AddItem.driver.js
  packages/wix-style-react/src/AddItem/AddItem.js
  packages/wix-style-react/src/AddItem/AddItem.spec.js
  packages/wix-style-react/src/AddItem/AddItem.st.css
  packages/wix-style-react/src/AddItem/AddItem.uni.driver.d.ts
  packages/wix-style-react/src/AddItem/AddItem.uni.driver.js
  packages/wix-style-react/src/AddItem/constants.js
  packages/wix-style-react/src/AddItem/docs/examples.js
  packages/wix-style-react/src/AddItem/docs/index.story.js
  packages/wix-style-react/src/AddItem/index.d.ts
  packages/wix-style-react/src/AddItem/test/AddItem.visual.js
Labels: PR: unreviewed, WSR

#6783 [wix-u-tpa]: remove logger from scripts
  packages/wix-ui-tpa/scripts/tag.js
  packages/wix-ui-tpa/scripts/utils.js
Labels: PR: reviewed-approved, WUT

#6773 [wix-ui-tpa] fix card override styles
  packages/wix-ui-tpa/src/components/Card/Card.st.css
  packages/wix-ui-tpa/src/components/Card/Card.tsx
  packages/wix-ui-tpa/src/components/Card/Card.visual.tsx
  packages/wix-ui-tpa/src/components/Card/docs/CardVisual.st.css
  packages/wix-ui-tpa/src/components/Grid/Grid.spec.tsx
  packages/wix-ui-tpa/src/components/Grid/Grid.tsx
  packages/wix-ui-tpa/src/components/Grid/GridUtils.spec.tsx
  packages/wix-ui-tpa/src/components/Grid/GridUtils.tsx
Labels: PR: unreviewed, WUT

#6792 <AddItem /> - disabled button background colour fix for plain theme
  packages/wix-style-react/src/AddItem/AddItem.st.css
Labels: PR: reviewed-approved, WSR

#6791 <VariableInput /> - Use regex.exec instead of matchAll
  packages/wix-style-react/src/VariableInput/EditorUtilities.js
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, WSR

#6788 [wix-ui-tpa] release: v2.24.0
  packages/wix-ui-tpa/CHANGELOG.md
  packages/wix-ui-tpa/package.json
Labels: PR: unreviewed, WUT

#6797 <VariableInput/> add onFocus callback and focus to driver
  packages/wix-style-react/src/VariableInput/VariableInput.js
  packages/wix-style-react/src/VariableInput/VariableInput.uni.driver.d.ts
  packages/wix-style-react/src/VariableInput/VariableInput.uni.driver.js
  packages/wix-style-react/src/VariableInput/index.d.ts
  packages/wix-style-react/src/VariableInput/test/VariableInput.spec.js
  packages/wix-style-react/src/VariableInput/test/VariableInput.tsx
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, WSR

#6793 `<MessageBoxFunctionalLayout />` - introduce deprecation message in story
  packages/wix-style-react/src/MessageBox/FunctionalLayout/docs/index.story.js
Labels: PR: reviewed-approved, WSR

#6787 [wix-style-react] - <Calendar/> - adjusting the date indication size
  packages/wix-style-react/src/Calendar/Calendar.st.css
Labels: PR: reviewed-approved, WSR

#6766 Documentation fixes: testkit imports and README links
  packages/wix-style-react/docs/FAQ/README.md
  packages/wix-style-react/src/MultiSelectCheckbox/README.TESTKIT.md
  packages/wix-style-react/src/Search/README.TESTKIT.md
  packages/wix-style-react/src/Table/DataTable/README.md
  packages/wix-style-react/src/Table/Table.js
Labels: Contribution, PR: unreviewed, WSR

#6789 [WUT] - VERSION_RELEASE.md - add colonoscopy step to freeze merges
  packages/wix-ui-tpa/docs/internal/VERSION_RELEASE.md
Labels: PR: reviewed-approved, WUT

#6799 FocusOnRichEditor - Extract page from unidriver
  packages/wix-style-react/test/utils/unidriver/DraftJS.js
Labels: Contribution, PR: partially-approved, PR: unreviewed, WSR

#6801 PageSection- update description
  packages/wix-style-react/src/PageSection/docs/index.story.js
Labels: PR: unreviewed, WSR

#6745 add backgorund param
  packages/wix-ui-tpa/src/components/Counter/Counter.st.css
  packages/wix-ui-tpa/src/components/Counter/Counter.tsx
  packages/wix-ui-tpa/src/components/Counter/docs/CounterExtendedExample.st.css
  packages/wix-ui-tpa/src/components/Counter/docs/CounterExtendedExample.tsx
  packages/wix-ui-tpa/src/components/Counter/docs/index.story.tsx
Labels: Contribution, PR: unreviewed, WUT

#6804 FocusOnRichEditor fix: use element entity instead of the page
  packages/wix-style-react/test/utils/unidriver/DraftJS.js
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, WSR

#6803 Themes | Business Dashboard - Updating list actions item disabled state
  packages/wix-style-react/src/Themes/businessDashboard/components/ListItemAction.st.css
  packages/wix-style-react/src/Themes/businessDashboard/docs/components/PopoverMenu.js
Labels: Contribution, PR: partially-approved, PR: unreviewed, Themes - Business Dashboard, WSR

#6806 [WUT] - visualTestWrapper - Increase the timeout default value in ord…
  packages/wix-ui-tpa/src/test/visualTestWrapper.tsx
Labels: PR: unreviewed, WUT

#6771 Checkbox/RadioButton components- suffix should be node (instead of string)
  packages/wix-ui-tpa/src/components/Checkbox/Checkbox.tsx
  packages/wix-ui-tpa/src/components/Checkbox/Checkbox.visual.tsx
  packages/wix-ui-tpa/src/components/Checkbox/docs/examples.ts
  packages/wix-ui-tpa/src/components/Checkbox/docs/index.story.tsx
  packages/wix-ui-tpa/src/components/RadioButton/RadioButton.tsx
Labels: Contribution, PR: partially-approved, PR: unreviewed, WUT

#6751 <MobileDrawer /> - New Component
  packages/wix-ui-tpa/src/components/MobileDrawer/MobileDrawer.driver.ts
  packages/wix-ui-tpa/src/components/MobileDrawer/MobileDrawer.meta.tsx
  packages/wix-ui-tpa/src/components/MobileDrawer/MobileDrawer.spec.tsx
  packages/wix-ui-tpa/src/components/MobileDrawer/MobileDrawer.st.css
  packages/wix-ui-tpa/src/components/MobileDrawer/MobileDrawer.tsx
  packages/wix-ui-tpa/src/components/MobileDrawer/MobileDrawer.visual.tsx
  packages/wix-ui-tpa/src/components/MobileDrawer/docs/examples.ts
  packages/wix-ui-tpa/src/components/MobileDrawer/docs/index.story.tsx
  packages/wix-ui-tpa/src/components/MobileDrawer/index.tsx
  packages/wix-ui-tpa/src/components/index.ts
  packages/wix-ui-tpa/src/index.tsx
  packages/wix-ui-tpa/stories/index.ts
Labels: Contribution, PR: partially-approved, PR: reviewed-changes-requested, PR: unreviewed, WUT

#6798 [WUT] - <DatePicker/> - Add role region and update the storybook example
  packages/wix-ui-tpa/src/components/DatePicker/DatePicker.tsx
  packages/wix-ui-tpa/src/components/DatePicker/docs/examples.ts
Labels: PR: reviewed-approved, WUT

#6753 <TABLE/>: enable disabling checkboxes in specific rows
  packages/wix-style-react/src/Table/BulkSelection/BulkSelection.js
  packages/wix-style-react/src/Table/BulkSelection/BulkSelection.spec.js
  packages/wix-style-react/src/Table/Table.js
  packages/wix-style-react/src/Table/Table.spec.js
  packages/wix-style-react/src/Table/components/TableBulkSelectionCheckbox.js
  packages/wix-style-react/src/Table/docs/examples/TablePageExample.js
  packages/wix-style-react/src/Table/docs/examples/TableSubToolbarExample.js
  packages/wix-style-react/src/Table/index.d.ts
Labels: Contribution, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed, WSR

#6810 docs(Image): move to components category
  packages/wix-ui-tpa/src/components/HeroImage/docs/index.story.tsx
  packages/wix-ui-tpa/src/components/Image/docs/index.story.tsx
  packages/wix-ui-tpa/src/components/ThumbnailImage/docs/index.story.tsx
Labels: PR: reviewed-approved, WUT

#6811 release: version 2.25.0
  packages/wix-ui-tpa/CHANGELOG.md
  packages/wix-ui-tpa/package.json
Labels: PR: reviewed-approved, WUT

#6769 Checkbox component- adding focus-ring
  packages/wix-ui-tpa/src/components/Checkbox/Checkbox.e2e.ts
  packages/wix-ui-tpa/src/components/Checkbox/Checkbox.st.css
  packages/wix-ui-tpa/src/components/Checkbox/Checkbox.tsx
  packages/wix-ui-tpa/src/components/Checkbox/dataHooks.ts
Labels: Contribution, PR: partially-approved, PR: unreviewed, WUT

#6807 <Thumbnail/> - change tiny text to bold
  packages/wix-style-react/src/Thumbnail/Thumbnail.js
Labels: PR: unreviewed, WSR

#6808 <Input/> - fix styles for FireFox
  packages/wix-style-react/src/Input/Input.st.css
Labels: PR: reviewed-approved, WSR

#6812 <Badge/> - add visual tests
  packages/wix-style-react/src/Badge/test/Badge.visual.js
Labels: PR: reviewed-approved, WSR

#6584 <AvatarGroup/> - new component
  packages/wix-style-react/.wuf/components.json
  packages/wix-style-react/perfer.config.js
  packages/wix-style-react/src/Avatar/Avatar.js
  packages/wix-style-react/src/Avatar/Avatar.st.css
  packages/wix-style-react/src/Avatar/index.d.ts
  packages/wix-style-react/src/AvatarGroup/AvatarGroup.js
  packages/wix-style-react/src/AvatarGroup/AvatarGroup.meta.js
  packages/wix-style-react/src/AvatarGroup/AvatarGroup.st.css
  packages/wix-style-react/src/AvatarGroup/AvatarGroup.uni.driver.d.ts
  packages/wix-style-react/src/AvatarGroup/AvatarGroup.uni.driver.js
  packages/wix-style-react/src/AvatarGroup/constants.js
  packages/wix-style-react/src/AvatarGroup/docs/examples.js
  packages/wix-style-react/src/AvatarGroup/docs/index.story.js
  packages/wix-style-react/src/AvatarGroup/index.d.ts
  packages/wix-style-react/src/AvatarGroup/index.js
  packages/wix-style-react/src/AvatarGroup/moreIndicator/MoreIndicator.js
  packages/wix-style-react/src/AvatarGroup/test/AvatarGroup.private.uni.driver.js
  packages/wix-style-react/src/AvatarGroup/test/AvatarGroup.spec.js
  packages/wix-style-react/src/AvatarGroup/test/AvatarGroup.tsx
  packages/wix-style-react/src/AvatarGroup/test/AvatarGroup.visual.js
  packages/wix-style-react/src/AvatarGroup/test/storySettings.js
  packages/wix-style-react/src/index.d.ts
  packages/wix-style-react/src/index.js
  packages/wix-style-react/stories/index.js
  packages/wix-style-react/testkit/component-definitions.js
Labels: PR: reviewed-approved, WSR

#6817 <AvatarGroup/> - update example
  packages/wix-style-react/src/AvatarGroup/docs/index.story.js
Labels: PR: unreviewed, WSR

#6796 <Radio/> - move code from ui-core RadioButton
  packages/wix-style-react/src/Radio/Radio.driver.js
  packages/wix-style-react/src/Radio/Radio.js
  packages/wix-style-react/src/Radio/Radio.st.css
  packages/wix-style-react/src/Radio/Radio.uni.driver.js
  packages/wix-style-react/src/Radio/constants.js
  packages/wix-style-react/src/Radio/index.d.ts
  packages/wix-style-react/src/Radio/test/Radio.spec.js
Labels: PR: reviewed-approved, WSR

#6825 Pin babel versions
  packages/wix-style-react/package.json
Labels: PR: unreviewed, WSR

#6821 #DSM-1611 | feat (wix-ui-tpa) date-picker -> on month change
  packages/wix-ui-tpa/src/components/DatePicker/DatePicker.spec.tsx
  packages/wix-ui-tpa/src/components/DatePicker/DatePicker.tsx
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, WUT

#6828 Pin babel versions
  packages/wix-ui-tpa/package.json
Labels: PR: reviewed-approved, WUT

#6814 [wix-ui-tpa] Some package.json fixes
  packages/wix-ui-tpa/package.json
Labels: PR: unreviewed, WUT

#6829 <Radio/> - move focusable props on input instead of wrapper div
  packages/wix-style-react/src/Radio/Radio.js
Labels: PR: reviewed-approved, WSR

#6820 Remove tooltip append to
  packages/wix-ui-tpa/src/components/TextField/TextField.tsx
Labels: PR: unreviewed, WUT

#6809 <Badge/> - fix font color when it is wider then max width
  packages/wix-style-react/src/Badge/Badge.st.css
Labels: PR: reviewed-approved, WSR

#6834 add git add to lint-staged
  packages/wix-ui-tpa/package.json
Labels: PR: reviewed-approved, WUT

#6840 use npx for wuf
  package.json
  packages/wix-style-react/.wuf/update-components.sh
  packages/wix-ui-tpa/.wuf/update-components.sh
Labels: Infrastructure, PR: reviewed-approved, PR: unreviewed

#6815 align versions of common dependencies
  packages/wix-style-react/package.json
  packages/wix-ui-tpa/package.json
Labels: Infrastructure, PR: draft, PR: unreviewed, WSR, WUT

#6795 <Input /> - story according new guidelines
  packages/wix-style-react/src/Input/Input.js
  packages/wix-style-react/src/Input/docs/examples.js
  packages/wix-style-react/src/Input/docs/index.story.js
Labels: PR: reviewed-approved, WSR

#6708 <Selector/> - use <Radio/> instead of <RadioButton/>
  packages/wix-style-react/src/Selector/Selector.js
Labels: PR: partially-approved, WSR

#6835 [wix-ui-tpa] some fixes to perfer basic files
  packages/wix-ui-tpa/perfer.config.js
  packages/wix-ui-tpa/src/components/Popover/perf/PopoverBasic.tsx
  packages/wix-ui-tpa/src/components/RadioButtonGroup/perf/RadioButtonGroupBasic.tsx
Labels: PR: partially-approved, WUT

#6770 TextArea component- fix focus-ring height
  packages/wix-ui-tpa/src/components/TextArea/TextArea.e2e.ts
  packages/wix-ui-tpa/src/components/TextArea/TextArea.st.css
  packages/wix-ui-tpa/src/components/TextArea/TextArea.tsx
  packages/wix-ui-tpa/src/components/TextArea/dataKeys.ts
  packages/wix-ui-tpa/stories/helperComponents/FocusRing.st.css
Labels: Contribution, PR: unreviewed, WUT

#6833 [wix-ui-tpa] dropdown error fix
  packages/wix-ui-tpa/src/components/Dropdown/Dropdown.st.css
  packages/wix-ui-tpa/src/components/Dropdown/Dropdown.visual.st.css
  packages/wix-ui-tpa/src/components/Dropdown/Dropdown.visual.tsx
  packages/wix-ui-tpa/src/components/Dropdown/DropdownBase.st.css
  packages/wix-ui-tpa/src/components/Dropdown/docs/DropdownExtendedExample.tsx
Labels: PR: partially-approved, WUT

#6832 <Popover/> fix how visibility state is determined
  packages/wix-ui-tpa/src/components/Popover/Popover.tsx
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, WUT

#6823 <Badge/> - Fix icon to correct size
  packages/wix-style-react/src/Badge/Badge.st.css
  packages/wix-style-react/src/Badge/docs/examples.js
  packages/wix-style-react/src/Badge/test/Badge.visual.js
  packages/wix-style-react/src/BadgeSelect/BadgeSelect.js
Labels: PR: unreviewed, WSR

#6800 update support readme
  packages/wix-style-react/SUPPORT.md
Labels: Docs, PR: draft, PR: unreviewed, WSR

#6837 Remove storybook-chromatic
  packages/wix-style-react/package.json
Labels: PR: unreviewed, WSR

#6839 <Modal/> - fix closing nested modals
  packages/wix-style-react/src/Modal/Modal.js
Labels: PR: unreviewed, WSR

#6830 <AvatarGroup/> - add avatarGroup component to cheatsheet
  packages/wix-style-react/stories/Introduction/Cheatsheet/componentsFamilies/OtherFamily.js
  packages/wix-style-react/stories/symbolsComponentsMapping/components.js
  packages/wix-style-react/stories/symbolsComponentsMapping/families/otherFamily.js
  packages/wix-style-react/stories/symbolsComponentsMapping/symbols.js
Labels: PR: unreviewed, WSR

#6802 fix(Image): update state when native image is completed
  packages/wix-ui-tpa/src/components/Image/Image.tsx
  packages/wix-ui-tpa/src/components/Image/RelativeMediaImage/RelativeMediaImage.tsx
Labels: PR: unreviewed, WUT

#6847 Applitools - update applitoolsConfig
  packages/wix-style-react/applitools.config.js
Labels: PR: unreviewed, WSR
