Repository wix/wix-style-react, pull requests merged in 2021-01, with the labels that each got.

#6467 Update typescript
  package.json
  src/BaseModalLayout/test/BaseModalLayout.spec.js
Labels: PR: unreviewed

#6454 <AtlasAddressInput/> - edit story page examples
  src/AtlasAddressInput/docs/examples.js
  src/AtlasAddressInput/docs/index.story.js
Labels: PR: unreviewed

#6481 <AtlasAddressInput/> - get place details on onSelect
  .storybook/mocks/atlas.js
  src/AtlasAddressInput/AtlasAddressInput.js
  src/AtlasAddressInput/docs/examples.js
  src/AtlasAddressInput/docs/index.story.js
  src/AtlasAddressInput/index.d.ts
  src/AtlasAddressInput/test/AtlasAddressInput.spec.js
  src/AtlasAddressInput/test/AtlasAddressInput.tsx
  src/providers/useAtlasClient/index.d.ts
  src/providers/useAtlasClient/useAtlasClient.js
  src/providers/useAtlasClient/useAtlasClient.spec.js
  src/providers/usePlacesAutocomplete/autocompleteClient.d.ts
Labels: PR: reviewed-approved

#6483 <InputArea> - move cursor to end on autoFocus
  src/Input/Input.uni.driver.d.ts
  src/Input/Input.uni.driver.js
  src/InputArea/InputArea.driver.d.ts
  src/InputArea/InputArea.driver.js
  src/InputArea/InputArea.js
  src/InputArea/InputArea.uni.driver.d.ts
  src/InputArea/InputArea.uni.driver.js
  src/InputArea/test/InputArea.spec.js
Labels: PR: reviewed-approved

#6471 <Sidebar/> - show gradient dynamically
  src/Sidebar/Sidebar.js
  src/Sidebar/Sidebar.uni.driver.js
  src/Sidebar/constants.js
  src/Sidebar/test/Sidebar.e2e.js
  src/Sidebar/test/Sidebar.e2eStory.js
  src/Sidebar/test/storySettings.js
Labels: PR: reviewed-approved

#6485 <AtlasAddressInput/> - export component from subfolder
  AtlasAddressInput/package.json
  src/AtlasAddressInput/docs/index.story.js
  src/AtlasAddressInput/index.d.ts
Labels: PR: unreviewed

#6489 <Table/>- adding more visuals
  src/Table/test/Table.visual.js
Labels: PR: unreviewed

#6474 <GooglePreview> - Add `titleMaxLines`, `descriptionMaxLines` and `skin` props
  src/GooglePreview/GooglePreview.js
  src/GooglePreview/GooglePreview.st.css
  src/GooglePreview/docs/examples.js
  src/GooglePreview/docs/index.story.js
  src/GooglePreview/docs/storySettings.js
  src/GooglePreview/index.d.ts
  src/GooglePreview/test/GooglePreview.tsx
  src/GooglePreview/test/GooglePreview.visual.js
Labels: PR: partially-approved

#6490 <Sidebar/> - move class variables to constructor
  src/Sidebar/Sidebar.js
Labels: PR: reviewed-approved

#6472 <StatisticsWidget/> - update padding for size tiny
  src/StatisticsWidget/StatisticsItem/StatisticsItem.st.css
  src/StatisticsWidget/StatisticsWidget.js
  src/StatisticsWidget/StatisticsWidget.st.css
Labels: PR: reviewed-approved

#6491 <AtlasAddressInput/> - add to files in package.json
  package.json
Labels: PR: unreviewed

#6497 Remove Axios
  package.json
  test-runtime/imports/test/e2e/puppeteer-testkit.e2e.js
Labels: PR: unreviewed

#6499 <Sidebar/> - fix inner div scrollbar to be hidden
  src/Sidebar/Sidebar.js
  src/Sidebar/Sidebar.st.css
Labels: PR: reviewed-approved

#6500 Revert "<Sidebar/> - fix inner div scrollbar to be hidden"
  src/Sidebar/Sidebar.js
  src/Sidebar/Sidebar.st.css
Labels: PR: unreviewed

#6498 Themes | Business Dashboard - add 3 more colors
  src/Themes/businessDashboard/foundations/colors.st.css
Labels: PR: reviewed-approved, Themes - Business Dashboard

#6502 <Sidebar/> - fix inner div scrollbar to be hidden
  src/Sidebar/Sidebar.js
  src/Sidebar/Sidebar.st.css
Labels: PR: unreviewed

#6441 Reduce Spacing- ColorPicker
  src/ColorPicker/ColorPickerConverter.js
  src/ColorPicker/test/ColorPicker.visual.js
Labels: <ColorPicker/>, PR: reviewed-approved, PR: unreviewed, Reduced Spacing & Improved Layout

#6503 Release 9.63.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#6470 Reduce Spacing- TableListItem
  src/TableListItem/TableListItem.js
  src/TableListItem/TableListItem.st.css
  src/TableListItem/docs/examples.js
  src/TableListItem/docs/examples/ColumnAlignmentExample.js
  src/TableListItem/docs/examples/ColumnsExample.js
  src/TableListItem/docs/examples/DividerExample.js
  src/TableListItem/docs/examples/DraggableExample.js
  src/TableListItem/docs/examples/PaddingExample.js
  src/TableListItem/docs/examples/SelectionExample.js
  src/TableListItem/docs/examples/StructureExample.js
  src/TableListItem/docs/examples/TableActionCellExample.js
  src/TableListItem/docs/index.story.js
  src/TableListItem/test/TableListItem.visual.js
Labels: <TableListItem/>, PR: reviewed-approved, PR: unreviewed, Reduced Spacing & Improved Layout

#6452 <Card.Subheader/>- reduce spacing
  perfer.config.js
  src/Card/Subheader/Subheader.js
  src/Card/Subheader/Subheader.st.css
  src/Card/Subheader/test/Subheader.visual.js
Labels: <Card/>, PR: reviewed-approved, PR: unreviewed, Reduced Spacing & Improved Layout

#6432 Tag - migrate to stylable
  perfer.config.js
  src/Tag/Tag.driver.js
  src/Tag/Tag.helpers.js
  src/Tag/Tag.js
  src/Tag/Tag.private.driver.js
  src/Tag/Tag.private.uni.driver.js
  src/Tag/Tag.scss
  src/Tag/Tag.st.css
  src/Tag/Tag.uni.driver.js
  src/Tag/test/Tag.spec.js
Labels: <Tag/>, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed

#6507 Update CHANGELOG.md
  CHANGELOG.md
Labels: PR: unreviewed

#6479 <SelectableAccordion/>- reduce Spacing and adding new verticalPadding prop
  src/SelectableAccordion/Item/Item.js
  src/SelectableAccordion/Item/Item.st.css
  src/SelectableAccordion/SelectableAccordion.js
  src/SelectableAccordion/constants.js
  src/SelectableAccordion/index.d.ts
  src/SelectableAccordion/test/SelectableAccordion.tsx
  src/SelectableAccordion/test/SelectableAccordion.visual.js
Labels: <SelectableAccordion/>, PR: reviewed-approved, PR: unreviewed, Reduced Spacing & Improved Layout

#6505 Themes | Business Dashboard - Badge - add urgent skin color override
  src/Themes/businessDashboard/components/Badge.st.css
Labels: PR: reviewed-approved, Themes - Business Dashboard

#6482 <MultiSelectCheckbox/> - [testkit] fix getLabels function
  src/MultiSelectCheckbox/MultiSelectCheckbox.driver.js
  src/MultiSelectCheckbox/MultiSelectCheckbox.uni.driver.js
  src/MultiSelectCheckbox/test/MultiSelectCheckbox.spec.js
Labels: PR: unreviewed

#6513 `<MultiSelectCheckbox/>` - add missing documentation about testkit methods arguments and missing types
  src/MultiSelectCheckbox/MultiSelectCheckbox.driver.d.ts
  src/MultiSelectCheckbox/MultiSelectCheckbox.driver.js
  src/MultiSelectCheckbox/MultiSelectCheckbox.uni.driver.d.ts
  src/MultiSelectCheckbox/MultiSelectCheckbox.uni.driver.js
  src/MultiSelectCheckbox/README.TESTKIT.md
  src/MultiSelectCheckbox/test/MultiSelectCheckbox.spec.js
Labels: PR: reviewed-approved

#6439 <FormField/>- reduce spacing and deprecate "labelSize" prop
  src/FormField/FormField.js
  src/FormField/test/FormField.visual.js
Labels: <FormField/>, PR: reviewed-approved, PR: unreviewed, Reduced Spacing & Improved Layout

#6510 <AtlasAddressInput/> - mock atlas in storybook
  .storybook/middleware.js
  .storybook/mocks/atlas.js
  .storybook/webpack.config.js
  src/AtlasAddressInput/docs/index.story.js
Labels: PR: unreviewed

#6516 release 9.64.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#6508 <AddressInput/> - move to components storybook category
  src/AddressInput/test/storySettings.js
  src/AtlasAddressInput/docs/index.story.js
  stories/index.js
Labels: PR: unreviewed

#6509 <Accordion/> - add bottom shadow to open item
  src/Accordion/AccordionItem/AccordionItem.st.css
  src/Foundation/stylable/shadows.st.css
Labels: PR: unreviewed

#6506 Themes | Business Dashboard - CloseButton - Add theme style
  src/CloseButton/test/CloseButton.visual.js
  src/Themes/businessDashboard/BusinessDashboard.st.css
  src/Themes/businessDashboard/components/CloseButton.st.css
  src/Themes/businessDashboard/docs/businessDashboard.story.js
  src/Themes/businessDashboard/docs/components/CloseButton.js
  src/Themes/businessDashboard/test/businessDashboard.visual.js
Labels: PR: reviewed-approved, Themes - Business Dashboard

#6518 perfer - update css bundles and fix incorrect declarations
  perfer.config.js
Labels: PR: unreviewed

#6521 `<Tag/>` - prevent onClick firing when its undefined
  src/Tag/Tag.js
Labels: PR: unreviewed

#6522 Release 9.65.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#6524 ToggleSwitch ToggleSwitch
  src/ToggleSwitch/docs/index.story.js
Labels: PR: reviewed-approved

#6511 Themes | Business Dashboard - Checkbox - Add checkbox to dashboard storybook
  src/Checkbox/test/Checkbox.visual.js
  src/Themes/businessDashboard/BusinessDashboard.st.css
  src/Themes/businessDashboard/components/Checkbox.st.css
  src/Themes/businessDashboard/docs/businessDashboard.story.js
  src/Themes/businessDashboard/docs/components/Checkbox.js
  src/Themes/businessDashboard/test/businessDashboard.visual.js
Labels: PR: partially-approved, Themes - Business Dashboard

#6475 <Accordion/> - Add accordionSectionItem
  src/Accordion/Accordion.js
  src/Accordion/Accordion.st.css
  src/Accordion/AccordionItem/AccordionItem.st.css
  src/Accordion/AccordionSectionItem/AccordionSectionItem.js
  src/Accordion/AccordionSectionItem/AccordionSectionItem.st.css
  src/Accordion/docs/examples.js
  src/Accordion/docs/index.story.js
Labels: PR: unreviewed

#6526 update dependencies
  package.json
Labels: PR: unreviewed

#6466 <DatePicker/> - Adding Unidriver
  src/Calendar/Calendar.uni.driver.js
  src/DatePicker/DatePicker.js
  src/DatePicker/DatePicker.uni.driver.d.ts
  src/DatePicker/DatePicker.uni.driver.js
  src/DatePicker/README.TESTKIT.md
  src/DatePicker/README.md
  src/DatePicker/constants.js
  src/DatePicker/test/DatePicker.spec.js
  src/Input/Input.js
Labels: PR: partially-approved

#6527 <AtlasAddressInput/> - replace `headers` prop with `token` prop
  src/AtlasAddressInput/AtlasAddressInput.js
  src/AtlasAddressInput/docs/examples.js
  src/AtlasAddressInput/docs/index.story.js
  src/AtlasAddressInput/test/AtlasAddressInput.tsx
  src/providers/useAtlasClient/index.d.ts
  src/providers/useAtlasClient/useAtlasClient.js
Labels: PR: unreviewed

#6496 <Input/> - add border prop
  src/Input/Input.js
  src/Input/Input.st.css
  src/Input/ThemedInput.js
  src/Input/docs/examples.js
  src/Input/docs/index.story.js
  src/Input/index.d.ts
  src/Input/test/Input.tsx
  src/Input/test/Input.visual.js
  src/Themes/businessDashboard/components/Input/Input.st.css
  src/TimeInput/TimeInput.js
Labels: PR: unreviewed

#6517 <SidePanel/> - adding support for noPadding
  src/SidePanel/COMPOUND_README.API.md
  src/SidePanel/Content/Content.js
  src/SidePanel/Content/Content.st.css
  src/SidePanel/Content/index.d.ts
  src/SidePanel/Divider/Divider.st.css
  src/SidePanel/Footer/Footer.js
  src/SidePanel/Footer/Footer.st.css
  src/SidePanel/Footer/index.d.ts
  src/SidePanel/Header/Header.js
  src/SidePanel/SidePanel.js
  src/SidePanel/SidePanel.st.css
  src/SidePanel/SidePanel.uni.driver.js
  src/SidePanel/docs/FixedPositionExample.js
  src/SidePanel/test/SidePanel.tsx
Labels: PR: reviewed-approved

#6531 Themes | Business Dashboard - Thumbnail - Style override
  src/Themes/businessDashboard/BusinessDashboard.st.css
  src/Themes/businessDashboard/components/Thumbnail.st.css
  src/Themes/businessDashboard/docs/businessDashboard.story.js
  src/Themes/businessDashboard/docs/components/Thumbnail.js
  src/Themes/businessDashboard/test/businessDashboard.visual.js
  src/Thumbnail/test/Thumbnail.visual.js
Labels: PR: reviewed-approved, Themes - Business Dashboard

#6529 <DatePicker/> - Update locale example, remove unnecessary tests and polyfills
  src/DatePicker/docs/index.story.js
  src/DatePicker/test/DatePicker.spec.js
Labels: PR: unreviewed

#6537 `<MultiSelectCheckbox/>` - make delimiter parameter optional for getLabel and getLabelAt
  src/MultiSelectCheckbox/MultiSelectCheckbox.driver.d.ts
  src/MultiSelectCheckbox/MultiSelectCheckbox.uni.driver.d.ts
  src/MultiSelectCheckbox/README.TESTKIT.md
Labels: PR: unreviewed

#6532 <AddressInput/> - disable browser autofill
  src/AddressInput/AddressInput.js
Labels: PR: unreviewed

#6534 <Input/> - fix border for affix/ticker
  src/AddressInput/AddressInput.js
  src/AddressInput/index.d.ts
  src/AddressInput/test/AddressInput.tsx
  src/AtlasAddressInput/AtlasAddressInput.js
  src/AtlasAddressInput/docs/index.story.js
  src/AtlasAddressInput/test/AtlasAddressInput.tsx
  src/Input/Affix/Affix.js
  src/Input/Affix/Affix.st.css
  src/Input/IconAffix/IconAffix.js
  src/Input/IconAffix/IconAffix.st.css
  src/Input/Input.js
  src/Input/Ticker/Ticker.js
  src/Input/Ticker/Ticker.st.css
  src/Search/Search.js
Labels: PR: unreviewed

#6488 <Table/>- reduce spacing (feature toggle) and add tiny to rowVerticalPadding prop
  src/Table/DataTable/DataTable.js
  src/Table/DataTable/DataTable.scss
  src/Table/DataTable/index.d.ts
  src/Table/Table.js
  src/Table/test/Table.visual.js
Labels: <Table/>, PR: draft, PR: partially-approved, PR: reviewed-approved, PR: unreviewed, Reduced Spacing & Improved Layout

#6533 <Tabs/> - fix testing in puppeteer
  src/Tabs/Tabs.uni.driver.js
Labels: PR: reviewed-approved

#6514 Themes | Business Dashboard - Tag - styling override.
  src/FormField/FormField.js
  src/Tag/Tag.js
  src/Tag/Tag.st.css
  src/Tag/test/Tag.visual.js
  src/Themes/businessDashboard/BusinessDashboard.st.css
  src/Themes/businessDashboard/components/Tag.st.css
  src/Themes/businessDashboard/docs/businessDashboard.story.js
  src/Themes/businessDashboard/docs/components/Tag.js
  src/Themes/businessDashboard/test/businessDashboard.visual.js
Labels: PR: reviewed-approved, Themes - Business Dashboard

#6541 <Page/> - rearrange docs
  src/Page/docs/ExampleEmptyState.js
  src/Page/docs/ExamplePageContainer.js
  src/Page/docs/ExamplePageContainer.scss
  src/Page/docs/ExampleStandAlone.js
  src/Page/docs/ExampleStandAlone.scss
  src/Page/docs/ExampleStickyTableWithGap.js
  src/Page/docs/ExampleStretchTable.js
  src/Page/docs/ExampleVerticalScrollListeners.js
  src/Page/docs/ExampleWithAppStructure.js
  src/Page/docs/PageExampleStories.js
  src/Page/docs/examples.js
  src/Page/docs/index.story.js
  src/Page/test/Page.e2eStory.js
  src/Page/test/examples/Breadcrumbs.js
  src/Page/test/examples/PageChildren.js
  src/Page/test/examples/PageStory.scss
  src/Page/test/examples/PageTestStories.scss
  src/Page/test/examples/SomeContentComponent2.js
  src/Page/test/examples/SomeTailComponent.js
  src/PageHeader/docs/index.story.js
  stories/ScrollBar/ExampleStandard.js
  stories/index.js
Labels: PR: unreviewed

#6544 <GoogleAddressInput/> - migrate to Stylable
  perfer.config.js
  src/GoogleAddressInput/GoogleAddressInput.js
  src/GoogleAddressInput/GoogleAddressInput.private.driver.js
  src/GoogleAddressInput/GoogleAddressInput.spec.js
  src/GoogleAddressInput/GoogleAddressInput.st.css
Labels: PR: unreviewed

#6547 Style Panel - text colors
  .storybook/addons/ThemeWSR/StylePanel.js
  src/Foundation/stylable/border.st.css
  src/Input/Input.st.css
Labels: PR: unreviewed

#6546 <Tabs/> - Refactor docs
  src/Tabs/README.md
  src/Tabs/Tabs.js
  src/Tabs/Tabs.uni.driver.js
  src/Tabs/core/SideContent/index.js
  src/Tabs/core/TabItems/index.js
  src/Tabs/docs/TabsHeaderExample.js
  src/Tabs/docs/examples.js
  src/Tabs/docs/index.story.js
  src/Tabs/test/Tabs.e2eStory.js
  src/Tabs/test/examples/TabsExample.js
  src/Tabs/test/examples/TabsExample.st.css
  src/Tabs/test/examples/TabsTemplate.js
Labels: PR: unreviewed

#6458 <MarketingLayout/> - update size tiny columns and spacing
  src/MarketingLayout/MarketingLayout.js
Labels: PR: partially-approved

#6540 Themes | Business Dashboard - VerticalTabsItem styling
  src/Themes/businessDashboard/BusinessDashboard.st.css
  src/Themes/businessDashboard/components/VerticalTabsItem.st.css
  src/Themes/businessDashboard/docs/businessDashboard.story.js
  src/Themes/businessDashboard/docs/components/VerticalTabsItem.js
  src/Themes/businessDashboard/test/businessDashboard.visual.js
  src/VerticalTabsItem/VerticalTabsItem.js
  src/VerticalTabsItem/VerticalTabsItem.st.css
  src/VerticalTabsItem/test/VerticalTabsItem.visual.js
Labels: PR: unreviewed, Themes - Business Dashboard

#6551 Style Panel - button
  .storybook/addons/ThemeWSR/StylePanel.js
  .storybook/addons/ThemeWSR/index.js
  src/Button/Button.st.css
  src/Foundation/stylable/border.st.css
  src/Input/Input.st.css
  src/ThemeProvider/ThemeProvider.js
  src/ThemeProvider/index.d.ts
Labels: PR: unreviewed

#6538 <InputWithOptions/> - fix highlighting for builder options
  perfer.config.js
  src/InputWithOptions/HighlightContext.js
  src/InputWithOptions/InputWithOptions.driver.d.ts
  src/InputWithOptions/InputWithOptions.driver.js
  src/InputWithOptions/InputWithOptions.js
  src/InputWithOptions/InputWithOptions.uni.driver.d.ts
  src/InputWithOptions/InputWithOptions.uni.driver.js
  src/InputWithOptions/test/InputWithOptions.spec.js
  src/InputWithOptions/test/InputWithOptions.visual.js
  src/ListItemSelect/ListItemSelect.js
  src/ListItemSelect/test/ListItemSelect.spec.js
  src/ListItemSelect/test/ListItemSelect.visual.js
Labels: PR: reviewed-approved

#6552 Release 9.67.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#6550 <Search> - fix clicking search icon to focus the input
  src/Search/Search.js
Labels: PR: reviewed-approved

#6548 AnalyticsLayouter: added rowItemsCount
  src/AnalyticsLayout/AnalyticsLayout.js
  src/AnalyticsLayout/docs/index.story.js
  src/AnalyticsLayout/index.d.ts
  stories/index.js
Labels: PR: reviewed-approved

#6553 <AtlasAddressInput/> - add onError prop for error handling
  .storybook/mocks/atlas.js
  src/AtlasAddressInput/AtlasAddressInput.js
  src/AtlasAddressInput/docs/examples.js
  src/AtlasAddressInput/docs/index.story.js
  src/AtlasAddressInput/index.d.ts
  src/AtlasAddressInput/test/AtlasAddressInput.spec.js
  src/providers/usePlacesAutocomplete/index.d.ts
  src/providers/usePlacesAutocomplete/usePlacesAutocomplete.js
  src/providers/usePlacesAutocomplete/usePlacesAutocomplete.spec.js
Labels: PR: reviewed-approved

#6549 <InputWithOptions/> - expose existing class methods in types
  src/InputWithOptions/InputWithOptions.js
  src/InputWithOptions/index.d.ts
  src/InputWithOptions/test/InputWithOptions.spec.js
Labels: PR: reviewed-approved

#6141 <SkeletonGroup/> - created new skeleton components
  .wuf/components.json
  docs/contribution/COMPONENT_STRUCTURE.md
  docs/contribution/CREATE_PR.md
  perfer.config.js
  src/Foundation/stylable/colors.st.css
  src/SkeletonCircle/SkeletonCircle.js
  src/SkeletonCircle/SkeletonCircle.meta.js
  src/SkeletonCircle/SkeletonCircle.st.css
  src/SkeletonCircle/SkeletonCircle.uni.driver.d.ts
  src/SkeletonCircle/SkeletonCircle.uni.driver.js
  src/SkeletonCircle/constants.js
  src/SkeletonCircle/index.d.ts
  src/SkeletonCircle/index.js
  src/SkeletonCircle/test/SkeletonCircle.private.uni.driver.js
  src/SkeletonCircle/test/SkeletonCircle.spec.js
  src/SkeletonCircle/test/SkeletonCircle.tsx
  src/SkeletonGroup/SkeletonGroup.js
  src/SkeletonGroup/SkeletonGroup.meta.js
  src/SkeletonGroup/SkeletonGroup.st.css
  src/SkeletonGroup/SkeletonGroup.uni.driver.d.ts
  src/SkeletonGroup/SkeletonGroup.uni.driver.js
  src/SkeletonGroup/SkeletonGroupAPI.js
  src/SkeletonGroup/constants.js
  src/SkeletonGroup/docs/examples.js
  src/SkeletonGroup/docs/index.story.js
  src/SkeletonGroup/index.d.ts
  src/SkeletonGroup/index.js
  src/SkeletonGroup/test/SkeletonGroup.private.uni.driver.js
  src/SkeletonGroup/test/SkeletonGroup.tsx
  src/SkeletonGroup/test/SkeletonGroup.visual.js
  src/SkeletonGroup/test/storySettings.js
  src/SkeletonLine/SkeletonLine.js
  src/SkeletonLine/SkeletonLine.meta.js
  src/SkeletonLine/SkeletonLine.st.css
  src/SkeletonLine/SkeletonLine.uni.driver.d.ts
  src/SkeletonLine/SkeletonLine.uni.driver.js
  src/SkeletonLine/constants.js
  src/SkeletonLine/index.d.ts
  src/SkeletonLine/index.js
  src/SkeletonLine/test/SkeletonLine.private.uni.driver.js
  src/SkeletonLine/test/SkeletonLine.spec.js
  src/SkeletonLine/test/SkeletonLine.tsx
  src/SkeletonRectangle/SkeletonRectangle.js
  src/SkeletonRectangle/SkeletonRectangle.meta.js
  src/SkeletonRectangle/SkeletonRectangle.st.css
  src/SkeletonRectangle/SkeletonRectangle.uni.driver.d.ts
  src/SkeletonRectangle/SkeletonRectangle.uni.driver.js
  src/SkeletonRectangle/constants.js
  src/SkeletonRectangle/index.d.ts
  src/SkeletonRectangle/index.js
  src/SkeletonRectangle/test/SkeletonRectangle.private.uni.driver.js
  src/SkeletonRectangle/test/SkeletonRectangle.spec.js
  src/SkeletonRectangle/test/SkeletonRectangle.tsx
  src/colors.scss
  src/index.d.ts
  src/index.js
  stories/index.js
Labels: PR: reviewed-approved

#6528 <SelectorList/> - add visual tests
  src/SelectorList/constants.js
  src/SelectorList/test/SelectorList.visual.js
Labels: PR: reviewed-approved

#6543 <PopoverMenu/> - pass isOpen prop to triggerElement
  src/DropdownBase/index.d.ts
  src/PopoverMenu/PopoverMenu.js
  src/PopoverMenu/index.d.ts
Labels: PR: unreviewed

#6558 perfer - increase threshold for composersidebar and listitemaction
  perfer.config.js
Labels: PR: unreviewed

#6560 <ListItemAction/> - allow events on disabled
  src/ListItemAction/ListItemAction.st.css
Labels: PR: unreviewed

#6494 <FloatingNotification/> - migration to stylable
  src/FloatingNotification/FloatingNotification.js
  src/FloatingNotification/FloatingNotification.scss
  src/FloatingNotification/FloatingNotification.st.css
Labels: PR: reviewed-approved

#6564 Stylable migration
  src/ModalSelectorLayout/ModalSelectorLayout.js
  src/ModalSelectorLayout/ModalSelectorLayout.scss
  src/ModalSelectorLayout/ModalSelectorLayout.st.css
  src/MultiSelect/MultiSelect.js
  src/MultiSelect/MultiSelect.st.css
  src/MultiSelectCheckbox/MultiSelectCheckbox.js
  src/MultiSelectCheckbox/MultiSelectCheckbox.st.css
  src/Selector/ProgressBar/ProgressBar.js
  src/Selector/ProgressBar/ProgressBar.scss
  src/Selector/ProgressBar/ProgressBar.st.css
  src/Table/DataTable/DataTable.scss
  wallaby.js
Labels: PR: unreviewed

#6567 Themes | Business Dashboard - fix checkbox hover
  src/Themes/businessDashboard/components/Checkbox.st.css
Labels: PR: reviewed-approved, PR: unreviewed

#6570 Drag and Drop - Improve Docs PR-1
  src/DragAndDrop/docs/Introduction/FAQ.md
  src/DragAndDrop/docs/Introduction/Introduction.js
  src/DragAndDrop/docs/Introduction/Introduction.md
  src/DragAndDrop/docs/Introduction/IntroductionExample.js
  src/DragAndDrop/docs/Introduction/IntroductionExample.st.css
  src/DragAndDrop/docs/Introduction/Roadmap.md
  src/DragAndDrop/docs/index.js
  stories/index.js
Labels: PR: unreviewed

#6569 <DataPicker/> - update DatePicker testkit definition
  .wuf/testkits/definitions.js
Labels: PR: reviewed-approved

#6469 <DropdownLayout/> - support puppeteer in mouseLeave function
  src/DropdownLayout/DropdownLayout.uni.driver.js
Labels: PR: unreviewed

#6571 <Text/> - fix cursor for inner links
  src/Text/Text.st.css
Labels: PR: unreviewed

#6565 <Calendar /> - close month and year dropdown after selection
  src/Calendar/DatePickerDropdown/DatePickerDropdown.js
Labels: PR: unreviewed

#6566 <AtlasAddressInput/> - add `fallbackToManual` prop
  .storybook/mocks/atlas.js
  package.json
  src/AddressInput/AddressInput.js
  src/AddressInput/AddressInput.uni.driver.d.ts
  src/AddressInput/AddressInput.uni.driver.js
  src/AddressInput/index.d.ts
  src/AddressInput/test/AddressInput.tsx
  src/AtlasAddressInput/AtlasAddressInput.js
  src/AtlasAddressInput/docs/examples.js
  src/AtlasAddressInput/docs/index.story.js
  src/AtlasAddressInput/index.d.ts
  src/AtlasAddressInput/test/AtlasAddressInput.spec.js
  src/AtlasAddressInput/test/AtlasAddressInput.tsx
  src/providers/useAtlasClient/index.d.ts
  src/providers/useAtlasClient/useAtlasClient.js
  src/providers/useAtlasClient/useAtlasClient.spec.js
  src/providers/usePlacesAutocomplete/autocompleteClient.d.ts
  src/providers/usePlacesAutocomplete/index.d.ts
Labels: PR: unreviewed

#6563 make zIndex configurable for dragging layer
  src/NestableList/API.md
  src/NestableList/DragLayer.js
  src/NestableList/NestableList.js
Labels: PR: unreviewed

#6583 gitignore
  .gitignore
Labels: PR: unreviewed

#6582 docs(readme): readme to the root of monorepo
  README.md
Labels: Docs, PR: partially-approved, PR: unreviewed

#6587 wix-style-react: update docs links to point to nested wix-style-react package
  packages/wix-style-react/CONTRIBUTING.md
  packages/wix-style-react/README.md
  packages/wix-style-react/docs/usage/COMPONENTS_DRIVERS.md
Labels: Docs, PR: unreviewed

#6589 [wix-style-react] - fix react peerDependencies
  packages/wix-style-react/package.json
Labels: PR: unreviewed

#6568 [wix-style-react] - <MarketingLayout/>- reduce spacing
  packages/wix-style-react/src/MarketingLayout/MarketingLayout.js
  packages/wix-style-react/src/MarketingLayout/MarketingLayout.st.css
  packages/wix-style-react/src/MarketingLayout/test/MarketingLayout.visual.js
Labels: <MarketingCard/>, PR: draft, PR: reviewed-approved, PR: unreviewed, Reduced Spacing & Improved Layout

#6593 Update CHANGELOG.md
  packages/wix-style-react/CHANGELOG.md
Labels: PR: unreviewed

#6598 [wix-style-react] - Allow pass node to CardFolderTab's name
  packages/wix-style-react/src/CardFolderTabs/Tab/Tab.js
  packages/wix-style-react/src/CardFolderTabs/Tab/index.d.ts
Labels: PR: reviewed-approved

#6600 Update CHANGELOG.md
  packages/wix-style-react/CHANGELOG.md
Labels: PR: unreviewed

#6599 [wix-style-react] - VanillaTestkitParams.wrapper: `HTMLElement` -> `Element`
  packages/wix-style-react/.wuf/testkits/vanilla-typescript.template.ejs
Labels: PR: unreviewed

#6601 Update CHANGELOG.md
  packages/wix-style-react/CHANGELOG.md
Labels: PR: unreviewed

#6596 [wix-style-react] - <Badge/> - change cursor to be inherit
  packages/wix-style-react/src/Badge/Badge.st.css
Labels: PR: unreviewed

#6602 Update CHANGELOG.md
  packages/wix-style-react/CHANGELOG.md
Labels: PR: unreviewed

#6574 [wix-style-react] - Themes | Business Dashboard - CustomModalLayout - update scrollbar colors
  packages/wix-style-react/src/Themes/businessDashboard/BusinessDashboard.st.css
  packages/wix-style-react/src/Themes/businessDashboard/components/CustomModalLayout.st.css
  packages/wix-style-react/src/Themes/businessDashboard/docs/businessDashboard.story.js
  packages/wix-style-react/src/Themes/businessDashboard/docs/components/CustomModalLayout.js
  packages/wix-style-react/src/Themes/businessDashboard/test/businessDashboard.visual.js
Labels: PR: reviewed-approved, Themes - Business Dashboard

#6606 Update CHANGELOG.md
  packages/wix-style-react/CHANGELOG.md
Labels: PR: unreviewed

#6608 Update issue templates
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/ISSUE_TEMPLATE/documentation.md
Labels: PR: unreviewed

#6594 [wix-style-react] - <AddressInput/> - add highlighting
  packages/wix-style-react/src/AddressInput/AddressInput.js
  packages/wix-style-react/src/AddressInput/test/AddressInput.private.uni.driver.js
  packages/wix-style-react/src/AddressInput/test/AddressInput.visual.js
  packages/wix-style-react/src/ListItemSelect/test/ListItemSelect.spec.js
Labels: PR: unreviewed

#6611 Update CHANGELOG.md
  packages/wix-style-react/CHANGELOG.md
Labels: PR: unreviewed

#6576 [wix-style-react] - Themes | Business Dashboard - Text - add error skin override
  packages/wix-style-react/src/Themes/businessDashboard/components/Text.st.css
  packages/wix-style-react/src/Themes/businessDashboard/components/TextButton.st.css
  packages/wix-style-react/src/Themes/businessDashboard/docs/components/Text.js
  packages/wix-style-react/src/Themes/businessDashboard/docs/components/TextButton.js
Labels: PR: unreviewed, Themes - Business Dashboard

#6612 Update CHANGELOG.md
  packages/wix-style-react/CHANGELOG.md
Labels: PR: unreviewed

#6613 [wix-style-react] - Release 9.70.0
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
Labels: PR: unreviewed

#6597 [wix-style-react] - <Accordion/> - Remove last item bottom shadow
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/src/Accordion/Accordion.js
  packages/wix-style-react/src/Accordion/AccordionItem/AccordionItem.js
  packages/wix-style-react/src/Accordion/AccordionItem/AccordionItem.st.css
  packages/wix-style-react/src/Accordion/test/Accordion.visual.js
Labels: PR: unreviewed

#6410 [wix-style-react] - <CarouselWIP/> - add new component
  packages/wix-style-react/.wuf/components.json
  packages/wix-style-react/.wuf/testkits/definitions.js
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/perfer.config.js
  packages/wix-style-react/src/CarouselWIP/CarouselWIP.driver.d.ts
  packages/wix-style-react/src/CarouselWIP/CarouselWIP.driver.js
  packages/wix-style-react/src/CarouselWIP/CarouselWIP.js
  packages/wix-style-react/src/CarouselWIP/CarouselWIP.meta.js
  packages/wix-style-react/src/CarouselWIP/CarouselWIP.st.css
  packages/wix-style-react/src/CarouselWIP/CarouselWIP.uni.driver.d.ts
  packages/wix-style-react/src/CarouselWIP/CarouselWIP.uni.driver.js
  packages/wix-style-react/src/CarouselWIP/Control/Control.js
  packages/wix-style-react/src/CarouselWIP/Control/index.js
  packages/wix-style-react/src/CarouselWIP/Slide/Slide.js
  packages/wix-style-react/src/CarouselWIP/Slide/index.js
  packages/wix-style-react/src/CarouselWIP/constants.js
  packages/wix-style-react/src/CarouselWIP/docs/examples.js
  packages/wix-style-react/src/CarouselWIP/docs/index.story.js
  packages/wix-style-react/src/CarouselWIP/index.d.ts
  packages/wix-style-react/src/CarouselWIP/index.js
  packages/wix-style-react/src/CarouselWIP/test/CarouselWIP.private.driver.js
  packages/wix-style-react/src/CarouselWIP/test/CarouselWIP.private.uni.driver.js
  packages/wix-style-react/src/CarouselWIP/test/CarouselWIP.spec.js
  packages/wix-style-react/src/CarouselWIP/test/CarouselWIP.tsx
  packages/wix-style-react/src/CarouselWIP/test/CarouselWIP.visual.js
  packages/wix-style-react/src/CarouselWIP/test/storySettings.js
  packages/wix-style-react/src/CarouselWIP/utils.js
  packages/wix-style-react/src/index.d.ts
  packages/wix-style-react/src/index.js
  packages/wix-style-react/stories/index.js
Labels: PR: unreviewed, Rebase Required, WIP

#6609 [wix-style-react] - <Page/>- reduce spacing
  packages/wix-style-react/src/Page/Page.js
  packages/wix-style-react/src/Page/Page.st.css
Labels: <Page/>, PR: reviewed-approved, PR: unreviewed, Reduced Spacing & Improved Layout

#6592 [wix-style-react] <Card.Subheader/>- reduce spacing phase 2
  packages/wix-style-react/src/Card/Subheader/Subheader.st.css
Labels: <Card/>, PR: reviewed-approved, PR: unreviewed, Reduced Spacing & Improved Layout

#6556 [wix-style-react] - <Modal /> introduced screen prop for spacing between viewport and modal content
  packages/wix-style-react/src/Modal/Modal.js
  packages/wix-style-react/src/Modal/Modal.st.css
  packages/wix-style-react/src/Modal/test/Modal.visual.js
Labels: PR: reviewed-approved

#6616 [wix-style-react] Update CHANGELOG.md for added modal screen prop
  packages/wix-style-react/CHANGELOG.md
Labels: PR: unreviewed

#6610 [wix-style-react] - <Calendar/> - Head - add aria-label and aria-labelledby to arrows
  packages/wix-style-react/src/Calendar/Calendar.js
  packages/wix-style-react/src/Calendar/DatePickerHead/DatePickerHead.js
  packages/wix-style-react/src/Calendar/index.d.ts
  packages/wix-style-react/src/Calendar/test/Calendar.tsx
Labels: PR: unreviewed

#6572 [wix-style-react] - <Calendar/> - add a11y attributes to month and year dropdown
  packages/wix-style-react/src/Calendar/Calendar.js
  packages/wix-style-react/src/Calendar/DatePickerDropdown/DatePickerDropdown.js
  packages/wix-style-react/src/Calendar/DatePickerDropdown/DatePickerDropdown.st.css
  packages/wix-style-react/src/Calendar/DatePickerHead/DatePickerHead.js
  packages/wix-style-react/src/Calendar/DatePickerHead/MonthDropdown/MonthDropdown.js
  packages/wix-style-react/src/Calendar/DatePickerHead/YearDropdown/YearDropdown.js
  packages/wix-style-react/src/Calendar/index.d.ts
  packages/wix-style-react/src/Calendar/test/Calendar.tsx
  packages/wix-style-react/src/DropdownLayout/DropdownLayout.js
  packages/wix-style-react/src/TextButton/TextButton.js
  packages/wix-style-react/src/TextButton/index.d.ts
  packages/wix-style-react/src/TextButton/test/TextButton.tsx
Labels: PR: unreviewed

#6575 [wix-style-react] - Themes | Business Dashboard - Thumbnail - Update box-shadow style on selected
  packages/wix-style-react/src/Themes/businessDashboard/components/Thumbnail.st.css
  packages/wix-style-react/src/Themes/businessDashboard/docs/components/Thumbnail.js
Labels: PR: reviewed-approved, Themes - Business Dashboard

#6586 [wix-style-react] - <Input /> - improved chrome autofill styles
  packages/wix-style-react/src/Input/Input.st.css
Labels: PR: unreviewed

#6627 [wix-style-react] - <Input/> - Update CHANGELOG.md for fixed chrome autofill styles
  packages/wix-style-react/CHANGELOG.md
Labels: PR: unreviewed

#6617 [wix-style-react] - <Modal/> - update storybook examples
  packages/wix-style-react/src/AnnouncementModalLayout/docs/examples/SimpleExample.js
  packages/wix-style-react/src/AnnouncementModalLayout/docs/index.story.js
  packages/wix-style-react/src/CustomModalLayout/docs/examples/MarketingExample.js
  packages/wix-style-react/src/CustomModalLayout/docs/examples/ModalExample.js
  packages/wix-style-react/src/CustomModalLayout/docs/examples/PageExample.js
  packages/wix-style-react/src/CustomModalLayout/docs/index.story.js
  packages/wix-style-react/src/MessageModalLayout/docs/examples/SimpleExample.js
  packages/wix-style-react/src/MessageModalLayout/docs/index.story.js
  packages/wix-style-react/src/Modal/docs/examples/SimpleExample.js
Labels: PR: reviewed-approved

#6624 [wix-style-react] extract `test-runtime` into dedicated package
  packages/wix-style-react-test-runtime/.eslintignore
  packages/wix-style-react-test-runtime/.gitignore
  packages/wix-style-react-test-runtime/.storybook/component-definitions.js
  packages/wix-style-react-test-runtime/.storybook/config.js
  packages/wix-style-react-test-runtime/.storybook/es-named.story.js
  packages/wix-style-react-test-runtime/.storybook/webpack.config.js
  packages/wix-style-react-test-runtime/index.js
  packages/wix-style-react-test-runtime/jest-yoshi.config.js
  packages/wix-style-react-test-runtime/package.json
  packages/wix-style-react-test-runtime/pom.xml
  packages/wix-style-react-test-runtime/src/cjs/App.js
  packages/wix-style-react-test-runtime/src/cjs/index.js
  packages/wix-style-react-test-runtime/src/es-named/App.js
  packages/wix-style-react-test-runtime/src/es-named/index.js
  packages/wix-style-react-test-runtime/src/es/App.js
  packages/wix-style-react-test-runtime/src/es/index.js
  packages/wix-style-react-test-runtime/src/index.vm
  packages/wix-style-react-test-runtime/src/puppeteer-testkit/App.js
  packages/wix-style-react-test-runtime/src/puppeteer-testkit/index.js
  packages/wix-style-react-test-runtime/test/dist-presence.spec.js
  packages/wix-style-react-test-runtime/test/e2e/cjs.e2e.js
  packages/wix-style-react-test-runtime/test/e2e/es-named.e2e.js
  packages/wix-style-react-test-runtime/test/e2e/es.e2e.js
  packages/wix-style-react-test-runtime/test/e2e/puppeteer-testkit.e2e.js
  packages/wix-style-react-test-runtime/tsconfig.declarations.json
  packages/wix-style-react-test-runtime/velocity.data.json
  packages/wix-style-react-test-runtime/vm.js
  packages/wix-style-react/package.json
  packages/wix-style-react/test-runtime/imports/package.json
Labels: Infrastructure, PR: unreviewed

#6628 useCopyClipboard - introduce browser api polyfills to cover CopyClipboard in JSDOM
  packages/wix-style-react/src/CopyClipboard/docs/index.story.js
  packages/wix-style-react/src/providers/useCopyClipboard/createToggleSelection.js
  packages/wix-style-react/src/providers/useCopyClipboard/test/useCopyClipboard.spec.js
  packages/wix-style-react/src/providers/useCopyClipboard/useCopyClipboard.js
  packages/wix-style-react/testkit/polyfills/execCommand-behavior.js
  packages/wix-style-react/testkit/polyfills/index.js
  packages/wix-style-react/testkit/polyfills/range.js
Labels: PR: reviewed-approved

#6629 [wix-style-react] - Release 9.72.0
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
Labels: PR: unreviewed

#6619 <Calendar /> - Add role="alert" to the wrapper container in Header
  packages/wix-style-react/src/Calendar/DatePickerHead/DatePickerHead.js
  packages/wix-style-react/src/Calendar/DatePickerHead/DatePickerHead.st.css
Labels: PR: unreviewed

#6622 [wix-style-react] - Themes | Business Dashboard - LinearProgressBar error state
  packages/wix-style-react/src/Themes/businessDashboard/components/LinearProgressBar.st.css
  packages/wix-style-react/src/Themes/businessDashboard/docs/components/LinearProgressBar.js
Labels: PR: reviewed-approved, Themes - Business Dashboard

#6554 [wix-style-react] - Themes | Business Dashboard - Tag - Set override only for lightOutlined and medium
  packages/wix-style-react/src/Themes/businessDashboard/components/Tag.st.css
  packages/wix-style-react/src/Themes/businessDashboard/docs/components/Tag.js
Labels: PR: unreviewed, Rebase Required, Themes - Business Dashboard

#6585 [wix-style-react] - <Sidebar /> add data-hook to onScreen children content
  packages/wix-style-react/src/Sidebar/Sidebar.js
Labels: PR: reviewed-approved

#6630 [wix-style-react] - <DatePicker /> - add aria labels props and pass them to the Calendar
  packages/wix-style-react/src/DatePicker/DatePicker.js
  packages/wix-style-react/src/DatePicker/test/DatePicker.tsx
Labels: PR: reviewed-approved

#6631 [wix-style-react] - <Calendar /> - fix arrows ariaLabel props in header
  packages/wix-style-react/src/Calendar/Calendar.js
  packages/wix-style-react/src/Calendar/DatePickerHead/DatePickerHead.js
  packages/wix-style-react/src/Calendar/test/Calendar.tsx
Labels: PR: reviewed-approved

#6595 [wix-style-react] - Themes | Business Dashboard - VerticalTabsItem update
  packages/wix-style-react/src/Themes/businessDashboard/components/VerticalTabsItem.st.css
  packages/wix-style-react/src/Themes/businessDashboard/docs/components/VerticalTabsItem.js
Labels: PR: reviewed-approved, Themes - Business Dashboard

#6633 [wix-style-react] - <Calendar /> - Add aria label to weekdayElement
  packages/wix-style-react/src/Calendar/Calendar.driver.js
  packages/wix-style-react/src/Calendar/Calendar.js
  packages/wix-style-react/src/Calendar/Calendar.uni.driver.js
Labels: PR: reviewed-approved

#6625 [wix-style-react] - <AtlasAddressInput/> - rename `fallbackToManual` to selectOnSubmit
  packages/wix-style-react/src/AtlasAddressInput/AtlasAddressInput.js
  packages/wix-style-react/src/AtlasAddressInput/index.d.ts
  packages/wix-style-react/src/AtlasAddressInput/test/AtlasAddressInput.spec.js
  packages/wix-style-react/src/AtlasAddressInput/test/AtlasAddressInput.tsx
Labels: PR: unreviewed

#6634 [wix-style-react] - <Sidebar/> - fix gradient for inner menu
  packages/wix-style-react/src/Sidebar/Sidebar.js
  packages/wix-style-react/src/Sidebar/SidebarContentWrapper.js
  packages/wix-style-react/src/Sidebar/test/Sidebar.e2e.js
  packages/wix-style-react/src/Sidebar/test/Sidebar.e2eStory.js
  packages/wix-style-react/src/Sidebar/test/storySettings.js
Labels: PR: reviewed-approved

#6614 [wix-style-react] - <CounterBadge/> - Add light skin and shadow prop
  packages/wix-style-react/src/CounterBadge/CounterBadge.js
  packages/wix-style-react/src/CounterBadge/CounterBadge.st.css
  packages/wix-style-react/src/CounterBadge/docs/examples.js
  packages/wix-style-react/src/CounterBadge/docs/index.story.js
  packages/wix-style-react/src/CounterBadge/index.d.ts
  packages/wix-style-react/src/CounterBadge/test/CounterBadge.tsx
  packages/wix-style-react/src/CounterBadge/test/CounterBadge.visual.js
Labels: PR: reviewed-approved

#6636 release 9.73.0
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
Labels: PR: unreviewed

#6621 [wix-style-react]- <BaseModalLayout/> - reduce spacing
  packages/wix-style-react/src/AnnouncementModalLayout/test/AnnouncementModalLayout.visual.js
  packages/wix-style-react/src/BaseModalLayout/LayoutBlocks/Header/ModalHeading/ModalHeading.js
  packages/wix-style-react/src/CustomModalLayout/test/CustomModalLayout.visual.js
  packages/wix-style-react/src/MessageModalLayout/test/MessageModalLayout.visual.js
Labels: <BaseModalLayout/>, PR: draft, PR: reviewed-approved, PR: unreviewed, Reduced Spacing & Improved Layout

#6615 [wix-style-react] <Accodrion/> - reduce spacing
  packages/wix-style-react/src/Accordion/AccordionItem/AccordionItem.js
  packages/wix-style-react/src/Accordion/AccordionItem/AccordionItem.st.css
  packages/wix-style-react/src/Accordion/test/Accordion.visual.js
Labels: <Accordion/>, PR: draft, PR: unreviewed, Reduced Spacing & Improved Layout

#6637 [wix-style-react] - <Badge/> and <CounterBadge/> - fix swedish letters get cut
  packages/wix-style-react/src/Badge/Badge.st.css
  packages/wix-style-react/src/Text/Caption.st.css
  packages/wix-style-react/src/Themes/businessDashboard/components/Badge.st.css
Labels: PR: unreviewed

#6620 [wix-style-react] - <InputWithOptions/> - fix onBlur is called when selecting an option with the cursor
  packages/wix-style-react/src/DropdownLayout/DropdownLayout.js
  packages/wix-style-react/src/InputWithOptions/InputWithOptions.js
  packages/wix-style-react/src/InputWithOptions/docs/storySettings.js
  packages/wix-style-react/src/InputWithOptions/docs/tests/TestFocus.js
  packages/wix-style-react/src/InputWithOptions/docs/tests/TestTabSwitches.js
  packages/wix-style-react/src/InputWithOptions/test/InputWithOptions.e2e.js
  packages/wix-style-react/src/InputWithOptions/test/InputWithOptions.e2eStory.js
  packages/wix-style-react/src/InputWithOptions/test/InputWithOptions.spec.js
  packages/wix-style-react/src/MultiSelect/InputWithTags.js
  packages/wix-style-react/src/MultiSelect/MultiSelect.js
Labels: PR: unreviewed

#6604 [wix-style-react] - <AddressInput/> - improve docs
  packages/wix-style-react/src/AddressInput/docs/examples.js
  packages/wix-style-react/src/AddressInput/docs/index.story.js
  packages/wix-style-react/src/AddressInputItem/docs/index.story.js
  packages/wix-style-react/src/AddressInputItem/test/storySettings.js
  packages/wix-style-react/src/AtlasAddressInput/docs/MIGRATION.md
  packages/wix-style-react/src/AtlasAddressInput/docs/index.story.js
  packages/wix-style-react/src/AtlasAddressInput/test/storySettings.js
  packages/wix-style-react/src/GoogleAddressInput/docs/index.story.js
  packages/wix-style-react/stories/utils/allComponents.js
Labels: Docs, PR: unreviewed

#6580 [wix-style-react] - <DatePicker/> - fix onChange triggered by getNthDayOfTheMonth method of calender unidriver
  packages/wix-style-react/src/Calendar/Calendar.driver.js
  packages/wix-style-react/src/Calendar/Calendar.uni.driver.js
  packages/wix-style-react/src/DatePicker/test/DatePicker.spec.js
Labels: PR: unreviewed, Rebase Required

#6605 [wix-style-react] - <Calendar/> - change the header navigation order
  packages/wix-style-react/src/Calendar/DatePickerHead/DatePickerHead.js
  packages/wix-style-react/src/Calendar/DatePickerHead/DatePickerHead.st.css
Labels: PR: reviewed-approved

#6626 [wix-style-react] - <Modal/> - added migration guide for screen prop
  packages/wix-style-react/src/Modal/docs/MIGRATION.md
  packages/wix-style-react/src/ModalMobileLayout/docs/MIGRATION.md
  packages/wix-style-react/src/ModalPreviewLayout/docs/MIGRATION.md
Labels: PR: unreviewed

#6639 [wix-style-react] chore(package.json): add more parallel builds
  package.json
Labels: Infrastructure, PR: unreviewed

#6643 <Calendar/> - Calendar fix warning
  packages/wix-style-react/src/Calendar/Calendar.js
Labels: PR: unreviewed

#6644 Minor semicolon fix in Stylable file
  packages/wix-style-react/src/Modal/Modal.st.css
Labels: PR: unreviewed

#6646 [wix-style-react] - <Input/> - remove redundant `withSelection` prop
  packages/wix-style-react/src/Input/Input.js
  packages/wix-style-react/src/Input/index.d.ts
Labels: PR: reviewed-approved

#6648 Update CHANGELOG.md
  packages/wix-style-react/CHANGELOG.md
Labels: PR: unreviewed

#6640 [wix-style-react]: add wix-style-react-test-runtime to test8
  package.json
Labels: Infrastructure, PR: unreviewed

#6650 Release 9.74.0
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
Labels: PR: unreviewed

#6635 [wix-style-react] - <Calendar/> - change arrows to buttons
  packages/wix-style-react/perfer.config.js
  packages/wix-style-react/src/Calendar/Calendar.uni.driver.js
  packages/wix-style-react/src/Calendar/DatePickerHead/DatePickerHead.js
  packages/wix-style-react/src/Calendar/DatePickerHead/DatePickerHead.st.css
  packages/wix-style-react/src/IconButton/IconButton.js
  packages/wix-style-react/src/IconButton/index.d.ts
  packages/wix-style-react/src/IconButton/test/IconButton.tsx
  packages/wix-style-react/src/TextButton/TextButton.js
Labels: PR: unreviewed

#6642 [wix-style-react] - stylelint for unsupported browsers
  .vscode/extensions.json
  .vscode/settings.json
  packages/wix-style-react/.stylelintrc.json
  packages/wix-style-react/README.md
  packages/wix-style-react/package.json
Labels: PR: reviewed-approved

#6590 [wix-style-react]- <Card/> reduce spacing
  packages/wix-style-react/src/Card/Card.visual.js
  packages/wix-style-react/src/Card/Content/Content.js
  packages/wix-style-react/src/Card/Content/Content.st.css
  packages/wix-style-react/src/Card/Header/Header.js
  packages/wix-style-react/src/Card/Header/Header.st.css
Labels: <Card/>, PR: reviewed-approved, PR: unreviewed, Reduced Spacing & Improved Layout

#6654 [wix-style-react] - <Search/> - fix flaky e2e test
  packages/wix-style-react/src/Search/Search.protractor.driver.js
  packages/wix-style-react/src/Search/test/Search.e2e.js
Labels: PR: reviewed-approved

#6653 [wix-style-react] - <InputWithOptions/> - don't call onFocus when re-focusing input after selecting option
  packages/wix-style-react/src/InputWithOptions/InputWithOptions.js
  packages/wix-style-react/src/InputWithOptions/test/InputWithOptions.spec.js
Labels: PR: reviewed-approved

#6658 Release 9.74.1
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
Labels: PR: unreviewed

#6657 [wix-style-react] - <CarouselWIP/> - sides gradient width to 30px
  packages/wix-style-react/src/CarouselWIP/CarouselWIP.st.css
Labels: PR: reviewed-approved

#6661 [wix-style-react] <StatisticWidget/>- reduce spacing
  packages/wix-style-react/package.json
  packages/wix-style-react/src/StatisticsWidget/StatisticsItem/StatisticsItem.js
  packages/wix-style-react/src/StatisticsWidget/StatisticsItem/StatisticsItem.st.css
  packages/wix-style-react/src/StatisticsWidget/test/StatisticsWidget.spec.js
  packages/wix-style-react/src/StatisticsWidget/test/StatisticsWidget.visual.js
Labels: PR: reviewed-approved, Reduced Spacing & Improved Layout

#6660 [wix-style-react] - <CarouselWIP/> - fix storybook issue
  packages/wix-style-react/src/CarouselWIP/CarouselWIP.js
  packages/wix-style-react/src/CarouselWIP/docs/examples.js
  packages/wix-style-react/src/CarouselWIP/docs/index.story.js
Labels: PR: unreviewed
