Repository wix/wix-style-react, pull requests merged in 2021-03, with the labels that each got.

#6846 <Calendar /> - fix behavior when focusing on header and pressing arrow down or arrow up
  packages/wix-style-react/src/Calendar/Calendar.js
  packages/wix-style-react/src/Calendar/DatePickerHead/DatePickerHead.js
Labels: PR: unreviewed, WSR

#6824 <Calendar/> - Add the missing locales
  packages/wix-style-react/perfer.config.js
  packages/wix-style-react/src/Calendar/Calendar.js
  packages/wix-style-react/src/Calendar/index.d.ts
  packages/wix-style-react/src/CalendarPanel/index.d.ts
  packages/wix-style-react/src/DatePicker/index.d.ts
  packages/wix-style-react/src/LocaleUtils.js
  packages/wix-ui-tpa/package.json
  packages/wix-ui-tpa/perfer.config.js
  packages/wix-ui-tpa/src/components/DatePicker/DatePicker.tsx
  packages/wix-ui-tpa/src/components/DatePickerInput/DatePickerInput.tsx
Labels: PR: reviewed-approved, WSR, WUT

#6767 Revert "Revert "<RadioGroup/> - refactor to use <Radio /> component""
  packages/wix-style-react/src/RadioGroup/RadioButton/RadioButton.js
  packages/wix-style-react/src/RadioGroup/RadioButton/RadioButton.st.css
  packages/wix-style-react/src/RadioGroup/RadioGroup.driver.js
  packages/wix-style-react/src/RadioGroup/RadioGroup.js
  packages/wix-style-react/src/RadioGroup/RadioGroup.protractor.driver.js
  packages/wix-style-react/src/RadioGroup/RadioGroup.st.css
  packages/wix-style-react/src/RadioGroup/RadioGroup.uni.driver.d.ts
  packages/wix-style-react/src/RadioGroup/RadioGroup.uni.driver.js
  packages/wix-style-react/src/RadioGroup/constants.js
  packages/wix-style-react/src/RadioGroup/sharedDriverMethods.js
  packages/wix-style-react/src/RadioGroup/test/RadioGroup.private.uni.driver.js
  packages/wix-style-react/src/RadioGroup/test/RadioGroup.spec.js
  packages/wix-style-react/src/RadioGroup/test/RadioGroup.visual.js
Labels: PR: reviewed-approved, WSR

#6786 <AddItem /> - added icon prop for illustrations
  packages/wix-style-react/perfer.config.js
  packages/wix-style-react/src/AddItem/AddItem.js
  packages/wix-style-react/src/AddItem/AddItem.st.css
  packages/wix-style-react/src/AddItem/docs/examples.js
  packages/wix-style-react/src/AddItem/docs/index.story.js
  packages/wix-style-react/src/AddItem/index.d.ts
  packages/wix-style-react/src/AddItem/test/AddItem.visual.js
  packages/wix-style-react/src/assets/generic_add_item_illustration.svg
  packages/wix-ui-tpa/perfer.config.js
  packages/wix-ui-tpa/src/components/AddItem/AddItem.st.css
Labels: PR: partially-approved, WSR, WUT

#6838 Color picker focus ring
  packages/wix-ui-tpa/src/components/ColorPicker/ColorPicker.e2e.ts
  packages/wix-ui-tpa/src/components/ColorPicker/ColorPicker.tsx
  packages/wix-ui-tpa/src/components/ColorPicker/ColorPickerItem/ColorPickerItem.st.css
  packages/wix-ui-tpa/src/components/ColorPicker/ColorPickerItem/ColorPickerItem.tsx
  packages/wix-ui-tpa/src/components/ColorPicker/docs/ColorPickerAnotherExtendedExample.tsx
  packages/wix-ui-tpa/src/components/ColorPicker/docs/ColorPickerExtendedExample.tsx
  packages/wix-ui-tpa/src/components/ColorPicker/docs/ColorPickerFocusTabExample.tsx
  packages/wix-ui-tpa/src/components/ColorPicker/docs/ColorPickerMobileTooltipExample.tsx
  packages/wix-ui-tpa/src/components/ColorPicker/docs/ColorPickerTestStory.tsx
  packages/wix-ui-tpa/src/components/ColorPicker/docs/examples.ts
  packages/wix-ui-tpa/src/components/ColorPicker/perf/ColorPickerBasic.tsx
  packages/wix-ui-tpa/src/components/ColorPicker/perf/ColorPickerExtended.tsx
  packages/wix-ui-tpa/stories/Playground/example.tsx
  packages/wix-ui-tpa/stories/testStories.ts
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, WUT

#6851 docs(DatePicker): remove from WIP
  packages/wix-ui-tpa/src/components/DatePicker/docs/index.story.tsx
Labels: PR: reviewed-approved, WUT

#6853 Relese WUT 2.26.0, WSR 9.86.0
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
  packages/wix-ui-tpa/CHANGELOG.md
  packages/wix-ui-tpa/package.json
Labels: PR: unreviewed, WSR, WUT

#6845 `<Table>` - stop propogation for disabled checkbox
  packages/wix-style-react/src/Table/Table.js
Labels: PR: reviewed-approved

#6805 Cheatsheet- update new and existing components
  packages/wix-style-react/stories/Introduction/Cheatsheet/componentsFamilies/ContentWidgetsFamily.js
  packages/wix-style-react/stories/Introduction/Cheatsheet/componentsFamilies/InternalFamily.js
  packages/wix-style-react/stories/Introduction/Cheatsheet/componentsFamilies/LayoutFamily/examples/PageExamples.js
  packages/wix-style-react/stories/Introduction/Cheatsheet/componentsFamilies/ModalFamily.js
  packages/wix-style-react/stories/Introduction/Cheatsheet/componentsFamilies/NavigationFamily.js
  packages/wix-style-react/stories/Introduction/Cheatsheet/componentsFamilies/PickerFamily.js
  packages/wix-style-react/stories/symbolsComponentsMapping/components.js
  packages/wix-style-react/stories/symbolsComponentsMapping/families/contentWidgetsFamily.js
  packages/wix-style-react/stories/symbolsComponentsMapping/families/internalComponentsFamily.js
  packages/wix-style-react/stories/symbolsComponentsMapping/families/layoutFamily.js
  packages/wix-style-react/stories/symbolsComponentsMapping/families/modalsFamily.js
  packages/wix-style-react/stories/symbolsComponentsMapping/families/navigationFamily.js
  packages/wix-style-react/stories/symbolsComponentsMapping/families/pickerFamily.js
  packages/wix-style-react/stories/symbolsComponentsMapping/symbols.js
Labels: PR: unreviewed, WSR

#6859 <Tooltip/> - fix testkit for puppeteer
  packages/wix-style-react/src/Tooltip/Tooltip.uni.driver.js
Labels: PR: reviewed-approved, WSR

#6726 add link to working-with-monorepo to the root readme.md
  README.md
Labels: Infrastructure, PR: unreviewed

#6857 move git tag script + add clone
  packages/wix-ui-tpa/package.json
Labels: PR: partially-approved, WUT

#6850 <RadioGroup/> - remove protractor driver and e2e tests
  packages/wix-style-react/.wuf/testkits/definitions.js
  packages/wix-style-react/src/RadioGroup/RadioGroup.driver.js
  packages/wix-style-react/src/RadioGroup/RadioGroup.protractor.driver.js
  packages/wix-style-react/src/RadioGroup/RadioGroup.uni.driver.js
  packages/wix-style-react/src/RadioGroup/test/RadioGroup.e2e.js
  packages/wix-style-react/src/RadioGroup/test/RadioGroup.e2eStory.js
  packages/wix-style-react/src/RadioGroup/test/RadioGroup.spec.js
Labels: PR: reviewed-approved, WSR

#6818 scss -> stylable
  packages/wix-style-react/src/CalendarPanel/CalendarPanel.js
  packages/wix-style-react/src/CalendarPanel/CalendarPanel.scss
  packages/wix-style-react/src/CalendarPanel/CalendarPanel.st.css
  packages/wix-style-react/src/ContactItemBuilder/ContactItemBuilder.js
  packages/wix-style-react/src/ContactItemBuilder/ContactItemBuilder.st.css
  packages/wix-style-react/src/FormField/FormField.st.css
  packages/wix-style-react/src/MultiSelect/InputWithTags.js
  packages/wix-style-react/src/MultiSelect/InputWithTags.scss
  packages/wix-style-react/src/MultiSelect/InputWithTags.st.css
  packages/wix-style-react/src/MultiSelect/MultiSelect.driver.js
  packages/wix-style-react/src/MultiSelect/MultiSelect.uni.driver.js
  packages/wix-style-react/src/MultiSelect/test/MultiSelect.spec.js
  packages/wix-style-react/src/Table/Table.st.css
Labels: PR: unreviewed, WSR

#6852 Drag and Drop - scss -> stylable
  packages/wix-style-react/src/DragAndDrop/docs/SortableGrid/SingleAreaGrid/SingleAreaGrid.js
  packages/wix-style-react/src/DragAndDrop/docs/SortableGrid/SingleAreaGrid/SingleAreaGrid.st.css
  packages/wix-style-react/src/DragAndDrop/docs/SortableGrid/SingleAreaGrid/index.js
  packages/wix-style-react/src/DragAndDrop/docs/SortableGrid/Styles/Styles.md
  packages/wix-style-react/src/DragAndDrop/docs/SortableList/ListWithDelay/ListWithDelay.js
  packages/wix-style-react/src/DragAndDrop/docs/SortableList/ListWithDelay/ListWithDelay.st.css
  packages/wix-style-react/src/DragAndDrop/docs/SortableList/ListWithDelay/index.js
  packages/wix-style-react/src/DragAndDrop/docs/SortableList/MultiAreaList/MultiAreaList.js
  packages/wix-style-react/src/DragAndDrop/docs/SortableList/MultiAreaList/MultiAreaList.st.css
  packages/wix-style-react/src/DragAndDrop/docs/SortableList/MultiAreaList/index.js
  packages/wix-style-react/src/DragAndDrop/docs/SortableList/MultiAreaListPreventOfDropping/MultiAreaListPreventDropping.js
  packages/wix-style-react/src/DragAndDrop/docs/SortableList/MultiAreaListPreventOfDropping/MultiAreaListPreventDropping.st.css
  packages/wix-style-react/src/DragAndDrop/docs/SortableList/MultiAreaListPreventOfDropping/index.js
  packages/wix-style-react/src/DragAndDrop/docs/SortableList/MultiAreaListWithInsertionRules/MultiAreaListWithInsertionRules.js
  packages/wix-style-react/src/DragAndDrop/docs/SortableList/MultiAreaListWithInsertionRules/MultiAreaListWithInsertionRules.st.css
  packages/wix-style-react/src/DragAndDrop/docs/SortableList/MultiAreaListWithInsertionRules/index.js
  packages/wix-style-react/src/DragAndDrop/docs/SortableList/MultiAreaListWithSortableColumns/MultiAreaListWithSortableColumns.js
  packages/wix-style-react/src/DragAndDrop/docs/SortableList/MultiAreaListWithSortableColumns/MultiAreaListWithSortableColumns.st.css
  packages/wix-style-react/src/DragAndDrop/docs/SortableList/MultiAreaListWithSortableColumns/index.js
  packages/wix-style-react/src/DragAndDrop/docs/SortableList/MultiAreaListWithSortableColumnsWithAnimations/MultiAreaListWithSortableColumnsWithAnimations.js
  packages/wix-style-react/src/DragAndDrop/docs/SortableList/MultiAreaListWithSortableColumnsWithAnimations/MultiAreaListWithSortableColumnsWithAnimations.st.css
  packages/wix-style-react/src/DragAndDrop/docs/SortableList/MultiAreaListWithSortableColumnsWithAnimations/index.js
  packages/wix-style-react/src/DragAndDrop/docs/SortableList/NestableListExample/NestableList.st.css
  packages/wix-style-react/src/DragAndDrop/docs/SortableList/NestableListExample/NestableListExample.js
  packages/wix-style-react/src/DragAndDrop/docs/SortableList/NestableListExample/index.js
  packages/wix-style-react/src/DragAndDrop/docs/SortableList/SingleAreaList/SingleAreaList.js
  packages/wix-style-react/src/DragAndDrop/docs/SortableList/SingleAreaList/SingleAreaList.st.css
  packages/wix-style-react/src/DragAndDrop/docs/SortableList/SingleAreaList/index.js
  packages/wix-style-react/src/DragAndDrop/docs/SortableList/SingleAreaListWithAnimation/SingleAreaListWithAnimation.js
  packages/wix-style-react/src/DragAndDrop/docs/SortableList/SingleAreaListWithAnimation/SingleAreaListWithAnimation.st.css
  packages/wix-style-react/src/DragAndDrop/docs/SortableList/SingleAreaListWithAnimation/index.js
  packages/wix-style-react/src/DragAndDrop/docs/SortableList/Styles/Styles.md
Labels: PR: unreviewed, WSR

#6864 Remove scss from example
  packages/wix-style-react/src/PageHeader/docs/PageHeader.scss
  packages/wix-style-react/src/PageHeader/docs/index.story.js
Labels: PR: unreviewed, WSR

#6848 <Avatar/> - fix incorrect text style
  packages/wix-style-react/src/Avatar/Avatar.st.css
  packages/wix-style-react/src/AvatarGroup/AvatarGroup.js
Labels: PR: reviewed-approved, WSR

#6862 <NoBorderInput/> - deprecate component
  packages/wix-style-react/src/NoBorderInput/NoBorderInput.js
  packages/wix-style-react/src/NoBorderInput/docs/index.story.js
  packages/wix-style-react/src/NoBorderInput/docs/storySettings.js
Labels: PR: unreviewed, WSR

#6861 <DatePicker /> - add size prop
  packages/wix-style-react/src/DatePicker/DatePicker.js
  packages/wix-style-react/src/DatePicker/docs/examples.js
  packages/wix-style-react/src/DatePicker/docs/index.story.js
  packages/wix-style-react/src/DatePicker/index.d.ts
  packages/wix-style-react/src/DatePicker/test/DatePicker.spec.js
  packages/wix-style-react/src/DatePicker/test/DatePicker.tsx
  packages/wix-style-react/src/DatePicker/test/DatePicker.visual.js
Labels: PR: reviewed-approved, WSR

#6854 Themes | Business Dashboard - Update text colors
  packages/wix-style-react/src/Themes/businessDashboard/components/Text.st.css
  packages/wix-style-react/src/Themes/businessDashboard/docs/components/Text.js
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, Themes - Business Dashboard, WSR

#6867 <Badge/> - improve visuals
  packages/wix-style-react/src/Badge/test/Badge.visual.js
Labels: PR: unreviewed, WSR

#6843 <Modal /> - story updates according new storybook guidelines
  packages/wix-style-react/src/Modal/Modal.js
  packages/wix-style-react/src/Modal/docs/examples.js
  packages/wix-style-react/src/Modal/docs/examples/ModalWithCloseButton.js
  packages/wix-style-react/src/Modal/docs/examples/SimpleExample.js
  packages/wix-style-react/src/Modal/docs/index.story.js
Labels: PR: reviewed-approved, WSR

#6856 <DatePicker /> vertical spacing & no outer padding props
  packages/wix-ui-tpa/src/components/DatePicker/DatePicker.st.css
  packages/wix-ui-tpa/src/components/DatePicker/DatePicker.tsx
  packages/wix-ui-tpa/src/components/DatePicker/DatePicker.visual.st.css
  packages/wix-ui-tpa/src/components/DatePicker/DatePicker.visual.tsx
  packages/wix-ui-tpa/src/components/DatePicker/docs/DatePickerWiringExample.st.css
  packages/wix-ui-tpa/src/components/DatePicker/docs/index.story.tsx
Labels: Contribution, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed, WUT

#6860 <PopoverMenu/> - change popover padding to 12px instead of 10px
  packages/wix-style-react/src/PopoverMenu/PopoverMenu.st.css
Labels: PR: unreviewed, WSR

#6868 `<TableListItem/>` - enable ellipsis support for value property
  packages/wix-style-react/src/TableListItem/TableListItem.st.css
  packages/wix-style-react/src/TableListItem/test/TableListItem.visual.js
Labels: PR: unreviewed, WSR

#6869 TextArea-add_width_height_variables
  packages/wix-ui-tpa/src/components/TextArea/TextArea.st.css
  packages/wix-ui-tpa/src/components/TextArea/docs/TextAreaExtendedExample.st.css
  packages/wix-ui-tpa/src/components/TextArea/docs/index.story.tsx
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, WUT

#6872 fix(DatePicker): align the arrows & allow changing font-size from the DatePicker
  packages/wix-ui-tpa/src/components/DatePicker/DatePicker.st.css
  packages/wix-ui-tpa/src/components/DatePicker/docs/index.story.tsx
  packages/wix-ui-tpa/src/components/DatePickerInput/DatePickerInput.st.css
  packages/wix-ui-tpa/src/components/DatePickerInput/docs/index.story.tsx
Labels: PR: reviewed-approved

#6875 fix(Checkbox): fixed fontFamily to avoid different alignment
  packages/wix-ui-tpa/src/components/Checkbox/Checkbox.st.css
Labels: PR: unreviewed, WUT

#6878 update perfer
  packages/wix-style-react/perfer.config.js
Labels: PR: reviewed-approved, WSR

#6855 Migrate non-scoped to scoped pacakges
  packages/wix-style-react-test-runtime/.storybook/webpack.config.js
  packages/wix-style-react-test-runtime/package.json
  packages/wix-style-react/.autotools/node-require-hooks.js
  packages/wix-style-react/.autotools/webpack.config.js
  packages/wix-style-react/.storybook/e2e/webpack.config.js
  packages/wix-style-react/.storybook/visual/webpack.config.js
  packages/wix-style-react/.storybook/webpack.config.js
  packages/wix-style-react/package.json
  packages/wix-style-react/scripts/bundlify-components/webpack.config.js
  packages/wix-style-react/wallaby.js
  packages/wix-ui-tpa/.autotools/node-require-hooks.js
  packages/wix-ui-tpa/package.json
  packages/wix-ui-tpa/tsconfig.json
  packages/wix-ui-tpa/wallaby.js
  packages/wix-ui-tpa/webpack.config.storybook.js
Labels: PR: partially-approved, WSR, WUT

#6870 <RadioButton/> - add deprecation message
  packages/wix-style-react/src/RadioGroup/RadioButton/RadioButton.js
Labels: PR: reviewed-approved, WSR

#6836 <Table/> - refactor story page
  packages/wix-style-react/src/Table/docs/examples/10_TableStickyScrollExample.js
  packages/wix-style-react/src/Table/docs/examples/11_TableToolbarExample.js
  packages/wix-style-react/src/Table/docs/examples/12_TableWithBulkSelectionExample.js
  packages/wix-style-react/src/Table/docs/examples/13_TableSubtoolbarExample.js
  packages/wix-style-react/src/Table/docs/examples/14_TableInfiniteScrollExample.js
  packages/wix-style-react/src/Table/docs/examples/15_TableInfiniteScrollAndBulkSelection.js
  packages/wix-style-react/src/Table/docs/examples/16_TablePaginationExample.js
  packages/wix-style-react/src/Table/docs/examples/17_TableEmptyStateExample.js
  packages/wix-style-react/src/Table/docs/examples/18_TableVerticalCellAlignmentExample.js
  packages/wix-style-react/src/Table/docs/examples/19_TableStickyToolbarExample.js
  packages/wix-style-react/src/Table/docs/examples/1_TableStructureExample.js
  packages/wix-style-react/src/Table/docs/examples/20_TableWithAdvancedFiltersExample.js
  packages/wix-style-react/src/Table/docs/examples/21_TableVirtualizationExample.js
  packages/wix-style-react/src/Table/docs/examples/2_TableSkinExample.js
  packages/wix-style-react/src/Table/docs/examples/3_TableRowVerticalPaddingExample.js
  packages/wix-style-react/src/Table/docs/examples/4_TableHighlightedRowsExample.js
  packages/wix-style-react/src/Table/docs/examples/5_TableExpandableRowsExample.js
  packages/wix-style-react/src/Table/docs/examples/6_TableWithUnselectableRowsExample.js
  packages/wix-style-react/src/Table/docs/examples/7_TableActionCellExample.js
  packages/wix-style-react/src/Table/docs/examples/8_TableColumnAlignmentAndWidthExample.js
  packages/wix-style-react/src/Table/docs/examples/9_TableImportantColumnExample.js
  packages/wix-style-react/src/Table/docs/examples/TableActionCellExample.js
  packages/wix-style-react/src/Table/docs/examples/TableAlignedColumnsExample.js
  packages/wix-style-react/src/Table/docs/examples/TableBulkSelectionCheckboxExample.js
  packages/wix-style-react/src/Table/docs/examples/TableEmptyStateExample.js
  packages/wix-style-react/src/Table/docs/examples/TableExample.js
  packages/wix-style-react/src/Table/docs/examples/TableHideHeaderExample.js
  packages/wix-style-react/src/Table/docs/examples/TableHighlightedRowsExample.js
  packages/wix-style-react/src/Table/docs/examples/TableInfiniteScrollExample.js
  packages/wix-style-react/src/Table/docs/examples/TableInfiniteScrollWithBulkSelectionExample.js
  packages/wix-style-react/src/Table/docs/examples/TablePageExample.js
  packages/wix-style-react/src/Table/docs/examples/TableRowDetailsExample.js
  packages/wix-style-react/src/Table/docs/examples/TableSkinNeutralExample.js
  packages/wix-style-react/src/Table/docs/examples/TableStickyScrollExample.js
  packages/wix-style-react/src/Table/docs/examples/TableSubToolbarExample.js
  packages/wix-style-react/src/Table/docs/examples/TableToolbarExample.js
  packages/wix-style-react/src/Table/docs/examples/TableVirtualizationExample.js
  packages/wix-style-react/src/Table/docs/examples/TableWithUnselectableRowsExample.js
  packages/wix-style-react/src/Table/docs/index.story.js
  packages/wix-style-react/stories/utils/createFetchEndpoint.js
Labels: PR: unreviewed, WSR

#6874 <Table/> - migrate to stylable
  packages/wix-style-react/src/Table/DataTable/DataTable.driver.js
  packages/wix-style-react/src/Table/DataTable/DataTable.js
  packages/wix-style-react/src/Table/DataTable/DataTable.scss
  packages/wix-style-react/src/Table/DataTable/DataTable.st.css
  packages/wix-style-react/src/Table/DataTable/DataTable.uni.driver.js
  packages/wix-style-react/src/Table/DataTable/DataTable.utils.js
  packages/wix-style-react/src/Table/DataTable/test/DataTable.spec.js
Labels: PR: unreviewed, WSR

#6884 [wix-ui-tpa] Fix bundle sizes
  packages/wix-ui-tpa/perfer.config.js
Labels: PR: reviewed-approved, WUT

#6880 Dialog-add_dialogContentClassName
  packages/wix-ui-tpa/src/components/Dialog/Dialog.tsx
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, WUT

#6885 release: 9.87.0-2.27.0
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
  packages/wix-ui-tpa/CHANGELOG.md
  packages/wix-ui-tpa/package.json
Labels: PR: partially-approved, WSR, WUT

#6887 dropdown missing default state EE-29772
  packages/wix-ui-tpa/src/components/Dropdown/Dropdown.st.css
Labels: Contribution, PR: unreviewed, WUT

#6819 hoist dev dependencies to the root package.json
  lerna.json
  package.json
  packages/wix-style-react-test-runtime/package.json
  packages/wix-style-react-test-runtime/tsconfig.declarations.json
  packages/wix-style-react/package.json
  packages/wix-style-react/src/Stepper/test/Stepper.spec.js
  packages/wix-ui-tpa/package.json
  packages/wix-ui-tpa/stories/helperComponents/baseUI.global.scss
  packages/wix-ui-tpa/tsconfig.json
  scripts/post-install.sh
Labels: PR: unreviewed, WSR, WUT, wip

#6893 add `npm run reinstall` script
  package.json
  scripts/reinstall.sh
Labels: Infrastructure, PR: unreviewed

#6865 <SectionHelper/> - fix close button position while no title
  packages/wix-style-react/src/SectionHelper/SectionHelper.st.css
Labels: PR: unreviewed, WSR

#6895 <InputWithOptions/> - use props.value for highlighting
  packages/wix-style-react/src/InputWithOptions/InputWithOptions.js
Labels: Bug, Contribution, PR: reviewed-approved, PR: unreviewed, WSR

#6883 <Accordion/> - fix item header on hover
  packages/wix-style-react/src/Accordion/AccordionItem/AccordionItem.st.css
Labels: PR: unreviewed, WSR

#6897 Storybook stories - phase 2 - facelift
  package.json
  packages/wix-style-react/package.json
  packages/wix-ui-tpa/package.json
Labels: PR: unreviewed, WSR, WUT

#6899 fetch tags in release-script
  scripts/unified-release.js
Labels: PR: reviewed-approved

#6882 <Checkbox/> - fix label when disabled
  packages/wix-style-react/src/Checkbox/Checkbox.js
Labels: PR: unreviewed, WSR

#6873 <inputWithOptions/> - fix onfocus triggered twice when suffix icon is clicked
  packages/wix-style-react/src/Input/Input.js
  packages/wix-style-react/src/Input/test/Input.spec.js
Labels: PR: unreviewed, WSR

#6906 update reinstall script to not use lerna
  scripts/reinstall.sh
Labels: Infrastructure, PR: unreviewed

#6901 Fix Stylable warnings
  packages/wix-style-react/src/CheckToggle/CheckToggle.st.css
  packages/wix-style-react/src/Foundation/stylable/typography.st.css
Labels: PR: unreviewed, WSR

#6881 <RadioGroup/> - make arrows navigate between radio items
  packages/wix-style-react/src/RadioGroup/RadioGroup.js
  packages/wix-style-react/src/RadioGroup/docs/examples.js
  packages/wix-style-react/src/RadioGroup/docs/index.story.js
Labels: PR: reviewed-approved, WSR

#6907 Release/9.87.1 2.27.1
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
  packages/wix-ui-tpa/CHANGELOG.md
  packages/wix-ui-tpa/package.json
Labels: PR: unreviewed, WSR, WUT

#6908 <ModalPreviewLayout/>- fix white tooltip background color
  packages/wix-style-react/src/ModalPreviewLayout/ModalPreviewLayout.st.css
Labels: Bug, PR: unreviewed, WSR

#6905 <Skeleton/> - deprecate component
  packages/wix-style-react/src/Skeleton/Skeleton.js
  packages/wix-style-react/src/Skeleton/docs/index.story.js
Labels: PR: unreviewed, WSR

#6831 <TableActionCell/> - Add primaryAction icon affixes
  packages/wix-style-react/src/TableActionCell/TableActionCell.driver.d.ts
  packages/wix-style-react/src/TableActionCell/TableActionCell.driver.js
  packages/wix-style-react/src/TableActionCell/TableActionCell.js
  packages/wix-style-react/src/TableActionCell/TableActionCell.uni.driver.d.ts
  packages/wix-style-react/src/TableActionCell/TableActionCell.uni.driver.js
  packages/wix-style-react/src/TableActionCell/index.d.ts
  packages/wix-style-react/src/TableActionCell/test/TableActionCell.spec.js
  packages/wix-style-react/src/TableActionCell/test/TableActionCell.visual.js
Labels: Contribution, Feature, PR: partially-approved, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed, WSR

#6896 Removed Grid usages from library
  packages/wix-style-react/src/BounceAnimation/docs/examples.js
  packages/wix-style-react/src/Card/Card.visual.js
  packages/wix-style-react/src/Card/docs/index.story.js
  packages/wix-style-react/src/ComposerSidebar/docs/examples.js
  packages/wix-style-react/src/CustomModalLayout/docs/examples/PageExample.js
  packages/wix-style-react/src/EditableSelector/docs/examples.js
  packages/wix-style-react/src/FormField/docs/examples.js
  packages/wix-style-react/src/FormField/docs/index.story.js
  packages/wix-style-react/src/Page/docs/examples.js
  packages/wix-style-react/src/Proportion/docs/examples.js
  packages/wix-style-react/src/PulseAnimation/docs/examples.js
  packages/wix-style-react/src/SectionHelper/docs/examples.js
  packages/wix-style-react/src/SkeletonGroup/docs/examples.js
  packages/wix-style-react/src/SkeletonGroup/docs/index.story.js
  packages/wix-style-react/src/ToggleButton/docs/examples.js
  packages/wix-style-react/stories/CardLayout/EmptyStateExample.js
  packages/wix-style-react/stories/CardLayout/FormExample.js
  packages/wix-style-react/stories/Introduction/Cheatsheet/ComponentsCheatsheet.js
  packages/wix-style-react/stories/Introduction/Cheatsheet/componentsFamilies/ContentWidgetsFamily.js
  packages/wix-style-react/stories/Introduction/Cheatsheet/componentsFamilies/LayoutFamily/examples/PageExamples.js
  packages/wix-style-react/stories/Introduction/Cheatsheet/componentsFamilies/ModalFamily.js
  packages/wix-style-react/stories/Introduction/Cheatsheet/sharedComponents/FamilyStructure.js
  packages/wix-style-react/stories/Introduction/Cheatsheet/sharedComponents/SingleComponentSideBySide.js
  packages/wix-style-react/stories/Introduction/Cheatsheet/sharedComponents/SingleComponentStacked.js
  packages/wix-style-react/stories/MultiSelect/index.story.js
  packages/wix-style-react/stories/PageLayout/ExampleEmptyState.js
  packages/wix-style-react/stories/PageLayout/ExampleGalleryLayout.js
  packages/wix-style-react/stories/PageLayout/ExampleGeneralLayout.js
  packages/wix-style-react/stories/PageLayout/ExampleSplitLayout.js
  packages/wix-style-react/stories/Spacing/index.story.js
  packages/wix-style-react/test/utils/visual/utils.js
Labels: PR: reviewed-approved, WSR

#6827 Themes | Business Dashboard - TableListItem - add theme
  packages/wix-style-react/src/TableListItem/test/TableListItem.visual.js
  packages/wix-style-react/src/Themes/businessDashboard/BusinessDashboard.st.css
  packages/wix-style-react/src/Themes/businessDashboard/components/TableListItem.st.css
  packages/wix-style-react/src/Themes/businessDashboard/docs/businessDashboard.story.js
  packages/wix-style-react/src/Themes/businessDashboard/docs/components/TableListItem.js
  packages/wix-style-react/src/Themes/businessDashboard/test/businessDashboard.visual.js
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, Themes - Business Dashboard, WSR

#6911 <Date Picker /> - Today prop
  packages/wix-style-react/src/Calendar/Calendar.js
  packages/wix-style-react/src/Calendar/index.d.ts
  packages/wix-style-react/src/Calendar/test/Calendar.visual.js
  packages/wix-ui-tpa/src/components/DatePicker/DatePicker.tsx
  packages/wix-ui-tpa/src/components/DatePicker/DatePicker.visual.tsx
  packages/wix-ui-tpa/src/components/DatePicker/docs/index.story.tsx
Labels: Contribution, PR: partially-approved, PR: unreviewed, WSR, WUT

#6871 <DatePicker /> - add readOnly prop and add examples to width prop
  packages/wix-style-react/src/DatePicker/DatePicker.js
  packages/wix-style-react/src/DatePicker/docs/examples.js
  packages/wix-style-react/src/DatePicker/docs/index.story.js
  packages/wix-style-react/src/DatePicker/index.d.ts
  packages/wix-style-react/src/DatePicker/test/DatePicker.spec.js
  packages/wix-style-react/src/DatePicker/test/DatePicker.tsx
  packages/wix-style-react/src/DatePicker/test/DatePicker.visual.js
Labels: PR: unreviewed, WSR

#6917 fix(DatePicker): fix the arrows bug
  packages/wix-ui-tpa/src/components/DatePicker/DatePicker.st.css
  packages/wix-ui-tpa/src/components/DatePickerInput/DatePickerInput.st.css
Labels: PR: reviewed-approved, WUT

#6919 Dropdown component- Adding placement prop for the error tooltip
  packages/wix-ui-tpa/src/components/Dropdown/Dropdown.tsx
  packages/wix-ui-tpa/src/components/Dropdown/DropdownError.tsx
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, WUT

#6904 <Radio/> - a11y fixed in order for screen reader to be able to read label
  packages/wix-style-react/src/Radio/Radio.js
  packages/wix-style-react/src/RadioGroup/test/RadioGroup.spec.js
Labels: PR: reviewed-approved, WSR

#6913 <SelectorList /> Add method to reload data from dataSource
  packages/wix-style-react/src/SelectorList/SelectorList.js
  packages/wix-style-react/src/SelectorList/index.d.ts
  packages/wix-style-react/src/SelectorList/test/SelectorList.spec.js
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, WSR

#6915 `<TextButton/>` - add missing proptype value for "destructive" skin
  packages/wix-style-react/src/TextButton/TextButton.js
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, WSR

#6894 Themes | Business Dashboard - Badge - Restore small badge styling override by theme
  packages/wix-style-react/src/Themes/businessDashboard/components/Badge.st.css
  packages/wix-style-react/src/Themes/businessDashboard/docs/components/Badge.js
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, Themes - Business Dashboard, WSR

#6826 `<HorizontalTimeline/>` - testkit - getLabel() method
  packages/wix-style-react/src/HorizontalTimeline/HorizontalTimeline.js
  packages/wix-style-react/src/HorizontalTimeline/HorizontalTimeline.uni.driver.js
  packages/wix-style-react/src/HorizontalTimeline/constants.js
  packages/wix-style-react/src/HorizontalTimeline/test/HorizontalTimeline.spec.js
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, WSR

#6925 Release 9.89.0-2.28.0
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
  packages/wix-ui-tpa/CHANGELOG.md
  packages/wix-ui-tpa/package.json
Labels: PR: unreviewed, WSR, WUT

#6916 [storybook-guidelines-phase-2] DoDont + StorybookComponents usage
  packages/wix-style-react/package.json
  packages/wix-style-react/src/AvatarGroup/docs/examples.js
  packages/wix-style-react/src/AvatarGroup/docs/index.story.js
  packages/wix-style-react/src/Input/docs/examples.js
  packages/wix-style-react/src/Input/docs/index.story.js
  packages/wix-style-react/src/Modal/docs/examples.js
  packages/wix-style-react/src/Modal/docs/index.story.js
  packages/wix-style-react/src/PageSection/docs/examples.js
  packages/wix-style-react/src/PageSection/docs/index.story.js
  packages/wix-style-react/stories/utils/allComponents.js
Labels: PR: unreviewed, WSR

#6890 <DatePicker /> - add clear button prop
  packages/wix-style-react/src/DatePicker/DatePicker.js
  packages/wix-style-react/src/DatePicker/docs/examples.js
  packages/wix-style-react/src/DatePicker/docs/index.story.js
  packages/wix-style-react/src/DatePicker/index.d.ts
  packages/wix-style-react/src/DatePicker/test/DatePicker.spec.js
  packages/wix-style-react/src/DatePicker/test/DatePicker.tsx
  packages/wix-style-react/src/DatePicker/test/DatePicker.visual.js
Labels: PR: unreviewed, WSR

#6927 [Playground] - add theme provider support
  packages/wix-style-react/stories/Playground/Playground.story.js
  packages/wix-style-react/stories/utils/allComponents.js
Labels: PR: unreviewed, WSR

#6902 infra - fix missing and incorrect types
  packages/wix-style-react/src/FailWhale/index.d.ts
  packages/wix-style-react/src/RadioGroup/RadioButton/index.d.ts
  packages/wix-style-react/src/RadioGroup/RadioButton/index.js
  packages/wix-style-react/src/RadioGroup/index.d.ts
  packages/wix-style-react/src/TimeInput/test/TimeInput.tsx
  packages/wix-style-react/src/index.d.ts
  packages/wix-style-react/tsconfig.declarations.json
Labels: PR: reviewed-approved, WSR

#6909 <RadioGroup/> - updated storybook without changing content of examples
  packages/wix-style-react/src/RadioGroup/docs/index.story.js
Labels: PR: unreviewed, WSR

#6918 Themes | Business Dashboard - Empty State children top margin
  packages/wix-style-react/src/Themes/businessDashboard/components/EmptyState.st.css
  packages/wix-style-react/src/Themes/businessDashboard/docs/components/EmptyState.js
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, Themes - Business Dashboard, WSR

#6923 fix(SectionNotification): adding missing margin in RTL
  packages/wix-ui-tpa/src/components/SectionNotification/SectionNotification.st.css
  packages/wix-ui-tpa/src/components/SectionNotification/SectionNotification.tsx
  packages/wix-ui-tpa/src/components/SectionNotification/docs/index.story.tsx
Labels: Contribution, PR: unreviewed, WUT

#6921 <Radio/> - change onChange type
  packages/wix-style-react/src/Radio/index.d.ts
Labels: PR: reviewed-approved, WSR

#6926 TextButton - connected the suffix and prefix of TextButton to color and font size
  packages/wix-ui-tpa/perfer.config.js
  packages/wix-ui-tpa/src/components/TextButton/TextButton.st.css
  packages/wix-ui-tpa/src/components/TextButton/TextButton.tsx
  packages/wix-ui-tpa/src/components/TextButton/TextButton.visual.tsx
  packages/wix-ui-tpa/src/components/TextButton/docs/TextButtonWiringExample.tsx
  packages/wix-ui-tpa/src/components/TextButton/docs/index.story.tsx
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, WUT

#6932 release: 9.90-2.29.0
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
  packages/wix-ui-tpa/CHANGELOG.md
  packages/wix-ui-tpa/package.json
Labels: PR: reviewed-approved, WSR, WUT

#6928 `<SelectableAccordion />` - add disabled property to items list
  packages/wix-style-react/src/SelectableAccordion/Item/Item.js
  packages/wix-style-react/src/SelectableAccordion/Item/Item.st.css
  packages/wix-style-react/src/SelectableAccordion/Item/index.d.ts
  packages/wix-style-react/src/SelectableAccordion/SelectableAccordion.js
  packages/wix-style-react/src/SelectableAccordion/SelectableAccordion.uni.driver.d.ts
  packages/wix-style-react/src/SelectableAccordion/SelectableAccordion.uni.driver.js
  packages/wix-style-react/src/SelectableAccordion/constants.js
  packages/wix-style-react/src/SelectableAccordion/docs/examples.js
  packages/wix-style-react/src/SelectableAccordion/docs/index.story.js
  packages/wix-style-react/src/SelectableAccordion/test/SelectableAccordion.spec.js
Labels: Contribution, PR: partially-approved, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed, WSR

#6933 extract wix-style-react perfer to dedicated package
  package.json
  packages/wix-style-react-test-perfer/.gitignore
  packages/wix-style-react-test-perfer/package.json
  packages/wix-style-react-test-perfer/perfer.config.js
  packages/wix-style-react-test-perfer/yoshi.config.js
  packages/wix-style-react/.perfer/package.json
  packages/wix-style-react/package.json
  packages/wix-style-react/perfer.config.js
Labels: Infrastructure, PR: reviewed-approved, WSR

#6794 `<Page/>` - change default min and max width according to new spec
  packages/wix-style-react/src/Page/Page.st.css
Labels: PR: unreviewed, WSR

#6936 wsr & wut - add `wix-ui-framework` to devDependencies
  packages/wix-style-react/package.json
  packages/wix-ui-tpa/package.json
Labels: PR: reviewed-approved, WSR, WUT

#6939 extract wix-ui-tpa perfer to dedicated package
  package.json
  packages/wix-ui-tpa-test-perfer/.gitignore
  packages/wix-ui-tpa-test-perfer/package.json
  packages/wix-ui-tpa-test-perfer/perfer.config.js
  packages/wix-ui-tpa-test-perfer/yoshi.config.js
  packages/wix-ui-tpa/.perfer/package.json
  packages/wix-ui-tpa/package.json
  packages/wix-ui-tpa/perfer.config.js
Labels: Infrastructure, PR: unreviewed, WUT

#6940 Release 9.91.0
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
Labels: PR: unreviewed, WSR

#6929 <Box /> - new prop gap
  packages/wix-style-react/src/Box/Box.js
  packages/wix-style-react/src/Box/Box.st.css
  packages/wix-style-react/src/Box/index.d.ts
  packages/wix-style-react/src/Box/test/Box.tsx
  packages/wix-style-react/src/Box/test/Box.visual.js
Labels: PR: reviewed-approved, WSR

#6937 <DropdownLayout /> - fix uni driver when using infinite scroll
  packages/wix-style-react/src/DropdownLayout/DropdownLayout.uni.driver.js
  packages/wix-style-react/src/DropdownLayout/test/DropdownLayout.spec.js
Labels: Contribution, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed, WSR

#6938 `<SidePanel.Header/>` - Changed tooltip content from string to node
  packages/wix-style-react/src/SidePanel/COMPOUND_README.API.md
  packages/wix-style-react/src/SidePanel/Header/Header.js
  packages/wix-style-react/src/SidePanel/Header/index.d.ts
Labels: Contribution, PR: partially-approved, PR: reviewed-approved, PR: unreviewed, WSR

#6935 <Layout /> - changed default gap for reduced spacing feature
  packages/wix-style-react/src/Layout/Layout/index.js
  packages/wix-style-react/src/Layout/Layout/index.spec.js
  packages/wix-style-react/src/Layout/test/Layout.visual.js
Labels: PR: reviewed-approved, WSR

#6941 wix-ui-tpa/Dialog-createPortal
  packages/wix-ui-tpa/src/components/Dialog/Dialog.tsx
Labels: Contribution, PR: partially-approved, PR: reviewed-approved, PR: unreviewed, WUT

#6942 <PageSection /> - changed title from string to node
  packages/wix-style-react/src/PageSection/PageSection.js
  packages/wix-style-react/src/PageSection/index.d.ts
Labels: Contribution, PR: unreviewed, WSR

#6934 Themes | Business Dashboard - Fix theme margin rule
  packages/wix-style-react/src/Themes/businessDashboard/components/TableListItem.st.css
Labels: Contribution, PR: partially-approved, PR: reviewed-approved, PR: unreviewed, Themes - Business Dashboard, WSR

#6943 Release 9.92.0
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
Labels: PR: unreviewed, WSR

#6945 <Box/> - story improvement according to new guidelines
  packages/wix-style-react/src/Box/Box.js
  packages/wix-style-react/src/Box/docs/examples.js
  packages/wix-style-react/src/Box/docs/index.story.js
  packages/wix-style-react/src/Box/docs/propExplanations.js
Labels: PR: reviewed-approved, WSR

#6951 wsr: fix markdown comment, use backticks for code example
  packages/wix-style-react/src/InputWithOptions/InputWithOptions.js
Labels: PR: unreviewed, WSR

#6922 `<SocialPreview/> - add support for twitter preview
  packages/wix-style-react/src/SocialPreview/SocialPreview.js
  packages/wix-style-react/src/SocialPreview/SocialPreview.st.css
  packages/wix-style-react/src/SocialPreview/SocialPreview.uni.driver.d.ts
  packages/wix-style-react/src/SocialPreview/SocialPreview.uni.driver.js
  packages/wix-style-react/src/SocialPreview/constants.js
  packages/wix-style-react/src/SocialPreview/docs/BasicExample.js
  packages/wix-style-react/src/SocialPreview/docs/examples.js
  packages/wix-style-react/src/SocialPreview/docs/index.story.js
  packages/wix-style-react/src/SocialPreview/index.d.ts
  packages/wix-style-react/src/SocialPreview/test/SocialPreview.spec.js
  packages/wix-style-react/src/SocialPreview/test/SocialPreview.tsx
  packages/wix-style-react/src/SocialPreview/test/SocialPreview.visual.js
Labels: Contribution, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed, WSR, auto pr, wip

#6952 [wsr + wut] DatePicker - increase thresholds for perfer
  packages/wix-style-react/perfer.config.js
  packages/wix-ui-tpa/perfer.config.js
Labels: PR: unreviewed, WSR

#6953 Storybook Guidelines documentation
  packages/wix-style-react/docs/assets/Bitmap.png
  packages/wix-style-react/docs/assets/CommonUseDO.png
  packages/wix-style-react/docs/assets/CommonUseDONT.png
  packages/wix-style-react/docs/assets/DO.png
  packages/wix-style-react/docs/assets/DONT.png
  packages/wix-style-react/docs/assets/DropdownLayoutDO.png
  packages/wix-style-react/docs/assets/DropdownLayoutDONT.png
  packages/wix-style-react/docs/assets/ErrorMessageDO.png
  packages/wix-style-react/docs/assets/ErrorMessageDONT.png
  packages/wix-style-react/docs/assets/FixedAreasDO.png
  packages/wix-style-react/docs/assets/FixedAreasDONT.png
  packages/wix-style-react/docs/assets/FooterDO.png
  packages/wix-style-react/docs/assets/FooterDONT.png
  packages/wix-style-react/docs/assets/InputDO.png
  packages/wix-style-react/docs/assets/InputDONT.png
  packages/wix-style-react/docs/assets/LayoutDO.png
  packages/wix-style-react/docs/assets/LayoutDONT.png
  packages/wix-style-react/docs/assets/LetterCountingDO.png
  packages/wix-style-react/docs/assets/LetterCountingDONT.png
  packages/wix-style-react/docs/assets/ListItemSelectDO.png
  packages/wix-style-react/docs/assets/ListItemSelectDONT.png
  packages/wix-style-react/docs/assets/MarketingContentDO.png
  packages/wix-style-react/docs/assets/MarketingContentDONT.png
  packages/wix-style-react/docs/assets/ModalStructureDO.png
  packages/wix-style-react/docs/assets/ModalStructureDONT.png
  packages/wix-style-react/docs/assets/NotificationsDO.png
  packages/wix-style-react/docs/assets/NotificationsDONT.png
  packages/wix-style-react/docs/assets/PageStructure.png
  packages/wix-style-react/docs/assets/StatesDO.png
  packages/wix-style-react/docs/assets/StatesDONT.png
  packages/wix-style-react/docs/assets/TextOverflowDO.png
  packages/wix-style-react/docs/assets/TextOverflowDONT.png
  packages/wix-style-react/docs/assets/ToggleButtonDO.png
  packages/wix-style-react/docs/assets/ToggleButtonDONT.png
  packages/wix-style-react/docs/contribution/storybook-guidelines/STORYBOOK_GUIDELINES.md
Labels: PR: unreviewed, WSR

#6954 moved guidelines
  packages/wix-style-react/docs/contribution/STORYBOOK_GUIDELINES.md
Labels: PR: unreviewed, WSR

#6946 BusinessDashboard Theme | Override Divider dark skin
  packages/wix-style-react/src/Divider/test/Divider.visual.js
  packages/wix-style-react/src/Themes/businessDashboard/BusinessDashboard.st.css
  packages/wix-style-react/src/Themes/businessDashboard/components/Divider.st.css
  packages/wix-style-react/src/Themes/businessDashboard/docs/businessDashboard.story.js
  packages/wix-style-react/src/Themes/businessDashboard/docs/components/Divider.js
  packages/wix-style-react/src/Themes/businessDashboard/foundations/colors.st.css
  packages/wix-style-react/src/Themes/businessDashboard/test/businessDashboard.visual.js
Labels: Contribution, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed, WSR

#6959 [wsr] Release 9.93
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
Labels: PR: unreviewed

#6956 <DatePicker/> - props excludePastDates and filterDate collide fix
  packages/wix-style-react/src/Calendar/Calendar.js
  packages/wix-style-react/src/Calendar/test/Calendar.spec.js
Labels: PR: reviewed-approved, WSR

#6961 [Storybook_Guidelines.md] - improvements
  packages/wix-style-react/docs/contribution/STORYBOOK_GUIDELINES.md
Labels: PR: unreviewed, WSR

#6963 WUT: fix(Tooltip/Arrows): add type annotation
  packages/wix-ui-tpa/src/components/Tooltip/Arrows.tsx
Labels: PR: unreviewed, WUT

#6955 Image - added image failure design
  packages/wix-ui-tpa/perfer.config.js
  packages/wix-ui-tpa/src/components/Image/Image.st.css
  packages/wix-ui-tpa/src/components/Image/Image.tsx
  packages/wix-ui-tpa/src/components/Image/Image.visual.tsx
  packages/wix-ui-tpa/src/components/Image/docs/index.story.tsx
  packages/wix-ui-tpa/src/components/Image/types.ts
Labels: Contribution, PR: unreviewed, WUT

#6965 fix `Uncaught [Error: Invalid hook call.`
  package.json
  packages/wix-style-react/package.json
  packages/wix-ui-tpa/src/components/Tooltip/Tooltip.protractor.driver.ts
Labels: Infrastructure, PR: draft, PR: unreviewed, WSR, WUT, wip

#6970 Added seo to the TPAComponentsContext & passing it to MediaImage
  packages/wix-ui-tpa/docs/USAGE.md
  packages/wix-ui-tpa/src/components/Image/Image.visual.tsx
  packages/wix-ui-tpa/src/components/Image/RelativeMediaImage/RelativeMediaImage.tsx
  packages/wix-ui-tpa/src/components/TPAComponentsConfig/TPAComponentsConfig.tsx
Labels: Contribution, PR: draft, PR: unreviewed, WUT

#6957 [dashboard theme] update inverted button hover
  packages/wix-style-react/src/Themes/businessDashboard/components/Button.st.css
Labels: Contribution, PR: partially-approved, PR: unreviewed, Themes - Business Dashboard, WSR

#6972 <TableListItem /> - Fix TableActionCell visibility on hover
  packages/wix-style-react/src/TableListItem/TableListItem.st.css
Labels: Contribution, PR: partially-approved, PR: reviewed-approved, PR: unreviewed, WSR

#6977 [wsr] Release 9.94.0
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
Labels: PR: unreviewed

#6974 `<ListItemAction/>` - remove unexpected title attribute tooltip
  packages/wix-style-react/src/ListItemAction/ListItemAction.js
Labels: PR: reviewed-approved, WSR

#6960 `<TableListItem/>` - cannot stretch value to 100%
  packages/wix-style-react/src/TableListItem/TableListItem.js
  packages/wix-style-react/src/TableListItem/test/TableListItem.visual.js
Labels: PR: reviewed-approved, WSR

#6981 pin @babel/core in wix-ui-tpa
  package.json
  packages/wix-ui-tpa/package.json
Labels: Infrastructure, PR: unreviewed, WUT

#6962 Run only changed visual tests in WSR
  package.json
  packages/wix-style-react/.storybook/visual/config.js
  packages/wix-style-react/.wuf/.gitignore
  packages/wix-style-react/package.json
  scripts/find-changed-visuals.js
Labels: Infrastructure, PR: draft, PR: unreviewed, WSR

#6948 fix(DatePicker): Change the min-width according to the font-size
  packages/wix-ui-tpa/src/components/DatePicker/DatePicker.st.css
  packages/wix-ui-tpa/src/components/DatePicker/docs/DatePickerWiringExample.st.css
  packages/wix-ui-tpa/src/components/DatePicker/docs/index.story.tsx
  packages/wix-ui-tpa/src/components/DatePickerInput/DatePickerInput.st.css
  packages/wix-ui-tpa/stories/helperComponents/MockSettings.tsx
Labels: DO NOT REVIEW, PR: draft, PR: partially-approved, PR: unreviewed, WUT

#6986 unpin `@babel/core`
  package.json
  packages/wix-ui-tpa/package.json
Labels: Infrastructure, PR: reviewed-approved, PR: unreviewed, WUT

#6978 <DropdownBase /> - add onShow, onHide props
  packages/wix-style-react/src/DropdownBase/DropdownBase.js
  packages/wix-style-react/src/DropdownBase/index.d.ts
  packages/wix-style-react/src/DropdownBase/test/DropdownBase.spec.js
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, WSR

#6958 Arial Vietnamese
  packages/wix-style-react/.storybook/stories.scss
  packages/wix-style-react/perfer.config.js
  packages/wix-style-react/src/FontUpgrade/FontUpgrade.js
  packages/wix-style-react/src/FontUpgrade/FontUpgrade.st.css
Labels: DO NOT MERGE, PR: unreviewed, WSR

#6989 Release 9.95.0-2.30.0
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
  packages/wix-ui-tpa/CHANGELOG.md
  packages/wix-ui-tpa/package.json
Labels: PR: unreviewed, WSR, WUT

#6920 disabled dropdown base broder color is being overrided
  packages/wix-ui-tpa/src/components/Dropdown/Dropdown.st.css
Labels: Contribution, PR: partially-approved, PR: unreviewed, WUT

#6988 eyes-storybook: Remove browser limitation + fix concurrency
  packages/wix-ui-tpa/applitools.config.js
Labels: PR: unreviewed, WUT

#6993 Release 9.96.0-2.31.0
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
  packages/wix-ui-tpa/CHANGELOG.md
  packages/wix-ui-tpa/package.json
Labels: PR: unreviewed, WSR, WUT
