Repository wix/wix-style-react, pull requests merged in 2021-04, with the labels that each got.

#6966 Grid to Layout: deprecation message for grid, migration doc, existing docs updates
  packages/wix-style-react/docs/FAQ/README.md
  packages/wix-style-react/docs/usage/LAYOUTING.md
  packages/wix-style-react/docs/usage/MOBILE_WEB_GUIDELINES.md
  packages/wix-style-react/src/Card/docs/index.story.js
  packages/wix-style-react/src/Grid/Grid.js
  packages/wix-style-react/src/Grid/docs/index.js
  packages/wix-style-react/src/Layout/docs/MIGRATION.md
  packages/wix-style-react/src/Page/Page.st.css
  packages/wix-style-react/src/Page/docs/index.story.js
  packages/wix-style-react/src/Swatches/docs/index.story.js
  packages/wix-style-react/stories/CardLayout/index.story.js
  packages/wix-style-react/stories/PageLayout/examples.js
  packages/wix-style-react/stories/PageLayout/index.story.js
  packages/wix-style-react/stories/symbolsComponentsMapping/components.js
  packages/wix-style-react/stories/symbolsComponentsMapping/families/layoutFamily.js
  packages/wix-style-react/stories/symbolsComponentsMapping/storybookMapping.js
Labels: PR: unreviewed, WSR

#6969 WSR: Update CONTRIBUTING.md
  packages/wix-style-react/CONTRIBUTING.md
Labels: PR: unreviewed, WSR

#6997 WUT: fix ts error
  packages/wix-style-react/src/Calendar/test/Calendar.spec.js
  packages/wix-ui-tpa/src/components/Checkbox/Checkbox.tsx
  packages/wix-ui-tpa/src/components/RadioButton/RadioButton.tsx
  packages/wix-ui-tpa/src/components/StatesButton/StatesButton.tsx
  packages/wix-ui-tpa/src/components/Tags/Tags.tsx
Labels: Infrastructure, PR: reviewed-approved, PR: unreviewed, WSR, WUT

#6998 WUT: add testkit folder to `includes` of `tsconfig`
  packages/wix-ui-tpa/tsconfig.json
Labels: Infrastructure, PR: reviewed-approved, PR: unreviewed, WUT

#7000 Fix wut postpublish phase
  packages/wix-ui-tpa/package.json
Labels: PR: partially-approved, WUT

#6983 Fix/dropdown styles
  packages/wix-ui-tpa/perfer.config.js
  packages/wix-ui-tpa/src/components/Dropdown/Dropdown.st.css
  packages/wix-ui-tpa/src/components/Dropdown/DropdownNativeSelect.st.css
  packages/wix-ui-tpa/src/components/Dropdown/DropdownNativeSelect.tsx
  packages/wix-ui-tpa/src/components/Dropdown/docs/DropdownExtendedExample.tsx
  packages/wix-ui-tpa/src/components/Dropdown/docs/index.story.tsx
Labels: Contribution, PR: partially-approved, PR: unreviewed, WUT

#6892 Update COMPOUND_README.API.md
  packages/wix-style-react/src/SidePanel/COMPOUND_README.API.md
Labels: Contribution, PR: unreviewed, WSR

#7003 release/9.96.1-2.31.1
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
  packages/wix-ui-tpa/CHANGELOG.md
  packages/wix-ui-tpa/package.json
Labels: PR: unreviewed, WSR, WUT

#6999 Storybook Guidelines - fixed titles, added demo section
  packages/wix-style-react/docs/assets/DemoDO.png
  packages/wix-style-react/docs/assets/DemoDONT.png
  packages/wix-style-react/docs/assets/PageStructure.png
  packages/wix-style-react/docs/contribution/STORYBOOK_GUIDELINES.md
  packages/wix-style-react/src/AvatarGroup/docs/index.story.js
  packages/wix-style-react/src/Box/docs/index.story.js
  packages/wix-style-react/src/Input/docs/index.story.js
  packages/wix-style-react/src/Modal/docs/index.story.js
  packages/wix-style-react/src/PageSection/docs/index.story.js
Labels: Contribution, PR: partially-approved, PR: unreviewed, WSR

#6994 fix getColumnTextAt typo
  packages/wix-style-react/src/TableListItem/TableListItem.uni.driver.js
  packages/wix-style-react/src/TableListItem/test/TableListItem.spec.js
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, WSR

#6982 < WixStyleReactProvider/> — Improved story
  packages/wix-style-react/src/WixStyleReactProvider/docs/examples.js
  packages/wix-style-react/src/WixStyleReactProvider/docs/index.story.js
  packages/wix-style-react/src/WixStyleReactProvider/test/storySettings.js
Labels: Contribution, Docs, PR: unreviewed, WSR

#7006 BusinessDashboard Theme | < IconButton /> - Changed inverted hover color
  packages/wix-style-react/src/Themes/businessDashboard/components/IconButton.st.css
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, Themes - Business Dashboard, WSR

#7007 `<Page.Sticky/>` - fix `style` prop proptype
  packages/wix-style-react/src/Page/PageSticky.js
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, WSR

#7001 `<AnalyticsSummaryCard />` - fix typo in isTrendVisible types
  packages/wix-style-react/src/AnalyticsSummaryCard/index.d.ts
  packages/wix-style-react/src/AnalyticsSummaryCard/test/AnalyticsSummaryCard.tsx
  packages/wix-style-react/src/AnalyticsSummaryCard/test/AnalyticsSummaryCard.visual.js
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, WSR

#7008 Release 9.98.0-2.33.0
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
  packages/wix-ui-tpa/CHANGELOG.md
  packages/wix-ui-tpa/package.json
Labels: PR: unreviewed

#7004 BusinessDashboard Theme | <Card /> - decreased content bottom padding
  packages/wix-style-react/src/Themes/businessDashboard/components/Card/Content.st.css
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, Themes - Business Dashboard, WSR

#6992 BusinessDashboard Theme | <Thumbnail> - Apply overrides to all size thumbnail
  packages/wix-style-react/src/Themes/businessDashboard/components/Thumbnail.st.css
  packages/wix-style-react/src/Themes/businessDashboard/docs/components/Thumbnail.js
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, Themes - Business Dashboard, WSR

#6971 BusinessDashboard Theme | <SidePanel> - Changed spacings and colors
  packages/wix-style-react/src/SidePanel/test/SidePanel.visual.js
  packages/wix-style-react/src/Themes/businessDashboard/BusinessDashboard.st.css
  packages/wix-style-react/src/Themes/businessDashboard/components/InfoIcon.st.css
  packages/wix-style-react/src/Themes/businessDashboard/components/SidePanel/Content/Content.st.css
  packages/wix-style-react/src/Themes/businessDashboard/components/SidePanel/Header/Header.st.css
  packages/wix-style-react/src/Themes/businessDashboard/docs/businessDashboard.story.js
  packages/wix-style-react/src/Themes/businessDashboard/docs/components/InfoIcon.js
  packages/wix-style-react/src/Themes/businessDashboard/docs/components/SidePanel.js
  packages/wix-style-react/src/Themes/businessDashboard/foundations/colors.st.css
Labels: Contribution, PR: partially-approved, PR: unreviewed, Themes - Business Dashboard, WSR

#6950 BusinessDashboard Theme | SectionHelper - override styles
  packages/wix-style-react/src/SectionHelper/test/SectionHelper.visual.js
  packages/wix-style-react/src/Themes/businessDashboard/BusinessDashboard.st.css
  packages/wix-style-react/src/Themes/businessDashboard/components/SectionHelper.st.css
  packages/wix-style-react/src/Themes/businessDashboard/docs/businessDashboard.story.js
  packages/wix-style-react/src/Themes/businessDashboard/docs/components/SectionHelper.js
  packages/wix-style-react/src/Themes/businessDashboard/foundations/colors.st.css
  packages/wix-style-react/src/Themes/businessDashboard/test/businessDashboard.visual.js
Labels: Contribution, PR: partially-approved, PR: reviewed-changes-requested, PR: unreviewed, Themes - Business Dashboard, WSR

#7002 <SidePanel /> - added width prop
  packages/wix-style-react/src/SidePanel/SidePanel.js
  packages/wix-style-react/src/SidePanel/SidePanel.st.css
  packages/wix-style-react/src/SidePanel/docs/index.story.js
  packages/wix-style-react/src/SidePanel/index.d.ts
  packages/wix-style-react/src/SidePanel/test/SidePanel.visual.js
Labels: Contribution, PR: partially-approved, PR: unreviewed, WSR

#6968 BusinessDashboard Theme | <IconButton /> - Changed colors
  packages/wix-style-react/src/Themes/businessDashboard/components/IconButton.st.css
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, Themes - Business Dashboard, WSR

#7010 Grid - add new visual tests for regression
  packages/wix-style-react/src/Grid/docs/ExampleFixedWidthGrid.js
  packages/wix-style-react/src/Grid/docs/ExampleTwoHalfWidthRows.js
  packages/wix-style-react/src/Grid/docs/ExampleTwoHalfWidthRowsFluid.js
  packages/wix-style-react/src/Grid/test/Grid.visual.js
Labels: PR: reviewed-approved, WSR

#6991 BusinessDashboard Theme | <Popover> - Changed colors
  packages/wix-style-react/src/Popover/test/Popover.visual.js
  packages/wix-style-react/src/Themes/businessDashboard/BusinessDashboard.st.css
  packages/wix-style-react/src/Themes/businessDashboard/components/Popover.st.css
  packages/wix-style-react/src/Themes/businessDashboard/docs/businessDashboard.story.js
  packages/wix-style-react/src/Themes/businessDashboard/docs/components/Popover.js
  packages/wix-style-react/src/Themes/businessDashboard/foundations/colors.st.css
  packages/wix-style-react/src/Themes/businessDashboard/test/businessDashboard.visual.js
Labels: Contribution, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed, Themes - Business Dashboard, WSR

#6947 <MultiSelect /> - story improvements
  packages/wix-style-react/src/MultiSelect/MultiSelect.js
  packages/wix-style-react/src/MultiSelect/README.API.md
  packages/wix-style-react/src/MultiSelect/docs/ExampleForHeader.js
  packages/wix-style-react/src/MultiSelect/docs/ExampleReorderable.js
  packages/wix-style-react/src/MultiSelect/docs/ExampleSelectAutocomplete.js
  packages/wix-style-react/src/MultiSelect/docs/ExampleSelectSimple.js
  packages/wix-style-react/src/MultiSelect/docs/ExampleSuggestions.js
  packages/wix-style-react/src/MultiSelect/docs/ExampleTagInput.js
  packages/wix-style-react/src/MultiSelect/docs/ExampleTagInputSelection.js
  packages/wix-style-react/src/MultiSelect/docs/ExampleThumbVariations.js
  packages/wix-style-react/src/MultiSelect/docs/MultiSelectPlaygroundConfig.js
  packages/wix-style-react/src/MultiSelect/docs/examples.js
  packages/wix-style-react/src/MultiSelect/docs/index.story.js
Labels: PR: unreviewed, WSR

#6973 BusinessDashboard Theme | <Button /> - Added light primary skin
  packages/wix-style-react/src/Themes/businessDashboard/components/Button.st.css
  packages/wix-style-react/src/Themes/businessDashboard/docs/components/Button.js
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, Themes - Business Dashboard, WSR

#6967 BusinessDashboard Theme | <Button /> - Changed min width
  packages/wix-style-react/src/Themes/businessDashboard/components/Button.st.css
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, Themes - Business Dashboard, WSR

#6985 BusinessDashboard Theme | <Badge> - Changed spacings and colors
  packages/wix-style-react/src/Themes/businessDashboard/components/Badge.st.css
  packages/wix-style-react/src/Themes/businessDashboard/docs/components/Badge.js
  packages/wix-style-react/src/Themes/businessDashboard/foundations/colors.st.css
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, Themes - Business Dashboard, WSR

#7016 Release 9.99.0
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
Labels: PR: unreviewed, WSR

#7015 `<SidebarSectionItem/>` - new sidebar experiment for changing hover and active colors
  packages/wix-style-react/src/SidebarSectionItem/SidebarSectionItem.js
  packages/wix-style-react/src/SidebarSectionItem/SidebarSectionItem.st.css
  packages/wix-style-react/src/SidebarSectionItem/test/SidebarSectionItem.visual.js
  packages/wix-style-react/src/Themes/businessDashboard/components/SidebarSectionItem.st.css
Labels: Contribution, PR: partially-approved, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed, WSR

#7019 fix `find-changed-visuals.js`
  scripts/find-changed-visuals.js
Labels: Infrastructure, PR: unreviewed

#7009 <Date Picker /> - fix rtl arrows position in responsive designs
  packages/wix-ui-tpa/src/components/DatePicker/DatePicker.st.css
  packages/wix-ui-tpa/src/components/DatePicker/DatePicker.visual.tsx
Labels: Contribution, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed, WUT

#7020 Fix SSR doesn't find document
  packages/wix-style-react/src/FontUpgrade/FontUpgrade.js
Labels: PR: unreviewed, WSR

#7022 Release 9.100.0-2.34.0
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
  packages/wix-ui-tpa/CHANGELOG.md
  packages/wix-ui-tpa/package.json
Labels: PR: unreviewed

#7023 <Input /> - fix styles for autoFocus prop
  packages/wix-style-react/src/Input/Input.js
Labels: PR: reviewed-approved, WSR

#7024 <SidebarContentWrapper /> - support SSR
  packages/wix-style-react/src/Sidebar/SidebarContentWrapper.js
Labels: PR: partially-approved, WSR

#7011 Grid - remove bootstrap and use Layout internally
  packages/wix-style-react/src/Grid/Grid.js
  packages/wix-style-react/src/Grid/Grid.scss
  packages/wix-style-react/src/Grid/Grid.spec.js
  packages/wix-style-react/src/Grid/Grid.st.css
  packages/wix-style-react/src/Grid/GridConstants.scss
  packages/wix-style-react/src/Layout/Cell/index.js
  packages/wix-style-react/src/Layout/Layout/index.js
Labels: PR: reviewed-approved, WSR

#7027 release 9.101.0-2.35.0
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
  packages/wix-ui-tpa/CHANGELOG.md
  packages/wix-ui-tpa/package.json
Labels: PR: unreviewed, WSR, WUT

#7018 <Tag/> - add success theme [Testkit][Docs][Types]
  packages/wix-style-react/src/Tag/Tag.driver.d.ts
  packages/wix-style-react/src/Tag/Tag.driver.js
  packages/wix-style-react/src/Tag/Tag.js
  packages/wix-style-react/src/Tag/Tag.st.css
  packages/wix-style-react/src/Tag/Tag.uni.driver.d.ts
  packages/wix-style-react/src/Tag/Tag.uni.driver.js
  packages/wix-style-react/src/Tag/docs/examples.js
  packages/wix-style-react/src/Tag/index.d.ts
  packages/wix-style-react/src/Tag/test/Tag.spec.js
  packages/wix-style-react/stories/Colors/index.story.js
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, WSR

#6987 < AnalyticsSummaryCard /> - Expose chart animation duration
  packages/wix-style-react/src/AnalyticsSummaryCard/AnalyticsSummaryCard.js
  packages/wix-style-react/src/AnalyticsSummaryCard/index.d.ts
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, WSR

#7026 BusinessDashboard Theme | <Text />
  packages/wix-style-react/src/Themes/businessDashboard/components/Text.st.css
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, Themes - Business Dashboard, WSR

#6944 <DatePicker /> - add typing functionality and disableKeyboardType prop
  packages/wix-style-react/src/DatePicker/DateInput/DateInput.js
  packages/wix-style-react/src/DatePicker/DatePicker.js
  packages/wix-style-react/src/DatePicker/DatePicker.st.css
  packages/wix-style-react/src/DatePicker/docs/examples.js
  packages/wix-style-react/src/DatePicker/docs/index.story.js
  packages/wix-style-react/src/DatePicker/index.d.ts
  packages/wix-style-react/src/DatePicker/test/DatePicker.spec.js
  packages/wix-style-react/src/DatePicker/test/DatePicker.tsx
  packages/wix-style-react/src/Input/Input.driver.js
Labels: PR: reviewed-approved, WSR

#7028 <MediaOverlay /> - add borderRadius property
  packages/wix-style-react/src/MediaOverlay/MediaOverlay.js
  packages/wix-style-react/src/MediaOverlay/index.d.ts
  packages/wix-style-react/src/MediaOverlay/test/MediaOverlay.visual.js
Labels: Contribution, PR: partially-approved, PR: reviewed-approved, PR: unreviewed, WSR, auto pr

#7021 BusinessDashboard Theme | <IconButton />
  packages/wix-style-react/src/Themes/businessDashboard/components/IconButton.st.css
  packages/wix-style-react/src/Themes/businessDashboard/docs/components/IconButton.js
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, Themes - Business Dashboard, WSR

#7033 updated bundle size
  packages/wix-style-react/perfer.config.js
Labels: PR: unreviewed, WSR

#7034 release/9.102.0-2.36.0
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
  packages/wix-ui-tpa/CHANGELOG.md
  packages/wix-ui-tpa/package.json
Labels: PR: unreviewed

#7025 <SidebarSectionItem/><SidebarSectionTitle/><SidebarDivider/> - sidebar experiment for reduce horizontal padding and height for sidebar items
  packages/wix-style-react/src/SidebarDivider/SidebarDivider.js
  packages/wix-style-react/src/SidebarDivider/SidebarDivider.st.css
  packages/wix-style-react/src/SidebarDivider/test/SidebarDivider.visual.js
  packages/wix-style-react/src/SidebarSectionItem/SidebarSectionItem.st.css
  packages/wix-style-react/src/SidebarSectionTitle/SidebarSectionTitle.js
  packages/wix-style-react/src/SidebarSectionTitle/SidebarSectionTitle.st.css
  packages/wix-style-react/src/SidebarSectionTitle/test/SidebarSectionTitle.visual.js
Labels: Contribution, PR: partially-approved, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed, WSR

#7038 <Grid/> - add default span value for col
  packages/wix-style-react/src/Grid/Grid.js
Labels: PR: reviewed-approved, WSR

#7040 remove classname from supported props
  packages/wix-style-react/src/Grid/README.md
Labels: PR: unreviewed, WSR

#7044 <Checkbox /> - fix stylable extend functionality
  packages/wix-ui-tpa/src/components/Checkbox/Checkbox.st.css
Labels: PR: unreviewed, WUT

#7047 release 9.103.0-2.37.0
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
  packages/wix-ui-tpa/CHANGELOG.md
  packages/wix-ui-tpa/package.json
Labels: PR: unreviewed, WSR, WUT

#7039 TableActionCell: popover prop types
  packages/wix-style-react/src/TableActionCell/TableActionCell.js
  packages/wix-style-react/src/TableActionCell/index.d.ts
Labels: Contribution, PR: unreviewed, WSR

#7030 BusinessDashboard Theme | EmptyState - update example
  packages/wix-style-react/src/Themes/businessDashboard/docs/components/EmptyState.js
Labels: Contribution, PR: unreviewed, Themes - Business Dashboard, WSR

#7045 `<DatePicker/>` - set disableKeyboardType as true by default
  packages/wix-style-react/src/DatePicker/DatePicker.js
  packages/wix-style-react/src/DatePicker/test/DatePicker.spec.js
  packages/wix-style-react/testkit/unidriver.js
Labels: PR: unreviewed, WSR

#7036 BusinessDashboard Theme | EmptyState
  packages/wix-style-react/src/Themes/businessDashboard/components/EmptyState.st.css
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, Themes - Business Dashboard, WSR

#6964 BusinessDashboard Theme | <PageSection />
  packages/wix-style-react/src/PageSection/test/PageSection.visual.js
  packages/wix-style-react/src/Themes/businessDashboard/BusinessDashboard.st.css
  packages/wix-style-react/src/Themes/businessDashboard/components/PageSection.st.css
  packages/wix-style-react/src/Themes/businessDashboard/docs/businessDashboard.story.js
  packages/wix-style-react/src/Themes/businessDashboard/docs/components/PageSection.js
  packages/wix-style-react/src/Themes/businessDashboard/test/businessDashboard.visual.js
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, Themes - Business Dashboard, WSR

#7050 release 9.104.0
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
Labels: PR: unreviewed, WSR

#7051 update codeowners
  CODEOWNERS
Labels: PR: unreviewed

#7046 [wix-ui-tpa] FloatingDropdownBase - change aria-haspopup prop value
  packages/wix-ui-tpa/src/components/FloatingDropdown/FloatingDropdownBase.tsx
Labels: Accessibility, Contribution, PR: reviewed-approved, PR: unreviewed, WUT

#7052 <Grid/> - dataHook support
  packages/wix-style-react/src/Grid/Grid.js
  packages/wix-style-react/src/Grid/Grid.spec.js
  packages/wix-style-react/src/Grid/README.md
  packages/wix-style-react/src/Grid/index.d.ts
  packages/wix-style-react/src/Layout/Cell/index.js
  packages/wix-style-react/src/Layout/index.d.ts
Labels: PR: reviewed-approved, WSR

#7055 Release 9.105.0
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
Labels: PR: unreviewed, WSR

#7056 <Grid> - support classnames and single Container
  packages/wix-style-react/src/Grid/Grid.js
Labels: PR: reviewed-approved, WSR

#7057 <DropdownBase /> - fix mismatch between proptypes and typesript
  packages/wix-style-react/src/DropdownBase/DropdownBase.js
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, WSR

#7053 `<SidebarBackButton/>` - [experiment] - adjust back button in sidebar to be as the rest of items in experiment
  packages/wix-style-react/src/SidebarBackButton/SidebarBackButton.js
  packages/wix-style-react/src/SidebarBackButton/SidebarBackButton.st.css
  packages/wix-style-react/src/SidebarBackButton/test/SidebarBackButton.visual.js
Labels: Contribution, PR: partially-approved, PR: reviewed-approved, PR: unreviewed, WSR

#7035 BusinessDashboard Theme | `<CheckToggle/>` - check toggle override styles
  packages/wix-style-react/src/CheckToggle/test/CheckToggle.visual.js
  packages/wix-style-react/src/Themes/businessDashboard/BusinessDashboard.st.css
  packages/wix-style-react/src/Themes/businessDashboard/components/CheckToggle.st.css
  packages/wix-style-react/src/Themes/businessDashboard/docs/businessDashboard.story.js
  packages/wix-style-react/src/Themes/businessDashboard/docs/components/CheckToggle.js
  packages/wix-style-react/src/Themes/businessDashboard/test/businessDashboard.visual.js
Labels: Contribution, PR: partially-approved, PR: unreviewed, Themes - Business Dashboard, WSR

#7041 wix-ui-tpa/TextField-add-label
  packages/wix-ui-tpa/src/components/TextField/TextField.driver.ts
  packages/wix-ui-tpa/src/components/TextField/TextField.spec.tsx
  packages/wix-ui-tpa/src/components/TextField/TextField.st.css
  packages/wix-ui-tpa/src/components/TextField/TextField.tsx
  packages/wix-ui-tpa/src/components/TextField/TextField.visual.tsx
  packages/wix-ui-tpa/src/components/TextField/dataKeys.ts
  packages/wix-ui-tpa/src/components/TextField/docs/TextFieldExtendedExample.st.css
  packages/wix-ui-tpa/src/components/TextField/docs/TextFieldExtendedExample.tsx
  packages/wix-ui-tpa/src/components/TextField/docs/examples.ts
  packages/wix-ui-tpa/src/components/TextField/docs/index.story.tsx
Labels: Contribution, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed, WUT

#7048 [wsr] Expose unidrivers for our users
  packages/wix-style-react/.gitignore
  packages/wix-style-react/.wuf/testkits/unidriver.template.ejs
  packages/wix-style-react/.wuf/update-components.sh
  packages/wix-style-react/docs/usage/COMPONENTS_DRIVERS.md
  packages/wix-style-react/testkit/testkit-smoke.test.js
Labels: PR: unreviewed, WSR

#7054 [wix-ui-tpa]: TextField - fix the theme line webpack style plugin bug.
  packages/wix-ui-tpa/src/components/TextField/TextField.st.css
Labels: PR: unreviewed, WUT

#7059 Release 9.106.0
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
Labels: PR: unreviewed, WSR

#7049 <HorizontalTimeline /> - add new props to component(skin, alignLabel, line, skin for icons, new icons)
  packages/wix-style-react/src/HorizontalTimeline/HorizontalTimeline.js
  packages/wix-style-react/src/HorizontalTimeline/HorizontalTimeline.st.css
  packages/wix-style-react/src/HorizontalTimeline/HorizontalTimeline.uni.driver.d.ts
  packages/wix-style-react/src/HorizontalTimeline/HorizontalTimeline.uni.driver.js
  packages/wix-style-react/src/HorizontalTimeline/HorizontalTimelineIcons.st.css
  packages/wix-style-react/src/HorizontalTimeline/docs/examples.js
  packages/wix-style-react/src/HorizontalTimeline/docs/index.story.js
  packages/wix-style-react/src/HorizontalTimeline/index.d.ts
  packages/wix-style-react/src/HorizontalTimeline/test/HorizontalTimeline.spec.js
  packages/wix-style-react/src/HorizontalTimeline/test/HorizontalTimeline.visual.js
Labels: Contribution, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed, WSR

#7043 <SectionNotification /> - sizes and wired type
  packages/wix-ui-tpa/src/components/SectionNotification/SectionNotification.driver.ts
  packages/wix-ui-tpa/src/components/SectionNotification/SectionNotification.spec.tsx
  packages/wix-ui-tpa/src/components/SectionNotification/SectionNotification.st.css
  packages/wix-ui-tpa/src/components/SectionNotification/SectionNotification.tsx
  packages/wix-ui-tpa/src/components/SectionNotification/SectionNotification.visual.tsx
  packages/wix-ui-tpa/src/components/SectionNotification/docs/SectionNotificationWiringExample.st.css
  packages/wix-ui-tpa/src/components/SectionNotification/docs/SectionNotificationWiringExample.tsx
  packages/wix-ui-tpa/src/components/SectionNotification/docs/examples.ts
  packages/wix-ui-tpa/src/components/SectionNotification/docs/index.story.tsx
  packages/wix-ui-tpa/src/components/SectionNotification/types.ts
Labels: Contribution, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed, WUT

#7061 release 9.107.0-2.38.0
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
  packages/wix-ui-tpa/CHANGELOG.md
  packages/wix-ui-tpa/package.json
Labels: PR: reviewed-approved, WSR, WUT

#7060 feat(puppeteer-typescript): #DSM-1852 add Frame as page argument
  packages/wix-style-react/.wuf/testkits/puppeteer-typescript.template.ejs
Labels: PR: partially-approved

#7062 <DatePicker/> - value prop on re-render does not update
  packages/wix-style-react/src/DatePicker/DatePicker.js
  packages/wix-style-react/src/DatePicker/test/DatePicker.spec.js
Labels: PR: reviewed-approved, WSR

#7066 <HorizontalTimeline /> - fix icons props and align label
  packages/wix-style-react/src/HorizontalTimeline/HorizontalTimeline.st.css
  packages/wix-style-react/src/HorizontalTimeline/index.d.ts
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, WSR

#7067 Release 9.108.0
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
Labels: PR: unreviewed, WSR

#7070 <Input/> - move to new story module
  packages/wix-style-react/.storybook/webpack.config.js
  packages/wix-style-react/package.json
  packages/wix-style-react/src/Input/docs/Input.content.js
  packages/wix-style-react/src/Input/docs/Input.demo.js
  packages/wix-style-react/src/Input/docs/Input.examples.js
  packages/wix-style-react/src/Input/docs/Input.story.js
  packages/wix-style-react/src/Input/docs/index.story.js
  packages/wix-style-react/src/Input/docs/storySettings.js
  packages/wix-style-react/stories/index.js
Labels: PR: reviewed-approved, WSR

#7068 <SidebarSectionItem/> [Testkit] - add `isSelected()` and `isDisabled()` methods
  packages/wix-style-react/src/SidebarSectionItem/SidebarSectionItem.js
  packages/wix-style-react/src/SidebarSectionItem/SidebarSectionItem.uni.driver.d.ts
  packages/wix-style-react/src/SidebarSectionItem/SidebarSectionItem.uni.driver.js
  packages/wix-style-react/src/SidebarSectionItem/test/SidebarSectionItem.spec.js
Labels: Contribution, PR: partially-approved, PR: unreviewed, WSR

#7077 feat(wix-ui-tpa): Add Ratio prop to <Card />
  packages/wix-ui-tpa/src/components/Card/Card.visual.tsx
  packages/wix-ui-tpa/src/components/Card/docs/CardVisual.st.css
  packages/wix-ui-tpa/src/components/Card/docs/examples.st.css
  packages/wix-ui-tpa/src/components/Card/docs/examples.tsx
  packages/wix-ui-tpa/src/components/Card/docs/index.story.tsx
  packages/wix-ui-tpa/src/components/NewCard/NewCard.st.css
Labels: Contribution, PR: partially-approved, PR: unreviewed, WUT, wip

#7074 <Box/> - move to new story module
  packages/wix-style-react/src/Box/Box.js
  packages/wix-style-react/src/Box/docs/Box.content.js
  packages/wix-style-react/src/Box/docs/Box.examples.js
  packages/wix-style-react/src/Box/docs/Box.story.js
  packages/wix-style-react/src/Box/docs/examples/ExampleEventItem.js
  packages/wix-style-react/src/Box/docs/index.story.js
  packages/wix-style-react/src/Box/docs/storySettings.js
  packages/wix-style-react/stories/index.js
Labels: PR: reviewed-approved, WSR

#7075 <PageSection/> - move to new story module
  packages/wix-style-react/src/PageSection/docs/PageSection.content.js
  packages/wix-style-react/src/PageSection/docs/PageSection.demo.js
  packages/wix-style-react/src/PageSection/docs/PageSection.examples.js
  packages/wix-style-react/src/PageSection/docs/PageSection.story.js
  packages/wix-style-react/src/PageSection/docs/index.story.js
  packages/wix-style-react/src/PageSection/test/storySettings.js
  packages/wix-style-react/stories/index.js
Labels: PR: reviewed-approved, WSR

#7079 <AvatarGroup/> - move to new story module
  packages/wix-style-react/src/AvatarGroup/docs/AvatarGroup.content.js
  packages/wix-style-react/src/AvatarGroup/docs/AvatarGroup.examples.js
  packages/wix-style-react/src/AvatarGroup/docs/AvatarGroup.story.js
  packages/wix-style-react/src/AvatarGroup/docs/index.story.js
  packages/wix-style-react/src/AvatarGroup/test/storySettings.js
  packages/wix-style-react/stories/index.js
Labels: PR: reviewed-approved, WSR

#7080 <HorizontalTimeline/> - move to new story module
  packages/wix-style-react/src/HorizontalTimeline/docs/HorizontalTimeline.content.js
  packages/wix-style-react/src/HorizontalTimeline/docs/HorizontalTimeline.demo.js
  packages/wix-style-react/src/HorizontalTimeline/docs/HorizontalTimeline.examples.js
  packages/wix-style-react/src/HorizontalTimeline/docs/HorizontalTimeline.story.js
  packages/wix-style-react/src/HorizontalTimeline/docs/index.story.js
  packages/wix-style-react/src/HorizontalTimeline/test/storySettings.js
  packages/wix-style-react/stories/index.js
Labels: PR: reviewed-approved, WSR

#7081 <FormField /> - expose labelId prop
  packages/wix-style-react/src/FormField/FormField.js
  packages/wix-style-react/src/FormField/index.d.ts
  packages/wix-style-react/src/FormField/test/FormField.spec.js
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, WSR

#7063 BusinessDashboard Theme | Small UI Fixes
  packages/wix-style-react/src/Themes/businessDashboard/components/Badge.st.css
  packages/wix-style-react/src/Themes/businessDashboard/components/Tooltip.st.css
  packages/wix-style-react/src/Themes/businessDashboard/docs/components/Button.js
  packages/wix-style-react/src/Themes/businessDashboard/docs/components/ListItemAction.js
  packages/wix-style-react/src/Themes/businessDashboard/docs/components/ListItemSelect.js
  packages/wix-style-react/src/Themes/businessDashboard/foundations/colors.st.css
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, Themes - Business Dashboard, WSR

#7083 <Multiselect/> - move to new story module
  packages/wix-style-react/src/MultiSelect/README.TESTKIT.md
  packages/wix-style-react/src/MultiSelect/docs/MultiSelect.content.js
  packages/wix-style-react/src/MultiSelect/docs/MultiSelect.examples.js
  packages/wix-style-react/src/MultiSelect/docs/MultiSelect.story.js
  packages/wix-style-react/src/MultiSelect/docs/index.story.js
  packages/wix-style-react/src/MultiSelect/test/MultiSelect.e2e.js
  packages/wix-style-react/src/MultiSelect/test/MultiSelect.e2eStory.js
  packages/wix-style-react/src/MultiSelect/test/Reorderable.js
  packages/wix-style-react/src/MultiSelect/test/StateSelection.js
  packages/wix-style-react/src/MultiSelect/test/TestTabsSwitches.js
  packages/wix-style-react/src/MultiSelect/test/storySettings.js
  packages/wix-style-react/stories/index.js
Labels: PR: reviewed-approved, WSR

#7073 wix-ui-tpa/Dropdown-label-styles-and-a11y
  packages/wix-ui-tpa/src/components/Dropdown/Dropdown.driver.ts
  packages/wix-ui-tpa/src/components/Dropdown/Dropdown.spec.tsx
  packages/wix-ui-tpa/src/components/Dropdown/Dropdown.st.css
  packages/wix-ui-tpa/src/components/Dropdown/Dropdown.tsx
  packages/wix-ui-tpa/src/components/Dropdown/DropdownBase.tsx
  packages/wix-ui-tpa/src/components/Dropdown/DropdownNativeSelect.tsx
  packages/wix-ui-tpa/src/components/Dropdown/constants.ts
  packages/wix-ui-tpa/src/components/Dropdown/docs/DropdownExtendedExample.st.css
  packages/wix-ui-tpa/src/components/Dropdown/docs/DropdownExtendedExample.tsx
  packages/wix-ui-tpa/src/components/Dropdown/docs/index.story.tsx
Labels: Contribution, PR: unreviewed, WUT

#7085 Card ratio style param - add Settings Panel storybook page
  packages/wix-style-react/.wuf/components.json
  packages/wix-ui-tpa/src/components/Card/docs/CardWiringExample.st.css
  packages/wix-ui-tpa/src/components/Card/docs/CardWiringExample.tsx
  packages/wix-ui-tpa/src/components/Card/docs/index.story.tsx
Labels: PR: unreviewed, WUT

#7082 [VariableInput] make insertVariable add text when variableParser returns false
  packages/wix-style-react/src/VariableInput/EditorUtilities.js
  packages/wix-style-react/src/VariableInput/VariableInput.js
  packages/wix-style-react/src/VariableInput/test/VariableInput.spec.js
Labels: Bug, Contribution, PR: draft, PR: unreviewed, WSR

#7076 `<MarketingLayout/>` - changing paddings according to specs
  packages/wix-style-react/src/MarketingLayout/MarketingLayout.js
  packages/wix-style-react/src/MarketingLayout/MarketingLayout.st.css
  packages/wix-style-react/src/MarketingLayout/docs/examples.js
Labels: Contribution, PR: partially-approved, PR: reviewed-changes-requested, PR: unreviewed, WSR

#7078 <Modal/> - move to new story module
  packages/wix-style-react/src/Modal/docs/Modal.content.js
  packages/wix-style-react/src/Modal/docs/Modal.examples.js
  packages/wix-style-react/src/Modal/docs/Modal.story.js
  packages/wix-style-react/src/Modal/docs/index.story.js
  packages/wix-style-react/stories/index.js
Labels: PR: reviewed-approved, WSR

#7088 Release 9.109.0
  packages/wix-style-react/CHANGELOG.md
  packages/wix-style-react/package.json
Labels: PR: unreviewed, WSR

#7037 feat(TextField): Adding MaxLength and CharCount
  packages/wix-ui-tpa/perfer.config.js
  packages/wix-ui-tpa/src/components/TextField/TextField.driver.ts
  packages/wix-ui-tpa/src/components/TextField/TextField.spec.tsx
  packages/wix-ui-tpa/src/components/TextField/TextField.st.css
  packages/wix-ui-tpa/src/components/TextField/TextField.tsx
  packages/wix-ui-tpa/src/components/TextField/TextField.visual.tsx
  packages/wix-ui-tpa/src/components/TextField/dataKeys.ts
  packages/wix-ui-tpa/src/components/TextField/docs/TextFieldExtendedExample.st.css
  packages/wix-ui-tpa/src/components/TextField/docs/TextFieldExtendedExample.tsx
  packages/wix-ui-tpa/src/components/TextField/docs/examples.ts
  packages/wix-ui-tpa/src/components/TextField/docs/index.story.tsx
Labels: Contribution, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed, WUT, auto pr

#7084 <AutoCompleteWithLabel/> - fix suffix align
  packages/wix-style-react/src/AutoCompleteWithLabel/AutoCompleteWithLabel.js
  packages/wix-style-react/src/AutoCompleteWithLabel/AutoCompleteWithLabel.st.css
  packages/wix-style-react/src/AutoCompleteWithLabel/test/AutoCompleteWithLabel.visual.js
Labels: PR: reviewed-approved, WSR

#7071 `<AnalyticsSummaryCard />` - add additional testkit methods
  packages/wix-style-react/src/AnalyticsSummaryCard/AnalyticsSummaryCard.js
  packages/wix-style-react/src/AnalyticsSummaryCard/AnalyticsSummaryCard.uni.driver.d.ts
  packages/wix-style-react/src/AnalyticsSummaryCard/AnalyticsSummaryCard.uni.driver.js
  packages/wix-style-react/src/AnalyticsSummaryCard/constants.js
  packages/wix-style-react/src/AnalyticsSummaryCard/test/AnalyticsSummaryCard.spec.js
Labels: Contribution, PR: reviewed-approved, PR: unreviewed, WSR
